### ISSUE TITLE
Line height in "history" listing

### ISSUE THREAD

**Issue by Procyon-b** [JasonBarnabe/greasyfork#1000]
Today I noticed that some entries in the history list of a script have upper and bottom margins. I don't remember seeing so much whitespace before. At least not several days ago (and I could swear 24/36h ago).

`https://greasyfork.org/en/scripts/412178-youtube-dismiss-sign-in/versions`
All my scripts/styles with changelog text younger than april 2021 display the same margins.

The margin seems to be on a `<p>` element contained in the changelog text. Older entries don't have this element and don't display margins.
I've tried to check other scripts (not mines) to see if the tag is inserted because I do something special (or my computer's behaviour is unconventional). I've failed to find the same issue elsewhere (those with changelog text don't have recent modifications, or are automated).

I can "fix" it localy in my browser with:
```
.version-changelog p {
  margin: 0;
}
```

**Comment by JasonBarnabe** [comment]
Fixed, thanks for reporting.
