### ISSUE TITLE
Issue when renaming account name

### ISSUE THREAD

**Issue by teisseire117** [JasonBarnabe/greasyfork#1003]
Hi,

When I rename my account it works for the day, then when I come back it's back to my original name.
I tried multiple times, it works for some time, then it goes back to my original name everytime.

Can you fix it please.
I registered/logged in via Github so maybe that's the issue ?

**Comment by JasonBarnabe** [comment]
Go to https://greasyfork.org/en/users/edit_sign_in, turn off syncing.
