### ISSUE TITLE
User profile, script sorted by ratings

### ISSUE THREAD

**Issue by Procyon-b** [JasonBarnabe/greasyfork#1004]
The new default order is now by "ratings". That's how I noticed that one of my scripts doesn't seem to be at the correct position. They are ordered like this (`/users/435938`). Notice the second one. All the other scripts are in descending order.
```
25-1-0
10-0-0 **
17-1-1
6-0-0
4-0-0
...
```

**Comment by JasonBarnabe** [comment]
It's not a straight numerical comparison. It takes into account OK and Bad too. Specifically, it is "Lower bound of Wilson score confidence interval for a Bernoulli parameter" at 95% confidence, meaning "we're 95% sure that if everyone voted, the script would get at least this rating".

**Comment by Procyon-b** [comment]
Thanks. I suspected that "bad" was taken into account.

I like how a sentence like _"Lower bound of Wilson score confidence interval for a Bernoulli parameter"_ still gives me shivers.  :)
And yet I chose (and failed) to study engineering.
