### ISSUE TITLE
Avoid excessive DOM size on the history page

### ISSUE THREAD

**Issue by Mehavoid** [JasonBarnabe/greasyfork#1005]
Example: 
https://greasyfork.org/en/scripts/19993-ru-adlist-js-fixes/versions

Lighthouse Report:
[greasyfork.org-20211113T064853.pdf](https://github.com/JasonBarnabe/greasyfork/files/7531406/greasyfork.org-20211113T064853.pdf)

**Comment by JasonBarnabe** [comment]
In other words, paginate the versions list.

**Comment by JasonBarnabe** [comment]
Now paginating.
