### ISSUE TITLE
Stats info, overall for user. Helps users know if the author is valid, and or offers good quality content.

### ISSUE THREAD

**Issue by GSRHackZ** [JasonBarnabe/greasyfork#1006]
A good feature that should be added would be stats on the author / user. It would display their average rating on scripts, how many installs they got overall, and average installation rate. You can also add more stat info, such as how fast they are to reply to issues and comments on their scripts, and also whether they are active or not along with when they were last active.

This is just a list of things that may be added to a stat display for any author on the site. You may pick and choose which pieces of info to actually implement and display, but I do feel like this feature will help users determine which author is reliable and which is not. The active or not display on an author's page would help a user better pick a correct time in which they can report an issue or have a discussion with the author. It will lead to a more of a social media feeling.

**Comment by JasonBarnabe** [comment]
I have no objection to this in general. Specific notes:

- Average rating on scripts - would likely need to calculate this and possibly store it ahead of time
- How many installs they got overall - easily doable
- Average installation rate - not sure what this means
- How fast they are to reply to issues and comments on their scripts - would need a lot of thought about this. For example if someone posts a good review, that doesn't really need a reply
- ,Whether they are active or not along with when they were last active - don't want to expose this information

**Comment by GSRHackZ** [comment]
I also have no objection to your specific notes.

Average installation rate, is how many installs they usually get a day. I should have probably named it daily installation rate.

**Comment by JasonBarnabe** [comment]
I think this would be minimally useful as few people actually check the author's page, so closing.
