### ISSUE TITLE
I hope users will see the feedback tips written by the author on the feedback page.

### ISSUE THREAD

**Issue by XIU2** [JasonBarnabe/greasyfork#1008]
I wrote feedback-related tips on the script introduction page, but no one seems to look at it.
Invalid feedback from users will only waste time for both parties.

Therefore, I hope that users can see the feedback tips written by the author when they are on the feedback page.
****
### I thought of three ways:
1. At the top of the feedback page, an area is added to display the tips written by the author.
2. The feedback prompt written by the author is displayed in the input box at the bottom of the feedback page.
![01](https://user-images.githubusercontent.com/54703944/143239232-8c3bd7b2-e9b5-4e7e-8232-7c2c53ef263f.png)
3. Allow a feedback discussion to be pinned to the top (E.g. Github).

> I can only manually implement the third method (regular reply to make it top) ...

**Comment by JasonBarnabe** [comment]
You can use `@supportURL` if you have an alternate place you'd like to people to go. Greasy Fork will show this prominently.

I don't want to implement any of your ideas due to the potential for abuse.
