### ISSUE TITLE
Old script versions cannot be viewed on SleazyFork when logged in

### ISSUE THREAD

**Issue by sanchan-gh** [JasonBarnabe/greasyfork#1009]
Clicking on any version in the History tab brings up the code for that version on GreasyFork, but on SleazyFork it just outputs the message

> This script is not available on this site.

There's the workaround of logging into GreasyFork and visiting the script's page from there.

This seems to only be an issue when logged in.
When not logged in, the SleazyFork page for an old version redirects to GreasyFork - which doesn't seem ideal either, but at least it works.

**Comment by JasonBarnabe** [comment]
Seems to work for me, e.g. https://sleazyfork.org/en/scripts/42382-better-caoliu?version=269222

What URL are you trying to access?

**Comment by JasonBarnabe** [comment]
Closing, if you can come back with an example, I can take a look.

**Comment by sanchan-gh** [comment]
Sorry, I completely missed this notification!

Originally I had this issue on any version link on https://sleazyfork.org/en/scripts/23597-sankakuaddon/versions when logged in sleazyfork and it is still happening for me as we speak, e.g. https://sleazyfork.org/en/scripts/23597-sankakuaddon?version=1015351 gives me "This script is not available on this site."
(I'm not logged into greasyfork if that matters.)

Signing out out of sleazyfork and visiting the exact same link again does let me see it, until I log in again.

This issue may be inconsistent, at one time while testing it looked like I was actually logged into sleazyfork and was able to see the old versions, but right now I can't for the live of me reproduce this - maybe my eyes deceived me.

One way I am able to make it fail consistently(?) is via a clean Chrome installation like this:

1. Logout of greasyfork and sleazyfork, clear all cookies/website data
1. Visit any sleazyfork version link like https://sleazyfork.org/en/scripts/42382-better-caoliu?version=269222
1. It works perfectly fine!
1. Press "Sign In" and log in (I use direct mail/password login if that matters)
1. It automatically redirects to the same version link as above
1. The page says "This script is not available on this site."
1. Any such version link says the same

**Comment by JasonBarnabe** [comment]
There was an error in the code where if you were viewing an old version of a script on Sleazy Fork, it didn't remember that the script belonged on Sleazy Fork, which is why you got "This script is not available on this site."

There was a further error where because of caching, you could sometimes get the version intended for Greasy Fork on Sleazy Fork. This explains why it works sometimes.

Both of these should be fixed now. Thanks for reporting.

**Comment by sanchan-gh** [comment]
Great, thanks for fixing it so quickly!
