### ISSUE TITLE
When the script uses `WebHook`, the script code can be omitted when updating the script introduction, saving server bandwidth + increasing speed.

### ISSUE THREAD

**Issue by XIU2** [JasonBarnabe/greasyfork#1010]
When the script uses WebHook, any changes made to the code will be overwritten during synchronization.
So the author updated on the webpage just to modify the content of the script introduction.

But I have observed that both when visiting the `/versions/new` webpage or when **submitting changes**, the script code is carried.
Under normal circumstances, there is no impact.
But when the script code is large, or the network connection is not good, I will feel a significant delay.

So I thought, if the script uses WebHook, it would be better not to carry the script code when updating the script through the web page.
It not only reduces the server bandwidth, but also improves the update experience of script writers.

**Comment by JasonBarnabe** [comment]
I don't think bandwidth is a significant concern here. From the server's perspective, receiving updates is a tiny fraction of total bandwidth.

I understand this for someone with a syncing script and a slow connection, doing an additional-info-only update can be annoying, but these seems like a rare case and not worth the confusion for someone who wants to do a code update for a syncing script, for whatever reason.
