### ISSUE TITLE
Where is button add script to favorites?

### ISSUE THREAD

**Issue by Bekon241** [JasonBarnabe/greasyfork#1011]
I love greasyfork but where is that opion alweys when i was logged in i can add any script to my fav list, now i not see any option fot that :( Anyone can help me and tell what change now?

I know EDIT script list option but paste url is much anoing then add 1 by 1 just pressing button...
Why someone change something who was not broken? :(

Thanks, cheers from Poland.
![GF-bug](https://user-images.githubusercontent.com/52114263/143817304-4a418836-1a11-404a-9dac-b1b03c96803d.jpg)

**Comment by JasonBarnabe** [comment]
This has been removed as it's not an important enough feature for the place it was occupying on the page.

**Comment by eight04** [comment]
Maybe we need a new script to take this feature back 😏

**Comment by Coldblackice** [comment]
> Maybe we need a new script to take this feature back 😏

Agreed. Odd that it was removed, given all the open available space on the page.

**Comment by Coldblackice** [comment]
> Maybe we need a new script to take this feature back 😏

Agreed. Kinda odd that it was removed, given all the open available space on the page (and it's not like anything took its place).

**Comment by decembre** [comment]
> I know EDIT script list option but paste url is much anoing then add 1 by 1 just pressing button...

And better in script page, we can remove it too:
All in one place !

"Was" a very clever feature.
