### ISSUE TITLE
I was mistakenly reported on the site and passed the administrator review, which puzzled me!

### ISSUE THREAD

**Issue by dayubuchixiami** [JasonBarnabe/greasyfork#1018]
Dear Greasy Fork administrator! Please forgive me for bothering you here, but https://greasyfork.org/zh-CN/reports/20579 This is obviously a different script, and the code is written by me. However, he was reported plagiarism and was approved by the administrator. This not only makes me wonder, where are the similarities between these two scripts?

**Comment by JasonBarnabe** [comment]
Looks like you got this resolved by appealing. Sorry about this, appears to be a mistake by the moderator.
