### ISSUE TITLE
Install/Update button serving old version

### ISSUE THREAD

**Issue by Hannah-GBS** [JasonBarnabe/greasyfork#1023]
Not sure if this is just a problem on Edge, but I made a script (https://greasyfork.org/en/scripts/438115-hide-ttroy-on-abb), and quickly noticed an issue with it, so updated it and changed the version to 1.1

However when clicking the "Update to version 1.1" button, it just tries to re-install 1.0, and on a fresh Edge (another PC), the "Install" button tries to install 1.0, despite 1.1 being shown as the current version on GF, and the code tab showing correctly.

**Comment by JasonBarnabe** [comment]
Does it continue to do so even now?

**Comment by Hannah-GBS** [comment]
It does seem to be serving the correct version now.
