### ISSUE TITLE
cant share my script on web

### ISSUE THREAD

**Issue by Dark3n89** [JasonBarnabe/greasyfork#1024]
502 bad gateway  :/

**Comment by JasonBarnabe** [comment]
This can be due to character encoding issues, or other things. Can you post your script here (on GitHub)?

**Comment by Dark3n89** [comment]
> This can be due to character encoding issues, or other things. Can you post your script here (on GitHub)?

github is reason why i can share into greasy, i dont understand github and want share completed fb ad block for all situations.
![image](https://user-images.githubusercontent.com/48175529/148593950-a60e5aed-cae3-4c85-90d3-c867d5a6b63a.png)
is not error on my side :/

**Comment by JasonBarnabe** [comment]
I'm saying attach the file here and I will test it with Greasy Fork and determine what the problem is.

**Comment by Dark3n89** [comment]
problem is 90% buttons  what i click say 502 error

pá 7. 1. 2022 v 20:14 odesílatel Jason Barnabe ***@***.***>
napsal:

**Comment by JasonBarnabe** [comment]
If you can't share it _anywhere_ then clearly there's some problem with your script. Not a Greasy Fork issue.

**Comment by Dark3n89** [comment]
wtf i want shared  to greasy a and shitty web dont work omg, what you bla bla about my script?  Is my freedom where are  want add my sources
