### ISSUE TITLE
web not work

### ISSUE THREAD

**Issue by Dark3n89** [JasonBarnabe/greasyfork#1027]
![image](https://user-images.githubusercontent.com/48175529/148930796-eb25ced7-5b38-43e1-bde0-54bafa817276.png)
![image](https://user-images.githubusercontent.com/48175529/148930967-b3d36b71-10c9-4bf9-938c-0430ed00ad71.png)
![image](https://user-images.githubusercontent.com/48175529/148930988-6986bfc6-c48a-4755-8a01-aa013630829d.png)

ever link force  502 error , last time you bla bla about .--- your code is bad paste JS here, but you are rly idiot, i talking full time about WEB!

**Comment by JasonBarnabe** [comment]
Fixed root cause in d959535268d3dae8e95b5fab84feb9b09ecbef47
