### ISSUE TITLE
1 error prohibited this user from being saved:

### ISSUE THREAD

**Issue by gclm** [JasonBarnabe/greasyfork#1029]
![image](https://user-images.githubusercontent.com/27618687/150045508-fcff4f7a-cf68-4d9a-bdc3-095d3736c73c.png)

**Comment by JasonBarnabe** [comment]
I assume you were trying to post a script. Certain domains are delayed from posting scripts for a short period to prevent spam. The message you received was incorrect. It's fixed now, and I assume you are able to post scripts.
