### ISSUE TITLE
promoted scripts don't work on sleazyfork

### ISSUE THREAD

**Issue by cheater** [JasonBarnabe/greasyfork#1036]
When you enter the url to a sleazyfork script, it gets rejected, and the error message says I have to enter the url to a sleazyfork script.

If I replace sleazyfork.org with greasyfork.org, the url gets accepted, and has greasyfork.org changed back to sleazyfork.org. However, after that's done, if I install the script that promotes another script, nothing happens. Honestly though I don't know what this looks like when it works, but whatever should be happening, isn't happening. There's no message / popup / whatever telling me to install the other script that I'm promoting.

**Comment by JasonBarnabe** [comment]
Promoted scripts appear after you click the install button, in the same area as the install button. It may depend on your user script manager - some may not keep you on the same page on install.

I've made some changes to make it allow sleazyfork URLs. You should be able to do any combination of greasyfork and sleazyfork with the exception of promoting a sleazyfork script on greasyfork.
