### ISSUE TITLE
I want permanent delete locked script.

### ISSUE THREAD

**Issue by heroboy** [JasonBarnabe/greasyfork#1044]
Even this script is locked, I think I have the right to do the permanent deletion.
I just want remove these useless scripts from my eyes.

**Comment by JasonBarnabe** [comment]
You can't do it from the Delete tab of the script?

**Comment by heroboy** [comment]
It will redirect to homepage. And shows "This script is locked and can't be permanently deleted".

**Comment by JasonBarnabe** [comment]
It's not deletable because it's useful to keep around so that if the author reuploads the same script, it's easier to spot.

I can manually delete them for you if they're really bothering you.

**Comment by heroboy** [comment]
Never mind.
I want to ask , should  private scripts obey to all the code rules?
If my script is reported, deleted and locked. Can I reuploaded as private? Or can I appeal it to be private.

Some scripts I used personally. I uploaded them is to backup and sync my multiple computers. I just don't care it to be public, maybe someone feel it is useful. So I also don't care it is private.

**Comment by JasonBarnabe** [comment]
All scripts have to follow the same rules, whether you intend others to use them or not. But I would suggest that if you don't want it to be public, just put it in a (possibly private) GitHub repo. There's no reason to post on Greasy Fork if you don't want to share your scripts.
