### ISSUE TITLE
`<details> <summary>` does not display properly when used with Markdown

### ISSUE THREAD

**Issue by XIU2** [JasonBarnabe/greasyfork#1046]
I want some content to be collapsed by default to keep it clean and beautiful so that visitors can quickly find what they want to see. But I found that when `<details> <summary>` is used with Markdown, it will not display properly.

****

### Original text:

<img src="https://user-images.githubusercontent.com/54703944/155152972-6e24a309-8c0e-4197-884d-559ac1567fa0.png" width="40%">

### Markdown:

<img src="https://user-images.githubusercontent.com/54703944/155152984-a28cefbb-db5e-4ddb-b20f-6fa4bccdae2e.png" width="40%">

### HTML:

<img src="https://user-images.githubusercontent.com/54703944/155152986-7a11feb1-6006-462c-ab67-2eda6b78a18b.png" width="40%">

### Desired result:

<img src="https://user-images.githubusercontent.com/54703944/155152989-6242a71b-626d-443f-aa1c-9afa694de044.png" width="40%">

**Comment by JasonBarnabe** [comment]
Same as #989
