### ISSUE TITLE
Confirm script JSON is permanent feature

### ISSUE THREAD

**Issue by erosman** [JasonBarnabe/greasyfork#1047]
Hi Jason

I have changed the update `version` check for userScript/userCSS from `.meta.js/.meta.css` to `id.json` in FireMonkey, as it is more convenient & robust.

I would like to verify that `id.json` will always be available.

**Comment by erosman** [comment]
Additionally, regarding [Getting diff version numbers ](https://greasyfork.org/en/discussions/greasyfork/120279-getting-diff-version-numbers)

As mentioned, an idea would be to set an internal redirect so that version numbers can be set as parameters. e.g.

```
https://greasyfork.org/scripts/...id.../diff?ver1=1.6.1.3&ver2=1.6.1.4
```

Another idea could be to add `history` to script JSON e.g.

```js
{
   id: '1234',
   // ...
   version: '1.6.1.4',
   locale": 'en',
   history: {
    '1.6.1.4': 1017885,
    '1.6.1.3': 1016564,
    // ...
  }
}
```

**Comment by JasonBarnabe** [comment]
I'm concerned because the `meta` URLs are optimized for a lot of traffic and the JSON URLs are not. (The `meta` URLs are static, only changing when an update is made, while the JSON URLs are dynamic, hit the DB, etc.).

In addition, requests to the `meta` URLs count for update statistics. JSON would not.

**Comment by erosman** [comment]
I see... well, fair enough.

**Comment by JasonBarnabe** [comment]
The statistic is "update checks" and it's a proxy for how many active users you have.

**Comment by JasonBarnabe** [comment]
To answer the original question, there are no plans to remove the JSON feed for an individual script. But as noted I don't want this to be an endpoint for script updates as it's not optimized as such.
