### ISSUE TITLE
Missing entries in meta.js

### ISSUE THREAD

**Issue by erosman** [JasonBarnabe/greasyfork#1050]
Hi Jason

I have been checking `.meta.js` & `.meta.css` and there seems to be missing lines comparing to the original.

Although it probably is of no use in 99.99% of the time, I was wondering if there is a reason for it.

I became aware of the situation as I was searching the code for `@resource` and thought it would be better to look at the `.meta.js` instead of loading the whole code page, so I wrote a script to add a link to `.meta.js`. I then noticed that they are all missing `@resource` (as well as `@icon` but that is not important).

**Comment by JasonBarnabe** [comment]
https://github.com/JasonBarnabe/greasyfork/blob/3e54cb0ed7a41f51376140a2e753a07ccb17829a/app/controllers/scripts_controller.rb#L907

`@icon` and `@resource` are deliberately stripped to lower bandwidth used, especially in situations where these are a data URI.
