### ISSUE TITLE
if sync url host is cdn.jsdelivr.net, autoupdate is not work

### ISSUE THREAD

**Issue by lisonge** [JasonBarnabe/greasyfork#1052]
when i set sync url to ` https://cdn.jsdelivr.net/gh/lisonge/op-wiki-plus@main/dist/op-wiki-plus.user.js` at https://greasyfork.org/zh-CN/scripts/441073-%E5%8E%9F%E7%A5%9Ewiki%E8%BE%85%E5%8A%A9%E5%B7%A5%E5%85%B7/admin

in first time, it will work

but when i upgrade version and update file https://cdn.jsdelivr.net/gh/lisonge/op-wiki-plus@main/dist/op-wiki-plus.user.js

then i click `Update Settings and sync immediately` at https://greasyfork.org/zh-CN/scripts/441073-%E5%8E%9F%E7%A5%9Ewiki%E8%BE%85%E5%8A%A9%E5%B7%A5%E5%85%B7/admin

but it not work, just show `Script successfully synced, but no changes found.`

finally i need click `Close synchronization of this script`  and fill in the update link again, it will work

I think the reason is max-age of cdn.jsdelivr.net, Is there any other solution?

**Comment by JasonBarnabe** [comment]
`@updateURL` does nothing on Greasy Fork. It will be removed if specified.

If you are using Greasy Fork's syncing feature, then I suggest you point it to the file on GitHub rather than a CDN.

**Comment by lisonge** [comment]
@JasonBarnabe ok

**Comment by lisonge** [comment]
ok, but i think greasyfork synchronous operations should not rely on caching

**Comment by JasonBarnabe** [comment]
They wouldn't cache client-side. There may be server-side caching though.

**Comment by JasonBarnabe** [comment]
As far as I can tell,

https://greasyfork.org/scripts/441073-%E5%8E%9F%E7%A5%9Ewiki%E8%BE%85%E5%8A%A9%E5%B7%A5%E5%85%B7/code/%E5%8E%9F%E7%A5%9EWiki%E8%BE%85%E5%8A%A9%E5%B7%A5%E5%85%B7.user.js
https://cdn.jsdelivr.net/gh/lisonge/op-wiki-plus@main/dist/op-wiki-plus.user.js
https://raw.githubusercontent.com/lisonge/op-wiki-plus/main/dist/op-wiki-plus.user.js

All have the same thing at the moment (except Greasy Fork stripped `@updateURL`, which is expected). So I don't see any problem here.
