### ISSUE TITLE
Report Action Notification Email Language

### ISSUE THREAD

**Issue by erosman** [JasonBarnabe/greasyfork#1053]
I got 2 notifications on reports today in Portuguese which I had to copy/paste to Google translate to understand.

I think, GF sends the email notification according to the language of the sender/moderator, and not the language of the reporter (or default English).

> Sua denúncia no ************ no Greasy Fork foi confirmada por um moderador e o script foi demovido. Você pode rever a denúncia em https://greasyfork.org/reports/****. Se você tiver alguma dúvida, por favor visite https://greasyfork.org/forum/.

PS. The view report link on Yahoo mail includes the dot which results in `404 - page not found.`. I suggest putting a space before the dot in the email template.

**Comment by JasonBarnabe** [comment]
A while back, a language field was added to users. Everyone who signed up would get this defaulted to the language they were using on signup. Anyone already existing did not have it set, but they could set it in the user settings.

In the absence of a locale, emails will use the locale used by the person who triggered them.

You need to go into your user profile and specify your language.
