### ISSUE TITLE
Revision export (feature suggestion)

### ISSUE THREAD

**Issue by HT-7** [JasonBarnabe/greasyfork#1054]
I suggest the ability to export scripts' revision histories like on MediaWiki.

As a reference, MediaWiki is able to generate XML files from revision histories, see *[Help:Export](https://www.mediawiki.org/wiki/Help:Export)*, and even has a dedicated page called *[Special:Export](https://www.mediawiki.org/wiki/Special:Export)* which allows adding multiple page titles at once.

The XML files also contain revision metadata such as numerical identifier and time stamps.

**Comment by JasonBarnabe** [comment]
There are already JSON versions of various pages. Is there some use case where XML would be better than JSON? Are there things missing from the current JSON endpoints that could be added?

**Comment by JasonBarnabe** [comment]
If there's something specific you need or want to do, please suggest it, but I don't work on APIs unless I have specifics.

**Comment by HT-7** [comment]
I apparently did not word it precisely enough. What I suggest is the ability to export all revisions of a script into a single file. It could be a markup file or a compressed archive. 

A markup file would contain the text of each revision, which is how MediaWiki does it, as mentioned earlier as an example. A ZIP archive would contain the script files with timestamped names for each revision.

It is far more convenient and efficient than scraping each revision individually.

**Comment by JasonBarnabe** [comment]
There should be no scraping required.

1. Parse the JSON of the version history, e.g. https://greasyfork.org/en/scripts/410512-sci-js-from-ksw2-center/versions.json
2. Take the `code_url` property of each.
3. Download each `code_url`, placing in a file format of your choosing.

It's not a file automatically provided to you, but this is very doable.
