### ISSUE TITLE
@-moz-document regexp("\\.") is new RegExp("\\\\.") would be converted to

### ISSUE THREAD

**Issue by esperecyan** [JasonBarnabe/greasyfork#1055]
In Conversion of user CSS to user JS, `@-moz-document regexp("\\.")` is `new RegExp("\\\\.")` would be converted to.

Also, and this is not a major problem,  an unnecessary `\` is inserted before `$`, and there is no `^` `$` before or after.

https://greasyfork.org/scripts/395307

Before conversion:
```css
@-moz-document regexp("https?://www\\.google\\.(?:com|(?:com?\\.)?[a-z][a-z])/(?!maps(?:$|.*)).*") {
```

Expected conversion result:
```js
if (new RegExp("^(?:https?://www\\.google\\.(?:com|(?:com?\\.)?[a-z][a-z])/(?!maps(?:$|.*)).*)$").test(location.href)) {
		css += `
```

Actual conversion result:
```js
if (new RegExp("https?://www\\\\.google\\\\.(?:com|(?:com?\\\\.)?[a-z][a-z])/(?!maps(?:\$|.*)).*").test(location.href)) {
		css += `
```

**Comment by JasonBarnabe** [comment]
I've made some changes. Now the line you posted is converted to:
```js
if (new RegExp("^https?://www\\.google\\.(?:com|(?:com?\\.)?[a-z][a-z])/(?!maps(?:\$|.*)).*$").test(location.href)) {
```
Fixed:
- 2 backslashes instead of 4
- Added `^` and `$`

`$` is still escaped - I think this is due to it trying to avoid template literals. Certain other strings would be escaped as well, but I don't think this breaks anything, so I think I'll just leave it.

**Comment by esperecyan** [comment]
Thanks for the correction.

I think it needs to be `^(?:******)$` because `^******$` will not work correctly when `|` is included.

**Comment by JasonBarnabe** [comment]
If `(?:...)` wasn't in the original CSS then why would it need to be in the JS? If the JS needed it, wouldn't the CSS need it as well?

**Comment by esperecyan** [comment]
For example, problems occur with CSS like `@-moz-document regexp("https://example\\.com/|https://example\\.net/")`. This matches https://example.com/ and https://example.net/, but when converted to `new RegExp("^https://example\\.com/|https://example\\.net/$")`, the https://example.com/foobar, etc. to match.

**Comment by JasonBarnabe** [comment]
I think I get it, it's necessary because of the added `^` and `$`, otherwise the `^` only applies to the part before `|` and the `$` only applies to the part after.

**Comment by JasonBarnabe** [comment]
Now including `(?:...)`. Look good now?

**Comment by esperecyan** [comment]
It is working as expected. Thank you!
