### ISSUE TITLE
greasyfork UserScript cannot match 'about: blank'

### ISSUE THREAD

**Issue by doublesweet01** [JasonBarnabe/greasyfork#1060]
I tried to use match to match 'about: blank' in UserScript, but it didn't take effect. I find there is no matching rule about 'about: blank' in the official document. How do I match this address?

我尝试在UserScript部分使用match匹配about:blank,但是发现无法生效，看官方文档里没有关于about:blank的匹配规则，请问这个地址要如何匹配？

**Comment by JasonBarnabe** [comment]
Are you saying that when you write a script it does not apply to about:blank? Because that would be a script manager (TamperMonkey, Greasemonkey, etc.) thing.

**Comment by doublesweet01** [comment]
Do you mean that the script does not have permission to modify ‘about_blank’ page?

**Comment by JasonBarnabe** [comment]
This repo is about greasyfork.org. If you have trouble making a script work (as opposed to posting it on Greasy Fork), then please file an issue in the appropriate place.
