### ISSUE TITLE
(email notifications) Separate with a newline the "View and reply to this comment" and "Manage your notification preferences" links

### ISSUE THREAD

**Issue by darkred** [JasonBarnabe/greasyfork#1062]
Currently in email notifications, the "View and reply to this comment" and "Manage your notification preferences" links are displayed in the same row, thus making it difficult to distinguish because they seem as single text. 

Screenshot from Gmail:
![2022-04-26_203719](https://user-images.githubusercontent.com/723651/165359908-8f96c214-a9ea-4e98-9226-8e7f9c40dfa4.jpg)

My suggestion is to separate them with a newline:
![2022-04-26_204201](https://user-images.githubusercontent.com/723651/165360404-b12b9c34-f2fe-4fc9-9474-cf538b54af37.jpg)

Thank you

**Comment by JasonBarnabe** [comment]
Every other notification gives the reason the user got the notification (e.g. "because you are subscribed"). I think this text should be added here, which would solve your issue.

**Comment by JasonBarnabe** [comment]
Updated:

**View and reply to this comment.** You received this notification because you chose to be notified about discussions on your scripts. **Manage your notification preferences.**
