### ISSUE TITLE
add official subdomains of jsdelivr to external scripts url white list

### ISSUE THREAD

**Issue by Sec-ant** [JasonBarnabe/greasyfork#1064]
`cdn.jsdelivr.net` is blocked by mainland China, but some of the official subdomains of `jsdelivr` can still be accessed normally for now:

CloudFlare：test1.jsdelivr.net
CloudFlare：testingcf.jsdelivr.net
Fastly：fastly.jsdelivr.net
GCORE：gcore.jsdelivr.net

Can you add them to the [external scripts url white list of greasy fork](https://greasyfork.org/en/help/external-scripts?locale_override=1)? Thanks

**Comment by JasonBarnabe** [comment]
Done! Thanks for the suggestion.
