### ISSUE TITLE
GreasyFork Error With Desc for no Reason

### ISSUE THREAD

**Issue by Yogesh-Togesh** [JasonBarnabe/greasyfork#1065]
Error Saying
![Screenshot 2022-05-22 21 41 57](https://user-images.githubusercontent.com/106044711/169733705-a42d7ac0-ff17-4c3e-9582-1f8518f3e948.png)

**Comment by JasonBarnabe** [comment]
What description are you putting in?

**Comment by JasonBarnabe** [comment]
This only happens if you're putting in a common, nonsensical description. Put in a real one and you'll be fine.
