### ISSUE TITLE
The cerificate expired the 24th of this month

### ISSUE THREAD

**Issue by Eichen97** [JasonBarnabe/greasyfork#1066]
Hey bro, plz renew the certificate.

**Comment by JasonBarnabe** [comment]
Works now?

**Comment by Eichen97** [comment]
HOLY SHIT! THAT WAS FAST MAN.
Thanks.

**Comment by JasonBarnabe** [comment]
I wish I could work that fast. Someone else told me 15 minutes ago. Just needed to reboot one of the backend servers for some reason.
