### ISSUE TITLE
License is always appearing as null in JSON

### ISSUE THREAD

**Issue by DenverCoder1** [JasonBarnabe/greasyfork#1068]
In the script and on the website, it displays "MIT", but in the JSON it says `null`. Tested on multiple scripts.

Example: 

https://greasyfork.org/en/scripts/407466-unedit-and-undelete-for-reddit

![image](https://user-images.githubusercontent.com/20955511/173378950-1a7e527c-d3a4-4d5d-87a6-01fcffcdab30.png)

https://greasyfork.org/en/scripts/407466-unedit-and-undelete-for-reddit.json

![image](https://user-images.githubusercontent.com/20955511/173379009-e9b8a1b5-39a2-43c7-b00b-cedbd4566877.png)

**Comment by JasonBarnabe** [comment]
Thanks for reporting.

This was working for licenses the site does not recognize but not for ones that it did. It's fixed now to show the name of recognized  licenses as well.
