### ISSUE TITLE
[Feature Request] Show script size information on search result page.

### ISSUE THREAD

**Issue by dembeck** [JasonBarnabe/greasyfork#1074]
# Feature Summary

Show script size and length on the search results page.

# Feature Reason

It would be helpful if the search results page showed the approximate size and number of lines of each result.

The search results often include scripts that vary widely in size. The size difference between scripts that perform similar tasks can be thousands of lines. There is usually little indication of what the huge scripts actually do extra to justify their size, whether through code documentation, or additional features.

Personally, I prefer the least amount of code that efficiently performs the task I require. I like to have at minimum a vague understanding of how a given script works, but when a script is thousands of lines long this is usually difficult. 

Having script size information on the search results page would make it much easier to sort through the scripts and find the one that best fits my needs.

# Requested Features

- Show number of lines of each script on the search results page.
- Show file size of each script on the search results page.

# Example

This is an example of how it might look if implemented.

![image](https://user-images.githubusercontent.com/9568447/178181021-0f2e4689-dc85-410d-a57f-d541af96af17.png)

**Comment by JasonBarnabe** [comment]
Closing per above.
