### ISSUE TITLE
Expired certificates, insecure websites

### ISSUE THREAD

**Issue by tianluanchen** [JasonBarnabe/greasyfork#1078]
## I think you may need to renew the ssl certificate for this site
![图片](https://user-images.githubusercontent.com/75252550/180653745-4f38be93-d3ad-405d-878e-3a82966e07bc.png)

**Comment by JasonBarnabe** [comment]
This should be OK as of about 10 minutes ago. Can you confirm?

**Comment by tianluanchen** [comment]
> This should be OK as of about 10 minutes ago. Can you confirm?

Now that it's back to normal, I suggest you can use a script like acme.sh to renew the certificate some days before it expires.
Thanks for your help.

**Comment by JasonBarnabe** [comment]
It's using normal Let's Encrypt scripts to renew, but for some reason it doesn't work until I reboot the server.
