### ISSUE TITLE
Unable to add more than 1 attachment out of 5 maximum

### ISSUE THREAD

**Issue by sj365** [JasonBarnabe/greasyfork#1079]
Windows 10
I7 3.6ghz
drivers up to date

adding comments to this page https://greasyfork.org/en/scripts/415797-piratebay-darkmode/discussions/142722 

Only 1 attachment .png is being uploaded.  Attempts to add additional attachments push out the prior one.  Effect is only 1 attachment being possible.  All attachments under 200kb maximum

**Comment by JasonBarnabe** [comment]
In the file input, you can select multiple images at once. This is how you attach multiple images.
