### ISSUE TITLE
[Email Notifications] I've never seen email notifications work for me

### ISSUE THREAD

**Issue by TFWol** [JasonBarnabe/greasyfork#1082]
Despite setting up notifications and verifying the usual (junk, filters, etc.), I've never seen a notification come in.

Maybe the system is getting choked up on the name format of the email?

**Comment by JasonBarnabe** [comment]
I've tested it - received it successfully on a gmail address, straight to inbox with no sorts of warnings or anything.

I know some servers will filter it out; I don't know why. If you trigger an email through the site (e.g. a password reset), then send me an email (jason.barnabe@gmail.com), I can check the logs to see if there's any problem reported there.

**Comment by TFWol** [comment]
@JasonBarnabe Thanks for the tip off. It used to work, but stopped working out of nowhere. It was the email provider blocking it. Didn't even make it to Junk.

I've gone ahead and changed providers (I was even able to received the confirmation email).

**Comment by JasonBarnabe** [comment]
If you have an information on why it was being blocked, I'd be eager to hear it. Perhaps some header/config is not set on my end.

**Comment by TFWol** [comment]
It was related to how Apple has their relay setup:
https://developer.apple.com/forums/thread/122270

**Comment by JasonBarnabe** [comment]
I had SPF set up already, and now I've gone ahead and set up DKIM as well. Maybe that will help.

**Comment by TFWol** [comment]
I went ahead and did a quick test. Unfortunately it didn't work, but I wouldn't fret over it. Apple's relay is garbage anyways.

btw, if the *Currently waiting confirmation for:* flag doesn't eventually go away could you remove it from my account? 
I'll keep the reflected non-icloud email.

**Comment by JasonBarnabe** [comment]
Please let me know your account ID or user name and I can do that.

**Comment by TFWol** [comment]
Sure thing: Gr_wolfe

**Comment by JasonBarnabe** [comment]
Done.

**Comment by TFWol** [comment]
Much obliged!
