### ISSUE TITLE
hope allow @require url support Data URLs

### ISSUE THREAD

**Issue by lisonge** [JasonBarnabe/greasyfork#1084]
```js
// ==UserScript==
// @name               example
// @namespace          https://github.com/lisonge
// @version            1.0.1
// @author             lisonge
// @match              https://i.songe.li/
// @require            https://cdn.jsdelivr.net/npm/vue@3.0.0/dist/vue.global.prod.js
// @require            data:application/javascript,%3Bwindow.Vue%3DVue%3B
// @require            https://unpkg.com/element-plus@2.2.15/dist/index.full.js
// ==/UserScript==

// `data:application/javascript,` + encodeURIComponent(`;window.Vue=Vue;`)
```

because `vue` use iife export, `element-plus` use umd, they can not both work in Tampermonkey/Violentmonkey window scope

full detail see [vite-plugin-monkey#5](https://github.com/lisonge/vite-plugin-monkey/issues/5)

The simplest solution is that add a `@require url` to set window.Vue to scope.Vue after `vue require url`

**Comment by JasonBarnabe** [comment]
I don't understand the purpose of this. Can you explain further? Is this something already supported by user script managers like Tampermonkey?

**Comment by lisonge** [comment]
Tampermonkey/Violentmonkey support `// @require            data:application/javascript,%3Bwindow.Vue%3DVue%3B`

**Comment by lisonge** [comment]
![image](https://user-images.githubusercontent.com/38517192/187336296-ee2edaa8-a107-4a38-a199-2d21836afb69.png)
![image](https://user-images.githubusercontent.com/38517192/187336311-9d117203-db07-47f0-90e1-a9b02bb88dbd.png)

**Comment by lisonge** [comment]
![image](https://user-images.githubusercontent.com/38517192/187336390-dacd8855-68b0-4210-aa3f-04da00d8320e.png)
![image](https://user-images.githubusercontent.com/38517192/187336412-6e740ba3-cda4-4454-8d6e-f7c268ddb7e9.png)

can be work

**Comment by lisonge** [comment]
![image](https://user-images.githubusercontent.com/38517192/187336610-ec9a63a0-ac6a-4d76-ae7b-4559d84963f0.png)

but `// @require            data:application/javascript,%3Bwindow.Vue%3DVue%3B` is not allowed at greasyfork

**Comment by lisonge** [comment]
Do you understand what I mean ？

**Comment by lisonge** [comment]
@JasonBarnabe hello, Could you please give me an accurate reply?

**Comment by JasonBarnabe** [comment]
data URI `@require`s are now allowed.

**Comment by lisonge** [comment]
ok, thanks
