### ISSUE TITLE
Comment emails are sent using the sender's language

### ISSUE THREAD

**Issue by ppixiv** [JasonBarnabe/greasyfork#1090]
When a user leaves a comment on a script, the email notification sent to the author is in the sender's language.  I frequently get emails templated in other languages:

> 您对于站点Greasy Fork的脚本ppixiv for Pixiv收到了一条评论。
> スクリプト ppixiv for Pixiv (Greasy Fork) にコメントがあります。
> Ваш скрипт ppixiv for Pixiv на Greasy Fork получил комментарий.

Not a big deal, but this is probably more annoying for non-English users, since it'll happen a lot more frequently for them.

**Comment by JasonBarnabe** [comment]
Do you have a preferred locale set at https://greasyfork.org/en/users/edit ? See #794, #1053.

**Comment by ppixiv** [comment]
I'd have thought it would save the user's browser language when viewing the site if it had never been set before, but I guess there's some legacy data reason for how it works.  Anyway, just wanted to make sure you were aware of it.
