### ISSUE TITLE
Suggestion: More lenient setting for non-NSFW scripts targetting sites w/ NSFW content

### ISSUE THREAD

**Issue by 20kdc** [JasonBarnabe/greasyfork#1092]
I'm the owner of a few scripts meant to be used on `discord.com`, which is a chat website that contains adult content (and supports the designation of such with specific "NSFW channels").

However my scripts don't contain adult content, and the site isn't really primarily about adult content - it just happens to exist there.

This leads to an unfortunate situation where anyone who might want to access these scripts is met with: "This script is no longer anonymously available on this site. [Log in](https://greasyfork.org/en/users/sign_in) and check your Greasy Fork account settings."

Even though I believe it is not reasonable for these scripts to be blocked, I'm complying with the rules, and as such my scripts aren't accessible to people who don't login to Greasy Fork.

**Comment by JasonBarnabe** [comment]
Can you provide URLs for the scripts affected?

**Comment by 20kdc** [comment]
https://greasyfork.org/en/scripts/28865-discord-hide-channel-list-button
https://greasyfork.org/en/scripts/402660-discord-obliterate-nitro-button
https://greasyfork.org/en/scripts/415753-discord-hide-bot-indicators
https://greasyfork.org/en/scripts/436919-discord-obliterate-snowsgiving
https://greasyfork.org/en/scripts/440693-discord-obliterate-activities-statuses

**Comment by JasonBarnabe** [comment]
I generally consider a site to be NSFW if the main page or the links from the main page are NSFW. For a multi-purpose site like Discord, Reddit, etc., as long as you are not specifically targeting a NSFW section/page on the site, and there is no mention of NSFW content in your description on Greasy Fork, you don't need to mark as NSFW.
