### ISSUE TITLE
Delete comments of a banned user

### ISSUE THREAD

**Issue by Murka007** [JasonBarnabe/greasyfork#1097]
All comments of the banned user should be deleted. This is really important, because after fixing the script, banned user will not be able to change his feedback to **good**

**Comment by JasonBarnabe** [comment]
Banned user comments are only deleted if their their comments are what caused them to get banned. If they were banned for other reasons, their comments stay.

**Comment by Murka007** [comment]
It doesn't make any sense, because feedback of the banned user may be irrelevant due to script updates and owner of the script couldn't do anything with it. Bad feedback will remain forever. Or maybe you could add an option to delete feedback from banned users.

**Comment by JasonBarnabe** [comment]
Current behaviour is intentional.

**Comment by Murka007** [comment]
I hope you will understand and change your opinion about this, because it is really important. There is also bad feedback attacks, group of users who specifically put bad feedbacks on all of my scripts.
