### ISSUE TITLE
"The following scripts had already been imported" points to deleted script

### ISSUE THREAD

**Issue by buenoudg** [JasonBarnabe/greasyfork#1103]
I have two accounts I use (or plan to) to separate personal scripts from scripts I do for my job. Today by mistake I imported a job script from GitHub to my personal GF account. After deleting it (both kinds of "delete") I went to import it to my job GF account, but I got a "The following scripts had already been imported" error message, and a link to the deleted one, although it doesn't look deleted until I follow the link and GF says: "The script you requested has been deleted, but here are some related scripts."

I've solved it adding an innocuous "?greasy=fork" at the end of the GitHub URL, but this should not probably happen, right?

The "already been imported" URL is:
https://github.com/buenoudg/Ajudant-UdGMoodle/raw/master/udgmoodle_participants_student_lists.user.js

**Comment by JasonBarnabe** [comment]
Fixed.
