### ISSUE TITLE
[Feature Request] Include reason why script was deleted by greasyfork in the @description of the script when it does get deleted

### ISSUE THREAD

**Issue by 32423d** [JasonBarnabe/greasyfork#1104]
This script called Amazon CamelCamelCamel and Keepa Injector (https://greasyfork.org/en/scripts/428175-amazon-camelcamelcamel-injector) was deleted from greasyfork and in the code for the script it was stated in the @description "This script was deleted from Greasy Fork, and due to its negative effects, it has been automatically removed from your browser." I have no idea why the script was deleted and whether or not it was because the author had malicious intentions with it. The author (https://greasyfork.org/en/users/762057-sh3ll) still has their account page up so I don't know if their greasyfork account got banned either. If any contributors do not want to add this feature in the future can you please state the reason why this script was removed and whether or not it was because the script was malicious?
![image](https://user-images.githubusercontent.com/95009201/204073434-9116dd3e-2a0c-48b4-a912-30ede2d91dbe.png)

**Comment by JasonBarnabe** [comment]
The author deleted it themselves and chose the option to do this. They did not provide a reason.

If a moderator does this, it's normally only for cases of potential malware.
