### ISSUE TITLE
Working userscript fails to sync

### ISSUE THREAD

**Issue by adamlui** [JasonBarnabe/greasyfork#1111]
My script https://github.com/adamlui/userscripts/blob/master/hide-forum-images.user.js
fails to sync w/ https://greasyfork.org/en/scripts/12639-hide-forum-images.

The code is:
```
// ==UserScript==
// @name             Hide Forum Images
// @version          2023.01.15.1
// @author           Adam Lui
// @namespace        https://elonsucks.org/@adam
// @description      Hides images/videos from XenForo and vBulletin forums.
// @supportURL       https://github.com/adamlui/userscripts/issues
// @license          MIT
// @compatible       chrome
// @compatible       firefox
// @compatible       opera
// @compatible       safari
// @compatible       edge
// @match            http*://*/*
// @grant            GM_addStyle
// @updateURL        https://greasyfork.org/en/scripts/12639/code/youtube-classic.meta.js
// @downloadURL      https://greasyfork.org/en/scripts/12639/code/youtube-classic.user.js
// ==/UserScript==

if (document.querySelector('[src*="vbulletin"]') || document.querySelector('a[href*="xenforo"]')) {
    GM_addStyle('img, [style*="background-image"], [class*="avatar"], [class*="player"] { display:none !important; }');
}
```

The error is:

![image](https://user-images.githubusercontent.com/10906554/212571484-439e7d31-89a3-4b7c-a061-83742bdaa9f9.png)

The script works in all @compatible tested browsers. Anyone know why? Thanks!

**Comment by adamlui** [comment]
It is also happening between https://greasyfork.org/en/scripts/458346-hide-mturk-alerts
and https://github.com/adamlui/userscripts/blob/master/mturk/hide-mturk-alerts.user.js

**Comment by JasonBarnabe** [comment]
Are you actually using the URL https://github.com/adamlui/userscripts/blob/master/hide-forum-images.user.js ? You need to use something that serves up raw JS, like the "Raw" link on GitHub: https://github.com/adamlui/userscripts/raw/master/hide-forum-images.user.js

**Comment by adamlui** [comment]
Thanks for the help, it works now!

**Comment by adamlui** [comment]
As a suggestion, your competitor openuserjs.org doesn't require you to select thee raw code so changing instruction from "provide a URL" to "provide a raw URL" may be more intuitive (or outright allow using the blob url)

**Comment by adamlui** [comment]
Also on a related note, when deleting scripts do I enter the URL for the raw script or the general page in "Enter the replacement script's URL"?

**Comment by JasonBarnabe** [comment]
That feature requires a URL on Greasy Fork. It can handle either the raw URL or the HTML version.

**Comment by adamlui** [comment]
I see, so you can copy the logic to github sync and more people would use it (e.g. those who never noticed failure message) leading to more up-to-date code thus users so ad clicks rise

**Comment by JasonBarnabe** [comment]
Added some logic to handle GitHub HTML view URLs, thanks for the suggestion.
