### ISSUE TITLE
Add Glitch CDN to CDN List

### ISSUE THREAD

**Issue by FlareZ123** [JasonBarnabe/greasyfork#1112]
Hello, I want to use some of Glitch.com's assets. They host a bunch of open source projects with CDN content, so if you can add "https://cdn.glitch.com/*" or some variant to the allowed CDN regexes, that would open up a lot of other libraries that we can use that are all open source. Thanks!

**Comment by JasonBarnabe** [comment]
Can you give some examples of URLs you would like to use?

**Comment by FlareZ123** [comment]
for example, game icon content: https://cdn.glitch.global/1409181a-b781-4d51-b219-d9d9994097b5/stratumspic.png
or https://cdn.glitch.global/1409181a-b781-4d51-b219-d9d9994097b5/valiantio.png?v=1672687568605

**Comment by FlareZ123** [comment]
the regex would just have to check cdn.glitch.global, and check for a valid uuidv4 in the middle. the CDN also includes scripts for other open source libraries. the CDN also hosts js, which is what I would like the regex to allow so we can use libraries from glitch in our scripts. also, if you can, add the glitch CDN mirror "https://content-delivery-network.glitch.me/cdn/*" regex to allow us to request more scripts from there, thanks!

**Comment by JasonBarnabe** [comment]
If Glitch is allowing arbitrary files, it will not be allowed into Greasy Fork's allow list. You will still be able to use content on it by other methods like subresource integity; see https://greasyfork.org/en/help/external-scripts

**Comment by Altanis** [comment]
I agree with @FlareZ123 , it would be much easier for developers to integrate CDNs they host on Glitch.
