### ISSUE TITLE
GitHub commit comments no longer sync if not selecting raw source

### ISSUE THREAD

**Issue by adamlui** [JasonBarnabe/greasyfork#1114]
In #1111 I gave you the idea to allow GitHub sync from HTML URLs. However I tested this out recently (when I moved a script into a subdir) and noticed 2 things:

1. Comments no longer sync with version history
2. A manual sync was required to update on GF (the v2023.01.29 in screenshot)

![image](https://user-images.githubusercontent.com/10906554/215315731-a3666eab-5524-4175-9f5f-68101d2f3aaf.png)

 (v2023.01.29.1+ syncs comments sucessfully because I turned off syncing then re-added the raw source instead)

**Comment by JasonBarnabe** [comment]
What URL are you trying to use?

**Comment by adamlui** [comment]
The URLs I used were copied from address bar when viewing a script on GitHub. So the logic for syncing comments should be modified to locate them correctly if URL is not raw one (also for syncing it should target changes to raw one instead)

Sent from Proton Mail mobile

-------- Original Message --------

**Comment by adamlui** [comment]
Actually for syncing, one of them did it automatically (I think), but the other didn't, leading me to believe it somehow detects changes to raw URLs faster (since when I use raw URL the sync always happens in a second)

Sent from Proton Mail mobile

-------- Original Message --------

**Comment by JasonBarnabe** [comment]
Commit comments are only pulled in when you are using webhooks. If you are using Manual or Automatic syncing, it's just downloading the URL you provide and doesn't know anything about what commit comments you used.

**Comment by adamlui** [comment]
@JasonBarnabe but that's only half the issue, the unresolved half is

> A manual sync was required to update on GF (the v2023.01.29 in screenshot)
