### ISSUE TITLE
Auto-update for Library Dependencies in Scripts

### ISSUE THREAD

**Issue by NuroC** [JasonBarnabe/greasyfork#1115]
As a script author, maintaining updated libraries used in my scripts can be a tedious process. It requires manual updating of the library URLs which can take a lot of time and effort, especially if I have multiple scripts. To streamline this process and save time, it would be great to have an option for automatically updating library dependencies in my scripts.

Having the ability to choose if library URLs should be updated automatically would be a useful feature for script authors. This would ensure that all scripts are using the latest version of the libraries and prevent any potential bugs caused by outdated libraries.

**Comment by JasonBarnabe** [comment]
Many CDNs have an URL that will serve up the latest version of a library. Is that not available for you?

**Comment by NuroC** [comment]
For a greasyfork library

**Comment by NuroC** [comment]
on a greasyfork library, for example https://greasyfork.org/scripts/12345-xxxx/code/xxxx?version=1143850 Always stays the same. Is there a way to capture always the latest version?

**Comment by JasonBarnabe** [comment]
Drop the version param?

**Comment by NuroC** [comment]
Ok, so I just checked and it seems like when I add the @require to the greasyfork library without the version param, it works fine but when I update it and run the script again, the script is using an old version even tho the library was updated.

Is this due browser sessions or smt like that or is there a time period that it takes to update it onto tampermonkey?
