### ISSUE TITLE
Update auto-synced to GF triggers 'Re-install' not 'Update' button

### ISSUE THREAD

**Issue by adamlui** [JasonBarnabe/greasyfork#1118]
Hi,

I made a minor change to the code for https://greasyfork.org/en/scripts/459849-duckduckgpt via https://github.com/adamlui/userscripts/blob/master/chatgpt/duckduckgpt/duckduckgpt.user.js and changed version from 2023.02.13 to 2023.02.13.1

GF auto-synced the code:

![image](https://user-images.githubusercontent.com/10906554/218605773-de370bd6-4f33-456a-8050-0b9c8f288190.png)

...but the button didn't change to "Update to 2023.02.13.1" instead it kept "Reinstall" as the label for some reason. Clicking the button does reveal it's an update though:

![image](https://user-images.githubusercontent.com/10906554/218605863-83449b12-aaff-41b5-b258-b5274b3557a5.png)

**Comment by JasonBarnabe** [comment]
The issue was in the version comparison script - it compared all the parts of the old version to the same-indexed parts of the new version. This did not take into account the case where the new version has additional parts. This should be fixed now. Thanks for reporting.
