### ISSUE TITLE
Raw user.js link doesn't update install counter

### ISSUE THREAD

**Issue by adamlui** [JasonBarnabe/greasyfork#1119]
Hi,

I noticed when I directed users to the raw GF user.js link (either by posting on external site or using URL redirect) the install counter didn't seem to update. Is this intended behavior? If so, may I suggest updating counter for all clicks on GF install links regardless of traffic source, so authors can use them elsewhere (e.g. on GitHub)?

**Comment by JasonBarnabe** [comment]
This is intended behaviour. This is a measure to prevent bots from inflating install counts.
