### ISSUE TITLE
Webhook sync option missing

### ISSUE THREAD

**Issue by adamlui** [JasonBarnabe/greasyfork#1120]
Hi,

I noticed in https://greasyfork.org/en/scripts/459849-duckduckgpt/admin syncing is set to 'Webhook' (I originally selected 'Automatic' iirc):

![image](https://user-images.githubusercontent.com/10906554/221431742-dc454002-ee36-44ca-b7c2-66ea295e4b7f.png)

However, I just added a new script but 'Webhook' is not available @ https://greasyfork.org/en/scripts/460805-auto-clear-chatgpt-history/admin:

![image](https://user-images.githubusercontent.com/10906554/221431792-d9109cda-8514-433a-bafb-d66e06e50126.png)

**Comment by adamlui** [comment]
After my first sync from github (https://github.com/adamlui/userscripts/raw/master/chatgpt/autoclear-chatgpt-history/autoclear-chatgpt-history.user.js) the option appeared (bubble filled in already):

![image](https://user-images.githubusercontent.com/10906554/221450106-fd542d37-a4bc-412b-98d0-33ed1513c9d0.png)

**Comment by JasonBarnabe** [comment]
This is expected and explained in https://greasyfork.org/en/users/webhook-info
