### ISSUE TITLE
Daily install counter inaccurate

### ISSUE THREAD

**Issue by adamlui** [JasonBarnabe/greasyfork#1122]
![image](https://user-images.githubusercontent.com/10906554/224534797-371e979d-7b35-4a3b-b77f-54b72cfa31d2.png)

Something is wrong with the math for https://greasyfork.org/en/scripts/459849-duckduckgpt (and potentially other scripts)

1169 / 29 = 40

**Comment by adamlui** [comment]
Here's some more examples..

![image](https://user-images.githubusercontent.com/10906554/224534984-75aad190-aeaf-4ac5-8589-a56dd4320bf0.png)

2911549 / 2683 = 1085

![image](https://user-images.githubusercontent.com/10906554/224535054-f644f2a9-47e1-449e-90d8-f9cc1f7fb1e4.png)

89295 / 97 = 921

![image](https://user-images.githubusercontent.com/10906554/224535125-71e67b95-4ea1-4f56-a788-00cfd1a5f103.png)

18406 / 2679 = 7

If the equation you're using is for past X period, you should include it for accuracy e.g. "Daily installs (past month)"

**Comment by JasonBarnabe** [comment]
Daily installs is the last 24 hours, not the average number of installs per day.

**Comment by adamlui** [comment]
But if someone asks, "How many installs does your app get a day?" they are obviously expecting an average w/ this question. Since 'daily installs' is the apt descriptor of this specific question, readers of such a label will expect an answer to this question

**Comment by adamlui** [comment]
Here's another example, on Quora my last 30 days is labeled 'this month':

![image](https://user-images.githubusercontent.com/10906554/224817005-ff5e2b37-5092-4008-925d-b40436aa74cc.png)

If we go by your logic, they would need to change it to 'monthly' instead (but don't since 12.4K is not the avg when you divide the 1.1 million)

**Comment by adamlui** [comment]
So sites use [period]ly for avg, and 'last/this/past' for your current formula, and your descriptor should be be accurate for what readers expect from the label (so label should be updated if you want to keep reflecting last 24h, or formula if you want a true daily count that actually mans avg)
