### ISSUE TITLE
[Bug] Scripts 404 when using multiple languages for name/description meta

### ISSUE THREAD

**Issue by adamlui** [JasonBarnabe/greasyfork#1129]
@hqlak47 cannot access any of my scripts on your site, he has to use my GitHub src code instead: https://greasyfork.org/en/scripts/462422-chatgpt-auto-refresh/discussions/177403#comment-381917

> I am a Chinese user, and whether switching between Chinese or English, it is 404, including your other scripts. But it can be installed from GitHub

I suspect this has something to do with I added meta for Chinese users e.g.

```js
// @name:zh-CN          ChatGPT 自动刷新 ↻
// @name:zh-HK          ChatGPT 自動刷新 ↻
// @name:zh-SG          ChatGPT 自动刷新 ↻
// @name:zh-TW          ChatGPT 自動刷新 ↻
// @description:zh-CN   保持 ChatGPT 会话新鲜，消除持续的网络错误 + Cloudflare 检查（全部来自后台！）
// @description:zh-HK   保持 ChatGPT 会话新鲜，消除持续的网络错误 + Cloudflare 检查（全部来自后台！）
// @description:zh-SG   保持 ChatGPT 會話新鮮，消除持續的網絡錯誤 + Cloudflare 檢查（全部來自後台！）
// @description:zh-TW   保持 ChatGPT 會話新鮮，消除持續的網絡錯誤 + Cloudflare 檢查（全部來自後台！）
```

**Comment by JasonBarnabe** [comment]
Is this a 404 on the info page (https://greasyfork.org/en/scripts/462422-chatgpt-auto-refresh) or when installing?

**Comment by adamlui** [comment]
I believe when installing, and the errors went away when he switched from Centbrowser 102 to Chrome 112

**Comment by JasonBarnabe** [comment]
I would be interested in knowing the URL he ended up at and the date/time of the request.

**Comment by JasonBarnabe** [comment]
Can't reproduce. I would guess a Centbrowser issue.
