### ISSUE TITLE
[Possible Bug?] Unable to see Created and Updated dates in script listings on Waterfox Classic

### ISSUE THREAD

**Issue by BattouSaeen** [JasonBarnabe/greasyfork#1130]
So as the title says, for the past couple of months I can't see the date.

The actual code if I inspect it, is there. For example:
<relative-time datetime="2023-04-04T18:11:01+00:00" prefix="" title="Apr 5, 2023, 6:11 AM GMT+12">2023-04-04</relative-time>

![image](https://user-images.githubusercontent.com/4526700/230987847-b2b23761-486c-4e6b-be36-62e93c35fdb6.png)

But it doesn't show up on the actual webpage.

I tried with similar browsers that are of this XUL/XPCOM generation, like the latest Basilisk browser. It shows the dates fine which is a little weird considering they don't support modern browser components at all I think and waterfox classic still has support for web extensions.

I tried with latest Waterfox (current, based on modern Firefox), which also shows the dates fine.

Any ideas why I'm having this issue? I'm posting here because creators of GreasyFork would know better about some compatibilities of scripts maybe. I'll try asking on WF forums as well.

**Comment by JasonBarnabe** [comment]
Greasy Fork uses @github/relative-time-element which has [a few browser requirements](https://github.com/github/relative-time-element#browser-support). I've updated it and some of the changelog entries seem to indicate it may be improved when there is no browser support - what happens now in Waterfox Classic?

**Comment by BattouSaeen** [comment]
> Greasy Fork uses @github/relative-time-element which has [a few browser requirements](https://github.com/github/relative-time-element#browser-support). I've updated it and some of the changelog entries seem to indicate it may be improved when there is no browser support - what happens now in Waterfox Classic?

Awesome, thank you so much! Now it shows the date; the format is in readable "Jul 9, 2021" format (just giving info, not complaining lol).

Just a while ago I found that disabling web components in about:config does the same thing (but format is 2021.07.09).

All in all, it's all good now, thanks again! :)
