### ISSUE TITLE
A very minor issue

### ISSUE THREAD

**Issue by DaTigerYT** [JasonBarnabe/greasyfork#1132]
Just thought I'd report this "bug" (I assume it is, I don't see why it wouldn't be):

![image](https://user-images.githubusercontent.com/35151380/231544251-d5cb0579-a322-42ab-a68a-32fb0dc45f30.png)

The 'Applies to' stat, is in a separate description list.

Moving the 'Applies to' into the script stats dl makes it look like this:

![image](https://user-images.githubusercontent.com/35151380/231545357-13a9b899-9489-4ceb-9d8d-6b3951e2e0b9.png)

I found this, minor bug because I have a large license that makes the right-hand side of the dl a bit too large and thus exposes the bug:

![image](https://user-images.githubusercontent.com/35151380/231545559-628a05da-8a3a-4577-8701-02f0e4d9fe65.png)

**Comment by JasonBarnabe** [comment]
The reason it was like this was so that it could render with the full width. I've updated how the stats are rendered so now it's all in one element.
