### ISSUE TITLE
[Bug] Script no longer auto-syncs

### ISSUE THREAD

**Issue by adamlui** [JasonBarnabe/greasyfork#1133]
My script here https://greasyfork.org/en/scripts/461473-chatgpt-widescreen-mode used to auto-sync w/ GitHub with each push. Then I renamed the GitHub repo (removing '-mode' from name), so re-connected it to adamlui/chatgpt-widescreen (few days ago)

Now, I have to manually click 'Update and sync' after a user [alerted me](https://github.com/adamlui/chatgpt-widescreen/issues/4#issuecomment-1509494362) an auto-sync didn't get triggered by my last GitHub edit few minutes ago

**Comment by adamlui** [comment]
Also the user @nhan000 experienced caching issues in Edge & especially Firefox:

> I had to refresh/uninstall about 5 times and I can update to the new version now. That is with Edge Stable. However, I still can't update the script on Firefox

And then 4 minutes later Firefox worked

> it just updated automatically on Firefox for me. All good now

**Comment by JasonBarnabe** [comment]
Your script is currently set to sync from https://github.com/adamlui/chatgpt-widescreen/raw/main/greasemonkey/chatgpt-widescreen-mode.user.js.

Can you post the GitHub webhook request/response that is triggered when you commit?

**Comment by adamlui** [comment]
> Your script is currently set to sync from https://github.com/adamlui/chatgpt-widescreen/raw/main/greasemonkey/chatgpt-widescreen-mode.user.js.

Yes that is true

> Can you post the GitHub webhook request/response that is triggered when you commit?

No response appears on Greasyfork, I do notice there used to be some "Webhook" option below "The script will be synced" (and I recall pointing out to you before sometimes it shows sometimes it doesn't and you dismissed it as expected behavior)

**Comment by JasonBarnabe** [comment]
No, I need the request/response that GitHub shows - under Settings, Webhooks.

**Comment by adamlui** [comment]
Here's what Settings > Webhooks looks like

![image](https://user-images.githubusercontent.com/10906554/232259116-97c0bf14-3943-4736-b727-40b731c522c9.png)

**Comment by JasonBarnabe** [comment]
If you want it to update immediately, you have to have a webhook set up on that screen. See instructions [here](https://greasyfork.org/en/users/webhook-info).

If you're fine with it periodically checking for updates, then you don't have to do that, but it will only check once a day.

**Comment by adamlui** [comment]
Ok I added it manually, but I distinctly remember never having to take any additional action to immediate-sync (since it is quite memorable to have to copy/paste URLs/secrets & change a default drop-down from `application/x-www-form-urlencoded` to `application/json`) so a bug is still occurring for this latest connection to not programmatically add the webhook

**Comment by adamlui** [comment]
..unless I did a really really long time ago and forgot which is possible

**Comment by JasonBarnabe** [comment]
Greasy Fork never programmatically added the webhook. The only thing it'll do automatically is check for updates if you give it an URL to do so and choose the Automatic option (and again, that's not going to notice changes immediately).

**Comment by adamlui** [comment]
@JasonBarnabe what about the caching issues users like me & nhan000 face do you have an idea for a solution
