### ISSUE TITLE
Fix JS error on update installed script button

### ISSUE THREAD

**Issue by JasonBarnabe** [JasonBarnabe/greasyfork#1139]
https://greasyfork.org/en/discussions/greasyfork/184230-greasyfork-bug-report-javascript-error-when-mouse-over-the-script-install-button

**Comment by cyfung1031** [comment]
This line should be removed?

https://github.com/JasonBarnabe/greasyfork/blob/fc61fea30cb4f9738502cdf0ffda551ed0103dfd/app/javascript/versioncheck.js#L89

or just ignore if this attribute is removed?
