### ISSUE TITLE
Solution to #1124

### ISSUE THREAD

**Issue by cyfung1031** [JasonBarnabe/greasyfork#1140]
## Quoted Issue   #1124
            Greasy Fork will cache the user.js for 60 minutes. It will also clear the cache when the script is updated

              It's happening again, 45mins since update in both TM + VM in Firefox 112.0.2 (64-bit):

              ![image](https://user-images.githubusercontent.com/10906554/236382935-a3c2d384-3da2-4025-9f0c-573ec969788e.png)
              ![image](https://user-images.githubusercontent.com/10906554/236383018-e2b4faff-95d3-4db6-aace-943dd70e2ad9.png)

_Originally posted by @adamlui in https://github.com/JasonBarnabe/greasyfork/issues/1124#issuecomment-1535715492_
            

## Solution I have found

I cannot reply in that open issue. I don't know why.

I would like to tell you that, it might be not GreasyFork issue.

If you use browser's download or fetch feature, you can valid that the file is already updated.

TM cached the script and since the link does not change, the cache remains unchanged.
When browser restarts fully, the cache problem might resolve.

A more direct way is to change to link to force download the latest version.

Here is the solution.

https://greasyfork.org/en/scripts/466746-no-cache-userscript-link-loader

**Comment by cyfung1031** [comment]
I am not sure whether GreaskFork has `no-cache` or `expired = now` to `.user.js` or not. But changing the link is effective.

**Comment by JasonBarnabe** [comment]
This should be fixed now, see #1124.
