### ISSUE TITLE
Illegal Script report gets rejected

### ISSUE THREAD

**Issue by doutatsu** [JasonBarnabe/greasyfork#1145]
Hello,

I and my team have been trying to report a script that illegally modifies the site I own, against the Terms of Service. Every report has been dismissed by a moderator (reason doesn't seem to be provided), which is quite upsetting. The script maker himself has admitted that he violated ToS, yet doesn't want to take down the script. What should be the process in such a situation? 

P.S. Another report for a different illegal script, that does a similar thing has been successfully removed, so I am not quite sure how the moderation action is taken.

**Comment by JasonBarnabe** [comment]
Only those scripts that violate [Greasy Fork's rules](https://greasyfork.org/en/help/code-rules) will be removed.

**Comment by doutatsu** [comment]
As far as I can tell @JasonBarnabe, it does violate the following rule:
> Your script must respect others' copyrights. This includes the code itself and any resources (for example images) it uses. If you intend on using someone else's content, abide by their licensing terms or get their permission before doing so. Licenses on scripts are specified by the @license meta key, and you can learn about what you can and cannot do by using [tldrlegal.com](https://tldrlegal.com/).

The code modifies the site's code, to provide access to the _functionality_ of the site, which is behind a paywall, which in turn makes them use copyrighted code, that they have not made themself. Do correct me if I am wrong

**Comment by JasonBarnabe** [comment]
That rule refers to posting others' code on Greasy Fork itself.
