### ISSUE TITLE
Not receiving confirmation mails

### ISSUE THREAD

**Issue by Jorengarenar** [JasonBarnabe/greasyfork#1148]
I've tried to delete my account; I'm getting "Deletion confirmation email has been sent." notification, but my inbox is empty.
I'd also tried changing to different email, but all I have is "Currently waiting confirmation for: <email address>" while empty inbox.

**Comment by JasonBarnabe** [comment]
Can you send me your user ID, or if you prefer, email? (You can email to jason.barnabe@gmail.com to keep it private).

**Comment by Jorengarenar** [comment]
https://greasyfork.org/en/users/309959-jorengarenar
