### ISSUE TITLE
Changelogs from webhooks not read as markdown

### ISSUE THREAD

**Issue by JasonBarnabe** [JasonBarnabe/greasyfork#1149]
https://greasyfork.org/en/discussions/greasyfork/187119-bug-report-webhook-changelog-message-does-not-contain-the-newlines-as-per-github-commit-message

**Comment by cyfung1031** [comment]
> https://greasyfork.org/en/discussions/greasyfork/187119-bug-report-webhook-changelog-message-does-not-contain-the-newlines-as-per-github-commit-message

Commit would not render as markdown, but it will have hyperlink for commit number and multiline features.
First line is the commit title
Second and more lines is the sub-content.

<img width="880" alt="Screen Shot 2023-06-17 at 7 52 12" src="https://github.com/JasonBarnabe/greasyfork/assets/44498510/06ebf11a-6ebf-43bb-b711-7ad10b98848a">

**Comment by JasonBarnabe** [comment]
Going forward, commit messages from GitHub webhooks will be treated as markdown.
