### ISSUE TITLE
Got `HTTP ERROR 500` trying to update script

### ISSUE THREAD

**Issue by PRO-2684** [JasonBarnabe/greasyfork#1151]
When I tried to update [this script](https://greasyfork.org/zh-CN/scripts/457282), I always got `500` (other scripts seem fine). Here's what happened after I've clicked that `Post new version` button:
- The browser returned `500`.
- The actual code is updated, but the "Updated" time remains the same.
- The displayed description is not updated, but when you try to update again, the editing area of description is what you're trying to save the previous time.
- Also, attachments cannot be uploaded and displayed normally.

**Comment by JasonBarnabe** [comment]
This was because it was trying to record the `@require` you were using. What you have is 263 characters long, but the limit was 256. I've increased the limit.
