### ISSUE TITLE
Please add Toast-UI's CDN

### ISSUE THREAD

**Issue by patarapolw** [JasonBarnabe/greasyfork#1153]
I am trying to \@require [@toast-ui/editor](https://www.npmjs.com/package/@toast-ui/editor#-install)

<blockquote>

TOAST UI products are available over the CDN powered by [NHN Cloud](https://www.toast.com/).

You can use the CDN as below.

```html
<body>
  ...
  <script src="https://uicdn.toast.com/editor/latest/toastui-editor-all.min.js"></script>
</body>
```

If you want to use a specific version, use the tag name instead of latest in the url's path.

</blockquote>

I don't find alternative CDN's like jsDelivr to work.

**Comment by JasonBarnabe** [comment]
Added to https://greasyfork.org/en/help/cdns
