### ISSUE TITLE
Please add npm.elemecdn.com CDN

### ISSUE THREAD

**Issue by starxg** [JasonBarnabe/greasyfork#1157]
[npm.elemecdn.com](https://npm.elemecdn.com) is the CDN of [ElementUI](https://github.com/element-plus/element-plus) company, please add it.

It is a proxy for UNPKG., npm.elemecdn.com is friendly to mainland China.

like this:
```html
<body>
    <script src="https://npm.elemecdn.com/jquery@3.6.4/dist/jquery.min.js"></script>
    <script src="https://npm.elemecdn.com/vue@2.6.1/dist/vue.min.js"></script>
</body>
```

[https://ping.chinaz.com/npm.elemecdn.com](https://ping.chinaz.com/npm.elemecdn.com)

![image](https://github.com/JasonBarnabe/greasyfork/assets/34997494/9022623d-40e6-4309-870b-62aec1dae4fd)

**Comment by JasonBarnabe** [comment]
Added.
