### ISSUE TITLE
HTTPS certificate expired issue

### ISSUE THREAD

**Issue by cyfung1031** [JasonBarnabe/greasyfork#1159]
Experience since Today

1. Occasionally  the website is not accessible.
<img width="765" alt="Screen Shot 2023-07-03 at 1 03 20" src="https://github.com/JasonBarnabe/greasyfork/assets/44498510/403df631-116e-4618-acbe-e75707c81e2a">
<img width="933" alt="Screen Shot 2023-07-03 at 1 08 46" src="https://github.com/JasonBarnabe/greasyfork/assets/44498510/ddda88c9-f70a-42b3-bcc0-af7111766ac8">

<img width="809" alt="Screen Shot 2023-07-03 at 1 12 50" src="https://github.com/JasonBarnabe/greasyfork/assets/44498510/32b05f12-51b2-4e1c-b33c-b4d2b3af25cb">

<img width="869" alt="Screen Shot 2023-07-03 at 1 15 35" src="https://github.com/JasonBarnabe/greasyfork/assets/44498510/9071b11a-b102-45d0-9c9d-6106b6af54b2">

2. It affects Webhook delivery.
<img width="801" alt="Screen Shot 2023-07-03 at 1 10 27" src="https://github.com/JasonBarnabe/greasyfork/assets/44498510/c6badf91-f45e-44ef-a157-6b745a133b21">

**Comment by cyfung1031** [comment]
You are using top-level domain. Instead of Let's Encrypt, you can obtain CloudFlare SSL cert freely.

**Comment by JasonBarnabe** [comment]
This is fixed now, thanks for reporting.

I do have Let's Encrypt, but for some reason I have to restart for the renewal to take effect. If it renews and then I go a while without restarting, then this happens.
