### ISSUE TITLE
Misspelled `@licence GPL3`

### ISSUE THREAD

**Issue by YDX-2147483647** [JasonBarnabe/greasyfork#1163]
In [Script meta keys read by Greasy Fork](https://greasyfork.org/en/help/meta-keys?locale_override=1), the `@license` section, there's an example `@licence GPL3`, which is -ce instead of -se. Is this on purpose?

Besides, I [search the repo](https://github.com/search?q=repo%3AJasonBarnabe%2Fgreasyfork+%40licence+GPL3&type=code) and find it's also misspelled in many localized versions.

Relevant issue: #324

(I can work out a PR if you want)

**Comment by JasonBarnabe** [comment]
Should be `license` as that's the spelling used by the code and by script managers. I've updated it in the English doc and the changes should be reflected in other languages shortly.
