### ISSUE TITLE
Add ChromeXt as a user script manager for Mobile (Android)

### ISSUE THREAD

**Issue by JingMatrix** [JasonBarnabe/greasyfork#1164]
Hello, the project [ChromeXt](https://github.com/JingMatrix/ChromeXt) supports running UserScripts on Chromium based and WebView based browsers, such as `Chrome`, `Egde`, `Brave`, `Bromite`...

Please add it to GreasyFork for users' information.

**Comment by JasonBarnabe** [comment]
I think I would need it to be more polished to include as an option. Those install instructions look scary to me even as a developer.
