### ISSUE TITLE
[BUG report] CDN links starts with @ not allowed

### ISSUE THREAD

**Issue by taozhiyu** [JasonBarnabe/greasyfork#1166]
For example, npm below should be allowed, but did not.
 
https://cdn.jsdelivr.net/npm/@zip.js/zip.js/dist/zip-full.min.js

**Comment by JasonBarnabe** [comment]
For jsDeliver npm URLs, only version-specific URLs are allowed.

https://cdn.jsdelivr.net/npm/@zip.js/zip.js@2.7.20/dist/zip-full.min.js - allowed
https://cdn.jsdelivr.net/npm/@zip.js/zip.js/dist/zip-full.min.js - not allowed
