### ISSUE TITLE
封禁申诉 - Banning appeals

### ISSUE THREAD

**Issue by wdssmq** [JasonBarnabe/greasyfork#1167]
wdssmq：[https://greasyfork.org/zh-CN/users/6865](https://greasyfork.org/zh-CN/users/6865 "wdssmq")

Greasy Fork 有关发布脚本的规则
https://greasyfork.org/zh-CN/help/code-rules

可能不受欢迎的功能
https://greasyfork.org/zh-CN/help/antifeatures

脚本作者不得在 Greasy Fork 的页面，如脚本描述页面，放置广告。**用于推广脚本作者的首页、代码仓库、、微信等内容是允许的。**

虽然不确定「知乎」或者「B 站」以及「爱发电」链接之类的是否在允许范围内；

然后「QQ 群」应该等价于「Discord 交流群」，**当然我也承认直接放在了部分脚本的标题中；**

**Comment by cyfung1031** [comment]
<img width="1182" alt="Screen Shot 2023-09-17 at 1 21 58" src="https://github.com/JasonBarnabe/greasyfork/assets/44498510/782b9154-010a-4e63-af0c-6a324b955cc7">

你被封掉的原因是spam. 可能是名字問題
wdssmq 看起來沒意義像spam一樣
你至少也要用個能拼出來的拼音吧

**Comment by wdssmq** [comment]
@cyfung1031 

我在几乎所有正式注册的网站都使用 **wdssmq** 作为身份 ID，虽然时光能重来的话我会重新想一个。
总之我不认为需要指出一个主要用于与其他账户区分的标识字串是否有意义来作为封禁理由，另外这串字符其实包含了以我姓名为词组的五笔编码；

然后**脚本元信息**应该是为了声明「脚本安装后」将产生的功能或效果，「脚本安装前」用于展示的描述信息（包括标题）则遵循另外的条款；

而且两者均有一定限度的例外，所以现在我需要**明确**我的行为能否被涵盖其中；


`宣传脚本作者的主页、代码仓库、Discord 语音群、微信等信息。`——`@antifeature ads` 例外条款

https://greasyfork.org/zh-CN/help/antifeatures#:~:text=%E5%AE%A3%E4%BC%A0%E8%84%9A%E6%9C%AC%E4%BD%9C%E8%80%85%E7%9A%84%E4%B8%BB%E9%A1%B5%E3%80%81%E4%BB%A3%E7%A0%81%E4%BB%93%E5%BA%93%E3%80%81Discord%20%E8%AF%AD%E9%9F%B3%E7%BE%A4%E3%80%81%E5%BE%AE%E4%BF%A1%E7%AD%89%E4%BF%A1%E6%81%AF%E3%80%82

`在不影响脚本功能的前提下添加作者频道、群或页面等链接`——`@antifeature membership` 例外条款

https://greasyfork.org/zh-CN/help/antifeatures#:~:text=%E5%9C%A8%E4%B8%8D%E5%BD%B1%E5%93%8D%E8%84%9A%E6%9C%AC%E5%8A%9F%E8%83%BD%E7%9A%84%E5%89%8D%E6%8F%90%E4%B8%8B%E6%B7%BB%E5%8A%A0%E4%BD%9C%E8%80%85%E9%A2%91%E9%81%93%E3%80%81%E7%BE%A4%E6%88%96%E9%A1%B5%E9%9D%A2%E7%AD%89%E9%93%BE%E6%8E%A5%E3%80%82

`用于推广脚本作者的首页、代码仓库、Discord 交流群、微信等内容是允许的。`—— 脚本发布页的描述要求；

https://greasyfork.org/zh-CN/help/code-rules#:~:text=%E7%94%A8%E4%BA%8E%E6%8E%A8%E5%B9%BF%E8%84%9A%E6%9C%AC%E4%BD%9C%E8%80%85%E7%9A%84%E9%A6%96%E9%A1%B5%E3%80%81%E4%BB%A3%E7%A0%81%E4%BB%93%E5%BA%93%E3%80%81Discord%20%E4%BA%A4%E6%B5%81%E7%BE%A4%E3%80%81%E5%BE%AE%E4%BF%A1%E7%AD%89%E5%86%85%E5%AE%B9%E6%98%AF%E5%85%81%E8%AE%B8%E7%9A%84%E3%80%82

**Comment by wdssmq** [comment]
@cyfung1031 

在一堆轻小说标题一样的脚本中，尝试加入 QQ 群的我确实心存侥幸，如果能解封会明确修改这一点；

下边是我之前添加在描述中的宣传信息，具体每一项能否符合限度正好作为一个范例；

「擅自认为自己可以」和「你们怎么就是看不懂我定制的规则」之间的矛盾果然是。。。

```md
博客：[https://www.wdssmq.com](https://www.wdssmq.com "沉冰浮水")

爱发电： [https://afdian.net/@wdssmq](https://afdian.net/@wdssmq "沉冰浮水正在创作和 z-blog 相关或无关的各种有用或没用的代码 | 爱发电")

更多脚本： [https://github.com/wdssmq/userscript](https://github.com/wdssmq/userscript "wdssmq/userscript: 各种猴子脚本")

<!-- GreasyFork： [https://greasyfork.org/zh-CN/users/6865](https://greasyfork.org/zh-CN/users/6865 "wdssmq - GreasyFork") -->

QQ 群：[189574683](//jq.qq.com/?_wv=1027&k=jijevXi0 "我的咸鱼心") [![QQ 群](https://pub.idqqimg.com/wpa/images/group.png "QQ 群")](//jq.qq.com/?_wv=1027&k=jijevXi0 "我的咸鱼心")

> wdssmq/rollup-plugin-monkey: 使用 rollup 开发「GM\_脚本」：
>
> [https://github.com/wdssmq/rollup-plugin-monkey](https://github.com/wdssmq/rollup-plugin-monkey "wdssmq/rollup-plugin-monkey: 使用 rollup 开发「GM\_脚本」")

```

**Comment by JasonBarnabe** [comment]
I have unbanned the account and unlocked the scripts. I suggest you do not put QQ groups in the script titles, because this is what spammers do a lot and arguably is spam.
