### ISSUE TITLE
Join GH commit messages with `\n\n` instead of `, `.

### ISSUE THREAD

**Issue by nexushoratio** [JasonBarnabe/greasyfork#1169]
I will often do several commits before pushing a change to GitHub.  As GF currently handles them, they get joined together by a comma and I think, become hard to read.  Often my comments are at least 3 paragraphs: Header/Body/Issue numbers.

I think joining with a comma makes them hard to read.  For example,

```
Reenable no-console lint check.

I do have a habit of having to delete, or almost checking in, errant debug statements.

Issue #66., Enable more eslint rules.

Went through https://eslint.org/docs/latest/rules/#possible-problems and turned on ones that look useful and required minimal changes.

Issue #66.
```

and

```
Change accident var to const., Remove unnecessary local variable., Address easy to deal with eslint errors.

Issue #66., Fix bug introduced by 2df7434a.

Found by eslint. Missed because we do not yet support any views on longer URLs. Well, that and because lack of tests.

Closes #66.
```

I think it would read better if it was a blank line instead.

**Comment by JasonBarnabe** [comment]
Sure, makes sense to do this as these are treated as markdown. It will do this going forward.

**Comment by nexushoratio** [comment]
I *just* noticed this!

Though now I wonder, if '\n--\n' might work better.  :-P

Never can please the masses.  :->

Thanks!
