### ISSUE TITLE
关于脚本的问题

### ISSUE THREAD

**Issue by wzry2580** [JasonBarnabe/greasyfork#1172]
你脚本作者被封禁，或者脚本不可用，那你把脚本下架呀，不然，老访问显示脚本不可用，我也不清楚什么原因，希望解决一下这个问题

**Comment by JasonBarnabe** [comment]
If the author is banned due to a report on the script, the script is deleted immediately.

If the author is banned for a reason unrelated to the script, the scripts will eventually deleted automatically.
