### ISSUE TITLE
Spam Site Pretending Greasy Fork

### ISSUE THREAD

**Issue by cyfung1031** [JasonBarnabe/greasyfork#1175]
https://greasyfork.org/en/discussions/greasyfork/200905-is-monkey-fork-a-variant-of-greasy-fork-like-sleazy-fork

I have also informed collaborators of Tampermonkey, Violentmonkey and FireMonkey to know that there is a spam site pretending Greasy Fork. Currently those userscript managers have no warning or disallowance for the installation from that website.

https://github.com/Tampermonkey/tampermonkey/issues/1850
https://github.com/violentmonkey/violentmonkey/issues/1889
https://github.com/erosman/support/issues/592

(I might delete this issue to avoid getting into trouble from that spam site owner)

**Comment by JasonBarnabe** [comment]
This seems to be a scraped copy of the site at a point in time - the newest script is lag behind what Greasy For khas.Some aspects have been slightly rewritten - the name obviously, some languages have been removed, scripts stripped out and added...

**Comment by cyfung1031** [comment]
@JasonBarnabe 

https://www.whois.com/whois/monkeyfork.com
The website hosts on Gname.com

Abuse Policy
https://www.gname.com/help/295.html

Online Reporting System Of Abuse Domain
https://www.gname.com/abuse?lang=us

**Comment by cyfung1031** [comment]
I have submitted a report to gname.


> monkeyfork.com is a fake website mimics greasyfork.org, a famous site for UserScripts. The imposter uses https://github.com/JasonBarnabe/greasyfork to clone the site under a different domain and site name, duping users by copying usernames and script titles. Although I've reported this to the greasyfork.org owner, he claim he can't intervene. It's crucial to shut down the counterfeit site, as it might spread malware and tarnish the reputation of genuine UserScript authors.

<img width="873" alt="Screen Shot 2023-10-18 at 3 55 37" src="https://github.com/JasonBarnabe/greasyfork/assets/44498510/46a14de1-1678-48ae-b876-0f81e04f19da">

But I think it is better to submit from your side too.

**Comment by cyfung1031** [comment]
Looks like the result is positive.
![Screenshot_2023-10-18-13-07-34-103_com google android gm-edit](https://github.com/JasonBarnabe/greasyfork/assets/44498510/d3d2ebdd-20c8-447a-b2db-36dac9035d70)

**Comment by joeytwiddle** [comment]
Thank you all for the efforts to keep our users safe.

I just want to consider from the other side for a moment:

- What if this person had no intention to spread malware, and simply wants to create a fork? (Which might be good for redundancy, or for experimenting with new features.)

- In this case, what should they have done differently, to dispel concerns and earn trust?

My guess: Change colours, so it looks less like an impersonation. And make it clear who the owner is. Any others?

**Comment by JasonBarnabe** [comment]
> what should they have done differently, to dispel concerns and earn trust?

Made it clear that it was fork of Greasy Fork for purposes x, y, and z, provide a link to the original, not make it look exactly like Greasy Fork, abide by the various licenses involved (both for Greasy Fork and the scripts posted)...

**Comment by JasonBarnabe** [comment]
Looks like it's gone, so closing the issue.
