### ISSUE TITLE
FR: Linkify @license URL

### ISSUE THREAD

**Issue by nexushoratio** [JasonBarnabe/greasyfork#1178]
If the @license is in the form of:
```
// @license License Type; License Homepage
```
(as described at https://sourceforge.net/p/greasemonkey/wiki/Metadata_Block/#license), would it be possible to make that a link on the scripts Info tab?

Or would that open up too many issues?

**Comment by JasonBarnabe** [comment]
We already linkify SPDX identifiers as that describes, but yeah we should support this syntax as well. Didn't know about it before now.

**Comment by cyfung1031** [comment]
> We already linkify SPDX identifiers as that describes, but yeah we should support this syntax as well. Didn't know about it before now.

The current practice in Greasy Fork is not good.

for example, `// @license MIT` means nothing. There is no a license text for others to copy to license.
Usually GitHub will create one LICENSE file for us in every repo, so we should do like this.

`// @license MIT; https://github.com/cyfung1031/Tabview-Youtube/raw/main/LICENSE`

However, this syntax is not supported in Greasy Fork

**Comment by JasonBarnabe** [comment]
Licensing is recommended but optional on Greasy Fork. I am going to support the suggested format, but not require it.
