### ISSUE TITLE
Hard to find webhook information

### ISSUE THREAD

**Issue by nexushoratio** [JasonBarnabe/greasyfork#1179]
I resorted to doing a websearch before I found https://greasyfork.org/en/users/webhook-info .  Hah!  And as I type this, I now see it on the user Control Panel!

It would be nice if it was linked from a script's Admin panel in the Source Syncing section.

**Comment by cyfung1031** [comment]
Agree. 
You might install this script to add the control panel into the navigation bar so that the access would be easier.

https://greasyfork.org/en/scripts/475796-greasyfork-user-control-panel-button

**Comment by JasonBarnabe** [comment]
Added a link when you're not already set up to use webhooks, thanks for the suggestion.
