### ISSUE TITLE
Suggestion - Issue Template for Script Feedback Discussion

### ISSUE THREAD

**Issue by cyfung1031** [JasonBarnabe/greasyfork#1181]
@JasonBarnabe 

(similar to GitHub issue)
Some users want to report the issue in Greasy Fork, but they might not know what to tell to the author.
Then it causes unnecessary back-and-fore discussions.

Also, just giving a "BAD" comment is no use. For giving the bad comment, they have to put the details more. Otherwise it should be just general feedback without BAD.

For good, it is easy, because it works. Nothing to mention.

This also helps reducing spam comments.
And the authors would not just see a "BAD" - "Does not work!" and cannot do the fixing due to no information and no further communication from the user.

### Type of issue
* #### UI Broken
* #### Making Browser Slow / Crash
* #### Conflict with other scripts / extensions
* #### Not working
* #### Other
### Frequency
* #### Always
* #### Sometimes
## Checklist
* ### Have you tried disable all other userscripts and extensions? (Y/N)
* ### Have you tried to use it on other browsers? (Y/N)

## Steps to Reproduce the Issue

# Impact

Users no longer able to give BAD directly without filling the info. (BAD and OK. Both requires explanation with filling the info)
If they just want to fighting hate speech, they can just do it with neutral feedback discussion.

**Comment by JasonBarnabe** [comment]
See #597.
