### ISSUE TITLE
Diff page should escape new lines `\n`

### ISSUE THREAD

**Issue by nexushoratio** [JasonBarnabe/greasyfork#1183]
Probably worth testing all backslash escapes.

https://greasyfork.org/en/scripts/472097-linkedin-tool/diff?v1=1257673&v2=1257136

At the bottom of the page, it reads like this:
```
-              this._log.log('via attributes', record.target, `
-old: ${oldValue}
-new:${newValue}`);
+              this.logger.log('via attributes', record.target, `
+old: ${oldValue}
+new:${newValue}`);
```

The [change](https://github.com/nexushoratio/userscripts/commit/cba012c669f69ccd92055e4824e42b02ec0f5182) here on GH is actually:
```
 -             this._log.log('via attributes', record.target, `\nold: ${oldValue}\nnew:${newValue}`);
 +             this.logger.log('via attributes', record.target, `\nold: ${oldValue}\nnew:${newValue}`);
```

The code view (currently line 2800), renders fine (well, outside of the fact that template literals are not called out at all).

**Comment by JasonBarnabe** [comment]
This is https://github.com/samg/diffy/issues/113.
