### ISSUE TITLE
Google Result might contains `greasyfork.org:4001`

### ISSUE THREAD

**Issue by cyfung1031** [JasonBarnabe/greasyfork#1187]
@JasonBarnabe 

https://www.google.com/search?q=https%3A%2F%2Fapi.iowen.cn%2Ffavicon%2Fget.php%3Furl%3Dgreasyfork.org&oq=https%3A%2F%2Fapi.iowen.cn%2Ffavicon%2Fget.php%3Furl%3Dgreasyfork.org&gs_lcrp=EgZjaHJvbWUyBggAEEUYOjIGCAEQRRg5MgYIAhBFGDzSAQgxMDAzajBqNKgCALACAA&sourceid=chrome&ie=UTF-8

<img width="875" alt="Screen Shot 2023-10-06 at 13 28 01" src="https://github.com/JasonBarnabe/greasyfork/assets/44498510/69dddddb-dc25-4dd8-966d-2f98fb11cf12">

I think only 80 port shall be allowed for people to access.

https://greasyfork.org:4000/
https://greasyfork.org:4001/
https://greasyfork.org:4002/

might be used for testing purpose but not for the access from the public.

Thus the google bot would not able to look inside the contents in these domain also.

**Comment by JasonBarnabe** [comment]
This is indeed for testing, but these will all return the same content as the main domain and this is not a security issue.

I've got a `<link rel=canonical>` without the port, but if Google doesn't listen :man_shrugging:
