### ISSUE TITLE
这个是假网站吗？Is it a fake webstie?

### ISSUE THREAD

**Issue by jasonfall** [JasonBarnabe/greasyfork#1189]
在几个脚本评论区下面看到的，界面几乎照版greasyfork。如果是假冒的，请处理相关账号和评论
https://monkeyfork.com/
https://greasyfork.org/zh-CN/scripts/427628-%E7%99%BE%E5%BA%A6%E7%BD%91%E7%9B%98%E7%A7%92%E4%BC%A0%E9%93%BE%E6%8E%A5%E6%8F%90%E5%8F%96-%E6%9C%80%E6%96%B0%E5%8F%AF%E7%BB%B4%E6%8A%A4%E7%89%88%E6%9C%AC/discussions/205646

**Comment by JasonBarnabe** [comment]
See #1175
