### ISSUE TITLE
Help the developer, if they import from the wrong URL

### ISSUE THREAD

**Issue by joeytwiddle** [JasonBarnabe/greasyfork#1194]
## Problem

I tried to import some scripts today, but I used the wrong URLs to import

Basically I used this URL:

https://github.com/joeytwiddle/code/tree/master/other/gm_scripts/GitLab_Tweaks/GitLab_Tweaks.user.js

When I should have used:

https://github.com/joeytwiddle/code/raw/master/other/gm_scripts/GitLab_Tweaks/GitLab_Tweaks.user.js

But the error message I got was completely confusing. I actually got this screen. But after trying to add descriptions, they still wouldn't import, and kept coming back to this screen!

![Screenshot_20231016_124957](https://github.com/JasonBarnabe/greasyfork/assets/911799/70b5d024-9021-4082-a6d4-152d0bbdc3b9)

## Solutions

1. Detect `https://github.com/[^/]*/[^/]*/tree/` and convert it to `.../raw/` automatically. Problem solved.
2. Alternatively, give the developer some more guidance, because the request to enter descriptions did not solve the problem!

**Comment by JasonBarnabe** [comment]
`https://github.com/joeytwiddle/code/tree/master/other/gm_scripts/GitLab_Tweaks/GitLab_Tweaks.user.js` redirects to `https://github.com/joeytwiddle/code/blob/master/other/gm_scripts/GitLab_Tweaks/GitLab_Tweaks.user.js`, which works if I give it to the importer. I will adjust so both work.
