### ISSUE TITLE
The data dump is missing

### ISSUE THREAD

**Issue by nropgrammer** [JasonBarnabe/greasyfork#1196]
There is no `db.sql.gz` file to download from the data directory referenced [here](https://github.com/JasonBarnabe/greasyfork/wiki/Running-Greasy-Fork-locally#mariadb-setup).

**Comment by JasonBarnabe** [comment]
This is no longer available. I've updated the document.

**Comment by nropgrammer** [comment]
May I ask why? Having a dump of all scripts would be much more preferable to scraping the entire site and using up server resources

**Comment by JasonBarnabe** [comment]
The intent was that it was an easy way to get a normal-ish site if you were going to send in PRs to this repo, but no one ever used it, so I removed it.

API endpoints exist if you want to pull data from the site.

**Comment by nropgrammer** [comment]
I'm aware of the The API (and of I'll be using it) but the API is missing:
- ~~Weekly installs & Daily update checks~~
    - API docs are missing the `stats.json` example 
- User feedback comments
- Userscript info html/markdown
- ~~Userscript version history~~
    - API docs are missing the `versions.json` example 
- Code search
- Userscript libraries

**Additionally the script list API's pagination is broken?**
Currently `https://greasyfork.org/scripts.json?meta=1` counts 36769 scripts, and with `https://greasyfork.org/scripts.json` having 50 results per page, there should be 736 pages of results. The pagination only goes to page 20 though, and `20 * 50 != 36769`. Maybe I am misunderstanding script count?

**Comment by JasonBarnabe** [comment]
If you have specific requests for the API, please create issues for each one.

I'm not sure what you're doing with the data, but keep in mind that you do not necessarily have permission from the creators (barring any explicit permission given by e.g. a license).

**Comment by nropgrammer** [comment]
The data is needed to find all `@require` libraries used. Is the 20 page limit on purpose?
