### ISSUE TITLE
Account e-mail verification never received.

### ISSUE THREAD

**Issue by RokeJulianLockhart** [JasonBarnabe/greasyfork#1198]
I am https://linksta.cc/going/9661?https://greasyfork.org/en/users/1012666:

0.	**https://greasyfork.org/en/users/edit**
	
	> Currently waiting confirmation for: s2qv57+s2qv5b@rokejulianlockhart.anonaddy.com
	
0.	**https://app.addy.io/aliases/65432473-cf46-4e7e-bc3c-b460480d2724/**
	
	> ![image](https://github.com/JasonBarnabe/greasyfork/assets/42837531/f5365bad-ad3a-43ed-8a3c-a4c9f1a091a7)

**Comment by JasonBarnabe** [comment]
I've manually marked your user as confirmed. I've put some tech details in #1199 but appears like the email was blocked due to
> client [2600:3c01::f03c:93ff:fe42:f60e] blocked using zen.spamhaus.org

**Comment by JasonBarnabe** [comment]
It's not easily done because this is an email bounce message.
