### ISSUE TITLE
please add registry.npmmirror.com CDN

### ISSUE THREAD

**Issue by magicdawn** [JasonBarnabe/greasyfork#1201]
this is an unpkg like service based on a npmjs.com mirror.

## example
```
https://registry.npmmirror.com/jquery/3.6.4/files/dist/jquery.min.js
https://registry.npmmirror.com/vue/2.6.1/files/dist/vue.min.js
```

## info
|key|val|
|---|---|
|name| `npmmirror`|
|pattern| `^https:\/\/registry\.npmmirror\.com\/.*`|
|homepage| https://npmmirror.com/|

**Comment by JasonBarnabe** [comment]
Done.
