### ISSUE TITLE
Resolve relative links in imported README to absolute ones

### ISSUE THREAD

**Issue by pke** [JasonBarnabe/greasyfork#1203]
A github hosted README file contains relative links (to the repo) which are not resolved when importing/syncing the file into greasyfork as additional information. A solution would be to give the markdown imported a base url to transform the relative links to absolute (github) links.

**Comment by JasonBarnabe** [comment]
There is logic in the importer to do this already. Do you have an example where it's failing?

**Comment by JasonBarnabe** [comment]
Per above, this is already implemented, but if you can provide an example where it's not working, I can investigate.

**Comment by pke** [comment]
In my newly connected/synched script it does seem to work with relative paths in README.md
