### ISSUE TITLE
Script `History` tab rendering history of wrong script

### ISSUE THREAD

**Issue by nexushoratio** [JasonBarnabe/greasyfork#1204]
The past few days I've noticed that when visiting a history tab for a script, it may use the history (and name) of some random script instead of the one I'm looking at.  At times it feels like it happens more than half of the time.

Sometimes reloading will eventually load the right history.

Which script it does show history for seems to be random, though at the moment, the two tabs I'm looking at show the same history for some unrelated script.  One I'm looking at is a userscript, the other a library.

https://greasyfork.org/en/scripts/478188-nh-xunit/versions
![xunit](https://github.com/JasonBarnabe/greasyfork/assets/6006766/bc43a67b-1678-42ec-8c5d-1167ff03d317)

https://greasyfork.org/en/scripts/472097-linkedin-tool/versions
![lit](https://github.com/JasonBarnabe/greasyfork/assets/6006766/8b8032bf-3221-409e-a4eb-c12b655bedc6)

**Comment by nexushoratio** [comment]
After taking a couple of minutes to file this report, a reload shows a different script:

![lit2](https://github.com/JasonBarnabe/greasyfork/assets/6006766/bd422b93-7d47-4b8e-91df-dc2679c8956e)

Feels like bad values are cached somewhere?

**Comment by nexushoratio** [comment]
I managed to get the history for my own userscript to load.  Then when I loaded my library, it showed me the history of my userscript.

Constantly reloading that page eventually got me the right content there.  Though it bounced between a few different scripts in the mean time.

I wonder: if two browsers are loading different histories at the same time, do they end up seeing the same page?

**Comment by JasonBarnabe** [comment]
> Feels like bad values are cached somewhere

Yup, the cache key was not correctly reading the script ID so whatever request happened first after expiry had its result stored for all scripts.

Your browser differences were likely due to you being logged in on one and not another.
