### ISSUE TITLE
[GreasyFork Server] Please check the script source code file issue

### ISSUE THREAD

**Issue by cyfung1031** [JasonBarnabe/greasyfork#1205]
I can confirm this is due to Greasyfork.org's network response, rather than userscript manager.

1. Using Chrome + Violentmoneky, install a script (e.g. https://greasyfork.org/scripts/479557-youtube-ads-skip/code/YouTube%20Ads%20Skip.user.js)
2. Update the script in Greasyfork.org
3. In Greasyfork.org, confirmed the script is updated to a new version (e.g. 0.2.8)
4. Failed to get the latest version. The response of the network request is 0.2.6, (status 200, without cache).
6. I opened Safari with Private mode (without userscript manager).
7. In Safari, browse the same source code url, I can get the 0.2.8 version. (in-browser text/plain file view)
8. Then after a while, I refresh the source code file tab in Safari Private Mode, it becomes 0.2.3
9. After few minutes, refresh the Safari tab, it becomes 0.2.8 
10. After a while, refresh the Safari tab, it becomes 0.2.6
11. After a while, refresh the Safari tab, it becomes 0.2.8

When the url is changed to like https://greasyfork.org/scripts/479557-hello/code/YouTube%20Ads%20Skip.user.js, it can always get the latest version.

@JasonBarnabe please check the server setting. I cannot think of any reason that the text/plain file can jump across history records. (0.2.8 -> 0.2.3 -> 0.2.8 -> 0.2.6). This is not a cache issue of the browser. My Safari did not open for a week. There is no cache for Safari for the old versions like 0.2.3 and 0.2.6

**Comment by cyfung1031** [comment]
cc @tophf

**Comment by JasonBarnabe** [comment]
This is the same as #1124.
