### ISSUE TITLE
[Bug] Incorrect `@require` url shown in library scripts

### ISSUE THREAD

**Issue by cyfung1031** [JasonBarnabe/greasyfork#1206]
Example

https://greasyfork.org/en/scripts/479598-myjscodelibrary

<img width="828" alt="Screen Shot 2023-11-13 at 17 42 45" src="https://github.com/JasonBarnabe/greasyfork/assets/44498510/cfb54b04-705f-4c4b-ae68-38d5ad99f2c9">

The path https://update.greasyfork.org/scripts/479598/1279054/MyJSCodeLibrary.user.js is invalid.

The correct path is https://update.greasyfork.org/scripts/479598/1279054/MyJSCodeLibrary.js

@JasonBarnabe Please fix

**Comment by JasonBarnabe** [comment]
Fixed in 430fb59596514e4e6a5a5dd570d0da2d03f4cacf.

**Comment by JasonBarnabe** [comment]
I've added update.greasyfork.org to the list of allowed CDNs.

**Comment by WhiteSevs** [comment]
> I've added update.greasyfork.org to the list of allowed CDNs.

ok，现在可以正常同步了
