### ISSUE TITLE
[Bug] SleazyFork.org shows greasyfork's scripts

### ISSUE THREAD

**Issue by cyfung1031** [JasonBarnabe/greasyfork#1207]
https://sleazyfork.org/en/scripts

~The non-adult scripts (which are inaccessible in sleazyfork.org domain) are hosted in greasyfork. They shall not appear in sleazyfork.~
Wrong website is displayed.

## Remarks
Not 100% reproducible. In the above link, sometimes it is sleazyfork and sometimes it is greasyfork.

Can be reproduced in Chrome, Brave, Firefox, but not Safari
(Copy and Paste the link above to access the page)

## Network

<img width="434" alt="Screen Shot 2023-11-13 at 19 22 50" src="https://github.com/JasonBarnabe/greasyfork/assets/44498510/5666b5a4-2037-4b57-bb51-2215fe3fb2f2">

<img width="629" alt="Screen Shot 2023-11-13 at 19 23 00" src="https://github.com/JasonBarnabe/greasyfork/assets/44498510/cd0b9fb6-6ab6-4116-8662-538dba96e648">

<img width="989" alt="Screen Shot 2023-11-13 at 19 23 24" src="https://github.com/JasonBarnabe/greasyfork/assets/44498510/b3a483c7-b389-4326-9e00-981c805ca1cc">

## Video

https://github.com/JasonBarnabe/greasyfork/assets/44498510/44492e6f-b337-44a2-ab2a-6e51eab2ddfc

**Comment by JasonBarnabe** [comment]
This was a caching issue and should be fixed now.
