### ISSUE TITLE
webhook push 502

### ISSUE THREAD

**Issue by WhiteSevs** [JasonBarnabe/greasyfork#1208]
![image](https://github.com/JasonBarnabe/greasyfork/assets/50544447/f4348b1b-ddd8-44d5-b090-d764f71feed5)

**Comment by a1mersnow** [comment]
Same problem...
Here is my settings:
<img width="528" alt="image" src="https://github.com/Tampermonkey/tampermonkey/assets/13799160/1bf75926-3b1b-4589-891b-434da56493df">
<img width="820" alt="image" src="https://github.com/Tampermonkey/tampermonkey/assets/13799160/46e4de23-2bf9-4b7a-9199-e7ec863891f1">

When a release is created, released, published, it will send three requests:
<img width="789" alt="image" src="https://github.com/Tampermonkey/tampermonkey/assets/13799160/13db7932-8a81-487b-99ef-d58a251c6f2e">
However, the last one always failed.

And, there is no error message telling me why:
<img width="844" alt="image" src="https://github.com/Tampermonkey/tampermonkey/assets/13799160/59ddd01c-5472-4b37-9b06-7d2b2c75028b">

**Comment by JasonBarnabe** [comment]
502 is a temporary thing, it should be better now.

**Comment by a1mersnow** [comment]
@JasonBarnabe What I got is a `500`, it still doesn't work now.

**Comment by JasonBarnabe** [comment]
Please post a new issue and include the time your request happened, the request data, and the response data.
