### ISSUE TITLE
400error

### ISSUE THREAD

**Issue by shenchanran** [JasonBarnabe/greasyfork#1210]
Some scripts get 400 error when click the install button.

https://greasyfork.org/zh-CN/scripts/437781

https://update.greasyfork.org/scripts/437781/%F0%9F%A5%87%E8%B6%85%E6%98%9F%E5%AD%A6%E4%B9%A0%E9%80%9A%E7%BD%91%E8%AF%BE%E5%B0%8F%E5%8A%A9%E6%89%8B%7C%E4%BF%AE%E5%A4%8D%E8%A7%86%E9%A2%91%E6%92%AD%E6%94%BE%7C%E8%87%AA%E5%8A%A8%E8%B7%B3%E8%BD%AC%E4%BB%BB%E5%8A%A1%E7%82%B9%7C%E7%AB%A0%E6%B5%8B%.user.js

**Comment by JasonBarnabe** [comment]
This should be fixed now, thanks for reporting. It was trying to limit the length of the URL but was cutting it in middle of an escape code. The URL you posted won't work, but the site is now offering a working URL.
