### ISSUE TITLE
Can you add an option to let users move to the support site for discussions?

### ISSUE THREAD

**Issue by cyfung1031** [JasonBarnabe/greasyfork#1214]
Currently there is a discussion page for each userscript.
However, as we have the support site like github
We have specified it in '@supportURL' etc

When the users try to start a discussion in the userscript discussion page, can you add a alert dialog to let them create the issue in the support site like github? (It can be an option set in userscript admin)

(2nd option)
Or can it be disabled such that the discussion will be always in the support site? The users can still leave good ok bad ratings if they want. 

main reasons as follows:
1. Most developers prefer github more for issue control and organization
2. It would be messy and confusing to monitor both sides
3. Greasy fork forum can offer limit features for discussions,  and also not editable after few minutes
4. Most users just raise a problem and dont follow up.  Even if the developer has solved the issue,  the developer can not close the issue in GF forum.  
5. Their ratings might be just due to the temporary bugs.  In GF, if the users are not active or do not know how to change it back to good after bug fixing,  the ratings will be in a disaster

**Comment by JasonBarnabe** [comment]
There's already a link, e.g. https://greasyfork.org/en/scripts/241-test-support-url/feedback#post-discussion. You're just asking to make it more strongly worded/prominent?

**Comment by cyfung1031** [comment]
> There's already a link, e.g. https://greasyfork.org/en/scripts/241-test-support-url/feedback#post-discussion. You're just asking to make it more strongly worded/prominent?

That just like a link 
It is no use

People always ignore it

**Comment by JasonBarnabe** [comment]
Best you're going to get is a suggested link. I'm not going to disable the ability to post discussions.
