### ISSUE TITLE
Clicking the links too fast will generate the error message

### ISSUE THREAD

**Issue by cyfung1031** [JasonBarnabe/greasyfork#1215]
```
We're down for maintenance. Check back again soon.
```

<img width="428" alt="Screen Shot 2023-12-02 at 23 21 33" src="https://github.com/JasonBarnabe/greasyfork/assets/44498510/e3c73686-0a51-4b22-ae1a-254e347b304a">

The page will restore after refreshing.

**Comment by JasonBarnabe** [comment]
This is due to some strict rate limiting I put in place to counter a DDOS attack. I've loosened things up a bit, but this is just changing what "too fast" means.
