### ISSUE TITLE
[Request] Add unique version control in HTML

### ISSUE THREAD

**Issue by cyfung1031** [JasonBarnabe/greasyfork#1218]
<img width="674" alt="Screen Shot 2023-12-05 at 9 07 08" src="https://github.com/JasonBarnabe/greasyfork/assets/44498510/ce64d2b8-ccfc-414a-bb1b-ebfea774d729">

I have a userscript to add a button in the list
<img width="1009" alt="Screen Shot 2023-12-05 at 9 08 06" src="https://github.com/JasonBarnabe/greasyfork/assets/44498510/5a215f72-8f7b-4d23-a53e-453da0033859">

But the LI element does not contain the version control information for me to generate the link like
`https://update.greasyfork.org/scripts/481384/1290420/Grid%20Smartschool.js`
as the version is not provided in the LI element dataset.

Could you please add it to the LI element dataset, like `data-script-unique-version`

Thanks

**Comment by JasonBarnabe** [comment]
So basically you just want the script's installation URL to be a data attribute there?

**Comment by cyfung1031** [comment]
> So basically you just want the script's installation URL to be a data attribute there?

Yes. 
It can be the whole url or just the version number
