### ISSUE TITLE
[Bug] Wrong Counting of Comment Rating. Might be due to cache issue

### ISSUE THREAD

**Issue by cyfung1031** [JasonBarnabe/greasyfork#1227]
<img width="717" alt="Screen Shot 2024-01-12 at 7 28 55" src="https://github.com/JasonBarnabe/greasyfork/assets/44498510/7e3c13e8-9c46-4bcf-a347-30fac8833390">
<img width="760" alt="Screen Shot 2024-01-12 at 7 29 05" src="https://github.com/JasonBarnabe/greasyfork/assets/44498510/79782e88-6a06-4527-9ec4-13d94721f7f5">

Previously it was OK. Then become GOOD now.

The counting is still OK, not GOOD.

**Comment by JasonBarnabe** [comment]
https://greasyfork.org/en/scripts/484611-youtube-audio-only

**Comment by cyfung1031** [comment]
the cache refreshed after around 10 minutes and become normal again.

**Comment by JasonBarnabe** [comment]
This is the current intended behaviour - these counts are only refreshed once an hour.
