### ISSUE TITLE
Source code synchronization problem

### ISSUE THREAD

**Issue by songbaicheng** [JasonBarnabe/greasyfork#1229]
Source code synchronization cannot synchronize code from Gitee

**Comment by JasonBarnabe** [comment]
Can you provide an example URL you're using? As long as the URL returns a JS file, it should work.

**Comment by songbaicheng** [comment]
This is my using URL:[https://gitee.com/songbaicheng/tampermonkey-script/raw/master/seer/SeerHelper.use.js](url),you can try it.

**Comment by JasonBarnabe** [comment]
I was able to import without issue - https://greasyfork.org/en/scripts/484947-seer-helper

**Comment by songbaicheng** [comment]
I have synced successfully because I used @updateURL and @downloadURL incorrectly. Thank you very much.
