### ISSUE TITLE
Moderator and Team Manager

### ISSUE THREAD

**Issue by Justman100** [JasonBarnabe/greasyfork#1238]
@JasonBarnabe

Hi, would like supporting GreasyFork as Moderator on greasyfork.org and Team Manager in [the Transifex Project](https://app.transifex.com/greasy-fork/greasy-fork/)

**Comment by Justman100** [comment]
@JasonBarnabe

**Comment by JasonBarnabe** [comment]
Please email me at jason.barnabe@gmail.com and explain your any related previous experience (development-wise or moderator-wise).

**Comment by Justman100** [comment]
> Please email me at [jason.barnabe@gmail.com](mailto:jason.barnabe@gmail.com) and explain your any related previous experience (development-wise or moderator-wise).

No answers anymore?

**Comment by Justman100** [comment]
> Please email me at [jason.barnabe@gmail.com](mailto:jason.barnabe@gmail.com) and explain your any related previous experience (development-wise or moderator-wise).

There?

**Comment by Justman100** [comment]
@JasonBarnabe
