### ISSUE TITLE
Are you allowed to upload AI/ChatGPT generated scripts to Greasyfork?

### ISSUE THREAD

**Issue by VillainsRule** [JasonBarnabe/greasyfork#1251]
I'm not sure of the best place to ask this, please direct me if this isn't.

I see so many AI generated scripts (I can tell from the AI comments and integration: most don't work) filling the list for some sites. This really clogs lists and hides scripts that should be up in the spotlight because they actually work. Do I have to live with this, or can I somehow report AI generated userscripts?

Thanks!

**Comment by JasonBarnabe** [comment]
There are currently no rules about AI generated scripts.

Do you have any way to prove it's AI?
