### ISSUE TITLE
FireMonkey: window.external userScript vs userStyle

### ISSUE THREAD

**Issue by erosman** [JasonBarnabe/greasyfork#1353]
Hi Jason

FireMonkey supports userScript, userCSS & userStyle.

- `==UserCSS==` has a userscript type metadata block
- `==UserStyle==` is similar to Stylish/Stylus

Subsequent to #1348, since userScript & userStyle have different buttons, I have updated the code to show new variables

### window.external.FireMonkey
```js
{
  version: '2.74',
  installedScriptVersion:'1.2.3',     // or undefined
  installedStyleVersion:'1.2.3',      // or undefined 
  installedCSSVersion:'1.2.3',        // or undefined
}
```

What do you think?

**Comment by JasonBarnabe** [comment]
Currently Greasy Fork only supports the `==UserStyle==` style meta block. Is there significant usage of `UserCSS`, and how is it different?

The detection logic for Stylus works differently than for user JS - it is based on `postMessage`. https://github.com/greasyfork-org/greasyfork/blob/b86847b3cba674918b8d8f52789aee3a37758701/app/javascript/managers.js#L18-L36

I'm not sure if for consistency's sake you want to act like Stylus or if you want it treated like JS.

**Comment by erosman** [comment]
> Currently Greasy Fork only supports the ==UserStyle== style meta block. Is there significant usage of ==UserCSS==, and how is it different?

Although it has been discussed on GreasyFork and Stylus repo, there aren't many users, except for FM users who write their own. 
(see [FireMonkey: Metadata Block](https://erosman.github.io/firemonkey/src/content/help.html#metadata-block))

Since, it is only a visual change, FM can change the data on the button, for now.

You can also try something like ....

```js
export async function canInstallUserCSS() {
  const fm = getFiremonkey();
  if (fm?.installedStyleVersion) {
    return true;
  }

  if (localStorage.getItem('stylusDetected') == '1') {
    return true;
  }
  postMessage({ type: 'style-version-query', name: "whatever", namespace: "whatever", url: location.href }, location.origin);
  return new Promise(resolve => setTimeout(function() {
    resolve(localStorage.getItem('stylusDetected') == '1')
  }, 200));
}
```

Similar thing can be done in `versioncheck.js`

**Comment by erosman** [comment]
Actually, scratch that....

It can be done quite simply based on the current code by simply reflecting the JS button on the CSS button in case of FireMonkey.

- process the JS button as it is
- if (FireMonkey && CSS button) { set the same on the CSS button }

**Comment by erosman** [comment]
Please also note that the button texts might need to better differentiate JS & CSS

![image](https://github.com/user-attachments/assets/863f914e-8c2a-4bbd-bd0c-70d7f101404f)

An idea ...

![image](https://github.com/user-attachments/assets/047e6c10-587e-4f31-92f6-31a307b052ae)

**Comment by JasonBarnabe** [comment]
I would like to have the JS and CSS buttons be separate checks. The updates I envision to the CSS button:

1. Have the `canInstallUserCSS` function return true if `getFiremonkey` returns not null - this will avoid the explanatory modal if FireMonkey is installed.
2. Adjust `checkForUpdatesCSS` to look at `getFireMonkey().installedStyleVersion` first before firing a message the Stylus may be listening for.

**Comment by erosman** [comment]
OK... I have updated the FM code to show either `installedScriptVersion` or `installedStyleVersion`.

**Comment by JasonBarnabe** [comment]
Yes, it will check and handle each separately.

**Comment by erosman** [comment]
Tested and working.

![image](https://github.com/user-attachments/assets/1dabd763-87b5-4a17-b697-8f3c3a499c0a)

![image](https://github.com/user-attachments/assets/ddeb0272-cc15-465c-9023-318159a65181)
