### ISSUE TITLE
Cannot register using GitHub account

### ISSUE THREAD

**Issue by Lorentz83** [JasonBarnabe/greasyfork#195]
On the login page, when I click on "Sign in with GitHub" I'm redirected to github page and I grant access to the app.
But when I'm redirected back to GreasyFork I see the the error "GitHub sign in failed."

**Comment by S-ed** [comment]
Why does "Greasy Fork requires an email" ?
I mean, is it necessary?

**Comment by JasonBarnabe** [comment]
No, but I've found that if I don't make people provide an e-mail, then I get a few people every week who get themselves locked out of their accounts.

**Comment by S-ed** [comment]
Are those used Login+Password combination or binded their accounts to GitHub?

**Comment by JasonBarnabe** [comment]
Little bit of both. I've just found not having an e-mail on accounts to cause more problems than it prevents. If it really bothers you, you can put in a fake e-mail. It's not like they need to be verified.

**Comment by S-ed** [comment]
Well.
I'm expecting problems with login using GitHub.
Even while I've set my email there and disabled "Keep my email address private" checkbox, I'm still getting

```
Greasy Fork requires an email to make a new account, but GitHub didn't provide one for you. You can either update your GitHub account to have one, then try signing in again, or create a normal email/password account on Greasy Fork, then add your GitHub account to it.
```

**Comment by JasonBarnabe** [comment]
So you created an account with a login/password, associated that account to GitHub, then get that message when you try to log in with GitHub?

**Comment by S-ed** [comment]
Nope. Thought I could skip the phase "created an account with a login/password". -_-
