### ISSUE TITLE
Permenant Deletion of Script

### ISSUE THREAD

**Issue by TimidScript** [JasonBarnabe/greasyfork#201]
Permanently deletion of your script? 

I am a big supporter of privacy and access control to ones own content. The ability to delete without trace your script, beside hiding it, should be a standard function.

Also maybe the closing of one's account.

**Comment by JasonBarnabe** [comment]
Revisiting this, I can see why someone would want to permanently delete their account or script. These are the problems with doing so:

1. Referential integrity. Deleting a user requires deleting their scripts, their discussions, their comments, etc. Deleting a script requires deleting its versions, code, stats, discussions, etc.
2. Hiding malware. As previously mentionned, someone could make a malware script, get some installs, then delete it. We'd be none the wiser and wouldn't be help people who installed it.
3. Removal of content creates nonsense. If two people are discussing something in the forum and one of them deletes their content, then that discussion becomes meaningless.

I can handle 1 and I can live with 3, but we would need something for 2. A moderator confirmation may be the solution.

**Comment by tobias-engelmann** [comment]
I had some Ideas and thoughts on deleting a user in [Delete user](https://github.com/JasonBarnabe/greasyfork/issues/264#issuecomment-55967149).

Regarding point 3: this is possible now as you allow to edit your own posts without limitations.

**Comment by TimidScript** [comment]
Maybe countdown timer. A month or 3 months before it gets removed. If it has not been registered as malicious script before then, I doubt it will ever be.

**Comment by TimidScript** [comment]
Is there any news on this? The countdown timer, before permanent deletion should be more than enough for malware. If a malicious script has not been reported within 3months, then it won't be reported at all. So if user selects to delete the script, the script goes into a recycle bin and a countdown timer begins. After x period the script get removed, maybe after a last confirmation message from the author. 

As to the issues raised:
1) Referential Integrity: I do not see why discussions are important after the script is deleted. Currently if the script gets deleted, a user can still access the scripts posts but unable to access the script. Maybe, have a dummy script for all versions. Therefore discussions and comments remain on the forum, but the actual script file, descriptions all point to the same dummy script/description. 
Example here: https://greasyfork.org/en/forum/discussion/199/x (Excuse the title of the script, I had a bad day)

So it makes little difference in essence to the integrity that currently exists. The script gets deleted not the posts. As for deletion of user. Give a countdown timer, but a longer one without a last minute confirmation as a user that wants to delete his account isn't going to comeback to comeback to confirm it. Username is kept but nothing else. So posts can remain and the username is preserved. 

Also one has to look at the EU data retention laws. One has the right to be forgotten. 

2) Few months (3?) countdown period is more than enough time for user to spot a malicious script and also give the author time to change his mind and remove the script from permanent deletion countdown.

3) Go back to 1. Deletion on scripts is normal and should be supported.

**Comment by JasonBarnabe** [comment]
No news. This is a low priority item for me. Feel free to put together a PR if you're able.

**Comment by TimidScript** [comment]
PR - Public Relation?

**Comment by JasonBarnabe** [comment]
Pull request.

**Comment by JasonBarnabe** [comment]
Looking into this now, I can see two pieces of data related to a script that won't be deleted.

1. Moderator log - this should be a non-changing log of what mods are doing. If a script gets deleted that's in the log, it would show "(deleted script)" and not link anywhere.
2. Forum discussions - as these are generally started by other people, it's not appropriate to delete them. These would show deleted scripts in a similar manner.

**Comment by JasonBarnabe** [comment]
You can now request permanent deletion from the delete screen. A moderator will review your request and delete the script or reject the request. The only reason I can see someone rejecting the request is if this is done to hide malware or other malfeasance.

**Comment by TimidScript** [comment]
Thank you
