### ISSUE TITLE
Script Icon

### ISSUE THREAD

**Issue by TimidScript** [JasonBarnabe/greasyfork#213]
Use icon from the script in main listing.

**Comment by JasonBarnabe** [comment]
I believe that the security issues with this can be worked through.

I still don't see much benefit to this and many possible drawbacks. Assuming people would use this "properly" then you've got icons all over the place that don't add any information on top of what the title/description already have. In the real world, there will be confusing, stolen, unintelligible, etc. icons.

So at best I would consider this "not worth it". If someone really wants icons, then I could add some markup that would include the `@icon` value and you could write a user script to show it. Please create a new issue if that interests anyone.
