### ISSUE TITLE
Hidden/Deleted/Unlisted New Discussion Threads

### ISSUE THREAD

**Issue by TimidScript** [JasonBarnabe/greasyfork#235]
Hidden/Unlisted/Delete script discussion feedback posts should not be displayed under the main "Script Discussion" thread. They should remain hidden and only accessible through the scripts page.

Example of a "deleted" script posting:
https://greasyfork.org/scripts/3313-do-not-install/feedback

(The post were added after the script got "deleted").

**Comment by JasonBarnabe** [comment]
Hidden just means not showing up in the site listings. There's lots of ways people can still end up on it. If you want "secret", I suggest hosting it on your own server.
