### ISSUE TITLE
filters by sites in users' page should only contain domains mentioned by this author

### ISSUE THREAD

**Issue by tiansh** [JasonBarnabe/greasyfork#255]
On the right of page for some user, filters by sites are listed as same as what they are on scripts list page. But maybe, someone only post scripts to example.com and example.net. Listing "baidu.com", "youtube.com" to the filters list of this user's page have nothing to do for visitors, since this user (author) have no script on these sites.

**Comment by JasonBarnabe** [comment]
Fixed now.
