### ISSUE TITLE
Forum Markdown: Link the syntax directly in the post add field.

### ISSUE THREAD

**Issue by tobbexiv** [JasonBarnabe/greasyfork#262]
Like on Greasy Fork or GitHub: Provide a link to the Markdown specification used by the forum directly in the post add form.

**Comment by JasonBarnabe** [comment]
http://vanillaforums.org/discussion/29299/is-there-a-doc-for-what-markdown-html-etc-is-allowed

**Comment by JasonBarnabe** [comment]
I created https://github.com/vanilla/vanilla/issues/6979 . If Vanilla does this then we will get it on upgrade, but I'm not going to do this myself, so closing this issue.
