### ISSUE TITLE
Greasy Fork -> Forum: no auto-login in some cases

### ISSUE THREAD

**Issue by tobbexiv** [JasonBarnabe/greasyfork#288]
Yu are not automatically logged in to the forum if you're logged in to Greasy Fork and then switch to the forum from a script discussion site.

**Comment by JasonBarnabe** [comment]
After some discussions on the Vanilla GH, the process of logging in with jsConnect should be much more smooth when you tell Vanilla it's the default sign in method. Unfortunately, this is broken in 2.1, but supposedly fixed in 2.2. So I guess we'll wait for that.

**Comment by Mottie** [comment]
For some reason, today I can not sign in to the Greasy Fork forums (Chrome only). I can log into Greasy Fork using my GitHub account, but when I click on the "sign in" button, it says I'm already signed it... it just keeps happening.

![gf](https://cloud.githubusercontent.com/assets/136959/16027123/2ada68bc-3199-11e6-8672-afda56be5998.gif)

I switched over to using Firefox, and first try it logs me in.

**Comment by JasonBarnabe** [comment]
@Mottie that issue should be fixed - #429.

**Comment by JasonBarnabe** [comment]
The problem as originally reported still exists, and we're on 2.2 now.

**Comment by JasonBarnabe** [comment]
I have filed this as https://github.com/vanilla/addons/issues/614. This is not an issue with the code in this repo, so closing.
