### ISSUE TITLE
Redirect one script to another

### ISSUE THREAD

**Issue by JasonBarnabe** [JasonBarnabe/greasyfork#295]
Ability to redirect all resources for a script to another, in case of a duplicate.

**Comment by devnoname120** [comment]
Any update on this issue?

**Comment by JasonBarnabe** [comment]
Nope. If there was, I would post here.

**Comment by JasonBarnabe** [comment]
OK, this is in now. I can't seem to find a case where we wanted to do this and the author agreed...

**Comment by devnoname120** [comment]
NoPicAds was superseded by AdsBypasser, but this first was eventually manually deleted.
Since this was linked in quite a few locations, I reckon that many users get on a dead link.

**Comment by JasonBarnabe** [comment]
@legnaleurc can undelete, then redelete and set AdsBypasser as the replacement.

**Comment by legnaleurc** [comment]
I'll give it a try, thank you.

**Comment by JasonBarnabe** [comment]
@legnaleurc let us know how it does.

[Zod-](https://greasyfork.org/en/users/1033-zod) marked https://greasyfork.org/en/scripts/918-instasynch-addons as replaced by https://greasyfork.org/en/scripts/5653-instasynchp-core so we can test it out with that too.

**Comment by legnaleurc** [comment]
What will happen if I check *Users who previously installed this script will be updated to a blanked-out version.* and setup a redirection URL?

**Comment by JasonBarnabe** [comment]
People updating will get blanked out. Visitors to the pages on Greasy Fork will get redirect to the other script.

**Comment by JasonBarnabe** [comment]
This works as expected as far as I know. If there's any problems, please create a new issue.

**Comment by devnoname120** [comment]
Would it be possible to make the new script appear in searches as well?
Example: https://greasyfork.org/scripts/search?q=nopicads (Expected: AdsBypasser appears here.)

**Comment by JasonBarnabe** [comment]
No, I don't think that'd be worth it. If you want to show up with that keyword, included in your additional info somewhere.

**Comment by devnoname120** [comment]
Would it not help users to find a superseded script, without cluttering the description?

**Comment by JasonBarnabe** [comment]
It could, but it's also weird that one author could essentially add keywords for another's scripts. If the other author wants to show up with that keyword, they can mention it.
