### ISSUE TITLE
Add compatibility info

### ISSUE THREAD

**Issue by JasonBarnabe** [JasonBarnabe/greasyfork#30]
Let authors specific install methods/browsers, doesn't work/untested/works.

**Comment by JasonBarnabe** [comment]
To get this moving again, I propose supporting version and user script compatibility info in such a way that it's easy to ignore for implementors who don't care, but can be defined by implementors who do. Here's the full proposal:

- Two keys: `@compatible` and `@incompatible`, with the format `@compatible <browserinfo> <comments>`
- Browserinfo will start be a browser identifier (e.g. "firefox", "chrome", "opera"), possibly followed by more descriptive info for user script engine, versions, etc. The syntax for the more descriptive info is to be determined. Only one browserinfo per `@compatible`/`@incompatible` line.
- Comments is optional - contains text that provides more info on the compatibility.
- Absence of `@compatible` and `@incompatible` for a browserinfo implies "untested/unknown".

Here's a simple example:
```
@compatible firefox
@compatible chrome Everything works except the auto-resize feature
@incompatible opera
```

More complex example with an example descriptive info syntax inspired by @derjanb's comments:

```
@compatible firefox+gm
@incompatible firefox+scriptish Scriptish does not have the GM_doIt function required by this script.
@compatible chrome(35+) Everything works except the auto-resize feature
@incompatible chrome(30-35)
@incompatible opera
```
So if someone just cares about the browser, they can check to see what the browser info string starts with (or grab it up to the first punctuation) and use that. If you do care, grab the whole thing and parse it. I'm not defining a particular syntax for this section because I don't intend to use it; defining it can be done separately so it doesn't block the initial implementaiton.

**Comment by JasonBarnabe** [comment]
This has been implemented on Greasy Fork. Let me know your thoughts.

**Comment by jesus2099** [comment]
Hi Jason,
I tried [those compatibility metadata lines](#issuecomment-75478176) but I don’t know where to look at.
I don’t see any changes on [the script page](https://greasyfork.org/fr/scripts/2334-mb-funkey-illustrated-records).

**Comment by JasonBarnabe** [comment]
I don't understand why it didn't work there. I tried [the same thing (though a webhook)](https://greasyfork.org/en/scripts/2375-mb-funkey-illustrated-records) and it worked. If you click for the most recent version of your script, you can it see working too - https://greasyfork.org/en/scripts/2334-mb-funkey-illustrated-records?version=41884.

I wonder if I forgot to restart delayed_job after I made that change. That would mean the webhook code was running on the old code.

**Comment by jesus2099** [comment]
OK so it means that it will work with my next version, then.
Thanks for testing. :)

**Comment by JasonBarnabe** [comment]
Looks like it works on https://greasyfork.org/en/scripts/2375-mb-funkey-illustrated-records now.

If anyone has problems or suggestions, please start a new issue.
