### ISSUE TITLE
Allow posting about a script from the forum

### ISSUE THREAD

**Issue by JasonBarnabe** [JasonBarnabe/greasyfork#301]

**Comment by JasonBarnabe** [comment]
https://greasyfork.org/forum/discussion/3282/start-a-discussion-about-a-script-from-the-forum#latest

**Comment by tophf** [comment]
Is it possible to use browser referrer to determine which script page a user came from and use it to fill the link automatically?

**Comment by JasonBarnabe** [comment]
The only way to go directly from a script page to a new discussion page is to click the "discuss this script" link, which associates it automatically.

**Comment by tophf** [comment]
I meant the following typical scenario:
1. open the script feedback page
2. click some discussion (the latest, for example) to read it
3. click New Discussion to post about this script

So the referrer should be remembered as a cookie when a user visits the forum coming from a script page for the first time (step 2), then this link is used to fill the script link in New Discussion.

**Comment by tophf** [comment]
The New discussion button clicked on a forum page with an "About: some script" subtitle should autofill the script field. Seems an easy thing to do: just add a custom url parameter to the New discussion button's link.
