### ISSUE TITLE
Forum emails have wrong language

### ISSUE THREAD

**Issue by tobbexiv** [JasonBarnabe/greasyfork#310]
I got a email from the forum that I was mentioned in a thread. This email was in Spain, but my prefereed language and also the detected language were German at this time. It might be the case that the language preference was fetched either from the other user or just randomly set.

Thread I was mentioned in: https://greasyfork.org/de/forum/discussion/comment/6743/#Comment_6743

**Comment by Owyn** [comment]
https://greasyfork.org/zh-CN/forum/discussion/comment/8519#Comment_8519

+1 yes please fix this.

**Comment by JasonBarnabe** [comment]
This is fixed in the new forum solution as is not going to be fixed in Vanilla.
