### ISSUE TITLE
Improve github commit message copy

### ISSUE THREAD

**Issue by jesus2099** [JasonBarnabe/greasyfork#318]
Hello,

I’ve seen two possible improvements for github comment copies in cool [History](https://greasyfork.org/scripts/2322/versions) tab.

It’s currently like this for instance :

    v2014.11.20.1720 24 minutes ago - Synced from GitHub - slightly
    better layout NEW. relationship editor (mass) Remove recording
    relationships &lt;ninja&gt; hazardous cleanup

Without changing the structure drastically, it could become easier to read by adding the same separator between each commit message and by fixing those html entities (I don’t understand whay we see them) :

    v2014.11.20.1720 24 minutes ago — Synced from GitHub — slightly
    better layout — NEW. relationship editor (mass) Remove recording
    relationships — <ninja> hazardous cleanup

**Comment by JasonBarnabe** [comment]
Done. Commit messages are no longer HTML-escaped. Multiple commit messages are separated by dashes.

**Comment by jesus2099** [comment]
Thank you. :)
