### ISSUE TITLE
Add report button to script installation area

### ISSUE THREAD

**Issue by tobbexiv** [JasonBarnabe/greasyfork#319]
At the moment there is a need to know that you have to hit the "Post new Discussion" link to report a script. [This is not intuitive and might be missed](https://greasyfork.org/de/forum/discussion/2275/malware-scripts). To make this option more present a button should be introduced which also states "Report" or or the report icon as button title and the report text as hover text. The report button should be shown at any place where you can install the script (so include it in the install template) and should just open the "Post new discussion" dialog with the report option selected.

**Comment by JasonBarnabe** [comment]
I agree that it needs to be more visible, but I think having just a report button makes it too prominent. Kind of sends the wrong impression if the first thing we ask you to do after installing something is to report it!

What I did is add some text below the install button suggesting that after people use the script, they discuss, rate, or report it.
