### ISSUE TITLE
Forum down

### ISSUE THREAD

**Issue by jerone** [JasonBarnabe/greasyfork#320]
When accessing the forum (https://greasyfork.org/en/forum/) I'm getting an error report:

> Fatal Error in Gdn_Database.Query();
> PDO Statement failed to prepare
> You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '? order by d.DateLastComment desc limit 30' at line 6

**Comment by JasonBarnabe** [comment]
This was fixed in Vanilla 2.1.7.
