### ISSUE TITLE
Request to add policy about reference to external scripts

### ISSUE THREAD

**Issue by JixunMoe** [JasonBarnabe/greasyfork#327]
For example, script [#6503](https://greasyfork.org/scripts/6503/code) loads a thrid party script (and it's minified, the site it self does not provide public CDN as well).

And the minified script was made by its competitors.

**Comment by JixunMoe** [comment]
Or should I just follow the external script policy?

**Comment by JasonBarnabe** [comment]
The external script policy is for any executable code, not just code `@require`d, so yes, it applies.

**Comment by JixunMoe** [comment]
Ok, thanks :3
