### ISSUE TITLE
Markdown image syntax in “additional info”

### ISSUE THREAD

**Issue by jesus2099** [JasonBarnabe/greasyfork#328]
It may be because I’m mistaking something but my images are not showing up from my Markdown “additional info”.
[This](https://greasyfork.org/en/scripts/2322-mb-super-mind-control-Ⅱ-x-turbo) has no images although it syncs on [this](https://github.com/jesus2099/konami-command/blob/master/mb_SUPER-MIND-CONTROL-II-X-TURBO.md) ([raw](https://raw.githubusercontent.com/jesus2099/konami-command/master/mb_SUPER-MIND-CONTROL-II-X-TURBO.md)) which shows some.

**Comment by jesus2099** [comment]
Hi Jason,
I was about to fix my text until I found a line in it with apparently the correct strict Markdown syntax for referenced image, according to [Daring Fireball](http://daringfireball.net/projects/markdown/syntax#img) but still the image is not showing up.

Maybe I mistake again but it seems I’m not :

    ![REMEMBER YAY][XZIZI]
    …
    [XZIZI]: http://i.imgur.com/XZIZI.gif

**Comment by JasonBarnabe** [comment]
Greasy Fork requires images to be https.

**Comment by jesus2099** [comment]
Oh OK, no problem with that, as long as I know it now. :)
Maybe a notice in the Sync tab, near where we set the script’s additional info ?
