### ISSUE TITLE
Certificate problem

### ISSUE THREAD

**Issue by jesus2099** [JasonBarnabe/greasyfork#329]
Hello,
I am using [Opera 12.17](http://opera.com/download/guide/?custom=yes) and since few days (maybe saturday, sunday or today), I have a certificate error that prevents me from visiting [GF](https://greasyfork.org) completely : 

> Secure connection: fatal error (48)
> The presented certificate has an unknown Certificate Authority.

※ I am behind a company firewall.

**Comment by JasonBarnabe** [comment]
I can access it just fine with Opera 12.16 on Linux.

**Comment by jesus2099** [comment]
I wanted to know if you changed something recently, but it seems you didn’t, right ?

There must be some problem with my firewall, maybe they have changed something recently… Some (few) HTTPS sites have minor errors (asking me for confirm once then OK) but it’s the first time a site is completely blocked (maybe too critical error)…

I have inspected github and greasyfork certificates but I don’t see the difference…
I think I’ll close this ticket since it’s all about « Opera 12.17 + this proxy + that firewall », you couldn’t do much about it…

**Comment by JasonBarnabe** [comment]
I *did* renew the certificate last week...

**Comment by jesus2099** [comment]
Thanks for the info… I’ll try some stuff.

**Comment by jesus2099** [comment]
Hey it works again now !
