### ISSUE TITLE
Enable the download button to be used on another website

### ISSUE THREAD

**Issue by devnoname120** [JasonBarnabe/greasyfork#330]
Would it be possible to create a button that can be used on another website, and when a user clicks on it, he gets the normal Greasemonkey box for installation?

This would be useful in order to count the downloads when I make my userscript available on another website. This would also help to spread the use of Userscripts, as sharing would be more convenient.

**Comment by JixunMoe** [comment]
Craft a button in HTML (Or even a download button image), and assign link `https://greasyfork.org/scripts/SCRIPT ID HERE/code/code.user.js`.

**Comment by devnoname120** [comment]
This will not affect the download statistics, I need to ping GreasyFork's server.

I could create an iframe and tailor it to the size of the button but this solution is not clean and not reliable.

**Comment by JasonBarnabe** [comment]
The method Greasy Fork uses to count installs is there to prevent false counts by bots, updates, people trying to pad their counts, etc. I can't think of any way to make countable installs from third party sites that couldn't be abused.

**Comment by devnoname120** [comment]
External javascript + CORS xmlHttpRequest?

The level of security would be the same as the actual.

**Comment by JasonBarnabe** [comment]
From a browser security perspective, it's totally doable. I'm talking more about how to ensure that every ping is actually a user wanting to install. Someone could include JS to ping on every page load, for example.

**Comment by JasonBarnabe** [comment]
I can't see any way that I could let other websites increase the install count without opening the door wide open to abuse, so I'm closing this. If you have a bright idea, feel free to reopen.

**Comment by devnoname120** [comment]
Maybe you can add the button yourself. For instance, website owners could include a javascript with a parameter in the URL specifying the id of the element, whose innerHTML should be replaced with the button.

It would not be perfectly cheater-proof though.
