### ISSUE TITLE
API to fetch all scripts by site

### ISSUE THREAD

**Issue by Ede123** [JasonBarnabe/greasyfork#331]
It would be great if there was an API to fetch all scripts by site.

(E.g. similar to #247 but for listings available from https://greasyfork.org/en/scripts/by-site)

**Comment by JasonBarnabe** [comment]
Do you mean for each site individually or a list of all scripts, grouped by site?

**Comment by Ede123** [comment]
No only per site:
As an example an API query for all scripts for "opensubtitles.org" would return exactly the three scripts currently listed on https://greasyfork.org/en/scripts/by-site/opensubtitles.org)

This would provide a great possibility to programatically check which scripts are available for a given site.

**Comment by JasonBarnabe** [comment]
This is supposed to exist
```html
<link rel="alternate" type="application/json" href="/en/scripts/by-site/opensubtitles.org.json" >
```
but I'm guessing doesn't work because of the multiple periods.

**Comment by Ede123** [comment]
Ah, I see... I tried that before but because it didn't work I guessed it wasn't available.

**Comment by JasonBarnabe** [comment]
Try now.

**Comment by Ede123** [comment]
Great! Thanks for that amazingly fast fix. :-)
