### ISSUE TITLE
Upload failed

### ISSUE THREAD

**Issue by dg9ngf** [JasonBarnabe/greasyfork#332]
> We're sorry, but something went wrong.
> If you are the application owner check the logs for more information.

That's what I got uploading my first script. Can somebody please check the logs? Happened right now. Reproducible always.

**Comment by JasonBarnabe** [comment]
I found two uploaded errors in the log, and fixed them both:

- If you uploaded a non-UTF-8 file as your source, it would correctly catch that as a validation failure, but would fail when trying to display the screenshot controls.
- If you uploaded a screenshot with a really long file name, it would fail.

Try now and let me know if it works (or at least gives you a sensible message).

**Comment by dg9ngf** [comment]
Oh yes, encoding. I found that my file had a broken encoding. (I should have tested it in Greasemonkey after adding a localised description.) After I saved it as UTF-8, it worked fine. Sorry, can't test it anymore now that I have fixed and successfully published the file. But that sounds plausible.
