### ISSUE TITLE
Libraries in emptied out script on delete.

### ISSUE THREAD

**Issue by Zod-** [JasonBarnabe/greasyfork#333]
The libraries in an emptied out script don't get removed when the blank version gets pushed which means that libraries that execute any code will still work. So any malicious script would be unaffected until it also updates it's libraries.

For example: 
https://greasyfork.org/en/scripts/7868-delete-test/code
https://greasyfork.org/en/scripts/7869-delete-test-2/code

You would still see "script 1" in the console after getting the blank script.

**Comment by JasonBarnabe** [comment]
Good catch! Fixed now.
