### ISSUE TITLE
Github Webhook Error 500

### ISSUE THREAD

**Issue by devnoname120** [JasonBarnabe/greasyfork#334]
I want my script AntiAdware (https://greasyfork.org/en/scripts/4294-antiadware) to be automatically synchronized with my Github repository (https://github.com/HandyUserscripts/AntiAdware).

For this, I have tried to set a Webhook, by using the information from https://greasyfork.org/en/users/webhook-info.

However, every request seems to fail with the error 'We're sorry, but something went wrong (500)'.
Here are the request headers:
```
Request URL: https://greasyfork.org/en/users/4531-devnoname120/webhook
Request method: POST
content-type: application/json
Expect: 
User-Agent: GitHub-Hookshot/afa9a7c
X-GitHub-Delivery: f590f480-ad89-11e4-911a-9f88667fbede
X-GitHub-Event: push
X-Hub-Signature: sha1=c2af94a29724138b0aeda7e7754adc8abfa2c0bf
```

And here are the response headers:
```
Connection: keep-alive
Content-Length: 1266
Content-Type: text/html; charset=utf-8
Date: Thu, 05 Feb 2015 23:08:01 GMT
Server: nginx/1.6.1 + Phusion Passenger 4.0.52
Status: 500 Internal Server Error
X-Powered-By: Phusion Passenger 4.0.52
X-Request-Id: 1629f8bc-7cfb-4e2d-96bc-0b17c1e735ff
X-Runtime: 0.032317
```

Could you please check what is wrong with my Webhook?

**Comment by JasonBarnabe** [comment]
`commits` in your request is null, which is what it's choking on. I don't know what you could do on GitHub to get a push event with no commits.

**Comment by devnoname120** [comment]
You are right, I did not see this.
I believe that this request is sent when I create a new release, as it is considered as a push event.

However, I think that you should print some information in the page, rather than displaying a generic error 500. Otherwise it is hard to investigate what is wrong from a user point of view.

**Comment by JasonBarnabe** [comment]
OK, try resending the ones that failed; you should get a friendlier message.

Greasy Fork will only do its thing when the push has commits in it, though.

**Comment by devnoname120** [comment]
It works well now, thank you!
