### ISSUE TITLE
Unlisted scripts in script set

### ISSUE THREAD

**Issue by Zod-** [JasonBarnabe/greasyfork#336]
Can you add unlisted scripts to a script set? I can add them without any warnings but they won't get displayed.

**Comment by JasonBarnabe** [comment]
Well then that would make them "listed", wouldn't it?

**Comment by Zod-** [comment]
Sure, I just was confused at the time since I forgot that I had them unlisted and they wouldn't show up in the set. Maybe add it to the description at the new script set page?
