### ISSUE TITLE
Report about script

### ISSUE THREAD

**Issue by UksusoFF** [JasonBarnabe/greasyfork#338]
Where anyone can abuse for script? 
For e.g. https://greasyfork.org/ru/scripts/7633-turbobit-free-premium-downloader 
Script generate links with paid link shorter and insert adv.

**Comment by JasonBarnabe** [comment]
You can report a script by starting a discussion in it and choosing the "Report" option.

**Comment by UksusoFF** [comment]
Found it. Thanks.
