### ISSUE TITLE
Rework library list

### ISSUE THREAD

**Issue by tobbexiv** [JasonBarnabe/greasyfork#340]
Rework the library list to be displayed in a similar way like the script page. Add the option to filter the scripts. Add a search for libraries (see #339). Also move the link from the help page directly to the main page so new authors don't have to know where the link is.

**Comment by Danielv123** [comment]
Will just say that is a highly wanted feature.

**Comment by TimidScript** [comment]
> Also move the link from the help page directly to the main page so new authors don't have to know where the link is.
So true. It was only by accident I found the library page. If I didn't I would have never bothered looking for it.

**Comment by JasonBarnabe** [comment]
✓ Rework the library list to be displayed in a similar way like the script page.

**Comment by tobbexiv** [comment]
Looks way better. Thank you!

But I still have suggestions :)

- You can sort by multiple options, but installs make no sense as they are not counted for libraries: Daily installs, Total installs
- I would show the rating of the library in the overview as you can rate a library.
- The new sorting makes it even harder to find a library, as I can not search them. So having a library search is even more important (maybe in the advanced search page).
- Link the libraries on the normal script page (like it is already done for script sets). This makes it more prominent. Maybe you can also add other topics there.  
![Link Script Libraries from normal Script page](https://cloud.githubusercontent.com/assets/5681598/22303851/644da296-e335-11e6-9085-1eae7aa78977.png)

**Comment by JasonBarnabe** [comment]
> You can sort by multiple options, but installs make no sense as they are not counted for libraries: Daily installs, Total installs

I have changed it so it only sorts by created, updated, or name. The rest don't make much sense. You can rate libraries, but I'm not sure if anyone does...

**Comment by JasonBarnabe** [comment]
✓ Add a search for libraries

I don't think libraries are important enough to warrant a link to somewhere else. The advanced search page, which includes library search, may get a prominent link, though.
