### ISSUE TITLE
[Translation] Make help pages multilingual

### ISSUE THREAD

**Issue by tobbexiv** [JasonBarnabe/greasyfork#341]
The help pages should also be translated to help those users who don't speak English that well.

**Comment by JixunMoe** [comment]
Agree, :+1:

**Comment by JasonBarnabe** [comment]
I am slowly translating pages as I do updates to them. They were left out before because I want to be sure there won't be major changes before I i18nize them.

**Comment by JasonBarnabe** [comment]
Done, finally.
