### ISSUE TITLE
Forum links broken

### ISSUE THREAD

**Issue by tobbexiv** [JasonBarnabe/greasyfork#344]
Redirect to `https://greasyfork.org/de/forum/index.phpentry/jsconnect?client_id=1234568790` and I get an 404 error.

Edit: Seems to be the same for other links to the forum. They all have a index.php in the link now.

**Comment by JasonBarnabe** [comment]
Yes, I upgraded the server and `/forum/` stopped working. I put in `index.php` temporarily until I could figure it out.

**Comment by JasonBarnabe** [comment]
The `entry/jsconnect` link should work now. I'm going to investigate further today.

**Comment by JasonBarnabe** [comment]
https://github.com/phusion/passenger/issues/1444

Fixed now.
