### ISSUE TITLE
Ask Commenter Update Feedback Button

### ISSUE THREAD

**Issue by TimidScript** [JasonBarnabe/greasyfork#345]
A way to auto-ask a commenter to update the feedback if problem is fixed (or if there was no problem in the first place with the script but with the GM plugin).

**Comment by JasonBarnabe** [comment]
If you start a discussion on a script, when you go to add a new comment you are given the option to change your rating. I'm not sure if this is the kind of "auto-ask"ing you're talking about.

**Comment by JasonBarnabe** [comment]
I'm going to assume that it was.
