### ISSUE TITLE
Images not displayed in script description

### ISSUE THREAD

**Issue by RasmusWL** [JasonBarnabe/greasyfork#346]
I'm trying to display a [markdown document](https://github.com/RasmusWL/userscripts/blob/master/kunet-absalon-fag/README.md) that contains images as the description of [my script](https://greasyfork.org/en/scripts/6638-kunet-absalon-fag).

When I preview it under `Sync` I can see the images alright, but on the script page nothing shows up. (I have made the path to the images full, as I thought that might be a problem)

ps. Thanks for the good work!

**Comment by JasonBarnabe** [comment]
You are correct that you need the full path. It looks like Greasy Fork still has the older revision. GitHub caches content on its raw server for a few minutes, so maybe that was the problem.

Try syncing it again.

**Comment by RasmusWL** [comment]
Yes, that did solve the problem. That was kinda odd.

Could you please add a `max-width: 100%` to the `img` tag? Currently it overflows in chrome. 

Should probably be done [here](https://github.com/JasonBarnabe/greasyfork/blob/master/app/assets/stylesheets/application.css#L38), but didn't want to setup the whole build systems just for a one-line fix.

**Comment by JasonBarnabe** [comment]
Done, thanks for the suggestion.
