### ISSUE TITLE
Extension of the API (overall number of results)

### ISSUE THREAD

**Issue by Ede123** [JasonBarnabe/greasyfork#348]
Currently there's the possibility to fetch collections, e.g. in JSON format:
https://greasyfork.org/en/scripts/by-site/youtube.com.json
This request returns 50 scripts.

However a look at
https://greasyfork.org/en/scripts/by-site/youtube.com
shows that there are actually 4 pages of scripts with a total of 152 scripts at the time of this writing.

Actually it's possible to fetch all the scripts with
https://greasyfork.org/en/scripts/by-site/youtube.com.json?page=1 (?page=1 can be omitted)
https://greasyfork.org/en/scripts/by-site/youtube.com.json?page=2
https://greasyfork.org/en/scripts/by-site/youtube.com.json?page=3
https://greasyfork.org/en/scripts/by-site/youtube.com.json?page=4
but how should one now for how many pages one has to query? It's surely possible to query up to
https://greasyfork.org/en/scripts/by-site/youtube.com.json?page=5
which will return an empty set, but this does not seem like an elegant approach.

Question would therefore be if it was (reasonably) possible to

1. add another request (e.g. https://greasyfork.org/en/scripts/by-site/youtube.com.json?list) that returns the overall number of scripts / pages and maybe all IDs (but nothing more).
2. And/or offer a possibility to download _all_ scripts via an API request in one go instead of splitting them into multiple pages?

**Comment by Ede123** [comment]
Note: If 1. could be implemented with reduced performance impact in comparison to the other queries this could offer an easy possibility for external tools to query the number of scripts available for a specific domain. It will certainly save banwidth.

As a usage scenario I'm currently developing a Firefox add-on, that will show the number of scripts available on the domain the user is currently on (similar to what Greasfire did, but I'm planning to do it without a database). Therefore a quick an performant way to get this number would be advantageous.
Additional content could then be requested if (and only if) the user chooses to see details.

**Comment by JasonBarnabe** [comment]
You can specify a `per_page` parameter, which can be up to 200.

But yeah, it's mostly a performance thing that prevents me from allowing any more. I could create a URL where you could get stats like the number of scripts, though.

**Comment by Ede123** [comment]
Sounds great! Looking forward to it...

**Comment by JasonBarnabe** [comment]
- Added `meta=1` parameter for JSON and JSONP feeds for script lists. This currently returns the count of scripts but can be expanded to include other useful things later.
- Added JSON and JSONP feeds to search results pages.
- Fixed some deprecation warnings along the way.

**Comment by Ede123** [comment]
Perfect!

I just noticed a minor issue. This does not work for collections by author yet:
https://greasyfork.org/en/users/8551-ede-123.json?meta=1
(Wouldn't know a use case for it right now, though)

**Comment by JasonBarnabe** [comment]
I think users will come out with all scripts anyway.
