### ISSUE TITLE
Plus signs in email addresses

### ISSUE THREAD

**Issue by Suitov** [JasonBarnabe/greasyfork#349]
Please validate email addresses when users sign up and explicitly disallow those with plus signs in (with helpful feedback).  Alternative: properly support email addresses containing plus signs.

GreasyFork let me sign up using a username with a plus in it (used in Gmail addresses to help in filing emails from different sources).  However, it wouldn't let me sign *in* with that address.  I was able to reset the password, which got me in long enough to change the email address to a non-plussed version so that's effectively fixed my problem but not solved the larger issue.

**Comment by JasonBarnabe** [comment]
I just tried it out and I didn't find any problems. I can create an account with a plus, log out, and then sign in with that account. In fact I do this for test accounts. I imagine something else was going on here.
