### ISSUE TITLE
Code highlight: add ECMAScript 6 support

### ISSUE THREAD

**Issue by CoolCmd** [JasonBarnabe/greasyfork#350]
Example: https://greasyfork.org/en/scripts/9129-%D0%A4%D0%BE%D1%82%D0%BE%D0%B3%D0%B0%D0%BB%D0%B5%D1%80%D0%B5%D1%8F-f1news-ru/code

Aren't highlighted yet:
```
const, let, for of
`template string with ${expressions}`
etc.
```

Several latest versions of Firefox already have ECMAScript 6 support.

**Comment by JasonBarnabe** [comment]
Greasy Fork uses https://github.com/rubychan/coderay for syntax highlighting, so please file your issue there. Once that's been updated I'd be glad to update to the new version.

It even doesn't look too hard to do a pull request to fix this, if you want to give it a shot. It looks like it's all defined in https://github.com/rubychan/coderay/blob/master/lib/coderay/scanners/java_script.rb. Not sure if the `${}` thing would be easy, but you could leave that out for now.

**Comment by tophf** [comment]
The ES6 issue was [reported half a year ago](https://github.com/rubychan/coderay/issues/200) in CodeRay repo and got zero traction.

I suggest switching to Ace editor which you already run on the site. The advantage is that it renders only the visible portion of the code so it'll handle huge scripts currently skipped by greasyfork without problems, presumably (based on my experience with a similar editor, CodeMirror).

**Comment by JasonBarnabe** [comment]
Not sure if using Ace in a read-only context makes sense. Will have to check.
