### ISSUE TITLE
Delete a specific version of a script

### ISSUE THREAD

**Issue by Ede123** [JasonBarnabe/greasyfork#351]
Currently there's no possibility to delete a specific version of a script. In some cases this could be very useful though, especially with scripts automatically syncing from a remote URL.

Usage scenario:
* Assume you're updating a script but forget some personal information (e.g. access password or the like).
* You can overwrite the script with a new version to limit the damage but the old version will still be publicly accessible.

**Comment by JasonBarnabe** [comment]
See #335.
