### ISSUE TITLE
Ping users with a space in their user name

### ISSUE THREAD

**Issue by Ede123** [JasonBarnabe/greasyfork#352]
It seems there is no possibility in the markdown syntax to ping/link users with a space in their user name.

This might be a fundamental and therefore not easily solvable issue because user names with spaces are allowed in the first place, but maybe there's a solution after all.

*For clarification purposes: The syntax in question is `@JasonBarnabe` which results in @JasonBarnabe but doesn't work with spaces for obvious reasons.*

**Comment by JasonBarnabe** [comment]
This is a Vanilla forums issue. They've said "no" to spaces in names before, but I think they may be coming around. See https://github.com/vanilla/vanilla/issues/2483.
