### ISSUE TITLE
"@name:xy" requires "@description:xy"

### ISSUE THREAD

**Issue by Ede123** [JasonBarnabe/greasyfork#354]
When adding a `"@name:xy"` meta key Greasy Fork requires the author to also add a localized `"@description:xy"`:
> @description:de can't be blank

Is there any reason for this? http://wiki.greasespot.net/Metadata_Block doesn't state anything similar. If there is no obligation to do so in script engines, Greasy Fork shouldn't require the author to add it either.

**Comment by JasonBarnabe** [comment]
See explanation in #355.
