### ISSUE TITLE
Localization for collections

### ISSUE THREAD

**Issue by Ede123** [JasonBarnabe/greasyfork#356]
Not a real bug report yet but a request for comment at this time:
- [ ] It seems collection URLs don't include localized information, e.g. compare<br>
  &nbsp;&nbsp;&nbsp;&nbsp;https://greasyfork.org/en/scripts/8714-test.json?locale_override=1 and<br>
  &nbsp;&nbsp;&nbsp;&nbsp;https://greasyfork.org/de/scripts/8714-test.json?locale_override=1<br>
  Is this wanted behavior or should we either
  - always output all localizations or
  - only output the specified localization?
- [ ] Currently when visiting the language neutral version of a collection, e.g.<br>
  &nbsp;&nbsp;&nbsp;&nbsp;https://greasyfork.org/scripts/8714-test.json<br>
  there's a 302 redirection taking place to the "localized" version of the page, e.g.<br>
  &nbsp;&nbsp;&nbsp;&nbsp;https://greasyfork.org/en/scripts/8714-test.json<br>
  If we introduce differently localized pages in response to the first point this is completely valid.
  However if collections stay untranslated or all "localizations" look the same, there's no need for any redirection. In this case: Would it be possible to directly answer the request with the requested content?

**Comment by JasonBarnabe** [comment]
It makes sense to me to include all localizations, regardless of the locale in your request. The output can still include a default name and description - maybe that should match the request's locale? Or maybe it should be the default name/description of the script?

**Comment by Ede123** [comment]
I'd keep "name" = `@name` and "description" = `@description`. Otherwise it gets confusing.

Also I think including all localizations in the request (therefore essentially not localizing API requests) is reasonable and the easiest solution. (Filtering for localized content can then be done programatically by the API user in exactly the way the API user prefers).

**Comment by JasonBarnabe** [comment]
-Scripts include all locales.
-Removed redirects to locale-specific URLs for non-HTML.

So this should be all good now.
