### ISSUE TITLE
Investigate using "it" for translation keys with links in them

### ISSUE THREAD

**Issue by JasonBarnabe** [JasonBarnabe/greasyfork#357]
https://github.com/iGEL/it

**Comment by tobbexiv** [comment]
I see an advantage (having the link text directly in the translation) but also an disadvantage: the translator neeeds to know which part of the string can be translated and which part has to remain the same. At the moment it's easy: everythin in the `%{...}` part has to stay the same. Then you also have to translate some of the words there. So it is necessary to make it clear (at least in the wiki) which part should be translated and which part shouldn't.

**Comment by JasonBarnabe** [comment]
Yes, it requires explanation, but probably less explanation than I already put in the comments when there's links...

**Comment by JasonBarnabe** [comment]
Set this up on https://greasyfork.org/en/help/credits, seems to work fine. Will use this going forward. I've made an announcement in Transifex to explain how it works.

**Comment by tophf** [comment]
* source `%{developers_link:these people}`
* translation `%{developers_link:abra cadabra}`
* warning:

  >The following url is either missing from the translation or has been translated: _'developers_link:**these**'._

**Comment by tobbexiv** [comment]
This warning can be disabled by @JasonBarnabe if he wants to.

**Comment by tophf** [comment]
Currently transifex marks such lines as untranslated and, supposedly, they won't be available for use.

**Comment by JasonBarnabe** [comment]
OK, I've disabled that check. Does that mean things are good now?

**Comment by tophf** [comment]
Yes, the issue is fixed.
