### ISSUE TITLE
Improve the changelog displaying

### ISSUE THREAD

**Issue by devnoname120** [JasonBarnabe/greasyfork#362]
Currently, the changelog is in one line, so it quickly gets unreadable: https://greasyfork.org/en/scripts/4294-antiadware/versions
Would it be possible to improve it?
Supporting Markdown would be a big plus too for the readability.

Also, some userscripts authors publish releases on Github with changelogs (example : https://github.com/HandyUserscripts/AntiAdware/releases). Would it be possible to fetch the changelog from here instead? (Might require #361 to be implemented first.)

**Comment by JasonBarnabe** [comment]
Does GitHub parse markdown in changelogs?

**Comment by devnoname120** [comment]
Yes.

**Comment by JasonBarnabe** [comment]
As far as I can tell, GitHub does *not* support markdown in commit summaries - https://github.com/JasonBarnabe/webhooktest/commits/master/test.user.js

**Comment by devnoname120** [comment]
By changelog I meant the one from the release section.

**Comment by JasonBarnabe** [comment]
Well, I've added the backend for different markup of changelogs, so the rest is just #361.
