### ISSUE TITLE
Website is not accessible

### ISSUE THREAD

**Issue by Yonezpt** [JasonBarnabe/greasyfork#366]
Sorry for posting this here, but I couldn't find a better place. For the past day or so I have been unable to access the greasyfork website, it always times out.

A quick down or not test reveals that this problem is not only happening to me: http://www.isitdownrightnow.com/greasyfork.org.html

![ss](https://cloud.githubusercontent.com/assets/8498057/7854905/ed0c49d8-050c-11e5-997e-0a4b87f1530e.png)

**Comment by lychichem** [comment]
I have seen same report from China. There are many users complaining about it.

**Comment by alexolog** [comment]
Confirmed inaccessible for me (and I'm in Canada, not China)

**Comment by JixunMoe** [comment]
Server is down.

**Comment by JasonBarnabe** [comment]
Site's being moved to a new server by the host. It's out of my hands at the moment.

**Comment by Yonezpt** [comment]
Good to know, then we shall be patient and this issue should help inform others facing the same issue.

**Comment by JasonBarnabe** [comment]
Should be back now, depending on DNS caching.

**Comment by Yonezpt** [comment]
Confirmed here, it is working already.

**Comment by JixunMoe** [comment]
Confirmed working now.
