### ISSUE TITLE
How do you make money? If not, would you not share the same fate as userscripts.org?

### ISSUE THREAD

**Issue by Pacerier** [JasonBarnabe/greasyfork#367]
Note: For the sake of intellectual honesty, I shall not mince words. Thus, this question will not sound nice, but it needs to be answered.

So, greasyfork.org homepage states that it "is aiming to become the premier user script site after the collapse of userscripts.org". [Déjà vu anyone](https://news.ycombinator.com/item?id=1574840)?

The important question is, How would greasyfork.org profit? What is stopping greasyfork.org from becoming defunct like userscripts.org?

**Comment by JasonBarnabe** [comment]
Well, I can't guarantee that I will be around forever, but the site is open source and I'm working on a feature that would make some of the data open as well. So worst comes to worst, someone could fork it and start it up again.

What would make going defunct less likely is if someone could step up and help out with the coding and maintenance of the site.

**Comment by Pacerier** [comment]
How many coders / maintainers are there currently?

**Comment by Pacerier** [comment]
How many coders / maintainers are there currently?

**Comment by Pacerier** [comment]
How many coders / maintainers are there currently?

**Comment by JasonBarnabe** [comment]
Well, there's four moderators who can handle spam and malware. But as you can see [here](https://github.com/JasonBarnabe/greasyfork/graphs/contributors), it's mostly me coding it at the moment. And only I have the "keys" to everything.

**Comment by Pacerier** [comment]
What's the "roadmap" like?

What are the future plans?

**Comment by JasonBarnabe** [comment]
Honestly, there's no roadmap or future plans. I'm pretty happy with how things are, and I'm not planning major changes. If you look through the open issues here, you'll see things that I and others think should be added or changed.
