### ISSUE TITLE
JSON return all your scripts including deleted ones

### ISSUE THREAD

**Issue by TimidScript** [JasonBarnabe/greasyfork#368]
Ability to get all your script listing including the deleted ones, using json. Only works when logged in. 

Initial suggestion found <a href="https://greasyfork.org/en/forum/discussion/comment/14152">here</a>

**Comment by JasonBarnabe** [comment]
Why do you want it to return deleted scripts?

**Comment by TimidScript** [comment]
Not  permanent deleted scripts. 
But basically it was for one of my scripts. I currently use html to get a listing of all scripts, including the deleted ones, so I can have all the scripts, including the deleted ones, listed in one page. At the time, JSON didn't return deleted scripts.

**Comment by JasonBarnabe** [comment]
I've added a boolean `deleted` attribute to each script in the JSON and included the deleted scripts for your own user in the JSON user feed.
