### ISSUE TITLE
Search Results Incomplete

### ISSUE THREAD

**Issue by TimidScript** [JasonBarnabe/greasyfork#369]
<b>by-site</b>
If you search by site, it does not return all scripts that include the site. Example if you search by site for <a href="https://greasyfork.org/en/scripts/by-site/google.com?per_page=100&sort=ratings">Google.com</a> a lot of scripts that use * will not be returned. So items like <a href="https://greasyfork.org/en/scripts/4686-ts-schmoogle">Schmoogle</a>. 

<b>Normal search</b>
If you search for <a href="https://greasyfork.org/en/scripts/search?per_page=100&q=pixiv.net&sort=updated">pixiv.net</a> it will exclude all scripts that do not have pixiv.net in the description but have it in the the include. What I am saying searching for pixiv.net should return the similar result as pixiv. I would suggest that pixiv.net would be the more important search item. Like "bato.to", most users would search for "bato.to" and not "bato" or batoto on first go. 

Shouldn't a normal search, parse through the "include" and description properties?

**Comment by JasonBarnabe** [comment]
Scripts for simply `*` should not be on the site-specific results. Those like Schmoogle which do things like `*//www.google.*` should. The code handles [all sorts of weird wildcards](https://github.com/JasonBarnabe/greasyfork/blob/master/app/models/script_version.rb#L386), but it didn't handle that one. I've fixed it.

"Normal search" will search name, author, description, and additional info. I guess I figured if you didn't mention the site in there, it wasn't that important...
