### ISSUE TITLE
Reviews, discussions, flagging and bug reports are not supposed to be the same thing.

### ISSUE THREAD

**Issue by Qon** [JasonBarnabe/greasyfork#373]
So don't treat them as the same thing. It is confusing users. I have examples, but do you really need them? I bet a significant portion if not an overwhelming majority of the negative reviews are actually bug reports that are have been fixed a long time ago in for any script that is activly maintained. *I've even done it myself...*

# Examples why this doesn't work
## Confusing reviews and bug reports
Easiest way to point out the problems that creeps up when users confuse different things is when a bug inevitably pops up. Since the review system is tied to the bug report system the user thinks "I have a problem with this script" and chooses "yellow" or "red" and leave a (permanent) bad review without even knowing that is what they are doing. They just know that those colors represent "problem thread" and green represents "no problem". Now even if the bug is fixed the bug report stays as a negative review forever.

I am not saying that a script being broken isn't a valid reason for giving a negative review. If the script stops working and people report bugs, and the script isn't maintained and bugs don't get fixed, then yes then it is reasonable to leave a nagative review to help other see that they shouldn't waste their time with the script. It isn't obvious that a "red symbol" is the same as rating down the script.

Bug reports are supposed to *help the developer*, right now they are doing the opposite! When you "can't" bug report without also leaving a bad review at the same time the system isn't fulfilling it's purpose. It is impossible to write bug free userscripts and a temporary problem should be fixed instead of punished.

## Confusing rule violations and discussions
Also reports to mods are public! That is just wrong. I don't want the developer I report to see that I reported him. Maybe he decides to retaliate or something?

## Doesn't make sense
And what if you give multiple reviews, what happens then? Can I give a script 200 positive reviews? Can I give both positive and negative reviews? Letting people review the same script multiple times doesn't make any sense.

# Solving the problem. I come with suggestions.
So how can we make it better? I have a suggestion. Split the system into several sections. Don't have one "do it all" Feedback tab where everything goes. 

![Graphical](http://s13.postimg.org/6hwhf26jb/x2scrap9.png)

## Reviews
Reviews gets their own section, where you can only post once and where the user is reminded that it is not for suggestions, discussions or bug reports. The ratings on the scripts page should be linkifyed.

## Reports
Reports should be decoupled from the discussion forum even more. Completely separated from the users perspective. Make a tiny little link on the scripts page that says "flag", just like you can flag forum posts right now.

## Feedback (suggestions, bug reports, discussions)
Feedback should ONLY have the blue "No rating - just a question, comment, feature request, or bug report". It could be split up into several radio buttons, one for each. So one radio button and icon for feature requests, one icon for bug reports (if bug reports stay in the feedback section), one for misc discussions. The important point is that the red, yellow, green and report radio buttons must be removed from this form!

## Edit: Bug reports
Maybe instead of a system of permanent "I like it and it works forever" vs "It's broken and will be forever" something different could be used to indicate if a script works or not. Right now a script where the dev stops maintaining a popular script will stay at the top for a very long time even if it's broken, simply because positive reviews are permanent. And bugs that are squashed instantly will not get rid of their negative publicity. 

### A completely new way of thinking about the problem
So a new system that works a bit like the current review system with the difference being that the dev can mark bugs as solved himself when he updates the script. Bug report could have severity options like "Mild - annoying issue but works" and "Broken - doesn't do anything at all or is unusable" where a script with a lot of unsolved small bugs or a few "broken" level bugs gets downrated. It's essentially a like the review system but with the difference that the dev can change the status of the bugs himself to "solved". 

And that's why unmaintained scripts will be marked as broken quickly and fixed scripts will be marked as fixed instantly. *The "works/doesn't work" information will with this system always be up to date.*

# Also, what's up with this?
Also there are no rules for user feedback. If a user gives my script a negative review by mistake, when the report should actually be given to someone else, can I flag that review? Can I flag reviews that are bug reports? Can I flag reviews that are unfair and where the reviewer is lying? Can I flag reviews I don't like? I don't want to censor people, but there are no rules for forum posts of any kind and therefore no rules for what is considered abuse of the flagging system either.

**Comment by JasonBarnabe** [comment]
Review systems are for users to be able to see what other users think of something. Bug trackers are for developers to be able to keep tracker of things to implement or fix.

Greasy Fork's system is for reviews. If you want to use a bug tracker, set `@supportURL` and Greasy Fork will suggest that option to people. Then you can do whatever you like with your reports.

In Greasy Fork's review system, the reviewer has primacy. People can respond to what they say, but no one can delete or negate their review. I think this is the least worst option. Letting the developer "close" reviews is ripe for abuse, and admins just don't have the time or ability to verify reviews.

To answer some of your more specific complaints/questions: 

Only the most recent review written by a user counts. The previous ones get turned into "feedback"s.

User reviews will be deleted or edited in a few, very specific cases. For example:
- The review was clearly posted on the wrong script
- The review is clearly not a review (keyboard smashing, etc)
- Any review that violates normal forum rules (spam, abuse, etc.)
