### ISSUE TITLE
Signing in with a Google account resets your profile name

### ISSUE THREAD

**Issue by dlras2** [JasonBarnabe/greasyfork#376]
Signing in with a Google account resets your profile name to your real name, as provided by Google. I can go into my profile settings and change this back, but this seems like severely unintended behavior.

**Comment by JasonBarnabe** [comment]
Greasy Fork does this by default for all login methods. You can turn it off by going into your account, clicking Edit Sign In Methods, then turn off syncing for this login.

**Comment by dlras2** [comment]
That seems like really bizarre, unintuitive behavior, but thank you for the workaround.

**Comment by JasonBarnabe** [comment]
Seems normal to me; you sign in with an external method, it creates an account based on the data, and by default keeps the data in sync with the external method.

I guess the abnormal part would be Google using your real name. Not sure if that's something it does for everyone, or just you.

**Comment by dlras2** [comment]
I believe it is default.. tho I could be wrong. It just seems odd that if I specifically override something, it's still overwritten again.
