### ISSUE TITLE
rework adult-content marks

### ISSUE THREAD

**Issue by Owyn** [JasonBarnabe/greasyfork#381]
https://greasyfork.org/en/forum/discussion/comment/16550
>advertisement network bots mark the entire site as having adult content when any of such links are discovered. My point is that those links being listed on the script info page don't add anything useful to your script.

I'm suggesting to just mark & hide those links from "works on:" list of a script instead of removing whole script from bots and unauthorized users.

(if no links would be left after this operation - then automatically mark script as adult, but not just for having some of marked links in "works on" list)

Having less material to show to search bots and users makes website feel empty for them and it makes them unhappy when they can't find a userscript they want.

**Comment by JasonBarnabe** [comment]
Closing per my comments in the forum.
