### ISSUE TITLE
Synchronise from github doesn’t currently work any more for me

### ISSUE THREAD

**Issue by jesus2099** [JasonBarnabe/greasyfork#384]
I’m sorry if I create something that is only limited to me… ?

My Github [synchronised scripts](https://greasyfork.org/users/2206-jesus2099?sort=updated#user-script-list) don’t update any more, lately.

In the hook logs, I see no problem.
Code 200. Header and body seem correct : 

    {"affected_scripts":["https://greasyfork.org/en/scripts/2330-mb-chatlogs-power-up","https://greasyfork.org/en/scripts/2338-mb-mass-merge-recordings"]}

I don’t know if header are suitable to paste (do they contain private sutff) ?

**Comment by JasonBarnabe** [comment]
I kicked it, should be working now.

**Comment by jesus2099** [comment]
It skipped the intermediary commit messages but the final source code is the latest.
Thank you. :)
