### ISSUE TITLE
@downloadURL and @updateURL are both removed on upload

### ISSUE THREAD

**Issue by elundmark** [JasonBarnabe/greasyfork#385]
I recently synced one of my scripts, and noticed that both the `@downloadURL` and `@updateURL` variables were removed:
[greasyfork.org/scripts/1899-torrentz-all-in-one/code/Torrentz All-in-One.user.js](https://greasyfork.org/scripts/1899-torrentz-all-in-one/code/Torrentz%20All-in-One.user.js#OVERRIDE)
Synced from: [f.3r1k.se/js/tz-aio/tz-aio.user.js](http://f.3r1k.se/js/tz-aio/tz-aio.user.js#OVERRIDE)

Is this normal?
Could any of these 2 things have caused this? They are the 2 big changes since the last version.

1. The domain from which it is synced was changed (incl the domain for the meta and user files).
2. I edited the `@namespace` variable by mistake, but reverted it to the original one by making and syncing an updated version.

**Comment by tobbexiv** [comment]
This is normal and done for a simple reason: If you have those two pointing to a different location it would be possible to upload an allowed script to Greasy Fork and then let both of these urls point to a potential malicious script. This would bring a malicious script to the users without them knowing it.

The script addons automatically check the install location for updates when the urls are not given. So scripts installed from Greasy Fork check for updates automatically on Greasy Fork with this change. To maintain a script only on one place the automated sync features can be used.

Theses changes can also be found on Greasy Fork: https://greasyfork.org/help/rewriting

**Comment by JasonBarnabe** [comment]
As explained, this is expected and documented behaviour.
