### ISSUE TITLE
sticky discussion

### ISSUE THREAD

**Issue by ubless607** [JasonBarnabe/greasyfork#387]
The only thing that I miss from userscript.org is the sticky discussion function.
Could this be implemented too on greasyfork?

**Comment by JasonBarnabe** [comment]
How exactly is a sticky discussion different than a regular discussion, and what is it used for?

**Comment by ubless607** [comment]
Sticky Discussion could be useful for the author. 

It can be used for a guideline in github. or ... notice! thingy. 
The order of regular discussions changes when someone else replys. It goes first. 
Then the important message could be under-listed. My english is bad, sorry.

**Comment by ubless607** [comment]
@devnoname120 Any help... please?

**Comment by ubless607** [comment]
Also I would like this feature: Issue open or closed like github.

**Comment by JasonBarnabe** [comment]
You do have the option of adding `@supportURL` to your script, which Greasy Fork will suggest people use. This could be a discussion or your GitHub tracker or anything else.

**Comment by JasonBarnabe** [comment]
I don't think this is going to happen. If you want to use GitHub or a forum discussion for support, set it as your `@supportURL`.
