### ISSUE TITLE
search query that crash the site

### ISSUE THREAD

**Issue by jabawack81** [JasonBarnabe/greasyfork#388]
with a query beginning with a hyphen "-" the site crashes this is not happening with 2 hyphen "--" or any other special carachter.

e.g. 

https://greasyfork.org/en/scripts/search?q=-manga-onlineviewer = chash
https://greasyfork.org/en/scripts/search?q=-fdedww = crash
https://greasyfork.org/en/scripts/search?q=--manga-onlineviewer = query not valid page
https://greasyfork.org/en/scripts/search?q=$fdedww = no script found page

Jaba

**Comment by JasonBarnabe** [comment]
http://sphinxsearch.com/docs/current/extended-syntax.html

But the site should do something reasonable when things aren't valid.

**Comment by JasonBarnabe** [comment]
https://github.com/pat/thinking-sphinx/issues/1034

**Comment by JasonBarnabe** [comment]
Fixed.
