### ISSUE TITLE
Linebreak in forum posts is by ending the line with 2 spaces, while in posting script form|'Additional info' it's with 1 space

### ISSUE THREAD

**Issue by darkred** [JasonBarnabe/greasyfork#389]
Currently to make a linebreak in greasyfork you have: 
- (in forum) to end the line with 2 spaces  
- (in posting script form|Additional info) to end the line with 1 space

I'd suggest making it so that it's 1 space in both cases. 
(BTW here in GitHub's Markdown, linebreak is 1 space).

**Comment by JasonBarnabe** [comment]
I think this may be fixed in the forum by https://github.com/vanilla/vanilla/pull/2228. Will have to upgrade to 2.2 once it's out.

**Comment by JasonBarnabe** [comment]
Looks like it was indeed fixed in 2.2.
