### ISSUE TITLE
Idea for prevent user accidentally report script

### ISSUE THREAD

**Issue by JixunMoe** [JasonBarnabe/greasyfork#392]
So my idea is that, instead of letting people choose from 4 options, they can only select the 3 options (Bad, normal, good). Then a seperate url on the script page for reporting.

For example:

``` text
https://greasyfork.org/scripts/1
Report url (hide all other options, and select report by default) => https://greasyfork.org/forum/post/discussion?script=1&report=1
Normal url (with "report" radio button hidden) => https://greasyfork.org/forum/post/discussion?script=1
```

![image](https://cloud.githubusercontent.com/assets/5713045/11048099/d4c8a83c-872d-11e5-8bce-f153a120a5dd.png)

![image](https://cloud.githubusercontent.com/assets/5713045/11048103/dda91392-872d-11e5-839a-70b01635104b.png)

**Comment by JasonBarnabe** [comment]
I don't think this would really help. The issue is that people don't know what kind of things should be reported. To help with this, I've added some examples on the new discussion page for the kinds of things that should be reported.
