### ISSUE TITLE
Bitbucket Webhooks

### ISSUE THREAD

**Issue by jesus2099** [JasonBarnabe/greasyfork#393]
I don’t really use Bibucket but I saw that they rolled out some Webhook system too around 24/06/2015.
Maybe [those Webhooks](https://confluence.atlassian.com/bitbucket/manage-webhooks-735643732.html) work the same way as Github’s and, if so, the Github Webhook feature in GF could be relabelled differently.

**Comment by JasonBarnabe** [comment]
I don't have any objection to it, but I would rather do it if I knew someone would use it.

**Comment by jesus2099** [comment]
I know someone who might be interested, wouldn’t you, @loujine? :)

**Comment by loujine** [comment]
Indeed :)
I use a mercurial repository for my greasyfork scripts so I can't use github. I would be happy to test it if you implement something

**Comment by JasonBarnabe** [comment]
Bitbucket webhooks are now supported, but only for git repos.
