### ISSUE TITLE
#script-stats is too narrow

### ISSUE THREAD

**Issue by ssokolow** [JasonBarnabe/greasyfork#395]
The metadata block wraps incorrectly when "Updated" contains the word "minutes".

![screenshot of the problem](https://cloud.githubusercontent.com/assets/46915/11165144/d1d8891c-8ad4-11e5-96e2-5e6d6afd6dfe.png)

The simplest fix is to change the `min-width` on `#script-stats` from `18em` to `20em`.

**Comment by JasonBarnabe** [comment]
I would like to update this so this isn't an issue no matter what the length...

**Comment by ssokolow** [comment]
In that case, the simplest solution would be to make it a two column table with the left column being made up of `<th scope="row">` cells.

Failing that, one change that appears to work in my Firefox but I haven't tested elsewhere is:

1. Remove the `float: left` on `#script-stats dd`
2. set `white-space: nowrap` on `#script-stats`

**Comment by JasonBarnabe** [comment]
I don't think this is an issue any more.
