### ISSUE TITLE
Batch delete on search page.

### ISSUE THREAD

**Issue by JixunMoe** [JasonBarnabe/greasyfork#401]
Right now I have to click on the script, click delete, fill in a reason, and then confirm delete.
It's not convenient when I have found a list of scripts and have to delete it one by one.

**Comment by JasonBarnabe** [comment]
Theoretically you're supposed to be checking the script before deleting, but with the number of scripts people are deleting, I'm not sure that's feasible...

**Comment by JixunMoe** [comment]
Is mainly for duplicate script deletion, most time is reported by user at forum. 

What I did was search for the script title, see if they have the same meta. Maybe display `@author` at search page will help?

Thanks.

**Comment by JasonBarnabe** [comment]
I think the only case where you should mass-delete would be multiple things by one user, and that's doable when banning the user.
