### ISSUE TITLE
Profile Page Discussion JSON no Longer works

### ISSUE THREAD

**Issue by TimidScript** [JasonBarnabe/greasyfork#402]
Hi, hope you enjoyed your holiday. 

The issue at hand is the JSON version of the discussion on your scripts that appears on your profile page (link shown below). It use to produce a list of your discussion but it no longer does. What is the new link if there is one. I had planned to add it to my script so you do not need to be logged in to see the discussions.

https://greasyfork.org/en/forum/discussions/feed.json?script_author=1455

**Comment by JasonBarnabe** [comment]
https://greasyfork.org/en/forum/discussions.json?script_author=1455 seems to work. Is the old URL linked to from anywhere?

**Comment by TimidScript** [comment]
Thank you. I had it saved from a discussion thread and waiting to be implemented. I do not know how to arrive to the actual URL for it, it had to be given to me.
