### ISSUE TITLE
Incorrect "Applies to" link parsing

### ISSUE THREAD

**Issue by pavelxdd** [JasonBarnabe/greasyfork#404]
Using this regex in include:
`// @include     /^http:\/\/myanimelist\.net(\/?$|\/profile)/`
GreasyFork display this:
![img](http://i.imgur.com/aWziIxk.png)

**Comment by JasonBarnabe** [comment]
I don't think the code to do this will ever be perfect.

What it's doing is grabbing up to the fourth slash (one for start of regexp, two for protocol, then the fourth separating the domain and path). It then attempts to clean up any regexp-y things left, then does some checks to ensure what it found was valid.

I've modified it to consider a parenthesis left over to be a sign that it didn't figure it out properly. If you want a nice domain-y listing, I suggest: ` @include /^http:\/\/myanimelist\.net\/(profile.*)?/`.
