### ISSUE TITLE
Minification, optimization? Either or both?

### ISSUE THREAD

**Issue by rmenessec** [JasonBarnabe/greasyfork#407]
I just noticed that OpenUserJS has a feature whereby you can opt to install a userscript via a minification filter. This would be a neat thing to have for larger userscripts. (Scripts with lots of "data:" URIs, for instance.)

And, once I noticed that, I thought: why stop there?

https://developers.google.com/closure/compiler/

**Comment by JasonBarnabe** [comment]
What would this accomplish? Marginal savings on bandwidth? At the cost of making the code difficult to understand?

**Comment by JasonBarnabe** [comment]
Not going to do this.
