### ISSUE TITLE
A new obfuscation pattern, unknown tool.

### ISSUE THREAD

**Issue by JixunMoe** [JasonBarnabe/greasyfork#408]
`eval((function`

**Comment by JasonBarnabe** [comment]
Got a full example?

**Comment by JixunMoe** [comment]
https://greasyfork.org/scripts/17263

**Comment by JasonBarnabe** [comment]
I've keyed on a different part of the script and cleaned up all the scripts that used it.

**Comment by JixunMoe** [comment]
https://greasyfork.org/scripts/17906/code

The keyword is not effective as expected.

**Comment by JasonBarnabe** [comment]
I've updated it. There are no non-deleted scripts for the new pattern.

**Comment by JixunMoe** [comment]
New script using similar pattern.

Script id: 18377
