### ISSUE TITLE
Can't write reviews

### ISSUE THREAD

**Issue by Jendrej** [JasonBarnabe/greasyfork#411]
Clicking the new discussion button redirects to the main page with "You are already signed in" message.

**Comment by TimidScript** [comment]
I got caught by that more than once. After signing in GreasyMonkey you need to go to the forum and then sign in with GreasyMonkey from there.

**Comment by Storm-Engineer** [comment]
Same here, and opening the forum page as @TimidScript suggested (thanks!) indeed worked this around. Still needs fixing, though.

**Comment by superclarkk** [comment]
Issues #411, #415 and #429 are all related

**Comment by superclarkk** [comment]
The link to the Forum now goes to the github issues page, so I don't think the previous workaround works any more.

**Comment by JasonBarnabe** [comment]
Should be fixed by #429.
