### ISSUE TITLE
Suggestion: Weekly/Monthly Stats

### ISSUE THREAD

**Issue by TimidScript** [JasonBarnabe/greasyfork#412]
Is it possible to make the stats to show number of weekly unique update checks (hashed, protect user privacy, IP address) or better still unique update checks for each calendar month. This will allow authors to gauge the user base size.

**Comment by TimidScript** [comment]
*weekly should be from Monday till Sunday. So fixed start and end date.

**Comment by JasonBarnabe** [comment]
I think IP addresses change enough that anything past daily will just start counting people multiple times. I don't see this as adding much value.
