### ISSUE TITLE
Lightbox is broken with very short, wide images

### ISSUE THREAD

**Issue by ssokolow** [JasonBarnabe/greasyfork#413]
When displaying a screenshot that is very wide relative to its height, the lightbox scales it up above 100%, causing a horizontal scrollbar to appear.

See, for example, the second screenshot on this script of mine:
https://greasyfork.org/en/scripts/14251-mark-owned-scummvm-games

![screenshot13](https://cloud.githubusercontent.com/assets/46915/14232171/e9432b0e-f96d-11e5-8841-2aff128f3db8.png)

**Comment by JasonBarnabe** [comment]
I have switched lightbox libraries and this appears to be fixed now.
