### ISSUE TITLE
Qupzilla at /en/help/installing-user-scripts

### ISSUE THREAD

**Issue by GreenLunar** [JasonBarnabe/greasyfork#414]
See https://github.com/OpenUserJs/OpenUserJS.org/blob/master/views/includes/documents/QupZilla.md

**Comment by JasonBarnabe** [comment]
So Greasemonkey is included in the default install?

**Comment by GreenLunar** [comment]
Yes

**Comment by JasonBarnabe** [comment]
Qupzilla is now given a shout out on the home and help pages.
