### ISSUE TITLE
Cannot start a new discussion to report bugs with scripts

### ISSUE THREAD

**Issue by leemoorex** [JasonBarnabe/greasyfork#415]
When I click Feedback, then Start New Discussion so that I can report a problem with script, I'm forwarded to homepage (https://greasyfork.org/en).

**Comment by rmenessec** [comment]
I'm having what may be the same problem:
```
You are already signed in.
```

**Comment by superclarkk** [comment]
+1

**Comment by JasonBarnabe** [comment]
Should be fixed by #429.
