### ISSUE TITLE
No infomails for script discussions

### ISSUE THREAD

**Issue by tobbexiv** [JasonBarnabe/greasyfork#416]
Like #372: I have the feature activated to get an email when a new discussion about one of my scripts is started / a new answer is created. But I did not receive any email for this discussion: https://greasyfork.org/forum/discussion/9226

Mail provider: web.de

Can anyone confirm this (maybe with a different mail provider)?

**Comment by JasonBarnabe** [comment]
Is this still a problem? I fixed some mail configuration that may have resulted in the email being blocked.

**Comment by tobbexiv** [comment]
I need a comment to one of my scripts to check. e.g. here as it is only a test script: https://greasyfork.org/de/scripts/5410-test-1

**Comment by JasonBarnabe** [comment]
Commented.

**Comment by tobbexiv** [comment]
I got no mail (also checked spam) :/

**Comment by JasonBarnabe** [comment]
I was mistaken; I fixed it for userstyles.org, not greasyfork.org. I've now applied to greasyfork.org and started a new test discussion.

**Comment by tobbexiv** [comment]
Still no success :/

But I found out that my mail provider uses [SPF](https://en.wikipedia.org/wiki/Sender_Policy_Framework) in a hard way, meaning that every mail which either has no SPF record for that server or has a record which tells to reject also will be rejected. Could it be possible that the mail your system sends is blocked by SPF?

**Comment by JasonBarnabe** [comment]
SPF is in fact the thing that I configured that I thought would fix it. What I did seems to have satisfied Gmail at least.

**Comment by tobbexiv** [comment]
You deny the sending for all other servers. So the only thing I can imagine now is that the mail is sent from a different server than that one allowed for your SPF record. Otherwise I have no idea why this fails, as it works for many other users.

**Comment by JasonBarnabe** [comment]
(With your actual email as defined on Greasy Fork instead of "tobbexiv.email.address@web.de").
```
[www@greasyfork ~]$ mail -s "Greasyfork email test" -r "noreply@greasyfork.org" tobbexiv.email.address@web.de
Manually testing for https://github.com/JasonBarnabe/greasyfork/issues/416
EOT
```
```
Oct 16 20:18:19 greasyfork sendmail[29950]: u9GKIJ1B029950: from=<noreply@greasyfork.org>, size=627, class=0, nrcpts=1, msgid=<5803e08b.nLjPiYhQ94yYxh34%noreply@greasyfork.org>, proto=ESMTP, daemon=MTA, relay=localhost.localdomain [127.0.0.1]
Oct 16 20:18:19 greasyfork sendmail[29949]: u9GKIJud029949: to=tobbexiv.email.address@web.de, delay=00:00:00, xdelay=00:00:00, mailer=relay, pri=30391, relay=[127.0.0.1] [127.0.0.1], dsn=2.0.0, stat=Sent (u9GKIJ1B029950 Message accepted for delivery)
Oct 16 20:18:20 greasyfork sendmail[29952]: u9GKIJ1B029950: to=<tobbexiv.email.address@web.de>, delay=00:00:01, xdelay=00:00:01, mailer=esmtp, pri=120627, relay=mx-ha03.web.de. [212.227.15.17], dsn=5.0.0, stat=Service unavailable
Oct 16 20:18:20 greasyfork sendmail[29952]: u9GKIJ1B029950: to=<noreply@greasyfork.org>, delay=00:00:01, mailer=local, pri=120627, dsn=5.1.1, stat=User unknown
Oct 16 20:18:20 greasyfork sendmail[29952]: u9GKIJ1B029950: u9GKIK1B029952: postmaster notify: User unknown
```

**Comment by JasonBarnabe** [comment]
I sent one from my Gmail too. No bounce - did you get it?

**Comment by tobbexiv** [comment]
Yes, I got it. I answer you there with more information.

**Comment by JasonBarnabe** [comment]
If I look through the logs, I see other failures with "Service unavailable"/"User known" from yahoo.com and gmx.com. I would guess that either it's telling the truth for those or it lies because it thinks it's a spammer.

**Comment by tobbexiv** [comment]
web.de / gmx.de / gmx.com belong all to United Internet (the companies that run them are subsidiaries of United Internet). So it makes sense that they all deny your mails if you are blacklisted by them :/

Yahoo is independent from those companies as far as I kow.

**Comment by JasonBarnabe** [comment]
```
   ----- Transcript of session follows -----
... while talking to mx-ha03.web.de.:
<<< 554-web.de (mxweb002) Nemesis ESMTP Service not available
<<< 554-No SMTP service
<<< 554 invalid DNS PTR resource record, IP=66.71.250.27
... while talking to mx-ha02.web.de.:
<<< 554-web.de (mxweb108) Nemesis ESMTP Service not available
<<< 554-No SMTP service
<<< 554 invalid DNS PTR resource record, IP=66.71.250.27
554 5.0.0 Service unavailable
550 5.1.1 <noreply@greasyfork.org>... User unknown
```

**Comment by JasonBarnabe** [comment]
Got a PTR record confgured and sent another test...

**Comment by tobbexiv** [comment]
I got an email from noreply@greasyfork.org with title "Greasyfork email test" and content "Test email". So it seems to work :)
