### ISSUE TITLE
Can't update scripts anymore

### ISSUE THREAD

**Issue by MirekGH** [JasonBarnabe/greasyfork#418]
Since at least few days I can't update any of my scripts @greasyfork. When I click update link on script's page (to open page, where I can edit script's code) - I get this message:

> We're sorry, but something went wrong.
> If you are the application owner check the logs for more information.

Problem occurs with all scripts on two different accounts.

Regards,
Mirek

**Comment by JasonBarnabe** [comment]
This may have been caused by a bad translation. Are you using Polish? If so, try now.

**Comment by MirekGH** [comment]
Yes, Polish - and now it works fine!
Thanks.
