### ISSUE TITLE
Question about Forum JSON

### ISSUE THREAD

**Issue by TimidScript** [JasonBarnabe/greasyfork#419]
Can you get the content of the latest post in JSON or a specific post in JSON? If so what is the URL structure. Thank you

**Comment by JasonBarnabe** [comment]
You can get JSON of a specific discussion, like https://greasyfork.org/forum/discussion/9162.json . Is that what you want?

**Comment by TimidScript** [comment]
No quite. I just wanted the latest rather than the full thread. 

Thank you anyway. It was worth asking.
