### ISSUE TITLE
People spamming in the forum about "copying others' scripts"

### ISSUE THREAD

**Issue by JixunMoe** [JasonBarnabe/greasyfork#421]
* No idea where the script was copied from.
* Lack of knowledge about the script licensing - I think I should delete those scripts, but I think *maybe* is too aggressive?
* And most of those scripts involving external resources that can lead to remote JavaScript execution - I have deleted those ones for now.

**Comment by JasonBarnabe** [comment]
I'm not sure if it was actually "stolen", but there are multiple copies of the same script, and a lot of them are external scripts, so I deleted the bad ones and banned the guy.
