### ISSUE TITLE
Importing from github  Error

### ISSUE THREAD

**Issue by TimidScript** [JasonBarnabe/greasyfork#422]
Hi,
I am trying to set up a github webhook. I can import one file at a time but if I try to import more than one 
I get an error. 

Example the following works
> https://github.com/TimidScript/UserScripts/raw/master/libraries/GM_update.js

And the following does not, though they are valid links. 

> https://github.com/TimidScript/UserScripts/raw/master/libraries/Generic.js
> https://github.com/TimidScript/UserScripts/raw/master/libraries/jsColorGM
> https://github.com/TimidScript/UserScripts/raw/master/libraries/Draggable%20Table%20Rows.js

In the end I just imported one at a time.

**Comment by JasonBarnabe** [comment]
I believe this is because you're an evil Mac user who uses carriage returns instead of line feeds. I've updated it so that it works for you.

**Comment by TimidScript** [comment]
I am worse, an Evil Microsoft Windows 7 user using FireFox. Thank you
