### ISSUE TITLE
Support for more Require

### ISSUE THREAD

**Issue by TimidScript** [JasonBarnabe/greasyfork#423]
Please consider extending the @require  url support. Github is currently banned and libraries such as Ajax.org Cloud9 Editor.   

Currently I am writing a script that uses: 
https://raw.githubusercontent.com/einars/js-beautify/master/js/lib/beautify.js (https://github.com/beautify-web/js-beautify)
https://cdnjs.cloudflare.com/ajax/libs/ace/1.2.3/

The require limitation does not really offer much security as you can inject anything using the main userscript.

**Comment by JasonBarnabe** [comment]
cdnjs.cloudflare.com is in the whitelist.

Use of GitHub has been discussed elsewhere. Long story short, we want to be able to see what code the script uses, both currently and historically.
