### ISSUE TITLE
License Displayed Suggestion

### ISSUE THREAD

**Issue by TimidScript** [JasonBarnabe/greasyfork#425]
Please utilize the full license text that you extract from the script, rather than the recognizable parts (eg. CC or GPL). The extra text is added for a reason and sometimes (like myself) contains an addendum to the recognizable license.

**Comment by JasonBarnabe** [comment]
Could probably use https://spdx.org/license-list instead.

**Comment by JasonBarnabe** [comment]
Use of a SPDX identifier or full name will result in a link, otherwise it will be shown verbatim.
