### ISSUE TITLE
Fail to sync with GitHub Git

### ISSUE THREAD

**Issue by xymopen** [JasonBarnabe/greasyfork#426]
Hi, there.
I submit a script some time age and found that it didn 't sync new version recently. I try delete the sync config and re-config, but only get an error.
![screenshot_of_the_error](https://cloud.githubusercontent.com/assets/8053733/15633566/a0401538-25e2-11e6-8f97-391219952a1c.png)

Script page: https://greasyfork.org/zh-CN/scripts/13491-erya
Gist page: https://gist.github.com/xymopen/79e80a9322d7a1f35f16

However, my new script didn't get that issue and sync with GitHub Gist successfully and smoothly. I suspect there is something wrong there.

**Comment by JasonBarnabe** [comment]
This would happen if you didn't have any additional info set. I have fixed it, please try again.
