### ISSUE TITLE
Stats Pages Suggestions

### ISSUE THREAD

**Issue by TimidScript** [JasonBarnabe/greasyfork#427]
Related to #412 

- Please consider adding world map showing global interests based on version fresh and Update installs rather than update checks. 
- Install count with Update Install Count on the stats page. So this will avoid it being used for popularity, but still can be accessed for those who are interested in accessing it.
- Maybe if possible, Fresh install + Update Install Count based on version, that keeps a record on the last few version of a script.

**Comment by JasonBarnabe** [comment]
I don't see why you care how many people actually updated when you can know the number of people who are checking for updates. This will give you a more accurate sense of the number of users.
