### ISSUE TITLE
Posting a discussion for a script takes me to the front page

### ISSUE THREAD

**Issue by madmuffinz** [JasonBarnabe/greasyfork#429]
Clicking the link to start a script discussion ( https://greasyfork.org/en/forum/post/discussion?script= ) takes me to  the front page with the massage "You are already signed in."
This bug has been happening for a while now.

**Comment by fireattack** [comment]
I have this bug as well.

It's not always reproducible, and I only encounter it on Chrome, not Firefox

**Comment by madmuffinz** [comment]
When it happened to me I was using Firefox

**Comment by madmuffinz** [comment]
It's still happening

**Comment by blivingston86** [comment]
Has been happening to me now for a long long time. I need to report an issue to one of the programmers but can't!! Very frustrating. It doesn't matter if I use Chrome or Firefox.

**Comment by superclarkk** [comment]
+1

**Comment by superclarkk** [comment]
Why is this issue being ignored?

**Comment by JasonBarnabe** [comment]
I believe it happens when you are logged in to the main site but not the forum. I've put in a fix - try it out.

**Comment by JasonBarnabe** [comment]
Well I'll just assume this fixed it everyone unless I hear otherwise.
