### ISSUE TITLE
In the control panel/profile: HTML entities are not correctly escaped in discussion titles

### ISSUE THREAD

**Issue by cvzi** [JasonBarnabe/greasyfork#430]
![amp](https://cloud.githubusercontent.com/assets/8470684/16502343/34bff77a-3f0e-11e6-867a-7b8943cef501.png)
The correct title, that is shown in the forum, is **DFiles.eu (Depositfiles), Keep2Share.cc & NitroFlare.com**.

**Comment by JasonBarnabe** [comment]
Fixed.
