### ISSUE TITLE
Notifications use the language of the user causing the notification

### ISSUE THREAD

**Issue by WoLpH** [JasonBarnabe/greasyfork#433]
I just got an email saying something along the lines of `[Greasy Forum] <username> started a discussion on <script>` which had a link to the Turkish version of the site.

Since I can't read Turkish this has to be a bug ;) The user that created the discussion is most likely (judging by the username) Turkish.

The link in the mail: https://greasyfork.org/tr/forum/discussion/10696/not-working

**Comment by tobbexiv** [comment]
See also #310 :)

**Comment by WoLpH** [comment]
Ah, didn't see that one.

Closing as duplicate of #310
