### ISSUE TITLE
Small typo in /de/help/external-scripts

### ISSUE THREAD

**Issue by zenosewald** [JasonBarnabe/greasyfork#435]
Hi. There is a minor typo on /de/help/external-scripts . Please change "Skript auch schon immer sriös war" to "Skript auch schon immer **seriös** war". Thanks for this platform btw...

**Comment by zenosewald** [comment]
And here: "Skript bemerken, welches sich nciht an diese Vorgaben" -> "Skript bemerken, welches sich **nicht** an diese Vorgaben"

**Comment by JasonBarnabe** [comment]
Fixed, thanks. You can update on https://www.transifex.com/greasy-fork/greasy-fork/ if you see any more issues, then you don't have to ask me to update.
