### ISSUE TITLE
Change line break rewrite description

### ISSUE THREAD

**Issue by JamesTheAwesomeDude** [JasonBarnabe/greasyfork#436]
Right now, the [page detailing how userscripts will be rewritten](https://greasyfork.org/en/help/rewriting) says

>* Line breaks will be converted to Unix-style line breaks (\n).

I think it might be good to change this to

>* Windows-style CRLF (`0x13 0x10`) and old Mac-style CR (`0x13`) line breaks will be converted to standard Unix-style (`0x10`) line breaks for maximum cross-platform compatibility.

or even

>* CRLF and CR line breaks will be converted to standard/Unix-style LF line breaks.

**Comment by JasonBarnabe** [comment]
I dunno, seems pretty straightforward how it is now. And since we're in JS-world, people will know it as `\n`... Your final suggestion sounds OK to me though. If you think it's better, make a PR and I'll merge it in.
