### ISSUE TITLE
Make @supportURL more prominent

### ISSUE THREAD

**Issue by JamesTheAwesomeDude** [JasonBarnabe/greasyfork#438]
From the main page, the link which users are most encouraged to click on takes you straight to creating a new GreasyFork thread _without even suggesting the user go to the designated support location_:

![screenshot_2016-08-10_20-43-41](https://cloud.githubusercontent.com/assets/2776014/17576759/fa82d034-5f3b-11e6-9c18-2ae8e0d41fb0.png)

The only way to access the `@supportURL` at all is to click the Feedback tab and then hit the link "Visit the author's support site." There should be a link on the main information page directing users with bug reports to the appropriate/preferred location.

**Comment by JasonBarnabe** [comment]
We are of one mind.

#306
