### ISSUE TITLE
Update JSHint

### ISSUE THREAD

**Issue by kufii** [JasonBarnabe/greasyfork#439]
when you use the syntax-highlighting source editor, you get a jshint warning every time you use a GM_ api function. This is because of the JSHint newcap option, which has been deprecated in the latest version

**Comment by JasonBarnabe** [comment]
The site uses coderay, not JSHint, and I don't see any problem with GM_ functions. So I don't know what you're talking about.

**Comment by kufii** [comment]
In that case it's the exact same warning message I'd get when using older versions of JSHint

Here's a screenshot

http://imgur.com/FU6QwVG

**Comment by JasonBarnabe** [comment]
I don't get any warnings or errors like that at all. You sure you're not using something to augment the editor?

**Comment by kufii** [comment]
I'm sure, happens on every device for me too

**Comment by JasonBarnabe** [comment]
Alright, got it figured out.

1. The site uses Ace Editor, which includes JSHint (coderay is for syntax-highlighting display only)
2. The JSHint integration did not work with Firefox, which what I was primarily testing with.
3. The warning only shows when the script is in strict mode.

Fixed it to work in Firefox and told it to ignore that warning.
