### ISSUE TITLE
Suggestion on Librarires

### ISSUE THREAD

**Issue by TimidScript** [JasonBarnabe/greasyfork#442]
User profile should include all scripts including libraries. Also the libraries link in the help section is obtuse. Few people would consider looking under help to find a library. A way to access user libraries through json.

thanks

**Comment by tobbexiv** [comment]
Similar suggestion like #340. Libraries should be made more prominent, searchable , ... like normal userscripts. Otherwise they are quite useless as I will nor manually search such a big list ...

**Comment by JasonBarnabe** [comment]
Everything here is done except making it more prominent - that should happen in #478.
