### ISSUE TITLE
Suggestion: Detect Tampermonkey and/or installed scripts and change some page content accordingly

### ISSUE THREAD

**Issue by derjanb** [JasonBarnabe/greasyfork#446]
The latest [Tampermonkey BETA](http://tampermonkey.net/changelog.php?show=gcal&version=4.2.5308) version added experimental support to allow certain pages to detect Tampermonkey and query the installed version. It's also possible to query by name whether a script is installed.
This can be used for example to not show installation hints or to modify download/install buttons to say something like "already installed".

Feel free to post concerns, issues, hints and change requests here: Tampermonkey/tampermonkey#322

Thanks,
Jan

**Comment by JasonBarnabe** [comment]
I've implemented this. The install button will switch to "Update to version X", "Downgrade to version X", "Reinstall version X" depending on the results. If it's not installed, or if we're not on the right version of Tampermonkey, then the button remains "Install this script".

**Comment by derjanb** [comment]
Thanks. It's working great here. :)

**Comment by tiansh** [comment]
It seems that `compareVersions` may have wrong result?

```
compareVersions('1.10','1.2') // should be1 
compareVersions('1.0.0','1.0') // should be 0
compareVersions('16.4','16.04') // should be 0
```

**Comment by JasonBarnabe** [comment]
@derjanb can you comment on whether Greasy Fork's implementation of version checking matches yours? https://github.com/JasonBarnabe/greasyfork/blob/master/app/assets/javascripts/versioncheck.js#L35-L58

That first result @tiansh posted seems incorrect on my end, but not sure about the behaviour of the other two.

**Comment by derjanb** [comment]
@JasonBarnabe Tampermonkey compares versions as described by the [Mozilla toolkit version format](https://developer.mozilla.org/en/docs/Toolkit_version_format), which means all given examples are correct and it looks like your [ruby code](https://github.com/JasonBarnabe/greasyfork/blob/master/test/models/script_version_compare_numbers_test.rb) is using this format as well.
