### ISSUE TITLE
Forum suggestion

### ISSUE THREAD

**Issue by TimidScript** [JasonBarnabe/greasyfork#450]
* Preview when Private Messaging
* A way for people to upvote or thank a user on the forum and a way to see the results on under the users icon. (Numbers or titles according to count).
* Inconsistent action between  Private Mail notification list and Forum list. When you click on the world icon and you get the list, you need to click on the title. Clicking on the username, goes to user profile name. While the envelope icon list (PMs), you need to click on the username to get to the message. Why not make the whole section clickable and leading to the message, while the user-icon goes to the user profile.

**Comment by JasonBarnabe** [comment]
For pretty much anything to do with the forum, either find a [forum addon](https://vanillaforums.org/addons) that does that or make your request on https://github.com/vanilla/vanilla. These seem like reasonable things, but I'm not too into hacking on the forum code.

**Comment by TimidScript** [comment]
Didn't realise it's of the shelf. I just write a user-script that does it.
