### ISSUE TITLE
Search has lost functionality

### ISSUE THREAD

**Issue by wwfloyd** [JasonBarnabe/greasyfork#463]
Search now appears to only check the description line of a script. It used to also check the title and/or include url domain -- not sure which, but, results are now much more limited, with good matches screened out.

**Comment by JasonBarnabe** [comment]
I reworked the directory structure of the site to support deployment with capistrano. I think that messed up search. I've fixed it, but I'll have to watch to see if it reoccurs.

**Comment by JasonBarnabe** [comment]
Seems fixed nwo.
