### ISSUE TITLE
Can't search out scripts after scripts updated

### ISSUE THREAD

**Issue by hoothin** [JasonBarnabe/greasyfork#465]
For example, [__no result__](https://greasyfork.org/en/scripts/search?q=HacgGodTurn) with search "HacgGodTurn" for scripts/23316-HacgGodTurn.
And all the scripts [__here__](https://greasyfork.org/en/scripts?sort=updated) can't be searched out.

**Comment by hoothin** [comment]
Seems fixed.

**Comment by JasonBarnabe** [comment]
This was the same as #463. I just had to restart the service. I'll keep an eye on it in the next few days.

**Comment by hoothin** [comment]
It appears again

**Comment by JasonBarnabe** [comment]
Maybe actually fixed now, we'll see.

**Comment by JasonBarnabe** [comment]
Looks like it is.

**Comment by hoothin** [comment]
It appears again, and the scripts can't be searched out are not updated ones this time
