### ISSUE TITLE
Every Google account sign in resets renamed username to the one from Google account

### ISSUE THREAD

**Issue by mik13ST** [JasonBarnabe/greasyfork#472]
Hello,
I found a bug. If you login using Google account, then the username is parsed from Google account details (your real name probably). If you then rename that account to a different nickname, then sign out, then login using Google account again, it will be reset (parsed) again, and it will rename the user.

It's not just changing the displayed name back to your real name, it is really renames the user. You can try searching for your newly renamed user, after you login using Google account. You won't find it.
This renaming is visible in script's page too.

I don't want people be able to know my real name. I want to be known by my nickname instead.

This is really annoying.
And yes, I just don't wanna create a normal account nor use this GitHub one.

**Comment by JasonBarnabe** [comment]
You need to turn off syncing for the Google account.

It should be telling you this when you go to edit your user name (#471).

**Comment by tobbexiv** [comment]
Path where to do this: https://greasyfork.org/users/edit_sign_in

**Comment by mik13ST** [comment]
Thank a lot.
Sorry for posting this.
I should read some text too, instead of just flying from title to title on a page :D.
