### ISSUE TITLE
Reduce spam scripts.

### ISSUE THREAD

**Issue by JixunMoe** [JasonBarnabe/greasyfork#473]
There are quite a lot spam scripts, wonder how we can reduce those.

I'm thinking about some soft limit, like for some keyword, the script will require mod review before go public, like on forum there are some people claiming been scammed (Those script did something unusual and try to hide their code; e.g. [this script](https://greasyfork.org/scripts/26698/code) at line 18 and 36).

We need to make it harder for bots to post stuff automatically, but unfortunately I do not understand how ruby works. I am thinking about store a value on session and a hidden field on the page, so previous bots will fail because of the missing auto generated field value.

Of course if they are just posting scripts manually on the browser, we can't do much about that. I think we can introduce [recaptcha](https://www.google.com/recaptcha/intro/) for new registered user (less than a week and have <= 2 scripts for example?).

**Comment by JixunMoe** [comment]
I am aware that there will be no perfect way to solve this problem. 

We just need to make it harder for them to spam the server.

**Comment by JasonBarnabe** [comment]
> I'm thinking about some soft limit, like for some keyword, the script will require mod review before go public, like on forum there are some people claiming been scammed (Those script did something unusual and try to hide their code; e.g. this script at line 18 and 36).

There are strings defined that, if present in the code, prevent saving. If you can identify something that's unlikely to cause false positives, let me know.

> We need to make it harder for bots to post stuff automatically, but unfortunately I do not understand how ruby works. I am thinking about store a value on session and a hidden field on the page, so previous bots will fail because of the missing auto generated field value.

This is already done as an anti-CSRF protection.

I haven't seen anything to indicate this is the work of a bot. I just assumed people were manually reposting.

**Comment by JixunMoe** [comment]
Hmm... okey then.

I think I'll close this for now, since there were protections in the first place 👍
