### ISSUE TITLE
Add github as authorized host for @require

### ISSUE THREAD

**Issue by CodeOptimist** [JasonBarnabe/greasyfork#476]
Please allow external scripts hosted from github, such as this link to commonmark.js:
https://raw.githubusercontent.com/jgm/commonmark.js/master/dist/commonmark.min.js

If this is problematic because it may change (which it might) then just allow a link to a specific commit like the following:
https://raw.githubusercontent.com/jgm/commonmark.js/d2398482c3bb2292d73c7372560442f46df63e63/dist/commonmark.min.js

**Comment by CodeOptimist** [comment]
I have the most sublime script; a rendition of truly paradigm pulverizing proportions. A veritable POEM of syntax and structure. Woe is this tyranny which would hinder it! WOE ARE THE MASSES WHO SUFFER FROM ITS OCCLUSION!

Thank you.

**Comment by JasonBarnabe** [comment]
[Get it from a CDN instead.](https://www.google.ca/search?q=commonmark.js+cdn) Files committed on GitHub are not meant for this.

If it's not available on a CDN, you can set up a library on Greasy Fork to sync from whatever file you like, then you can reference the library in your script.

**Comment by CodeOptimist** [comment]
Thanks for the response. I wasn't aware it was discouraged now.
How about https://rawgit.com/ as a designed-for-CDN replacement?
Or GitCDN: https://gitcdn.link/

I took those both from this popular StackOverflow question: http://stackoverflow.com/questions/8779197/linking-files-directly-from-github

It's fine if the answer is "no". ;)

Looks like jquery-textareaPreview isn't on any popular CDNs. I was able to get links from both those services however.

**Comment by JasonBarnabe** [comment]
GitHub says hotlinking is not allowed - https://github.com/blog/1482

rawgit.com and gitcdn.link I guess would be acceptable if you're referring to a specific commit. I will look into it.

**Comment by CodeOptimist** [comment]
Hey thanks! And thanks for that link, good find.
I'll be okay if you can't regarding those, but would be fantastic if you could. Cheers.

**Comment by JasonBarnabe** [comment]
Whitelisted RawGit and GitCDN, commit-specific URLs only.

**Comment by CodeOptimist** [comment]
Worked fantastic, thank you.
Just a quick note I just noticed that https://gitcdn.xyz is apparently an alternate domain name for https://gidcdn.link (I somehow ended up on the xyz one but merely replaced 'xyz' with 'link' in my @require URL and it immediately worked.)

**Comment by JasonBarnabe** [comment]
Yes, the gitcdn rule allows .xyz and .link.

**Comment by CodeOptimist** [comment]
Ah I think I found it. I had `https://gitcdn.xyz/repo/` which apparently redirects to `https://gitcdn.xyz/cdn/` when you visit it in a browser.

![](http://i.imgur.com/1Th2At9.png)

**Comment by JasonBarnabe** [comment]
I have updated it to accept both /cdn/ and /repo/.
