### ISSUE TITLE
Remove tracking scripts and replace other third-party resources with self-hosted copies

### ISSUE THREAD

**Issue by KOLANICH** [JasonBarnabe/greasyfork#480]
I see the site is using tracking scripts like newrelic. I think you should really consider removal of them.

Another concern is other third-party resources like Google Fonts which can also be used for tracking. You should consider to replace them with self-hosted copies.

**Comment by JasonBarnabe** [comment]
In use are New Relic, Google Analytics, and ad servers. Not sure why you would single out New Relic...

Self-serving the fonts is doable, but when you say "can be used for tracking", is that just theoretical or more?

**Comment by KOLANICH** [comment]
>Self-serving the fonts is doable, but when you say "can be used for tracking", is that just theoretical or more?

Just  theoretical. It leaks information about the browser, OS, locale, about the site visited, about the time it was visited. IP address is also leaked. This all allows Google to know that a user of specific computer have visited some website at specific time. Snooping is Google's and Cloudflare's businesses. And everyone using these services on own website is helping them to do this in exchange for free service.

Another problem is that CDN can return not the file been intended by the  website author, but a maliciously modified.

This problem can be solved by developing a package manager for browser which will discover, download developer-signed components, required by websites by using special URI scheme in addresses, from IPFS, verify and cache them. But the temporary solution is to download all the stuff, put it on own website, set distant expire time and link from there.

**Comment by JasonBarnabe** [comment]
Let me ask you this... If I were to self-serve the font file but still have New Relic, Google Analytics, etc. would you consider that an improvement or would it not even be worth it?

**Comment by KOLANICH** [comment]
It depends on if you are removing them.

**Comment by JasonBarnabe** [comment]
To be frank, they're not going anywhere. So if you're just going to block all third party stuff anyway, just do it.
