### ISSUE TITLE
Unable to sign in/up to the forum if either JS is disabled or third-party scripts are blocked

### ISSUE THREAD

**Issue by KOLANICH** [JasonBarnabe/greasyfork#482]

**Comment by JasonBarnabe** [comment]
This is probably not ever going to work without JS, considering the single sign on method used is called "jsConnect".

Not sure what third-party scripts would be causing the problem, though.

**Comment by KOLANICH** [comment]
How about not using jsconnect and use server-side solution for that?

**Comment by JasonBarnabe** [comment]
jsConnect seems to be the standard single sign in method for Vanilla forums. I'm not sure there is another option.

What are you using to disable third party scripts? It shouldn't require any third party stuff.

**Comment by KOLANICH** [comment]
NoScript + uMatrix. NoScript is nice for blocking features and JS by default it also has anti-clickjacking, uMatrix is nice to block XHRs, cookies and third-party scripts, this functionality not present in NoScript, so I have to use both.

**Comment by JasonBarnabe** [comment]
Vanilla by default references jQuery on ajax.googleapis.com. There's a setting to make it not do this, but it doesn't seem to work. Created https://github.com/vanilla/vanilla/issues/5207.

**Comment by JasonBarnabe** [comment]
Should no longer require ajax.googleapis.com with the upgrade to Vanilla 2.5.1. It will always require JS, though.
