### ISSUE TITLE
font key for language?

### ISSUE THREAD

**Issue by JixunMoe** [JasonBarnabe/greasyfork#483]
For example, Chinese is looks better when shown in `Microsoft YaHei UI` (`Microsoft JHengHei UI` for Traditional Chinese; not sure for Japanese).

Not sure about mac though.

Before and after replace the fallback font:

![image](https://cloud.githubusercontent.com/assets/5713045/23048528/520691da-f4ae-11e6-9b16-6672241d1443.png)

![image](https://cloud.githubusercontent.com/assets/5713045/23048514/393c868c-f4ae-11e6-8bfc-f6fba04ebc30.png)

**Comment by JasonBarnabe** [comment]
I guess I'll take your word for it that it's better.

So are you saying to use `font-family: "Open Sans", "Microsoft YaHei UI" sans-serif;` or `font-family: "Open Sans", "Microsoft JHengHei U" sans-serif;` or something else?

**Comment by JixunMoe** [comment]
I think it depends the language; like 2 Chinese have different preferred font.

I was thinking about adding this as an option to transflex and then rendered to the page like `<style>body {font-family: "Open Sans", "<Custom Font Name>", sans-serif;}</style>`, not sure if this is easy to do..

**Comment by JasonBarnabe** [comment]
I don't think that would be hard to do, but I bet a lot of people wouldn't understand. Most languages use the Latin alphabet anyway, so it's not like they each need their own.

I will implement your recommendations for zh-CN and zh-TW, and if there are other font recommendations for other languages, people can suggest them.

**Comment by JixunMoe** [comment]
I believe that will do for now, thank you 👍

**Comment by JasonBarnabe** [comment]
Better now?

**Comment by JixunMoe** [comment]
Looks great, thank you :D
