### ISSUE TITLE
Webm inline player for Google Chrome

### ISSUE THREAD

**Issue by Reydenge** [JasonBarnabe/greasyfork#488]
Hello, i wanted to install this expansion for Google, but webstore gave me that answer - 404. That’s an error. The requested URL was not found on this server. That’s all we know. Where i can find a working version of this scrit for Google? Tnx

**Comment by marsjaninzmarsa** [comment]
Umm, I think, that you're referring to another "Greasyfork" (Greasyfox maybe?)...
