### ISSUE TITLE
video element in script description can't work

### ISSUE THREAD

**Issue by noe132** [JasonBarnabe/greasyfork#489]
In script description field, the video element is allowed to be used but with limit attribute which are "src=(https) poster height width", I try using a video but all it can do was display the poster of the video, the video can't set to be autoplay, or using control button to play it (controls attrubute not allowed), therefore video only act like a image.

I suggest to add autoplay or controls attributes support on video element

**Comment by JixunMoe** [comment]
[app/helpers/application_helper.rb#L91](https://github.com/JasonBarnabe/greasyfork/blob/ece4b528102d99206c6a81399db6d3ce89237f9a/app/helpers/application_helper.rb#L91)

I think this is the line to be configured.

**Comment by noe132** [comment]
@JixunMoe 是的应该就是这个地方。。。video写进去不能播放不能控制，像一张图片一样动也动不了，根本没有用。。。

**Comment by JixunMoe** [comment]
@noe132 可以右键手动播放 hh

**Comment by JasonBarnabe** [comment]
Autoplay sucks, so it seem like we should always have `controls` on?

**Comment by noe132** [comment]
@JasonBarnabe On some browser cannot get `controls `easily or some user don't know how to get `controls`. Having `controls `will always be good for user. having `controls `always or optional either is ok I think

**Comment by JasonBarnabe** [comment]
`controls` will now automatically be added.
