### ISSUE TITLE
Can't access my scripts - "something went wrong"

### ISSUE THREAD

**Issue by TomRobert** [JasonBarnabe/greasyfork#491]
When I try to click on my name or one one of my scripts, I get: We're sorry, but something went wrong.
https://greasyfork.org/users/7962-tom-robert
It happens even when I'm not logged in.

**Comment by JasonBarnabe** [comment]
Should be fixed now, thanks for reporting.

**Comment by TomRobert** [comment]
Thanks for fixing.
