### ISSUE TITLE
https://greasyfork.org/en/scripts/by-site not working

### ISSUE THREAD

**Issue by ted120** [JasonBarnabe/greasyfork#496]
Example;

https://greasyfork.org/en/scripts/by-site/diamondhunt.co

shows scripts from all sites and lots of chinese scripts instead of the usual small number of diamondhunt scripts

![](http://i.imgur.com/XfmmbAt.png)

**Comment by jing2si** [comment]
Same problem.

**Comment by JasonBarnabe** [comment]
Fixed now.
