### ISSUE TITLE
Please add Violentmonkey to installation instruction for Firefox and Opera

### ISSUE THREAD

**Issue by AlexBeLi** [JasonBarnabe/greasyfork#497]
On this page https://greasyfork.org/en/help/installing-user-scripts
Violentmonkey is supported Firefox for now. 
https://addons.mozilla.org/en-US/firefox/addon/violentmonkey/
https://github.com/violentmonkey/violentmonkey/issues/84
Support for the opera was added long time ago.
https://addons.opera.com/en/extensions/details/violent-monkey/

**Comment by JasonBarnabe** [comment]
Done.
