### ISSUE TITLE
One name, multiple locales.

### ISSUE THREAD

**Issue by knoajp** [JasonBarnabe/greasyfork#499]
I want to use just one, identifiable name for my script.
But also want to describe introductions with multiple languages(English and Japanese).

Currently when I want to write "additional info" with multiple locales, you requires each of meta sections below
// @name:en
// @name:ja

But it's quite redundant.
// @name:en Some Script Name
// @name:ja Some Script Name

I want to use just one.
// @name Some Script Name

Please not to require corresponding locale on @name with locale for "additional info".

--
my scripts
https://greasyfork.org/ja/users/78927-knoa

**Comment by JasonBarnabe** [comment]
The normal case is that you translate the script's name as well. I can't see how you can sensibly have a script name in multiple languages with different writing systems. If you want to do this anyway, then you will have to live with the redundancy of repeating it in your code.
