### ISSUE TITLE
Set the baselines to ZERO on stats graphs

### ISSUE THREAD

**Issue by knoajp** [JasonBarnabe/greasyfork#500]
The baselines of "Daily installs" and "Daily update checks" are 1, and of "Weekly installs" is now 15.0 below.
https://greasyfork.org/en/scripts/31506-youtube-embedded-popupper/stats

They all and always should be 0 at the baselines.

**Comment by JasonBarnabe** [comment]
Congratulations on never being shut out.

Fixed now.

**Comment by knoajp** [comment]
Thank you very much!!
