### ISSUE TITLE
希望能够添加此外部Javascript到白名单

### ISSUE THREAD

**Issue by Antecer** [JasonBarnabe/greasyfork#503]
我希望能够添加此外部JavaScript
> www.17track.net/externalcall.js

该外部脚本来自于17track网站，用于查询快递单号使用。
我打算使用该脚本来更改ebay网站的订单查询，使其能够更方便。

以下是本人编写的脚本内容：
> // ==UserScript==
// @name         Ebay订单追踪器2
// @namespace    https://greasyfork.org/zh-CN/users/42351
// @require      https://code.jquery.com/jquery-3.2.1.min.js
// @require      https://www.17track.net/externalcall.js
// @version      0.4
// @description  使用17Track替代Ebay自带的订单追踪功能(API详情: https://extcall.17track.net/zh-cn/singlef2)
// @author       Antecer
// @grant        none
// @match        http://my.ebay.com/ws/eBayISAPI.dll?MyEbayBeta*
// @match        http://my.ebay.com/ws/eBayISAPI.dll?MyEbay&gbh=1&CurrentPage=MyeBayAllSelling&ssPageName=STRK:ME:LNLK:MESX
// @match        http://my.ebay.com.hk/ws/eBayISAPI.dll?MyEbayBeta*
// @match        http://my.ebay.com.hk/ws/eBayISAPI.dll?MyEbay&gbh=1&CurrentPage=MyeBayAllSelling&ssPageName=STRK:ME:LNLK:MESX
// ==/UserScript==
(function() {
    $("#shipTrack").remove(); // 删除ebay自带的订单追踪功能
    $("a").attr("target","_blank"); // 修改所有超链接打开方式为新窗口打开(如不喜欢可注释掉)
    $("a:contains('CN')").click(function(){// jQuery选择运单号
        $(".jcTrkApiDialog").remove();     // 开始查询前删除上次查询留下的对话框
        YQV5.trackSingleF2({
            //必须，指定悬浮位置的元素ID。
            YQ_ElementId:this.id,
            //可选，指定查询结果宽度，最小宽度为600px，默认撑满容器。
            YQ_Width:600,
            //可选，指定查询结果高度，最大高度为800px，默认撑满容器。
            YQ_Height:600,
            //可选，指定运输商，默认为自动识别。
            YQ_Fc:"0",
            //可选，指定UI语言，默认根据浏览器自动识别。
            YQ_Lang:"zh-CN",
            //必须，指定要查询的单号。
            YQ_Num:$(this).text()
        });
    });
})();

效果演示：
![111](https://user-images.githubusercontent.com/8684916/29487370-5e3eb3c6-852a-11e7-8745-a557e25e81a0.png)

**Comment by JixunMoe** [comment]
English translation:

> This external script is from "17 track" for tracking parcels.
> 
> I am planning to use this in my script to replace the tracking system in eBay.
>
> Script below is what I have so far:

个人想法：

1. 脚本有一定的局限性，17track 有提供不同语言的接口，可以不用写死。
2. 快递单号不一定总是包含 CN （如非国内发送到非国内的地区）。
3. 17track 对这个脚本有提供 HTTPS 版本。
4. 鼠标中键或按下 ctrl 点击链接可以在新窗口打开链接。你可以额外编写一个脚本实现永远在新窗口打开连接，而非尝试集成到同一个脚本。
4. 你可以尝试提取它的 API 然后直接利用 `GM_xmlHttpRequest` 等 API 进行查询，并对数据进行展现，避免引入第三方脚本。但是这样会加大工作量。

避免第三方脚本主要是为了防止第三方网站因为某种原因将提供的脚本变成带有奇怪代码的版本，导致目标页面被干坏事。

还有一个选择就是自己建立一个网页，将追踪号传过去，然后在网页调用这个脚本。你可以利用 GitHub Page 功能来建立。

此方案优点如下：

1. 因为域名不同于 eBay，即使因为各种原因导致第三方脚本被替换、修改，也不会影响用户的财产资源。假设（仅仅假设）第三方脚本被人为替换为自动下退单脚本，也会因为域名不同而无法继续操作。
2. 避免在脚本直接引入第三方脚本，无需对脚本进行大幅修改，符合脚本提交策略。

本人不代表网站所有者的观点，以上仅为我个人的观点。另外这类 Issue 建议使用英文发表。

**Comment by Antecer** [comment]
@JixunMoe 
API的话，JS跨域无法解决，而且找17track官方提供api也很麻烦。
自于，利用GitHub Page做中转，这个需要另外再开一个脚本回传数据，GitHub Page只支持静态页面，没法接收外部数据。

**Comment by JixunMoe** [comment]
@Antecer 用户脚本有提供跨域的方法，参见 [`GM_xmlHttpRequest`](https://wiki.greasespot.net/GM_xmlhttpRequest) 函数。另外上文中直接调用 API 指的是分析它提供的 JavaScript API 模拟如何与服务器交互抓取数据并实现，然后再进行数据归类与展现。当然，这么做得话会占用太多的时间。

至于利用 GitHub Pages 服务做中转，指的是在 eBay 页面上开一个 `iframe` 框架指向这个页面。至于你页面上执行的脚本，大体就是调用 17track 的这个脚本。直接利用框架将内容展现出来，这部分不需要回传数据。

**Comment by Antecer** [comment]
@JixunMoe
使用iframe指向github page这个方法不错，简单好用，待会试试。

**Comment by Antecer** [comment]
@JixunMoe 
今天试了下用GitHub pages 做中转，然后发现性能很糟糕，特别是国内用户。
后来仔细研究了以下17track调用的iframe结构，惊喜的发现可以直接调用它的iframe来实现，性能和安全兼顾的方式达成！
