### ISSUE TITLE
Horrible mistranslation when language set to hungarian

### ISSUE THREAD

**Issue by mzso** [JasonBarnabe/greasyfork#506]
Hi!

I couldn't find the button to post a discussion, so I needed to change the language to english.
It turns out the "utólagos megbeszélés" which roughly means "discuss in follow-up" is the button I need to press.
Since in english it's "Post Discussion". It should be something like "beszélgetés kiírása" (though we don't really use "beszélgetés" the hungarian word for discussion for this), or "téma kiírása"

If the site uses auto-translation it's a really bad idea to automatically switch/translate from english.

**Comment by tobbexiv** [comment]
Hi mzso,

could you indicate where you find this string? We use [transifex](https://www.transifex.com/greasy-fork/greasy-fork/dashboard/) for translation, but I could not find this string. Thus it might be the case that it comes from the translations of the forum or an add-on.

**Comment by mzso** [comment]
I encountered it when I wanted to start a new discussion in the feedback session, but it's like that with any new discussion: https://greasyfork.org/hu/forum/post/discussion
![uj_beszelgetes_-_greasy_forum_-_2017-09-03_15 57 39](https://user-images.githubusercontent.com/4479090/30003626-a9d6e208-90c0-11e7-9ac9-c603905a3d4e.png)

**Comment by JixunMoe** [comment]
That's part of the forum. I believe you need to report that to [Vanilla Team](https://open.vanillaforums.com/).

**Comment by JasonBarnabe** [comment]
@JixunMoe is correct. You can provide a new translation for Vanilla [here](https://www.transifex.com/vanilla/vanilla/).
