### ISSUE TITLE
Make language setting unrelated on URL

### ISSUE THREAD

**Issue by zcyzcy88** [JasonBarnabe/greasyfork#508]
In another word, make [same pages but different languages] use same URL, have no these shit:
><img width="546" alt="2017-09-07 21_39_45-greasyfork xzhihu - google search" src="https://user-images.githubusercontent.com/15178410/30166326-89d743aa-9415-11e7-9679-97171fc9e9ee.png">
<!-->
><img width="521" alt="2017-09-07 21_36_37-greasyfork singlescroll - google search" src="https://user-images.githubusercontent.com/15178410/30166319-85de8fec-9415-11e7-9fda-574fc8d7ad4b.png">
I wonder why Google don't think this as SEO-abuse.

**Comment by JasonBarnabe** [comment]
This is done intentionally as is OK with Google. https://support.google.com/webmasters/answer/182192?hl=en

If you access the URLs without the language tag, it will detect and redirect you.
