### ISSUE TITLE
Why does GreasyFork set Content-Disposition attachment?

### ISSUE THREAD

**Issue by arantius** [JasonBarnabe/greasyfork#513]
Context: https://github.com/greasemonkey/greasemonkey/issues/2586

Greasemonkey 4 is incompatible with Greasy Fork, because it forces a download action for script installs, but our script detection depends on the browser navigating to the script.  Before I try to rush a rewrite before Firefox 57 lands I'd like to ask: Why set the force download headers?

(Sorry if there's a better contact mechanism than GH issues, but all I could find was the site forum, and that seemed suboptimal.)

**Comment by JasonBarnabe** [comment]
I don't think I set that on purpose. [The code](https://github.com/JasonBarnabe/greasyfork/blob/4f54f6301a80dda7c347cdd37fbdd7377ed81544/app/controllers/scripts_controller.rb#L330) uses `send_file` which [sets `Content-Disposition: attachment` by default](https://apidock.com/rails/ActionController/Streaming/send_file).

I will change this.

**Comment by JasonBarnabe** [comment]
Better now?

**Comment by arantius** [comment]
Yes, thanks a ton!
