### ISSUE TITLE
Reduce data sent in .meta.js

### ISSUE THREAD

**Issue by JasonBarnabe** [JasonBarnabe/greasyfork#516]
Figure out which keys are necessary and only send those.

**Comment by tobbexiv** [comment]
How do you want to determine which keys are necessary? I for example have keys like history in my metadata which are not used by the normal update routine, but the script also has an update check which evaluates these keys. If you drop them, my update check would not display the newest information and a changelog.

**Comment by JasonBarnabe** [comment]
Your script downloads the .meta.js and not the .user.js?

Really, my motive for this change is that I realized some scripts have data URI images in their meta. I could just strip those out and achieve most of what I wanted.

**Comment by tobbexiv** [comment]
I download the meta.js to check for updates and if an update is available, the user will get a popup with the changelog and a link to the .user.js file. Then the full script is only accessed if the user really wants to get the script. I assume that an access to the meta.js is less effort for the server than the full user.js as the scripts source has thousands of lines of code in comparison to the stripped meta.js with a maximum of a few hundred lines of code.

Maybe you can start ba stripping all resource keys as I would assume that most of the data URIs are included in such keys.

**Comment by JasonBarnabe** [comment]
All `@resource` and `@icon` keys are being stripped in .meta.js requests now.
