### ISSUE TITLE
Show only English results for English users by default

### ISSUE THREAD

**Issue by JasonBarnabe** [JasonBarnabe/greasyfork#518]
Possibly other combinations.

**Comment by JixunMoe** [comment]
How about an option in profile page, "Show scripts in language [ dropdown* ] and [ user.language (readonly text) ]"

\* expecting dropdown behaviour to be something like this: https://select2.org/selections#limiting-the-number-of-selections

**Comment by JasonBarnabe** [comment]
Implemented as a link at the top of the script results.
