### ISSUE TITLE
Cannot modify username from google login

### ISSUE THREAD

**Issue by lidiamartinez** [JasonBarnabe/greasyfork#519]
I logged using my google account. I get my real name displayed, which I don't like. I go to my profile, edit my name. My top bar name is modified. I go to any other page or logout, login, and my previous username is still there. I cannot modify it but on the first page where I save changes.

**Comment by JasonBarnabe** [comment]
Go into your account, edit your log in methods, and turn off "Syncing".

This comes up periodically so I should probably mention this when you sign in as a new user. https://github.com/JasonBarnabe/greasyfork/blob/master/config/locales/en.yml#L707

**Comment by JasonBarnabe** [comment]
The first time you log in, it tells you what your name is. If you go to change it and you have syncing turned on, it says "Your user name and email are set to be synced when you log in with Google. Edit your sign in methods to remove syncing if you want to permanently set a custom user name or email. " at the top of the page. So I think this is mentioned sufficiently.
