### ISSUE TITLE
Fail to sign up. Error "Name can't be blank"

### ISSUE THREAD

**Issue by sympethetic** [JasonBarnabe/greasyfork#521]
Having problem when I sign up.
"1 error prohibited this user from being saved:
Name can't be blank"

Name : sympethetic
Email : sympethetic@sina.com

**Comment by willowj** [comment]
+1,me too.

**Comment by JasonBarnabe** [comment]
What method are you using to sign up (Google/GitHub/username)?

**Comment by willowj** [comment]
If use github, then:
> Greasy Fork requires an email to make a new account, but GitHub didn't provide one for you. You can either update your GitHub account to have one, then try signing in again, or create a normal email/password account on Greasy Fork, then add your GitHub account to it.

It raises error 'Name can't be blank' , although typed, when to create a normal email/password account. 

Also reCAPTCHA error after tried too many times, which maybe caused by GFW.

Just now, successfully signed in.
You did ? Thanks.

**Comment by JasonBarnabe** [comment]
- Go to https://greasyfork.org/en/users/sign_up
- Fill in name, email, password, password confirmation
- Submit

Works for me. Am I missing something?

**Comment by sympethetic** [comment]
Just succeed to sign up using username and email address.
Maybe GFW issue caused former error.
Thanks for your replies.

**Comment by dominent7** [comment]
i still get same error："1 error prohibited this user from being saved:
                                   Name can't be blank

**Comment by JasonBarnabe** [comment]
I don't see this problem, but I believe others do. Maybe something is changing the page (a script?). I have posted https://greasyfork.org/forum/discussion/35676/unable-to-register-accounts-china-only to discuss it.
