### ISSUE TITLE
GM4 polyfill

### ISSUE THREAD

**Issue by Mottie** [JasonBarnabe/greasyfork#523]
From my understanding, Tampermonkey and Greasymonkey won't update an `@require` script unless the url changes.

The [GM4 polyfill](https://github.com/greasemonkey/gm4-polyfill/commits/master) continues to be updated; but we're told to use (source [GF](https://greasyfork.org/en/help/external-scripts) & [polyfill](https://greasemonkey.github.io/gm4-polyfill/)):

```js
// @require https://greasemonkey.github.io/gm4-polyfill/gm4-polyfill.js
```

I just updated a few of my userscripts by adding `?updated=20180103` to the end of the above address to ensure that all users are getting the latest (unbuggy) version; but now the userscripts won't update on GreasyFork because of the addition.

![2018-01-30 13_41_01-gist raw links](https://user-images.githubusercontent.com/136959/35587657-0a4f6d62-05c4-11e8-9849-7ac048c31769.png)

So, right now the only option a user has is to remove and reinstall all userscripts to ensure they're getting the most recent version of the GM4 polyfill.

**Comment by JasonBarnabe** [comment]
This is one of the reasons I recommend CDNs - the content at the URLs does not change. But this is a special case. I have updated it to allow arbitrary query parameters for this URL.
