### ISSUE TITLE
Not verify password before change email is a security risk.

### ISSUE THREAD

**Issue by strongop** [JasonBarnabe/greasyfork#525]
Change email on this page https://greasyfork.org/en/users/edit,
didn't verify the user's password.
The user forget to log off on some machine, he may lost his account forever if someone changed his email.

**Comment by FranklinYu** [comment]
Any updates? Will this ever be fixed?

**Comment by JasonBarnabe** [comment]
Now it will send you an email (to the old address) to confirm the change before it takes effect. Not exactly what you asked for but I believe it solves the issue you raised.
