### ISSUE TITLE
Can't correctly highlight template literals

### ISSUE THREAD

**Issue by strongop** [JasonBarnabe/greasyfork#527]
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals

See line 247 of https://greasyfork.org/en/scripts/37974-12306%E5%B8%A6%E6%88%91%E5%9D%90%E7%81%AB%E8%BD%A6%E5%9B%9E%E5%AE%B6/code

**Comment by JasonBarnabe** [comment]
Same as #350.
