### ISSUE TITLE
Use cases for `@includes` and `@matches` in scripts.

### ISSUE THREAD

**Issue by Sxderp** [JasonBarnabe/greasyfork#536]
I posted a request on the usersScript API bugzilla about adjusting how `@include` and `@match` work (allow "OR") and they've asked for additional information regarding use cases. I suspect the majority of use cases, where both are used, have to do with the ability to use RegExp in `@include` but nevertheless, it would be great if some sort of details or statics could be provided on how scripts are currently using the fields. Any additional input is appreciated.

Bugzilla Link: https://bugzilla.mozilla.org/show_bug.cgi?id=1437098#c2

@JasonBarnabe 

Cross posted on openuserjs repo. https://github.com/OpenUserJS/OpenUserJS.org/issues/1333

Check out https://github.com/greasemonkey/greasemonkey/issues/2663 for various additional details.

**Comment by JasonBarnabe** [comment]
So you're looking for scripts that use both `@include` and `@match`?

**Comment by Sxderp** [comment]
That is correct.

**Comment by JasonBarnabe** [comment]
There are hundreds that do that. Here's 50 of them:

https://greasyfork.org/scripts/39-wallpaperfox-com-add-pinterest-button/code
https://greasyfork.org/scripts/66-vkontakte-chat-translator/code
https://greasyfork.org/scripts/99-cendoldarkbb-qrfixer/code
https://greasyfork.org/scripts/107-deviantart-direct-download-image/code
https://greasyfork.org/scripts/118-tieba-utilities/code
https://greasyfork.org/scripts/119-baidu-multiuser/code
https://greasyfork.org/scripts/280-html5-for-moefm/code
https://greasyfork.org/scripts/281-cc-code/code
https://greasyfork.org/scripts/282-tieba-preload/code
https://greasyfork.org/scripts/283-baidu-zhidao-thread-notification/code
https://greasyfork.org/scripts/285-%E4%BC%AA-%E8%BD%AC%E6%8D%A2%E8%B4%B4%E5%90%A7-ed2k-%E9%93%BE%E6%8E%A5/code
https://greasyfork.org/scripts/286-moe-fm-downloader/code
https://greasyfork.org/scripts/289-tieba-template/code
https://greasyfork.org/scripts/350-izhihu/code
https://greasyfork.org/scripts/387-html5-youtube-f-key-fullscreen/code
https://greasyfork.org/scripts/453-watchitlater/code
https://greasyfork.org/scripts/474-github-unfold-commit-history/code
https://greasyfork.org/scripts/475-github-json-reformatter/code
https://greasyfork.org/scripts/603-gamefaqs-user-page-in-search-bar/code
https://greasyfork.org/scripts/606-gamefaqs-post-and-track/code
https://greasyfork.org/scripts/608-gamefaqs-multiple-single-pm-recipients/code
https://greasyfork.org/scripts/610-gamefaqs-new-poll-link-in-topic-list/code
https://greasyfork.org/scripts/612-gamefaqs-close-topic-confirmation/code
https://greasyfork.org/scripts/613-gamefaqs-quicker-new-poll/code
https://greasyfork.org/scripts/614-gamefaqs-account-specific-site-colors/code
https://greasyfork.org/scripts/615-gamefaqs-collapsible-spoilers/code
https://greasyfork.org/scripts/846-feedly-slimfeed/code
https://greasyfork.org/scripts/943-youtube-center/code
https://greasyfork.org/scripts/988-marginal-revolution-kill-file/code
https://greasyfork.org/scripts/1008-add-print-page-to-zhihu/codehttps://greasyfork.org/scripts/1017-niconico-%E5%8B%95%E7%94%BB%E3%83%9A%E3%83%BC%E3%82%B8%E3%81%8B%E3%82%89%E3%83%9E%E3%82%A4%E3%83%AA%E3%82%B9%E3%83%88%E7%99%BB%E9%8C%B2/code
https://greasyfork.org/scripts/1022-neogaf-quick-quote-reply-and-edit/code
https://greasyfork.org/scripts/1023-youtube-me-again/code
https://greasyfork.org/scripts/1025-neogaf-image-scaling-lite/code
https://greasyfork.org/scripts/1027-what-cd-album-art-display/code
https://greasyfork.org/scripts/1030-whatimg-drag-drop-files/code
https://greasyfork.org/scripts/1037-gazelle-toggle-format-visibility/code
https://greasyfork.org/scripts/1255-tieba-chat/code
https://greasyfork.org/scripts/1284-lucifers-happyplace-redirect/code
https://greasyfork.org/scripts/1285-mafia-wars-facebook-tinyurl/code
https://greasyfork.org/scripts/1303-new-torrent-notifier/code
https://greasyfork.org/scripts/1314-doa-power-tools-plus-iv-update-by-tlc/code
https://greasyfork.org/scripts/1315-unified-chekplay-for-challenge-group-administration/code
https://greasyfork.org/scripts/1527-metafilter-recent-activity-border-o-rainbows/code
https://greasyfork.org/scripts/1528-metafilter-inline-video-fishy-icon/code
https://greasyfork.org/scripts/1529-metafilter-hedgehog-comment-pointer/code
https://greasyfork.org/scripts/1575-clean-up-denverpost-com-articles-for-easy-reading/code
https://greasyfork.org/scripts/1679-google-site-tool-site-results-exclude-sites/code
https://greasyfork.org/scripts/1681-google-cache-highlight-search-query-terms-for-https/code
https://greasyfork.org/scripts/1741-show-localstorage-entries/code
https://greasyfork.org/scripts/2024-w-a-r-links-checker-premium/code

**Comment by Sxderp** [comment]
Hey, thanks a lot. It's actually fairly interesting that none of the linked scripts actually utilize any of the features of `@include`. Instead they just duplicate `@match`.

**Comment by JasonBarnabe** [comment]
You may want to try asking on https://greasyfork.org/forum/ to see if any the experts have an opinion.
