### ISSUE TITLE
An Error occured when I tried to Login the Forum

### ISSUE THREAD

**Issue by mscststs** [JasonBarnabe/greasyfork#538]
Here are the errors that the console report
![qq 20180226163148](https://user-images.githubusercontent.com/18003247/36660287-98565a9a-1b12-11e8-90bb-dd2bc2df0415.png)

UA : Chrome 64.0.3282.186 
OS : Ubuntu 16.04 LTS
Location : China 

Addition : with Firefox I have got some information.
The problem is about the Jquery script from [Google](https://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js?v=2.3.1).
This Domain has been blocked by the GFW (Great Fire Wall)

Now ,Everything is OK when I add the domain into my proxy list.
But I still hope that you can solve this problem.

PS : The performance under Windows is normal. This may be an exception.

Thank you.

**Comment by JasonBarnabe** [comment]
This is the same as #482.
