### ISSUE TITLE
GF hosted library not working

### ISSUE THREAD

**Issue by Mottie** [JasonBarnabe/greasyfork#539]
We are using a library hosted on GF &ndash; [jscolor](https://greasyfork.org/en/scripts/15563-jscolor/code) &ndash; which recently stopped working. On that page, this require url is shown:

```js
// @require https://greasyfork.org/scripts/15563-jscolor/code/jscolor.js?version=106439
```

but the link &ndash; https://greasyfork.org/scripts/15563-jscolor/code/jscolor.js?version=106439 &ndash; is delivering a blank page with no content as no response data is provided. If the `version=106439` parameter is removed, the content is delivered.

**Comment by tflori** [comment]
btw.: the [mutation](ttps://greasyfork.org/scripts/28721-mutations/code) library has the same issue

**Comment by JasonBarnabe** [comment]
Should be fixed now, thanks for reporting.
