### ISSUE TITLE
Idee: Transform script into bookmarklet

### ISSUE THREAD

**Issue by Djamana** [JasonBarnabe/greasyfork#540]
Just got the idea that it'll be nice if GF offers the option to also provide the script as bookmarklet.
For that there should be an options in your admin to enable this .
-> So when enabled there'll be the link of the bookmarklet somewhere need the green install button. 
(or maybe to save bandwidth - that the user have to click to request the bookmarklet  before it is shown/rendered in the page )

The creation of a bookmarklet: 
1. Minify the script (or just remove  all comments of a script)
2. Remove all linebreaks so the whole just get's some long long line
3. Put "javascript:" o front of it.
Wrap it all in into some <a> link tag and put it on the site.

-> The bookmarklet offers and extra way to use the script without the need to install so Userscript client like Trampermonkey

**Comment by tobbexiv** [comment]
What about `@requires` etc.?

**Comment by Djamana** [comment]
Well good point.
Download and paste the @requires scripts before the user script?

Better not - keep it simple show a warning and/or disable the option bookmarklet if there is some `@requires`

**Comment by JasonBarnabe** [comment]
This sounds like it would not be very friendly functionality. It would be hard to see/change/update the code. As mentioned you would need to handle `@require`s.

I would suggest if you are interested in this, then you create a user script that could actually do it. If that works good and is popular, then I can see about integrating it into the site.

**Comment by Djamana** [comment]
> This sounds like it would not be very friendly functionality.
People who release stuff on GF aren't users, they are mostly developers, who (hopefully) know how to code, how code works and how to make it working aka debugging.

Why are ya that 'scared/fixed' about that @requires?
Nice ya consider this , but this 'problem' is really secondary.
**Its no real 'blocker' in implementing  the idea.**
Without having check that yet I guess 90% of the script don't make use of @requires.
Put a notice aside that @requires is currently not supported and I guess 'we'( the community ) will be come along with that.
... and later there is always room to elaborate that and update the code so it'll take care for @requires.

Some bookmarklet creating code is here
https://github.com/mrcoles/bookmarklet
That'll run it.
https://mrcoles.com/bookmarklet/
^-Well out of the box it won't support '@requires'.
 
Suggestion: 1
Okay and I got a more simple idea about this.
What about to let the user/developer create the bookmarklet on their own.
Just provide the some **text field** for the  **bookmarklet** and that's it.

Hmm well when I think about this I may do this already by just pasting a bookmarklet link in the description(if the  'javascript:' suffix is not blocked anything like that). 
However having extra text field for that purpose -just like the one for the screenshot- would be more nice.

**Comment by tobbexiv** [comment]
> People who release stuff on GF aren't users, they are mostly developers, who (hopefully) know how to code, how code works and how to make it working aka debugging.

None of my scripts will work as bookmarklet as I make use of too many features of the userscript managers. And as an author I would not care whether my script works as a bookmarklet. I write for userscript managers and not for bookmarklets (especially as my scripts usually contain thousands lines of code.

> Well without having checked that yet I would guess 90% of the script don't make use of @requires keyword.

I doubt this. Especially with GM 4.0 many scripts make use of the polyfill. I would say that more than 50% of the popular scripts make use of requires. And requires are not everything. There is also `@grant` which is used by a lot of scripts. So, to bring this functionality for all scripts, you basically have to recreate all the possibilities of the userscript managers into the bookmarklet. And with CORS XHR this will not be possible. If you are not able to do this, the feature will only be possible for a small amount of userscripts.

Summed up, I see quite a lot of effort for only a few scripts and even fewer users. I agree with Jason that this is better placed in a userscript than in the Greasemonkey source code.
