### ISSUE TITLE
GreaseFork 上我更新油猴脚本时候提示：附加信息 - 脚本语言 必须存在

### ISSUE THREAD

**Issue by pendave** [JasonBarnabe/greasyfork#541]
GreaseFork 上我更新油猴脚本时候提示：

很抱歉，您提交的内容有点问题…

附加信息 - 脚本语言 必须存在

附加信息 - 脚本语言 不能为空字符

![1ms 2p8l 3z8suv9 g5](https://user-images.githubusercontent.com/1331881/37551663-1ff12144-29df-11e8-9bb4-99e6652c10e8.png)

But yesterday when I update my script there's no such warninig!
但是昨天我更新此脚本的时候并没有这样的提示！
必须怎么改啊？

**Comment by JasonBarnabe** [comment]
This is a bug uncovered by a change I made today. I have undone part of the change so you should be able to update again.
