### ISSUE TITLE
Can't search my scripts

### ISSUE THREAD

**Issue by luochenzhimu** [JasonBarnabe/greasyfork#542]
I have published a scripts on https://greasyfork.org.

Name: BaiduPan Explorer
Link: https://greasyfork.org/en/scripts/39844-baidupan-explorer 

I have select the Script type: Public user script - a user script for all to see and use. 
But when I search about “BaiduPan Explorer” or “BaiduPan”, there is “No scripts found”.
What’s the problem of it? 
Thanks!

**Comment by JasonBarnabe** [comment]
There was a problem with the process to index new and updated scripts. I have kicked it a few times and it seems to be picking up on new ones now.
