### ISSUE TITLE
Short the Default Link of Raw Userscirpt

### ISSUE THREAD

**Issue by Rhilip** [JasonBarnabe/greasyfork#548]
Now, The Install and Update link of userscript may like `https://greasyfork.org/scripts/<id>-<name>/code/<name>.user.js`. The `name` came up twice in this link.

It is not a terrible problem when the name of userscript is in english language or it is too short.
But when it's name is not only in other language but also too long, User maynot update successfully as the discussion in Forum [名字太长,同步失败](https://greasyfork.org/zh-CN/forum/discussion/32745/x) "Long Script Name cause sync failed"

In other way, the name of userscript can be changed when owner update their script. But the post id will not change after first publish.

Maybe Link like `https://greasyfork.org/scripts/<id>/code/<id>.user.js` is more easy to use. And it can touch now.

**Comment by JasonBarnabe** [comment]
The reason the name is included in `<name>.user.js` is that (at least at the time this code was written), the "filename" of the script was used as the name by some user script managers. I'm not sure if that's still the case.
