### ISSUE TITLE
Can't login with GitHub Account

### ISSUE THREAD

**Issue by RoestVrijStaal** [JasonBarnabe/greasyfork#555]
I'm getting error "Greasy Fork requires an email to make a new account, but GitHub didn't provide one for you. You can either update your GitHub account to have one, then try signing in again, or create a normal email/password account on Greasy Fork, then add your GitHub account to it."

I tried to revoke GreasyFork access and try it again. Same error.

**Comment by JasonBarnabe** [comment]
Does your GitHub account have an email attached? Did you try the alternate method suggested?

**Comment by RoestVrijStaal** [comment]
My GH has an verified emailaddress. My intention of using my GH as login is to not create yet another account of the dozens I already have and need to keep care of. 

But I'll try it out soon.
