### ISSUE TITLE
The link provided for the webhook doesn't work and give a 404 error

### ISSUE THREAD

**Issue by tunisiano187** [JasonBarnabe/greasyfork#557]
Hello,
the webhook link give a 404 error when testing it.
and if the test is on Gitlab, it says HTTP 403.
Thanks

**Comment by JasonBarnabe** [comment]
I'm not sure which "webhook link" you're referring to. Do you mean testing the webhook from GitHub?

**Comment by JasonBarnabe** [comment]
Not enough info provided.
