### ISSUE TITLE
Not getting popup or email notifications in discussions

### ISSUE THREAD

**Issue by FunnyPocketBook** [JasonBarnabe/greasyfork#558]
I've never gotten an email that a new discussion has been opened for one of my scripts, only when I got a private message. I also do not get notified if someone replied to one of my discussions/replies

**Comment by JasonBarnabe** [comment]
Just tested it now, worked fine. So either it's been fixed or it's something specific to you. Check your notification settings at https://greasyfork.org/en/users/edit . If it's still not working, give me the URL for a script of yours and I will try to trigger notifications.
