### ISSUE TITLE
[Request] Separate unlisted userscripts on user page

### ISSUE THREAD

**Issue by valacar** [JasonBarnabe/greasyfork#559]
I find it annoying on my user page that my unlisted scripts are mixed in with my normal scripts. Would it be possible to move them to their own separate block, or perhaps move them all down to the bottom of the list?

Also, as far as I can tell, my scripts are (by default) sorted by daily installs, and then anything with zero daily installs appears to be unsorted and essentially random...I can't make much sense of it. Would be nice to see that changed as well.

**Comment by JasonBarnabe** [comment]
Not sure if this changed since your report, but there's a sorting control on the right that default to sorting by daily installs. If daily installs are tired, older scripts come first.

**Comment by JasonBarnabe** [comment]
Unlisted scripts, libraries, and deleted scripts are all split out from the main list now. Note that not all these will be visible to all users.

**Comment by valacar** [comment]
Thanks for adding the feature, I appreciate it.
