### ISSUE TITLE
Exception 403006

### ISSUE THREAD

**Issue by qsniyg** [JasonBarnabe/greasyfork#560]
While trying to update [my userscript](https://greasyfork.org/en/scripts/36662-image-max-url) (code here: https://github.com/qsniyg/maxurl/blob/master/userscript.user.js?raw=true), I got this error:

>Exception 403006

The userscript is now >1MB, does that have anything to do with it?

**Comment by JixunMoe** [comment]
false positive on obfuscation detection. 

@JasonBarnabe Maybe add `\b` before and after the pattern?

**Comment by JasonBarnabe** [comment]
Sure, try now.

**Comment by qsniyg** [comment]
Thanks, it works now!

**Comment by Yuriy008** [comment]
Pls I need to some help
Exception 403006
[43534.txt](https://github.com/JasonBarnabe/greasyfork/files/2808374/43534.txt)

**Comment by JasonBarnabe** [comment]
Obfuscated script is not allowed. You should be able to post the original source.
