### ISSUE TITLE
Automatically generated scripts

### ISSUE THREAD

**Issue by qsniyg** [JasonBarnabe/greasyfork#561]
I'm curious what the site's policy on automatically generated scripts are. My script is currently ~1.2MB, which means it could be a little slow, as the majority of it is a huge if-else chain. I have an idea to make it faster (adblock-like compilation), but I'm curious if this would be considered obfuscation.

The automatically generated script would still be readable (not minified), but admittedly less so than the state it's currently in.

It would look something like this:

```
if (domain[0] === 'a') {
    if (domain[1] === 'a') {
        if (domain.length === 2) {
            // code here
        }
    } else if (domain[1] === 'b') {
    }
} else if (domain[0] === 'b') {
}
```

Whereas the original code would have been:

```
if (domain === 'aa') {
    // code here
} else if ...
```

I would link to the source code generating the file, of course. Is this acceptable under the current rules?

**Comment by eight04** [comment]
If they are all equality checks (`===`), you can use a map:
```js
const handlers = {
  "aa": () => {
    // code here
  },
  "ab": () => {
    // code here
  },
  "bb": () => {
    // code here
  },
  ...
};
handlers[domain]();
```

**Comment by qsniyg** [comment]
Right, but actually it's a little more complex than that (with regex-like expressions). I just gave that as an example of how the code could be harder to read :)

**Comment by JasonBarnabe** [comment]
I would not consider the example given to be contravening the obfuscation policy. I would question why this is necessary, but that's not really my concern.

**Comment by qsniyg** [comment]
Thanks! That's all I wanted to know :)
