### ISSUE TITLE
reCAPTCHA is a MAJOR pain for users who block or clear tracking cookies

### ISSUE THREAD

**Issue by ssokolow** [JasonBarnabe/greasyfork#562]
If I don't allow Google to set a uniquely identifying cookie on my browser (ostensibly, to build up a reputation score), I can find myself spending 30-120 seconds futzing my way through images before reCAPTCHA is finally satisfied... every single time... and, lately, it's been multiple minutes because I have to keep loopingthrough your "reCAPTCHA verification failed. Please try again." despite my having filled out the CAPTCHAs correctly.

(I'm not sure if this is a bug, since I seem to run into this on GreasyFork and Packt Publishing's Free Learning promo and nothing else.)

This time, I spent close to 10 minutes clicking CAPTCHAs, just to **finally** get a refusal from GreasyFork because I'd forgotten to bump the version number, and then it was back to the CAPTCHAs again! (A frustration made worse by how, for half of them, I have to wait multiple seconds for the stupid "fade old image out, wait for new one to appear" animation.)

That's a major disincentive to updating scripts not significant enough to merit their own Git repo to sync against and to releasing fixes in a timely manner when they could instead be batched up indefinitely to procrastinate the CAPTCHAs.

Is there any chance you could use another CAPTCHA provider?

**Comment by JasonBarnabe** [comment]
I would consider another provider as an alternative or replacement to what we have now; however, I am not familiar with the alternatives and whether they would cause you the same issue.

**Comment by ssokolow** [comment]
I've never had a problem with any CAPTCHA other than reCAPTCHA (and that includes some of the big-name alternative paid-only services with strong incentives to be as tough as Google, like the former FunCaptcha).

As far as I can tell, it's just a bug in reCAPTCHA that only manifests with users who block their "reputation" cookies, similar to how, whenever I buy a Humble Bundle, I have to chase the thing up the page because each "Verify" click causes it to jump up a bit unless the page is scrolled up to the top (but I can't reach the "Pay with..." buttons when it's scrolled up to the top.)

It seems to have at least three bugs relating to that situation that I've noticed.

**Comment by TimidScript** [comment]
All I want to do is set my unlisted script back to public and have to go through this nightmare. I have spent over 3min trying to achieve this. What is the point of reCAPTCHA?

You can update your script from github auto after it is created. And then you can bypass and abuse the system all you want. So what is the point of reCAPTCHA?

A sincere question: Can someone please explain the reason to have it in the first place?

**Comment by eight04** [comment]
I think it is used to prevent spam posted by bots.

**Comment by TimidScript** [comment]
Really? 

Then maybe limit the number of manual updates a person can do. A small number like 5 manual updates a day, and a little more a week.  

And add trusted level. For those who have contributed scripts to the site for years, they should not have to deal with this nonsense. These reCAPTCHA with the images are a pain to get right.

**Comment by machsix** [comment]
Let's face the fact: `Google sucks!`. This reCAPTCHA completely makes me unable to sign in Cloudflare with a cookie blocker. I highly hesitate Google uses this reCAPTCHA  as a platform to accumulate data to train their Machine Learning tools.

**Comment by JixunMoe** [comment]
Possible alternative: [hCaptcha](https://www.hcaptcha.com/)

See Cloudflare's post: [Moving from reCAPTCHA to hCaptcha](https://blog.cloudflare.com/moving-from-recaptcha-to-hcaptcha/)

The captchas from this hCaptcha are usually more annoying than reCAPTCHA (2 pages). Is a bit sarcastic that you can abuse (human) spammers to get earn some money as well...

**Comment by ssokolow** [comment]
My experience was the opposite, but that's because reCAPTCHA really punishes you if you don't allow them to set cross-site tracking cookies.

**Comment by maple3142** [comment]
My experience:
If you don't heavily block tracking, then reCAPTCHA is better than hCaptcha. But if you block it, reCAPTCHA will be very annoying.

**Comment by ssokolow** [comment]
If they're equally good at keeping bots out, you could always do something comparable to what FurAffinity does and let the user choose whichever CAPTCHA is less inconvenient for them.

**Comment by Smoke-N-Mirrors** [comment]
I usually spend 3 times of boring recapture until it lets me pass. It's driving me mad. I don't wanna post scripts on GF any more until you change the way

**Comment by Smoke-N-Mirrors** [comment]
> Really?
> 
> Then maybe limit the number of manual updates a person can do. A small number like 5 manual updates a day, and a little more a week. After that annoy the hell out him, so he quits for the day.
> 
> And add trusted level. For those who have contributed scripts to the site for years, they should not have to deal with this nonsense. These reCAPTCHA with the images are a pain to get right.

yes, your example fits me. I don't wanna post scripts on GF any more until it changes the way

**Comment by ssokolow** [comment]
...and, apparently, now Google wants to start charging for reCAPTCHA.

https://www.zdnet.com/article/cloudflare-dumps-recaptcha-as-google-intends-to-charge-for-its-use/

**Comment by JasonBarnabe** [comment]
Greasy Fork uses Recaptcha to stop bots from posting spam. There have been cases where tens of thousands of spam scripts have been posted before a moderator came on to the site and noticed.

Initially, Recaptcha was only on account creation, but we found that mass spam was still happening - presumably a human created the account(s), then set a bot wild posting spam with it. So Recaptcha was added to script creation and script set creation.

(Greasy Fork had other anti-spam measures such as rate limiting, requiring email confirmation, text blocking, and other things, but Recaptcha has still been necessary.)

Per the discussion above, I've come to realize that Recaptcha sucks if you're blocking cookies. So what I've done is to exempt users who have a script that's over a month old. The thought is that it's unlikely for a spammer to create an account with a valid script, wait a month, then start spamming.

Users will still need to do Recaptcha to register, post their first script, and create/update scripts in that first month, but after that, they'll be in the clear.

I hope this satisfies everyone who complained about Recaptcha. If there are still issues, let me know.

**Comment by 07416** [comment]
Was reCAPTCHA semi-recently enabled for posting comments ('feedback'), even for established accounts and when the comment contains no URLs and is relatively short in length?

**Comment by JasonBarnabe** [comment]
There have been no changes recently.

**Comment by JasonBarnabe** [comment]
I've put in a change where if you've posted a discussion/comment more than a month ago, you're also exempt from recaptcha. Logic here is that if your comment lasted that long and hasn't been flagged as spam, you're probably a good gut.
