### ISSUE TITLE
Searching function is not perfect

### ISSUE THREAD

**Issue by machsix** [JasonBarnabe/greasyfork#563]
I'm the maintainer of script [Super_preloaderPlus_one_New](https://greasyfork.org/en/scripts/33522-super-preloaderplus-one-new). 

Sadly, I find my script will only appear in the list if I search with the complete name of the script `Super_preloaderPlus_one_New`. If I use keyword like `Super_preloaderPlus_one` or `Super_preloaderPlus_one New` , it won't appear.

I think this should be a easy fix. Thanks for the developers and moderators of greasefork. :)

**Comment by FranklinYu** [comment]
As a workaround, you can probably name your script “Super PreloaderPlus One new”
