### ISSUE TITLE
GitCDN rule

### ISSUE THREAD

**Issue by FlandreDaisuki** [JasonBarnabe/greasyfork#566]
The [GitCDN](https://www.gitcdn.xyz/) transform my script from
`https://raw.githubusercontent.com/FlandreDaisuki/zip_player/ecf3751317079fcabef70af4bd0e92411288303d/dist/zip_player.iife.min.js`
to
`https://www.gitcdn.xyz/repo/FlandreDaisuki/zip_player/ecf3751317079fcabef70af4bd0e92411288303d/dist/zip_player.iife.min.js`
by default.

The rule `^https:\/\/gitcdn\.(xyz|link)\/(cdn|repo)\/[^/]+\/[^/]+\/[0-9a-f]{40}/.*$` has no `www` in GreasyFork.

I think the rule can change to `^https:\/\/(www\.)?gitcdn\.(xyz|link)\/(cdn|repo)\/[^/]+\/[^/]+\/[0-9a-f]{40}/.*$`

**Comment by JasonBarnabe** [comment]
Done.
