### ISSUE TITLE
Userstyles/stylish/stylus conversion?

### ISSUE THREAD

**Issue by CollinChaffin** [JasonBarnabe/greasyfork#570]
Hi Jason!

If I remember correctly you also created the userstyles.org conversion of the stylish extended css to userscripts, or am I wrong?  I have two questions I am opening an issue here because it relates to Greasyfork to put in (unless it's there and I'm not seeing it or it's hidden) an enhancement request for GF to perform the same import of a stylish/stylus extended CSS style as a new GF userscript.  Also, beyond/separate from the enhancement request I would also ask if that conversion process could possibly be utilized separately as either a standalone webapp or utility?  I think both adding to GF natively as well as standalone would fill a huge gap as there is really not a current workflow to allow a style author (other than to rely on the behind-the-scenes conversion process limited currently to the userstyles.org site) to easily convert their style to a userscript.

Thanks!
-C

**Comment by JasonBarnabe** [comment]
Stylus has a new CSS format that is different than what was previously implemented, but perhaps easier to implement a converter for.

There is no plan to add a converter to Greasy Fork at this time, but keep in mind that you can set up a script to sync to an arbitrary URL.

**Comment by CollinChaffin** [comment]
Ok thanks not sure I follow regarding the script sync do you mean stylus css scripts or userscripts?  I currently and for many years use (and write) only userscripts, and have converted the old moz doc stylish CSS to userscript but have noticed this new stylus format CSS has use of variables and sometimes requires selections etc. and since userstyles.org currently not only hosts them but still converts them dynamically to offer their userscript counterpart, I didn't know if it was you responsible for updating that server-side conversion code.  Since the only others out there seem to not support this new extended css, that code that is working really needs to be made public to give the community a huge shot in the arm when those new styles can be forked as userscripts etc. and re-shared.
