### ISSUE TITLE
Redirect caching and alerting users

### ISSUE THREAD

**Issue by crazycaveman** [JasonBarnabe/greasyfork#582]
When attempting to use an old URL for a script that's been deleted and redirected to a new URL, the old URL doesn't seem to get the update at the same time as the new one. Using https://greasyfork.org/scripts/22059-wme-clicksaver (which was deleted and goes to [this location now](https://greasyfork.org/scripts/369629-wme-clicksaver/)), I see that the code took almost an hour to be updated vs going to the new page. Also, would it be possible for the pages of deleted and redirected scripts to have an alert on the page so users can easily tell where the new location is? Currently, the install button is just replaced with "This script has been deleted" and no indication that a new location is available.

In case you're curious, here's some header info showing the discrepancies:
```
$ curl -LI https://greasyfork.org/en/scripts/369629/code/WME%20ClickSaver.user.js
HTTP/2 200
server: nginx/1.14.0 (Ubuntu)
date: Tue, 29 Jan 2019 15:21:48 GMT
content-type: text/javascript
content-length: 52392
last-modified: Tue, 29 Jan 2019 15:18:25 GMT
etag: "5c506ec1-cca8"
access-control-allow-origin: *
strict-transport-security: max-age=31536000
accept-ranges: bytes

$ curl -LI https://greasyfork.org/scripts/369629-wme-clicksaver/code/WME%20ClickSaver.user.js
HTTP/2 200
server: nginx/1.14.0 (Ubuntu)
date: Tue, 29 Jan 2019 15:21:16 GMT
content-type: text/javascript
content-length: 52392
last-modified: Tue, 29 Jan 2019 14:25:12 GMT
etag: "5c506248-cca8"
access-control-allow-origin: *
strict-transport-security: max-age=31536000
accept-ranges: bytes
```

Just after the update was pushed at the new link:
```
$ curl -Li https://greasyfork.org/scripts/22059-wme-clicksaver/code/WME%20ClickSaver.user.js | grep '@version'
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   136    0   136    0     0    433      0 --:--:-- --:--:-- --:--:--   433
100 51944  100 51944    0     0  99319      0 --:--:-- --:--:-- --:--:-- 99319
// @version         2019.01.25.002

$ curl -L https://greasyfork.org/scripts/369629-wme-clicksaver/code/WME%20ClickSaver.user.js | grep '@version'
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 52392  100 52392    0     0   116k      0 --:--:-- --:--:-- --:--:--  116k
// @version         2019.01.29.001
```

**Comment by JasonBarnabe** [comment]
The URL used by https://greasyfork.org/en/scripts/369629-wme-clicksaver for installation is `https://greasyfork.org/scripts/369629-wme-clicksaver/code/WME%20ClickSaver.user.js`. The URL used by the deletion/replacement is `https://greasyfork.org/en/scripts/369629/code/WME ClickSaver.user.js`. These are different, but specifically, including the /en/ portion is making it so its cache is not purged on update.

This should be fixed now.
