### ISSUE TITLE
Script author not changing on account page after username change

### ISSUE THREAD

**Issue by SimonHertoge** [JasonBarnabe/greasyfork#586]
On an account page (https://greasyfork.org/en/users/<userid\>), "author" shows the original username instead of the new one, unlike on a script info page (https://greasyfork.org/en/scripts/<scriptid\>), which shows the same info.

**Comment by JasonBarnabe** [comment]
Could be caching. Where do you see the problem?

**Comment by SimonHertoge** [comment]
On my personal page:
https://greasyfork.org/en/users/20473-shertoge

Maybe it is caching, I only just changed it.

**Comment by JasonBarnabe** [comment]
It's all good now, so it is caching, but this cache should be cleared when the username gets updated.
