### ISSUE TITLE
Broken SSL when loading via https

### ISSUE THREAD

**Issue by MANICX100** [JasonBarnabe/greasyfork#589]
If you try to load greasy fork via:
[https://www.greasyfork.org/en]
A certificate error is thrown. This also breaks oauth logins.

You have to browse to
[http://www.greasyfork.org/en] (http not https)
This then successfully redirects to the functional http version.

**Comment by JixunMoe** [comment]
SSL seems ok for me - can you share some more details?

e.g. What certificate did your browser receive?

![image](https://user-images.githubusercontent.com/5713045/52753633-5a4a0380-2fef-11e9-87d5-a208ce6f0416.png)![image](https://user-images.githubusercontent.com/5713045/52753667-7e0d4980-2fef-11e9-9ac8-1fde63d8ddb0.png)

**Comment by MANICX100** [comment]
Hi, You have to browse specifically to **https://www.**greasyfork.org/
E.g. This is where users are sent from google search - for the issue to appear.
![greasy-fork-cert 3](https://user-images.githubusercontent.com/5303241/52785039-e9d2cf00-304e-11e9-92f9-dbbcf2ac5cd2.png)
![greasy-fork-cert 1](https://user-images.githubusercontent.com/5303241/52785041-e9d2cf00-304e-11e9-848c-66fc8b98dc6d.png)
![greasy-fork-cert 2](https://user-images.githubusercontent.com/5303241/52785042-e9d2cf00-304e-11e9-94dd-721e7c0c258e.png)

http://www.greasyfork.org/en
OR
https://greasyfork.org/

Both work correctly

**Comment by FranklinYu** [comment]
Because `www.greasyfork.org` is not on the certificate. If I understand correctly, currently Jason is using a certificate from GlobalSign, which costs $250 per year. One more domain means $100 per year, so it adds up to $350. I doubt the necessity of that.

Or maybe Jason can switch to cheaper alternatives like Comodo ($150 for 4 domains). GreasyFork isn't a bank, after all.

**Comment by JasonBarnabe** [comment]
I do not use the www subdomain anywhere. I don't know why Google is using that for some links.

I am contacting GlobalSign to see if they can help. I may just purchase a new certificate. They're not as expensive as @FranklinYu describes.

**Comment by JasonBarnabe** [comment]
I've added a redirect and explicitly set the host to greasyfork.org so maybe that will make Google stop using www. Of course anyone who still tries to access https://www.greasyfork.org directly will still get a cert error...

**Comment by JasonBarnabe** [comment]
Google is now using the correct domain.

The certificate I have cannot be reissued to have www supported.

**Comment by tobbexiv** [comment]
Is there a possibility for you to get Let's Encrypt certificates? There it should be possible to get certificates for all domains and the cost is up to what you want to donate.

https://letsencrypt.org/

**Comment by JasonBarnabe** [comment]
Yes, that's possible. The cost there is time to set up/possibility that I'll screw it up.

**Comment by FranklinYu** [comment]
> This also breaks oauth logins.

I think this is weird. OAuth shouldn’t redirect user back to the www subdomain. Maybe there is a bug in configuration.

**Comment by JasonBarnabe** [comment]
Now using Let's Encrypt so the www subdomain should no longer have issues.
