### ISSUE TITLE
additional info don't sync with webhook

### ISSUE THREAD

**Issue by indefined** [JasonBarnabe/greasyfork#591]
- [x] [script](https://greasyfork.org/scripts/378513) set code sync to [CODE](https://github.com/indefined/UserScripts/raw/master/bilibiliCCHelper/bilibiliCCHelper.js) and additional info to [README](https://github.com/indefined/UserScripts/raw/master/bilibiliCCHelper/README.md)
- [x] webhook works fine in my other script which set synced to the same repo 
- [x] code synced fine in this script
- [ ] additional info didn't sync in this script with webhook, even it was change
  - [x] additional info preview works fine in the script setting page
  - [x] additional info manually synced fine
  - [ ] had try delete and resetting/change the additional sync path but fail

<details>
<summary>webhook deliver and response data sample in github</summary>
<pre>
<code>
<b>Request</b>
Headers
Request URL: https://greasyfork.org/zh-CN/users/187614-indefined/webhook
Request method: POST
content-type: application/json
Expect: 
User-Agent: GitHub-Hookshot/1174c8d
X-GitHub-Delivery: e4e127ae-3dae-11e9-9731-8b8f20719669
X-GitHub-Event: push
X-Hub-Signature: sha1=17a6dac60a993804926e53e8ae45f7db76df8eaaPayload
{
  "ref": "refs/heads/master",
  "before": "31d6612709f857983f7116c4d4d6a11828d663eb",
  "after": "f5934f1a78c2c2112aef373ffde84f1d7c61a2a3",
  "created": false,
  "deleted": false,
  "forced": false,
  "base_ref": null,
  "compare": "https://github.com/indefined/UserScripts/compare/31d6612709f8...f5934f1a78c2",
  "commits": [
    {
      "id": "f5934f1a78c2c2112aef373ffde84f1d7c61a2a3",
      "tree_id": "707b8e90322fdc5f0ae467ca8807635a8f72e240",
      "distinct": true,
      "message": "test",
      "timestamp": "2019-03-03T20:21:23+08:00",
      "url": "https://github.com/indefined/UserScripts/commit/f5934f1a78c2c2112aef373ffde84f1d7c61a2a3",
      "author": {
        "name": "indefined",
        "email": "...",
        "username": "indefined"
      },
      "committer": {
        "name": "indefined",
        "email": "...",
        "username": "indefined"
      },
      "added": [

      ],
      "removed": [

      ],
      "modified": [
        "bilibiliCCHelper/README.md",
        "bilibiliCCHelper/bilibiliCCHelper.js"
      ]
    }
  ],...
}
<b>Response</b>
Headers
Access-Control-Allow-Origin: *
Cache-Control: max-age=0, private, must-revalidate
Connection: keep-alive
Content-Length: 135
Content-Type: application/json; charset=utf-8
Date: Sun, 03 Mar 2019 12:21:39 GMT
Referrer-Policy: strict-origin-when-cross-origin
Server: nginx/1.14.0 + Phusion Passenger 6.0.1
Status: 200 OK
Strict-Transport-Security: max-age=31536000
Transfer-Encoding: chunked
X-Content-Type-Options: nosniff
X-Download-Options: noopen
X-Frame-Options: SAMEORIGIN
X-Permitted-Cross-Domain-Policies: none
X-Powered-By: Phusion Passenger 6.0.2
X-Request-Id: a8ffb2ca-7f11-4113-a031-f51739ea40d7
X-Runtime: 0.557191
X-XSS-Protection: 1; mode=block
Body
{"updated_scripts":["https://greasyfork.org/zh-CN/scripts/378513-bilibili-cc%E5%AD%97%E5%B9%95%E5%8A%A9%E6%89%8B"],"updated_failed":[]}
</code>
</pre>
</details>

**Comment by indefined** [comment]
it happen on [my new script](https://greasyfork.org/scripts/382065) ,too.
script sync fine but additional info could only sync by manually
seems the two script had same action
1. i import the script from github
2. go to the script Admin page and set the` Default additional info ` link
3. press `Update` button and the script page show `(Awaiting sync)`
4. press `Update and sync now` button , the additional info synced fine and info page show the correct info
5. after that the additional info can only sync by click  `Update and sync now` button

**Comment by Brandon-Beck** [comment]
Also have this issue. Can confirm

**Comment by JasonBarnabe** [comment]
I found an oversight from when I allowed scripts to have multiple authors. Anything made after that would likely not have worked for syncing additional info.

It's corrected now, let me know if you still see problems.

**Comment by indefined** [comment]
it seems work fine now

**Comment by aminomancer** [comment]
it's not working for me, even hitting "udpate and sync now" does nothing. the additional info section always says "(Awaiting sync)"
