### ISSUE TITLE
Can't change username

### ISSUE THREAD

**Issue by moham96** [JasonBarnabe/greasyfork#592]
Hi,
I wanted to change my email and username in greasyfork main site and the forums.
I was able to change the email and username in the main account 
https://greasyfork.org/en/users/edit
but this doesn't change the forum email and username, so I went to the account settings in the forum
https://greasyfork.org/en/forum/profile/edit?locale=en
but the username field is grayed out(I can't change it) while the email field is not but even if I change the email alone I can't save the settings and I get this error

    Usernames must be 3-20 characters and consist of letters, numbers, and underscores.

Regards

**Comment by JasonBarnabe** [comment]
Your name on the forum is only updated on login, so log out and log back in and it should be changed.

**Comment by moham96** [comment]
@JasonBarnabe Thanks, it worked, would be nice to have a notice about this when you change the username.
