### ISSUE TITLE
无法下载脚本是怎么回事？

### ISSUE THREAD

**Issue by leeenight** [JasonBarnabe/greasyfork#596]
已经下载了Tampermonkey，下载脚本后跳出网页内容显示：无法访问此网站 网址为 https://greasyfork.org/scripts/370005-一键vip视频解析-去广告-全网-一站式音乐搜索下载-2019-03-22-更新-报错请及时反馈/code/一键VIP视频解析、去广告（全网）,一站式音乐搜索下载%202019-03-22%20更新，报错请及时反馈.user.js 的网页可能暂时无法连接，或者它已永久性地移动到了新网址。

**Comment by derjanb** [comment]
See also Tampermonkey/tampermonkey#667

**Comment by JasonBarnabe** [comment]
Sounds like this is not a Greasy Fork issue and is fixed now anyway.
