### ISSUE TITLE
L18n: Japanese localization of the "New Discussion" page isn't updated

### ISSUE THREAD

**Issue by Phroneris** [JasonBarnabe/greasyfork#600]
Maybe localization of the "New Discussion" page is based on the one managed by Vanilla forums system?

When I use Greasy Fork in Japanese and try to create a new discussion, I see a button to post it saying `ポストディスカッション` ("Post Discussion") at the bottom of the page.
This translation is **incorrect** (should be `ディスカッションを投稿`) and it has been already fixed. -> https://github.com/vanilla/locales/commit/6a7eec127c78ed1cc0009b06ac4bed2ae27a2dfd#diff-826d217af7602d9a6ef619bb275264c3
Please merge it to update.

**Comment by JasonBarnabe** [comment]
I've pulled in fresh locales from Vanilla. Does it look good?

**Comment by Phroneris** [comment]
Looks great. Thank you!
