### ISSUE TITLE
Add version check for Violentmonkey

### ISSUE THREAD

**Issue by maple3142** [JasonBarnabe/greasyfork#602]
Violentmonkey has its own [vm-detector](https://github.com/violentmonkey/vm-detector)  to check version, but I think it would be good if Greasy Fork can integrate it into the site. Just like Tampermonkey.

**Comment by JasonBarnabe** [comment]
@gera2ld I'd like to build this in. Is it exactly the same as the Tampermonkey version? So simply checking for `window.external.Violentmonkey` [here](https://github.com/JasonBarnabe/greasyfork/blob/master/app/assets/javascripts/versioncheck.js#L3-L17) would be enough?

**Comment by gera2ld** [comment]
@JasonBarnabe `isInstalled` is implemented slightly differently now.

```js
external.Violentmonkey.isInstalled(name, namespace)
.then(versionOrNull => { console.log(versionOrNull); })
```

Anyway I can make it compatible in the next version so that you could simple check it with a different name.

**Comment by JasonBarnabe** [comment]
@gera2ld With Violentmonkey in both Chrome and Firefox, when I go to greasyfork.org and open up the console, window.external.Violentmonkey is undefined. Am I missing something?

**Comment by gera2ld** [comment]
@JasonBarnabe In recent versions we did some optimization to avoid unnecessary script injection. As a result, `external.Violentmonkey` is not exposed when there is nothing to inject.
I think this is a bug. For now you can add an empty script to bypass the optimization.

**Comment by tophf** [comment]
I wonder what GF will do if some weird user has both Tampermonkey and Violentmonkey...

**Comment by JasonBarnabe** [comment]
I've built this in.

@gera2ld No need to change the function, it works as is.

@tophf The implementation will check for Tampermonkey first.
