### ISSUE TITLE
Script Icon in listing to show if it supports GM4 or GM3 API

### ISSUE THREAD

**Issue by TimidScript** [JasonBarnabe/greasyfork#603]
A lot of scripts do not work on GM4. Allow users to mark what browser addon they support. Extract the information from the metadata if present. 

Present icons to show what API they support.

https://github.com/greasemonkey/greasemonkey/issues/3031

**Comment by JasonBarnabe** [comment]
I would prefer to encourage maximum compatibility between script managers. Let's say we assume that nearly all Greasemonkey users are on GM4.

- Is there a way to detect whether a script was written for GM4 (by the presence or absence of certain metadata, for example)?
- Do the changes in GM4 bring it closer to other managers like Tampermonkey?

**Comment by JasonBarnabe** [comment]
This isn't going to happen. Any compatibility info can be provided with `@compatible` and `@incompatible` - https://greasyfork.org/en/help/meta-keys#meta-compatible.
