### ISSUE TITLE
2MB limit

### ISSUE THREAD

**Issue by qsniyg** [JasonBarnabe/greasyfork#608]
I've just hit the 2MB limit for my userscript ( https://greasyfork.org/en/scripts/36662-image-max-url ), because it now contains ~2400 rules. Can the limit be relaxed per-userscript (and if so, where would one apply for this?), or is it fixed for all scripts?

**Comment by JixunMoe** [comment]
I think as a workaround (or separate data from code), you can embed the rules to a file and include it via [`@resource`](https://wiki.greasespot.net/Metadata_Block#.40resource).
Or have it hosted somewhere and keep updating the rules.

**Comment by JasonBarnabe** [comment]
There is no exemption from the limit. I would also suggest having the rules in a separate (JSON?) `@resource`.
