### ISSUE TITLE
Spammer list (csv)

### ISSUE THREAD

**Issue by JixunMoe** [JasonBarnabe/greasyfork#610]
https://gist.github.com/JixunMoe/4a044b32905aad23f778512ba66d2ee2

CSV Headers: `User ID, User Name, Keywords`

**Comment by JixunMoe** [comment]
[out.csv.tar.gz](https://github.com/JasonBarnabe/greasyfork/files/3164328/out.csv.tar.gz)

**Comment by JixunMoe** [comment]
Keywords used to search

```
  const kwds = ['SN888C'];
  // const kwds = ['V芯', '微信', '薇芯'];
  // const kwds = ['电、微', '电/微'];
  // const kwds = ['V信', '首页', '【薇', '電同微'];
  // const kwds = ['芯片', '银行', '价格', '多少钱', '毕业', '医院', '学位', '.微.'];
  // const kwds = ['发票', '短信', '群发', '出售', '购买'];
```

**Comment by JixunMoe** [comment]
Suggestion:

Restrict the number of Chinese characters one can use as user name, and I believe `7` covers most "normal" user names.

**Comment by JasonBarnabe** [comment]
So these are all user profile page spammers? Is your list of keywords a good blocklist for user names?

**Comment by JixunMoe** [comment]
> So these are all user profile page spammers?

I believe there are more, the keywords aren't complete. I suggest search in the database for those names contains more than 7 Chinese characters to see if any spammers left over. Not sure how to implement this in MySQL query though...

> Is your list of keywords a good blocklist for user names?

Those are the words rarely used (if at all) for a normal user name.

**Comment by JixunMoe** [comment]
Keywords translated to English:

```
Platform (平台)
Web URL (网址/地址)
Tax (税务)
To register (注册)
Where to get or buy (哪里有/哪里可/哪里卖/哪里能/可以开/可以买)
WeChat (徴呺/V芯/微信/薇芯/V信/【薇/.微.)
Phone number or WeChat ("电/微"/电、微/電同微)
Must read Instructions (必看介绍)
Credit Card IC Chip (for card clone?) (芯片/银行)
Price/How Much (价格/多少钱)
[fake] Graduation certs (毕业/学位)
Hospital (医院) * see https://github.com/open-power-workgroup/Hospital/blob/master/README_en.md
[fake] invoice (for tax invasion) (发票)
Send spam text messages (短信/群发)
To sell (出售/购买)
```

**Comment by JasonBarnabe** [comment]
Cleared out the users. I have yet to add any sort of blocking.

**Comment by JixunMoe** [comment]
It has started again,

("invoice") https://greasyfork.org/users?utf8=%E2%9C%93&q=%E5%8F%91%E7%A5%A8
("instruction") https://greasyfork.org/zh-TW/users?utf8=%E2%9C%93&q=%E4%BB%8B%E7%BB%8D
("where", except the earliest 3 seems to be a normal user name) https://greasyfork.org/zh-TW/users?page=1&q=%E5%93%AA%E9%87%8C&utf8=%E2%9C%93

**Comment by JasonBarnabe** [comment]
Deleted, but those didn't appear to be new accounts.

**Comment by JasonBarnabe** [comment]
I've added the ability to block users in the same way as scripts based on their attributes, and I've added blocks based on your suggestions. Let me know if you notice anything else that should be blocked.
