### ISSUE TITLE
Unknown column when editing a comment

### ISSUE THREAD

**Issue by joeytwiddle** [JasonBarnabe/greasyfork#615]
I just edited a comment, and when I submitted I saw the error message:

    Unknown column 'Active' in 'field list'

This appeared in the bottom-left, in `InformMessages`.

The UI is acting as if the comment failed to update (it's keeping the comment in edit mode), but actually if I reload I can see it did update!

**Comment by decembre** [comment]
same pb for me...

**Comment by JasonBarnabe** [comment]
Just upgraded the forum, doesn't seem to happen any more. Can you confirm?

**Comment by joeytwiddle** [comment]
Thanks. Cannot reproduce today! Closing.
