### ISSUE TITLE
Not recieving confirmation email to gmail account

### ISSUE THREAD

**Issue by almercier** [JasonBarnabe/greasyfork#617]
I've verified that the email I specified is correct, verified that I am receiving other emails on the account, checked the spam folders, and have attempted to resend the email multiple times but I have still not received the email after 24 hours. Is there any known issues with emailing from the site? This is blocking me from being able to post my scripts.

**Comment by JasonBarnabe** [comment]
You you send your email to jason.barnabe@gmail.com? I will check.

**Comment by JasonBarnabe** [comment]
```
Jun 17 13:08:13 greasyfork sm-mta[31207]: x5HD8DSg031207: from=<noreply@greasyfork.org>, size=542, class=0, nrcpts=1, msgid=<5d0790bddf364_147e2b2913e63ea01424a@greasyfork.mail>, proto=ESMTP, daemon=MTA-v4, relay=localhost [127.0.0.1]
Jun 17 13:08:14 greasyfork sm-mta[31210]: STARTTLS=client, relay=gmail-smtp-in.l.google.com., version=TLSv1.3, verify=FAIL, cipher=TLS_AES_256_GCM_SHA384, bits=256/256
Jun 17 13:08:14 greasyfork sm-mta[31210]: x5HD8DSg031207: to=<example@gmail.com>, delay=00:00:01, xdelay=00:00:01, mailer=esmtp, pri=120542, relay=gmail-smtp-in.l.google.com. [IPv6:2607:f8b0:400e:c08:0:0:0:1b], dsn=2.0.0, stat=Sent (OK  1560776894 b8si10551393pff.119 - gsmtp)
```

**Comment by almercier** [comment]
Aha so it actually was classified as spam, but the gmail's spam folder on iphone's mail client doesn't match the spam folder on the gmail website. 

Regardless I got the email and confirmed, thanks!
