### ISSUE TITLE
[Request] Add https://bundle.run

### ISSUE THREAD

**Issue by chocolateboy** [JasonBarnabe/greasyfork#618]
This is a [web service](https://bundle.run) which translates CommonJS modules to UMD bundles using Rollup + Browserify. The packages are from NPM, so using it with version numbers should always return the same response.

For convenience, it would be nice to use the option to rename the exported global e.g. https://bundle.run/left-pad@1.3.0?name=padLeft, but each new name has to be processed on the server and takes time, so it might be kinder not to allow that.

Also, responses to named tags (e.g. https://bundle.run/left-pad@latest) are not immutable, so they should probably be disallowed for [security reasons](https://github.com/JasonBarnabe/greasyfork/issues/494) (assuming they're disallowed for [unpkg.com](https://github.com/JasonBarnabe/greasyfork/issues/511)).

- Cc:  @Rich-Harris @xtuc
- Repo: https://github.com/Rich-Harris/packd
- Discussion: https://observablehq.com/@observablehq/how-to-require-stubborn-modules

**Comment by JasonBarnabe** [comment]
Added.
