### ISSUE TITLE
无法发布脚本！提示不完整！！！

### ISSUE THREAD

**Issue by FirstGitHubID** [JasonBarnabe/greasyfork#623]
请问为什么无法提交脚本、而且提示信息很不完整！？

reCAPTCHA verification failed, please try again.

就这一句到底是哪里有问题倒是提示一下啊！！！

**Comment by maple3142** [comment]
你沒有通過Google的reCAPTCHA測試，

**Comment by maple3142** [comment]
它不是很清楚的說了你沒有通過Google的reCAPTCHA測試，可能是因為連不上Google伺服器的原因，最好考慮翻牆

**Comment by FirstGitHubID** [comment]
谢谢评论、但就是因为用了VPN、全局模式PAC模式都不行所以才提问、最主要的是提示很不完整、相似的脚本一个能提交一个不能提交、很是诡异

**Comment by FirstGitHubID** [comment]
> 它不是很清楚的說了你沒有通過Google的reCAPTCHA測試，可能是因為連不上Google伺服器的原因，最好考慮翻牆

**Comment by JixunMoe** [comment]
@JasonBarnabe Add this text to transifex?

**Comment by JasonBarnabe** [comment]
We're supposed to be using recaptcha.net which is supposed to work in China. I've updated the recaptcha gem so maybe that helps.

I've filed https://github.com/ambethia/recaptcha/issues/326 for translating the message. The support is there, it's just the translations are not included.

**Comment by JasonBarnabe** [comment]
If anyone wants to contribute, you can create translations at https://github.com/ambethia/recaptcha/tree/master/rails/locales
