### ISSUE TITLE
script can`t auto sync

### ISSUE THREAD

**Issue by yukinotech** [JasonBarnabe/greasyfork#624]
Script sync failed - Does not appear to be a user script..

this is my script url,and I set this url to be the url for auto sync.
https://github.com/yukinotech/WeiboDL/blob/master/weiboDL%E5%BC%82%E6%AD%A5%E5%A2%9E%E5%BC%BA%E7%89%88.js

this is my script page in greasyfork
https://greasyfork.org/zh-CN/scripts/369485-weibodl-%E5%BC%82%E6%AD%A5%E5%A2%9E%E5%BC%BA%E7%89%88

however，I can parse my code ,and update my script by hand. And it work successfully.

why my script is not appear to be a user script?

**Comment by maple3142** [comment]
I think you have to use the "raw" link instead.

**Comment by yukinotech** [comment]
> I think you have to use the "raw" link instead.

谢谢回复。
原生链接具体指啥意思啊？看到是台湾的朋友我就打中文了

**Comment by maple3142** [comment]
@yukinotech ![](https://i.imgur.com/HPcYZty.png)

**Comment by yukinotech** [comment]
> @yukinotech ![](https://camo.githubusercontent.com/d38e2fe33329cdeb5af73231ed759a896d60a759/68747470733a2f2f692e696d6775722e636f6d2f485063595a74792e706e67)

非常感谢。就是有些奇怪，因为以前用老地址是能自动更新的，所以没能注意到是这个问题。
