### ISSUE TITLE
error message when logging in

### ISSUE THREAD

**Issue by drhouse** [JasonBarnabe/greasyfork#629]
> We're sorry, but something went wrong.
> If you are the application owner check the logs for more information.
https://greasyfork.org/en/users/sign_in

Above is the error message I get when I try to log in. 
My username is: drhouse 
https://greasyfork.org/en/users/10118-drhouse

I've used the site for several years and written several scripts. The only thing I can remember being different is having recently reported a script for duplicating a script I contributed. Hope this can be resolved sometime soon.

**Comment by JasonBarnabe** [comment]
This should be fixed now. I put in a notice for when you have scripts with
syntax errors - this notice had an error when you have more than one.
