### ISSUE TITLE
Is browserify allowed?

### ISSUE THREAD

**Issue by thorio** [JasonBarnabe/greasyfork#633]
I found [this discussion](https://greasyfork.org/en/forum/discussion/488/strangely-formatted-very-long-lines), but it wasn't conclusive.
I'm testing out a new workflow and would like to know if [browserify](http://browserify.org/) is okay to use, since it does introduce some minified code.
See [this script](https://greasyfork.org/en/scripts/391642-test/code) for a simple example.

Solution: fish the unminified prelude out of your node_modules and pass it to your browserify constructor:
```js
const fs = require("fs"),
	browserify = require("browserify");

var preludePath = require.resolve("browser-pack").replace("index.js", "prelude.js");
var prelude = fs.readFileSync(preludePath).toString();

browserify({ entries: "file"] }, { prelude: prelude })
```

**Comment by maple3142** [comment]
I think it is possible to replace `require` or `import` call to use external dependencies (`using @require`) in some build tools such as Rollup.
Using that could easily avoid that grey area.
Example: https://greasyfork.org/en/scripts/20423-patchouli/code

**Comment by thorio** [comment]
I'm not trying to require external dependencies, I want to bundle multiple files into one userscript.
Right now I am just concatenating the files. I want a more solid solution, and browserify seems like a good one.

**Comment by maple3142** [comment]
The rule states `Code posted to this site must not be obfuscated or minified.`, so it is okay if your output is not obfuscated. But I am not sure whether Browserify output obfuscated scripts by default.

**Comment by thorio** [comment]
When i run my code through browserify, my code is kept as it is. Browserify adds a wrapper of sorts around it, and it's the wrapper that's minified. See [here](https://greasyfork.org/en/scripts/391642-test/code): there are some lines with minified code by browserify, and my modules are sitting inbetween, not minified.

**Comment by JasonBarnabe** [comment]
The "wrapper" that browserify adds is the first line after the header, and the rest of the code is yours (unminified)?

**Comment by eight04** [comment]
Here is the source code of the module wrapper:
https://unpkg.com/browse/browser-pack@6.1.0/_prelude.js
Which is uglified from:
https://unpkg.com/browse/browser-pack@6.1.0/prelude.js
I'm not sure if there is an option to use the beautified version of the wrapper in browserify though.

BTW, if you like to use a cleaner solution, try [rollup](https://github.com/rollup/rollup). [Linkify Plus Plus](https://github.com/eight04/linkify-plus-plus) also uses rollup to build the userscript and the extension.

**Comment by thorio** [comment]
Now knowing it's called prelude, I was able to find an [option in browser-pack](https://github.com/browserify/browser-pack#packopts) to substitute prelude with the unminified version.
