### ISSUE TITLE
Script sync failed - Exception 403006.

### ISSUE THREAD

**Issue by lelinhtinh** [JasonBarnabe/greasyfork#634]
https://greasyfork.org/vi/scripts/369802-manga-comic-downloader

My script has not been updated since version 1.12.7.
I have read #560, understanding that the script was blocked for source code obfuscation. But it is not.

I think the reason is this code: [manga_comic_downloader.user.js#L963-L965](https://github.com/lelinhtinh/Userscript/blob/master/manga_comic_downloader/manga_comic_downloader.user.js#L963-L965)
These variables are immutable _(`_0xc320`, `_0x5f54`, `_0x5213`, `_0x52f5`)_, as they are used to deobfuscate.
See how it works at: https://jsfiddle.net/baivong/4a3wbuys/embedded/js,html,css,result/

**Comment by JasonBarnabe** [comment]
You are correct that it's blocked for obfuscation. But I don't see how your script is not obfuscated. If you have something to deobfuscate then that means part of it is obfuscated...?

**Comment by lelinhtinh** [comment]
Have you seen my source code? [manga_comic_downloader.user.js](https://github.com/lelinhtinh/Userscript/blob/master/manga_comic_downloader/manga_comic_downloader.user.js).
Compare changes between [v1.12.7 and v1.13.0](https://github.com/lelinhtinh/Userscript/compare/d257cbf..f9b2213).
Source Syncing settings of [369802-manga-comic-downloader](https://greasyfork.org/en/scripts/369802-manga-comic-downloader).

![image](https://user-images.githubusercontent.com/5460915/67921920-d6b35f80-fbdb-11e9-9554-31c576d8a993.png)

Where is obfuscated code? Your algorithm for detecting obfuscation is wrong.

**Comment by lelinhtinh** [comment]
Passed obfuscation detection by [separating variable name](https://github.com/lelinhtinh/Userscript/commit/8ad5a5a34accea93b95882ed5169bc6d42674469).

**Comment by JixunMoe** [comment]
> You are correct that it's blocked for obfuscation. But I don't see how your script is not obfuscated. If you have something to deobfuscate then that means part of it is obfuscated...?

I think is just how we implemented the filter.
