### ISSUE TITLE
"Name has already been taken" error when updating specific libraries

### ISSUE THREAD

**Issue by darkred** [JasonBarnabe/greasyfork#635]
*(Continuing this GF forum topic: [Can't update library script - Name already taken error](https://greasyfork.org/forum/discussion/61879/cant-update-library-script-name-already-taken-error))*

I'm getting a "Name has already been taken"`" error when updating the following 3 libraries:
*(all 5 others update ok)*

- [TableSorter](https://greasyfork.org/en/scripts/5844-tablesorter)
- [GM_config](https://greasyfork.org/en/scripts/28536-gm-config)
- [jScroll](https://greasyfork.org/en/scripts/11636-jscroll)

I have set them both in their 'Admin' tab to be synced `Automatically - it will be periodically checked for updates` and their `This script's code is set up to sync from` textboxes point to:

> `https://raw.githubusercontent.com/Mottie/tablesorter/master/js/jquery.tablesorter.js`
> `https://raw.githubusercontent.com/sizzlemctwizzle/GM_config/master/gm_config.js`
> `https://raw.githubusercontent.com/pklauzinski/jscroll/master/jquery.jscroll.js`

respectively.

&nbsp;

I'm also getting the same "Name has already been taken" error when trying to modify anything in their 'Info' tab (via the 'Update' tab).

---

(post by @JasonBarnabe in [the GF topic](https://greasyfork.org/forum/discussion/comment/76071/#Comment_76071))
> Note that when you post libraries, the UserScript meta block is not required. So maybe it's just getting confused by that.

There's no userscript meta block to remove in any of these libraries.

**Comment by JasonBarnabe** [comment]
There are legitimately other libraries with those names. In the case of TableSorter you are the first, so I'll rename the other one so you get the name.

They were all added before this restriction was put in in https://github.com/JasonBarnabe/greasyfork/commit/3d822b17476961275e43206e5efab0d1455bb3bb#diff-9cacd63540753d6929377d6cb58210cb

**Comment by darkred** [comment]
> In the case of TableSorter you are the first, so I'll rename the other one so you get the name.

Any update on this, @JasonBarnabe ? I'm still getting the error for TableSorter .

**Comment by JasonBarnabe** [comment]
I didn't do the update properly. It should be fine now.

**Comment by darkred** [comment]
Yes, it works ok now. Thank you

**Comment by darkred** [comment]
Hi @JasonBarnabe 
Could you please check my library [arrive.js](https://greasyfork.org/en/scripts/21927-arrive-js)? I'm getting the `Name has already been taken` error when trying to update.

I noticed that there's another library, [arrive-upload](https://greasyfork.org/en/scripts/20860-arrive-upload), which was uploaded earlier than mine (Aug 2, 2016 vs Jun 24, 2016) but its name is not the original one (arrive.js vs arrive-upload), plus that one is minified while mine is not.

**Comment by JasonBarnabe** [comment]
There is another one at https://greasyfork.org/en/scripts/14637-arrive-js which has been deleted by the author, but they still get to "keep" the name.

**Comment by darkred** [comment]
But, in this case there will be no updated version in greasyfork: latest version 2.5.1 of arrive.js  was released today, and the other posted library [arrive-upload](https://greasyfork.org/en/scripts/20860-arrive-upload) is dated 2016 (never updated).
And, I'm using arrive.js in 5 of my scripts. If want to use the latest version I have to use a CDN, in this case https://cdnjs.com/libraries/arrive ?

**Comment by JasonBarnabe** [comment]
You can still post it, you just can't call it exactly "arrive.js". Call it "arrive.js 2.5.1" or "arrive.js library" or "arrive.js (~~Taylor's~~ darkred's version)" or whatever.
