### ISSUE TITLE
Name already taken

### ISSUE THREAD

**Issue by brazenvoid** [JasonBarnabe/greasyfork#637]
I have this issue for some time now which forces me to always rename my base script upon update. Is this default behavior now? It started with the uniqueness validation.

What I do is to add the version in the name to circumvent "Name Already Taken" error. Considering its my own script with blatant username in the name itself, does version not catered for libraries?

Without it or with previous version suffixed, it always ends up in error, as if version is just cosmetic sugar.

Library: https://greasyfork.org/en/scripts/375557-brazenvoid-s-base-resource-v1-6-3

**Comment by JasonBarnabe** [comment]
This is the other script with the matching name - https://greasyfork.org/en/scripts/380690-brazenvoid-s-base-resource

**Comment by brazenvoid** [comment]
That's mine too... The one I had to abandon or it got abandoned as I started doing the suffix thing and renamed the script name, due to the same problem...

**Comment by brazenvoid** [comment]
Now there are two problems:
1. Specific to me is that someone posted an older version of my script with the same name when the uniqueness filter was not in existence. When it did got added, me, the original author lost their right to update the script.

2. The uniqueness filter does not cater updates to the same script from the author account. Meaning my X script update will always fail unless I always rename my script to something unique.

**Comment by JasonBarnabe** [comment]
Note that when you update a library, it has a separate field for the name. It may be getting confused if you are including`@name` in your code.

I've tried it in a dev environment, and I had no problems doing the update.

**Comment by brazenvoid** [comment]
Omitting @name from info block works. The usual scripts do not exhibit this issue. Is the validation filter only for libraries? 

Also I hope you understand that logic getting confused is an error state not an excusable design limitation.

**Comment by JasonBarnabe** [comment]
This validation is only for libraries.

It's not expected that libraries use `@name` in a library. It should be ignored, but it's not currently.

**Comment by brazenvoid** [comment]
Should I keep this open?

**Comment by JasonBarnabe** [comment]
Should be fixed now.
