### ISSUE TITLE
某些翻译不符合中国人的语言习惯

### ISSUE THREAD

**Issue by xiaopangju** [JasonBarnabe/greasyfork#643]
在https://greasyfork.org/zh-CN/forum/profile/discussions/冰川橘子   页面的已加入 10:07AM应该改为加入于10:07AM

**Comment by JixunMoe** [comment]
论坛的翻译报告请向 Vanilla 项目提交。

* Vanilla 官方关于翻译贡献的说明：https://github.com/vanilla/locales/blob/master/README.md#contributing
* Transifex 链接：https://www.transifex.com/vanilla/vanilla/
