### ISSUE TITLE
Error occured when update or add new script

### ISSUE THREAD

**Issue by noe132** [JasonBarnabe/greasyfork#648]
whenever update or add new scripte, after click upload button, the page redirects to this error page

![](https://user-images.githubusercontent.com/2271900/73586500-2b22ef80-44e9-11ea-8919-166d146ee17b.jpg)
```
We're sorry, but something went wrong.
If you are the application owner check the logs for more information.
```

**Comment by JasonBarnabe** [comment]
Can you look at the JS console to see what HTTP code is returned?

I don't see any server errors, but I do see some anti-CSRF errors, which would probably indicate you're blocking cookies or something.

**Comment by noe132** [comment]
There's no JS console error report, it's a POST request to `https://greasyfork.org/zh-CN/scripts/{id}/versions` page with 500 status code

![image](https://user-images.githubusercontent.com/2271900/73602639-6d643380-45b2-11ea-9335-4618cd932179.png)

btw, I've tried to logout and re-login then perform the action above, I still get this error.

after some testing, I think it's caused by some script content, but it's quite random and I can't get the bare minimum code to reproduce

this is the least amount of code to reproduce this error I can found currently.
https://gist.github.com/noe132/87954f1591fe96158dded1c696cd3bd8
try upload this script will get the error.

But, if I edit `test.js` at line 3115 from `a = new r.a({` to `a = new r.b({`  and try upload, the error disappears.

Or if I remove function in `test.js` from line 3003 to 3094 ([`test_remove_function_from_line_3003-3094.js`](https://gist.github.com/noe132/87954f1591fe96158dded1c696cd3bd8#file-test_remove_function_from_line_3003-3094-js)), the error dissappears too

**Comment by JasonBarnabe** [comment]
OK, I can reproduce with the code you provided, thanks.

**Comment by JasonBarnabe** [comment]
Looks like a problem with the JS execution - filed https://github.com/rubyjs/mini_racer/issues/158

**Comment by noe132** [comment]
Is there any updates about this issue? Will this gonna be addressed soon?

**Comment by JasonBarnabe** [comment]
It's a bug in mini_racer - I'm not able to fix it myself so we'll have to wait for them to do it.

Note that Greasy Fork does not accept obfuscated/minified scripts anyway.

**Comment by JasonBarnabe** [comment]
This will get fixed whenever that mini_racer issue is fixed. Nothing to do in this project.
