### ISSUE TITLE
Info Request: Stats on @require

### ISSUE THREAD

**Issue by erosman** [JasonBarnabe/greasyfork#649]
I was wondering... if it was possible for you to compile a list of `@require` libraries that are used frequently by user-scripts hosted on GreasyFork (with some numbers or percentages)

It would also be great to see what percentage of user-scripts actually have `@require`.

Thank you

**Comment by JasonBarnabe** [comment]
It's definitely possible to write a script that would calculate this. Do you have a reason for knowing this, or is it just curiosity?

**Comment by erosman** [comment]
Hi Jason

The reason relates to the query made here in relation to FireMonkey `@require` https://github.com/erosman/support/issues/132

**Comment by JasonBarnabe** [comment]
8011/31170 (26%) use requires.

Top 10 URLs required are:
http://code.jquery.com/jquery-latest.js: 338
http://code.jquery.com/jquery-3.3.1.min.js: 288
http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js: 288
http://code.jquery.com/jquery-latest.min.js: 218
https://code.jquery.com/jquery-3.3.1.min.js: 205
https://code.jquery.com/ui/1.12.0/jquery-ui.min.js: 174
https://cdnjs.cloudflare.com/ajax/libs/jquery-confirm/3.3.0/jquery-confirm.min.js: 172
https://greasyfork.org/scripts/368273-msgpack/code/msgpack.js?version=598723: 172 https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js: 138
http://cdn.bootcss.com/jquery/1.8.3/jquery.min.js: 133

[Full data is here](https://gist.github.com/JasonBarnabe/074891696f578f067143ea50d40aee0b). It's a map from script ID to the requires used.

```ruby
used_requires = {}
Script.listable(:all).find_each do |script|
  sv = script.get_newest_saved_script_version
  used_requires[script.id] = sv.parser_class.parse_meta(sv.code)['require']
end
File.open('requires.json', 'w') {|f| f.write(used_requires.to_json)}
```

**Comment by erosman** [comment]
Thank you. It is greatly appreciated.
