### ISSUE TITLE
[Feature Request] Provide Version via Header Request

### ISSUE THREAD

**Issue by erosman** [JasonBarnabe/greasyfork#654]
Hi Jason

As I have been working on FireMonkey, I thought the following idea would be beneficial to GreasyFork and users.

ATM, for the update checking, FireMonkey only requires the **version** value.
I have set FireMonkey to check via `https://greasyfork.org/scripts/.....meta.js` which (dynamically I think) serves the metadata block as content.

If you are able to set custom headers for GreasyFork, then a simple HEAD request and a response which would include `version` would do the job. The benefit would be significant reduction in bandwidth and resource usage for both GreasyFork & users, in comparison to serving actual content.

IMHO, the head could be added to `.user.js` which would even eliminate the need for `.meta.js`

For example:
ref: `https://greasyfork.org/scripts/34153-pixiv-plus/code/Pixiv%20Plus.user.js`

Head Request to `https://greasyfork.org/scripts/34153-pixiv-plus/code/Pixiv%20Plus.user.js`
```
access-control-allow-origin: *
content-encoding: gzip
content-length: 14003
content-type: text/javascript; charset=utf-8
date: Tue, 18 Feb 2020 09:52:55 GMT
last-modified: Tue, 18 Feb 2020 09:27:14 GMT
server: nginx/1.14.0 (Ubuntu)
strict-transport-security: max-age=31536000
x-firefox-spdy: h2
```

Head Request to `https://greasyfork.org/scripts/34153-pixiv-plus/code/Pixiv%20Plus.meta.js`

```
content-type: text/x-userscript-meta
last-modified: Tue, 18 Feb 2020 09:22:06 GMT
```

custom header needed: (`// @version     0.7.4`) 

```
version: 0.7.4
```

If you think it is a good idea, and are able to implement it, I will also implement the version checking via header request in FireMonkey for GreasyFork.

**Comment by JasonBarnabe** [comment]
`.user.js` and `.meta.js` files on Greasy Fork are cached by writing them to a cache location and having nginx check there first, bypassing the application entirely. I'm not sure how I could get nginx to set a dynamic custom header with this setup.

**Comment by erosman** [comment]
I will ask around to see if that is possible.

**Comment by erosman** [comment]
I asked and was given the some answers in the comment. Please see if it is helpful.
I am not familiar with nginx to know. :stuck_out_tongue:

[Can dynamic header response be made in nginx?](https://stackoverflow.com/questions/60313098/can-dynamic-header-response-be-made-in-nginx?noredirect=1#comment106692278_60313098)

**Comment by eight04** [comment]
This should benefit usercss since usercss metadata may contain long CSS code.

**Comment by JasonBarnabe** [comment]
Greasy Fork already strips out `@resource` and `@icon` from the originating script when serving up  `.meta.js` to save bandwidth. More keys to strip can be easily added.

I think overall the idea of having the version in an HTTP header is solid, but really, bandwidth is not in short supply with Greasy Fork. The current bottleneck is CPU, so the solution I made was with this in mind (avoid the app altogether). I don't know that nginx could be configured in a sensible way to do this within the implementation on Greasy Fork.

If you're willing to get a bit further out of the box of current behaviour - what if Greasy Fork had a "master file" of all scripts and their latest version? Then you could check that one file instead of having multiple requests - and Greasy Fork could implement caching on this as well to avoid CPU load.

**Comment by erosman** [comment]
"master file" itself can generate CPU load for GreasyFork as site grows and updates become numerous and result in rapid frequent need for master-file update.
A file with 31+k entries may also be over 1mb (affects read/write)


I noticed _OpenUserJS_ is serving a much reduced `.meta.js` in newly updated user-scripts e.g.

```
// ==UserScript==
// @version    2.0.2.7
// @name    Nixian Raid Tracker
// @namespace    play.nixian.eu
// ==/UserScript==
```

In _FireMonkey_ the following would be just fine without anything else (although other user-script manager may require `==UserScript==`, `//`,  `@name` & `@namespace`)
```
@version     2.0.2.7
```

FM ref: `const version = text.match(/@version\s+(\S+)/);`


:bulb: **Another idea** 

Can you set a redirect map?

Imagine creating a map of redirection such as:

```
https://greasyfork.org/scripts/34153-pixiv-plus/code/Pixiv%20Plus.meta.js
to
https://greasyfork.org/scripts/34153-pixiv-plus/code/Pixiv%20Plus.meta.js?version=0.7.4
```

I can then grab the REDIRECT from the HEAD request header and parse the URL parameters without actually getting the file itself.

Others can continue to get the `.meta.js` content.

🤔

**Comment by erosman** [comment]
@JasonBarnabe What do you think about above?

**Comment by JasonBarnabe** [comment]
Greasy Fork already serves up a reduced meta block in response to .meta.js requests. Serving up update information via HTTP headers in HEAD requests would be a small savings in bandwidth.

Currently, Greasy Fork serves up .meta.js in a way that avoids the application server. I don't know of a way to have it set a variable header on these requests.

The redirect suggestion would have it hit the application server (twice!) and so is not viable.

Greasy Fork serves up million of update checks a day. The priority is to have those served up efficiently without the application server (and so CPU/memory). Bandwidth is a secondary concern.

**Comment by erosman** [comment]
Thank you... it was only a suggestion :)
