### ISSUE TITLE
Implement '.meta.css'

### ISSUE THREAD

**Issue by erosman** [JasonBarnabe/greasyfork#657]
It seems `.meta.css` has not been implemented like `.meta.js`

**Comment by JasonBarnabe** [comment]
User CSS support was added based on what Stylus does, and I don't think it reads `.meta.css`. Presumably Firemonkey does? What is it expecting it to be?

**Comment by erosman** [comment]
I have set FireMonkey to read '.meta.js'
I was about to set it to read '.meta.css' as well when I noticed it is not implemented.

FireMonkey can read `.meta.css`  for both UserStyle & UserCSS (also read https://github.com/JasonBarnabe/greasyfork/issues/656#issuecomment-601734059)

**Comment by JasonBarnabe** [comment]
Added, for example https://greasyfork.org/en/scripts/391902-example-usercss-style/code/Example%20UserCSS%20style.meta.css
