### ISSUE TITLE
Set the Tweet share button to each script page

### ISSUE THREAD

**Issue by kagekiyo7** [JasonBarnabe/greasyfork#659]
![image](https://user-images.githubusercontent.com/22173829/77942922-582c2c80-72f7-11ea-9f2c-2f7a6c3d02d4.png)
To share script.

Tweet button — Guides — Twitter Developers
https://developer.twitter.com/en/docs/twitter-for-websites/tweet-button/overview

**Comment by JasonBarnabe** [comment]
Not going to include Twitter's JS for this. The site used to have a non-remote Twitter share button, but I don't think it saw much use.
