### ISSUE TITLE
Someone is posting baby sex choice ads. Can we remove these?

### ISSUE THREAD

**Issue by cavok94** [JasonBarnabe/greasyfork#661]
https://greasyfork.org/zh-CN/users/473323-yiluo123

He released these abnormal scripts (including advertisements) in batches on April 2. 

Example:
In Chinese: "江西供卵试管机构选性别包成功承诺 (库)"
In English: "**We provide baby sex choice serviece in Jiangxi Province**. 100% successful rate guarantee."

In Chinese: "南昌供卵试管机构选性别包成功承诺"
In English: "**We provide baby sex choice serviece in Nancang Province**. 100% successful rate guarantee."

**He looks like a ad robot. Can we ban this user forever?**

**Comment by JasonBarnabe** [comment]
Someone else already got to it. Next time you see it, you can report it on the site. Thanks.

**Comment by cavok94** [comment]
> Someone else already got to it. Next time you see it, you can report it on the site. Thanks.

Thanks :D
