### ISSUE TITLE
看起来广告营销号已经开始盯上这里了，建议作者增加个举报用户功能。

### ISSUE THREAD

**Issue by Mr-NullNull** [JasonBarnabe/greasyfork#662]
他们可以写脚本天天发布灌水 广告 恶意 垃圾推文形成的脚本，建议封号封ip。

https://greasyfork.org/zh-CN/users/470936-gong-zhuangpaxing

**Comment by JasonBarnabe** [comment]
You can report any one of the scripts. Moderators will take a look at the whole account in case of spam.

**Comment by Mr-NullNull** [comment]
I see, Thanks♪(･ω･)ﾉ（来自我蹩脚的英语）




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Jason Barnabe"<notifications@github.com&gt;; 
发送时间: 2020年4月5日(星期天) 上午10:19
收件人: "JasonBarnabe/greasyfork"<greasyfork@noreply.github.com&gt;; 
抄送: "Mr.Null"<airsnightsky@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [JasonBarnabe/greasyfork] 看起来广告营销号已经开始盯上这里了，建议作者增加个举报用户功能。 (#662)





 
You can report any one of the scripts. Moderators will take a look at the whole account in case of spam.
 
&mdash;
