### ISSUE TITLE
[Feature Request] Auto-Receive update from Alt source (i.e. GitHub)

### ISSUE THREAD

**Issue by Cyberavater** [JasonBarnabe/greasyfork#663]
E.g. https://greasyfork.org/en/scripts/4881-adsbypasser
This script hasn't been updated on Greasyfork since 2017 but's continuously updating on the GitHub platform (and yeah it's maintained by the same dev), https://adsbypasser.github.io/

It'd be nice if there was a feature to link Greasyfork to the GitHub, So, that the Greasyfork users could get the automatic update as well (after the dev links it of course!).

**Comment by JasonBarnabe** [comment]
This already exists on the Admin tab that authors see.
