### ISSUE TITLE
Report users

### ISSUE THREAD

**Issue by FranklinYu** [JasonBarnabe/greasyfork#664]
This is a feature request.

We can now report a script, but sometimes the user is simply a spammer. Examples:

- https://greasyfork.org/zh-TW/users/475883-借卵试管微ivf138
- https://greasyfork.org/zh-TW/users/475889-代孕包男孩选性别18820000977

Would be nice if signed-in users can directly report these spammers.

**Comment by JasonBarnabe** [comment]
Just report any of the scripts. You can mention that all scripts are spam if you want, but moderators should notice regardless and clear it all out.
