### ISSUE TITLE
A new wave of spammers coming

### ISSUE THREAD

**Issue by JixunMoe** [JasonBarnabe/greasyfork#666]
https://greasyfork.org/users

It seems like I landed this page as they are creating accounts. Every-time I refresh I can see something different...

It looks like they are batch registering using name `[a-z]{8}\d{3}`:

```
fzdjftfr399
suaeeqcy040
kisgmecm062
```

Then they set the title and description.

**Comment by JixunMoe** [comment]
![image](https://user-images.githubusercontent.com/5713045/79049484-dce24900-7c1b-11ea-8d00-7c608a99509c.png)

**Comment by JasonBarnabe** [comment]
All these accounts where using a disposable email service. I've added that domain to the block list and made a stronger block type - it won't even let them register now.

I've additionally deleted all the users using that domain.

**Comment by Procyon-b** [comment]
Apparently it's still coming in.
Many names with random letters and  2-4 digits.
As well as "chinese" names containing `P-O-S` and every odd-char can't be displayed properly by my browser.  In my text editor they have the value `$E708`

**Comment by JasonBarnabe** [comment]
This was using a different disposable email. I've blocked it and cleared them out. Thanks for reporting.

**Comment by Procyon-b** [comment]
I think they are it again: "chinese" names with odd-char = `$E708` ending with 3 latin letters.

**Comment by JasonBarnabe** [comment]
Same story, all using a disposable email service. Thanks for reporting. In the future, you can also use the report feature on the user's page - just mention that you think it's a bot and I'll investigate.

**Comment by Procyon-b** [comment]
I'll do that the next time (if there is one  :) )  if this is easier for you.
