### ISSUE TITLE
Need help logging in

### ISSUE THREAD

**Issue by ttttmr** [JasonBarnabe/greasyfork#667]
I have always logged in with a username and password, and now it seems that I can only log in with an email, but I have forgotten what my registered email is. I tried my usual email but the prompt does not exist
This is my account
https://greasyfork.org/zh-CN/users/175669-tmr
My script is stored here
https://github.com/ttttmr/UserJS

**Comment by JasonBarnabe** [comment]
Looks like you made a typo. I've updated it - you should have received a confirmation email.

**Comment by ttttmr** [comment]
I received the email, thank you very much
