### ISSUE TITLE
ban + delete all scripts from reports page

### ISSUE THREAD

**Issue by JixunMoe** [JasonBarnabe/greasyfork#670]
... instead of click in to the user profile page and then delete them all.

**Comment by JasonBarnabe** [comment]
Would it not make more sense to give the option to delete all the author's scripts when banning from the report page?

**Comment by JixunMoe** [comment]
https://greasyfork.org/scripts/401067/reports/1489

Like in this page, there's an option to ban, but not to delete all scripts.

**Comment by JixunMoe** [comment]
https://greasyfork.org/users/516262/ban

I would need to click the user's profile name, then click on ban, to be offered to remove all scripts under this account.

**Comment by JasonBarnabe** [comment]
You can now delete all other scripts when resolving a report.
