### ISSUE TITLE
Greasyfork moomoo hacks

### ISSUE THREAD

**Issue by Battering101** [JasonBarnabe/greasyfork#674]
Moomoo scripts violate the greasyfork rule: "Your script must respect others' copyrights. This includes the script itself and any resources (for example images) it uses. If you intend on using someone else's content, abide by their licensing terms or get their permission before doing so.", there are hundreds of copies of this script everywhere, with minor css changes. For example: https://greasyfork.org/en/scripts/397005-moojaxnewheal-dark-theme-new-healbar-anti-ads-botmode-music-over-25-000-installs and https://greasyfork.org/en/scripts/398790-moomoo-io-labymod-2020

**Comment by JasonBarnabe** [comment]
Please report these on the site and a moderator will review them. GitHub is not the place for this.

**Comment by Battering101** [comment]
I actually just reported it on two scripts, I just wanted to make a
response on github. No mod has responded yet
