### ISSUE TITLE
Version control: Allow management of old versions snapshots 

### ISSUE THREAD

**Issue by trumpeta** [JasonBarnabe/greasyfork#675]
I'm having a slight problem with a way too high amount of version snapshots (as I'm not remarking slighter changes by different version, which is basically silent updating), 

I want to suggest adding feature to (per user preference) reduce tracing old versions by auto-removing all versions that already had been deprecated by a newer commit with identical version number. That would greatly improve lucidity of version history. Alternately, enable users to selectively delete snapshots by hand,, but the former method seems to me optimal.

**Comment by JasonBarnabe** [comment]
I don't understand what changes you're making where the code changes but the version number doesn't. Why would you do that? Doesn't that affect how script managers handle updates?

**Comment by trumpeta** [comment]
I have a reason for that. There's need to have online backup of latest script, but changes not  relevant for updating version number. Script manager sometimes discards latest changes, having very latest version always backup online is reasonable idea.

Anyway the option of keep only one or two (may be per preference) latest commits with same version number would make sense for me.

**Comment by JasonBarnabe** [comment]
I still don't get what you're doing. If you're changing code, you should be changing the version number. If you want to do a "release" thing, then use source control elsewhere and post/sync whenever you want to release..
