### ISSUE TITLE
GreasyFork may cause users who use vulnerable UserScript to be attacked when visiting malicious websites.

### ISSUE THREAD

**Issue by imdong** [JasonBarnabe/greasyfork#682]
If UserScript is malicious or vulnerable, users who have installed malicious / vulnerable UserScript scripts will be changed their passwords (or their accounts are controlled) when accessing pages with specific scripts.
It is even possible to modify the other scripts of the hijacked users to achieve the propagation vulnerability.

```
// ==UserScript==
// @name         Vulnerable UserScript
// @connect     http://website/
// ==/UserScript==

unsafeWindow.GM_xmlhttpRequest = GM_xmlhttpRequest;

// code...
```

Malicious page: 
```
GM_xmlhttpRequest({
    method: 'POST',
    url: 'http://website/change_password',
    data: "new_password"
})
```

It may even be modified by other scripts in the visitor ’s GreasyFork account to achieve dissemination.

// ==== Chinese original ======

# GreasyFork 可能会导致使用有漏洞的 UserScript 的用户在访问恶意网站时被攻击。
如果 UserScript 有恶意或有漏洞，那么安装了有恶意/漏洞的 UserScript 脚本的用户在访问有特定脚本的页面时，会被修改密码（或其账户被控制）。
甚至可以通过修改被劫持用户的其他脚本来实现传播漏洞。

// Code

甚至可能会通过对访客的GreasyFork账户中其他脚本进行修改，实现传播。

**Comment by JasonBarnabe** [comment]
It sounds like whatever issue here is not with Greasy Fork but with the user script manager you use (Tampermonkey/Greasemonkey) or perhaps with the entire concept of user scripts.

On Greasy Fork we try to catch malicious scripts but we have no control over their execution.

**Comment by imdong** [comment]
Grey fork does not need to confirm the owner to change the password. I think it is a security risk.

Greasy Fork 修改密码不需要确认所有者，我认为是个安全隐患。

**Comment by JasonBarnabe** [comment]
This is already reported in https://github.com/JasonBarnabe/greasyfork/issues/526.
