### ISSUE TITLE
Relative dates

### ISSUE THREAD

**Issue by JasonBarnabe** [JasonBarnabe/greasyfork#686]
Where dates are used, show them differently based on how long ago they are, keeping in mind caching. 

For example "30 minutes ago" rather than "2020-05-27".

**Comment by JixunMoe** [comment]
https://github.com/github/time-elements#relative-time

This might be useful.

**Comment by JasonBarnabe** [comment]
Yeah something like that is what I want. Need to see how i18n is done though.

**Comment by knoajp** [comment]
May it can be changed by user prefernce.
(I prefer actual dates :-)

**Comment by JasonBarnabe** [comment]
Now using relative dates when it's less than 30 days, absolute otherwise.
