### ISSUE TITLE
Request: add support for the arrive.js library

### ISSUE THREAD

**Issue by almaceleste** [JasonBarnabe/greasyfork#688]
Please, add support for the arrive.js library that is located on https://github.com/uzairfarooq/arrive. 
I have successfully uploaded my userscripts that use this library to openuserjs.org, but I can not upload them to greasyfork.org due to this error:

> Code uses an unapproved external script: 
> @require https://raw.githubusercontent.com/uzairfarooq/arrive/master/minified/arrive.min.js

**Comment by JasonBarnabe** [comment]
You can reference it from many popular CDNs that have it, for example https://cdnjs.com/libraries/arrive.

**Comment by almaceleste** [comment]
I know this, but I prefer to use the original source. 
You approve this library https://greasemonkey.github.io/gm4-polyfill/ from github, but do not want to approve other from no less famous author - why?
You approve this library from cdnjs.com, but do not approve from the original source - why?
Openuserjs.org approve this library, but Greasyfork.org not - why?

**Comment by JasonBarnabe** [comment]
This is explained at https://greasyfork.org/en/help/external-scripts.

**Comment by almaceleste** [comment]
what do you mean exactly?
