### ISSUE TITLE
Cant get confirm email

### ISSUE THREAD

**Issue by Leu552** [JasonBarnabe/greasyfork#690]
You must confirm your email before posting scripts.
2978610085@qq.com

but i cant email. what should i do? may be you can check the the server that I can be confirmed

thanks.

**Comment by JasonBarnabe** [comment]
I can see in the outgoing mail log qq.com is giving "service unavailable".

> May 30 11:18:29 greasyfork sm-mta[31439]: 04UBIQ2R031437: to=<2978610085@qq.com>, delay=00:00:03, xdelay=00:00:03, mailer=esmtp, pri=120683, relay=mx3.qq.com. [IPv6:240d:c040:1:40:0:0:0:133], dsn=5.0.0, stat=Service unavailable

Can you send me (jason.barnabe@gmail.com) an email from 2978610085@qq.com?

**Comment by JasonBarnabe** [comment]
Account has been marked as confirmed.
