### ISSUE TITLE
Access to deleted script's feedbacks

### ISSUE THREAD

**Issue by JixunMoe** [JasonBarnabe/greasyfork#700]
* Access to individual feedback thread is still accessible.
* Any other navigation link will redirect the user away.

e.g. https://greasyfork.org/scripts/404590/discussions/1900

**Comment by JixunMoe** [comment]
Suggestion: no access to thread, or keep basic meta information available for a while so it's consistent.

**Comment by JasonBarnabe** [comment]
Fixed, now handles like any other script page.
