### ISSUE TITLE
HTTP ERROR 500 when posting the style

### ISSUE THREAD

**Issue by almaceleste** [JasonBarnabe/greasyfork#702]
I tried to post my new userstyle, but I get the following error message:
> greasyfork.org is currently unable to handle this request.
> HTTP ERROR 500
I tried this methods with the same result:
- import by userstyle url
- post as text
- post as file
maybe there is some code in the style, that leads to an error, but I have tested this style (and I use it for myself) and it works fine.
what's wrong?
link to the style: https://github.com/almaceleste/userstyles/raw/master/src/MI-R3G_Padavan_Tweaks.user.css

**Comment by JasonBarnabe** [comment]
It was choking on this line:

```
@-moz-document url-prefix(http:///*[[ip]]*//) {
```

Fixed now.
