### ISSUE TITLE
I have a problem with a copyright. With this script https://greasyfork.org/en/scripts/38857-scriptsource-the-leading-portal-for-web-apps-youtube-quora-reddit-discord-more

### ISSUE THREAD

**Issue by GreastTT2** [JasonBarnabe/greasyfork#703]
But when I compare with a two scripts(using a website tool) it shows only a code that you need to do for making a script. There are only a requests link, that I thing can do that problem. 
https://user-images.githubusercontent.com/63648841/84707290-7257cd00-af2c-11ea-9c26-85ebab0e3fc6.png

How could I disable copyright thing? If you need i can show my script.

**Comment by JasonBarnabe** [comment]
I don't understand what you're asking.

**Comment by GreastTT2** [comment]
> I don't understand what you're asking.

I have a problem with copyright when I trying to post it says that copyright problem. I didn't copy anything from that script. How can I resolve that problem, if I have no access to a person who made a script(which is inactive for a current game moomoo.io)?

**Comment by JasonBarnabe** [comment]
So you posted something and it got deleted due to copyright issues? What was the URL of the script you posted?
