### ISSUE TITLE
Can't see new discussions of my script

### ISSUE THREAD

**Issue by e1sen-stein** [JasonBarnabe/greasyfork#709]
After converting the existing discussions to the new format I cannot see new discussions of my script. But I still can see counter updates on the Feedback's tab.

The <a href="https://greasyfork.org/scripts/38614-vk-media-downloader">script</a>

**Comment by JasonBarnabe** [comment]
I see the new format discussions on https://greasyfork.org/en/scripts/38614-vk-media-downloader/feedback

Did something change or do you still not see it?

**Comment by e1sen-stein** [comment]
Can't see this discussion https://greasyfork.org/en/forum/discussion/81662/skachivanie-muzyki/p1 in the Feedback's list

**Comment by JasonBarnabe** [comment]
After you converted, there were still links to post new discussions in the old forum. That link has since been removed.

I've migrated that discussion and all others in a similar situation.
