### ISSUE TITLE
Suggestions regarding the rating system

### ISSUE THREAD

**Issue by darkred** [JasonBarnabe/greasyfork#712]
As a [script author](https://greasyfork.org/en/users/2160-darkred?sort=updated), I'd like to make some suggestions regarding the rating system in GF :

1. Change the Discussion categories for scripts Feedback, to: `Discussion`, `Issues`, `Reports`, and `Good`
2. Add `close` and `lock` features (like Github) in the `Issues` category discussions that I suggest above
3. Add an appreciation notice in the "Feedback" tab 
  
&nbsp;

---

In details:

1. Change the discussion categories for scripts Feedback, from:

   ```
   No rating - just a question, comment, feature request, or bug report
   Bad - script doesn't work
   OK - script works, but has significant issues
   Good - script works well  (+ the current 'Add to favorites' functionality)
   ```
   
   
   to:
   
   ```
   Discussion - just a question, comment
   Issues - script doesn't work at all, bug report, feature request
   Reports - unauthorized copies of others script, malware, spam/other non-script content, other violations(incl. undisclosed ads or cryptominers)
   Good - script works well  (+ the current 'Add to favorites' functionality)
   ```
   
   My reasoning is that the `Bad - script doesn't work` and `OK - script works, but has significant issues` are constantly misused by GF users, a "hit-and-run" behavior.
   <details>
   <summary>My reasoning in details:</summary>
   
   As a script author, there's something annoying that's been happening unfortunately very often in GF :
  
   every now and then, someone posts a 1 line discussion post with some supposed "bug report"/"feature request", with a rating `Bad` or `OK` . *These people most of the times have posted 0 scripts in GF and have no Javascript knowledge.*
   When I ask them to give more details, be more specific, I usually don't get any feedback,
   and even when I manage to find out myself what they were meaning, and implement it in the script, 
   and I kindly notify them of the script update and ask them to change their rating to `No rating - just a question, etc`
   they never reply at all.
   
   And so, I end up having to ask from a GF mod to manually change the rating to "No rating" .
   </details>

   Notes: 
   
   - The 'Discussion' is a new beta feature in GitHub [link](https://news.ycombinator.com/item?id=22388639). My suggested combination of `Discussion` and `Issues` is with GitHub in mind.
   - The 'Reports' tab count would help the GF reader by warning them that the script has already been reported x times, therefore it's dangerous to try it, and that would occur early enough, before the GF mods actually get to remove it.

---

2. Add `close` and `lock` features (like Github) in the `Issues` category discussions that I suggest above :

    This has been suggested in [GF - New comment/review method for scripts](https://greasyfork.org/forum/discussion/comment/100701/#Comment_100701) :
    
    > can u add a "close" and "lock" feature like Github? We have no control to our discussions, only the administrators have the power to do so, that's ridiculous.
     
    and I'd love to have these features in GF: I believe the script authors should be able to have these moderation capabilities on Issue discussions about their scripts.

---

3. Add in the 'Feedback' tab of scripts pages this the appreciation notice used by the "[TS] Citrus GFork" script ([diff](https://greasyfork.org/en/scripts/4336-ts-citrus-gfork/diff?v1=19357&v2=18480)) :

    > Show your appreciation to the author by favouring the script and giving positive feedback
    
    <details>
    <summary>screenshot</summary>

    ![2020-06-24_114814](https://user-images.githubusercontent.com/723651/85524205-9e500e00-b610-11ea-9f15-14922670d886.jpg)
    </details>
    
    I find that this phrase gets the users to the positive mindset to express their appreciation     to the authors for what they offer spending their free time, and that, providing support/fixing bugs/fulfilling feature requests is something that they kindly offer, 
    not something that they are obliged to, nor *owe* to anyone.

**Comment by JasonBarnabe** [comment]
The goals of the feedback mechanisms on Greasy Fork are:

1. To identify malware/spam/etc. (Report)
2. To give users a way to provide feedback to authors (Review/Question)
3. To feed data into a ranking mechanism (Review)

Your suggestions would drastically change how goal 3 is achieved. Essentially it'd be reduced to a "like" count, with no ability for users to review a script poorly.

While the situation you describe is of an author trying to do something about untrue reviews, your changes would also apply to an author shutting down discussion of legitimate issues. The current featureset is trying to find a balance between the two. If you want more control, you can do as I suggest in that forum thread and provide a `@supportURL` pointing to GitHub (or wherever) where you have control over the discussions. Greasy Fork will show this link on the Feedback tab.

Couple of notes:

> The 'Reports' tab count would help the GF reader by warning them that the script has already been reported x times, therefore it's dangerous to try it, and that would occur early enough, before the GF mods actually get to remove it.

This is already done, but in a slightly different way. If a script is reported by a user who is "trusted", it will be hidden until mods do something about the report. To become "trusted" you have to have a certain number of previous reports, with a certain percentage of them being upheld.

> and I kindly notify them of the script update and ask them to change their rating to No rating - just a question, etc
they never reply at all.

This gave me the idea of #714.

**Comment by darkred** [comment]
Thank you for your response.

&nbsp;

> If you want more control, you can do as I suggest in that forum thread and provide a @supportURL pointing to GitHub (or wherever) where you have control over the discussions. Greasy Fork will show this link on the Feedback tab. 

Great idea, I'll add such a line pointing to GitHub to all my scripts.

&nbsp;

> This gave me the idea of #714.

Could you please explain who do you refer to with "Present UI to change a rating" ? To the commenter/reviewer or the script author?
I am asking, because, in GF's current status, if I start a discussion for a script, and put a rating, e.g. `Good`,
I can edit my original/first post(=OP), and also modify that `Good` rating, even after I have posted a reply in the discussion.

Because, if the UI is presented to the commenter, 
then unfortunately it doesn't help with that annoying "hit-and-run" behavior:
such commenters usually don't care to come back to provide feedback or ever fix the rating.
Just check the [latest](https://greasyfork.org/en/scripts/368881-protonmail-remove-forced-signature/discussions/7416) "hit-and-run" case for one of my scripts  :
> `Ok` Leave a space at the top when deleting the signature...

`Ok` "rating", case with a hurried 1-line, even ending with ellipsis (`...`) !!

And just look the "[commenter](https://greasyfork.org/en/users/592063-wuniversales)" whole activity? :
0 scripts posted, and only 3 almost identical `Ok` "ratings".
I added that improvement within a few hours, but he never responded nor fixed the rating.


&nbsp;

And what's your opinion on adding an appreciation notice in the "Feedback" tab ?

**Comment by JasonBarnabe** [comment]
> Could you please explain who do you refer to with "Present UI to change a rating" ? To the commenter/reviewer or the script author?
> I am asking, because, in GF's current status, if I start a discussion for a script, and put a rating, e.g. Good,
> I can edit my original/first post(=OP), and also modify that Good rating, even after I have posted a reply in the discussion.

The reviewer will be presented with an option to change their rating when they reply. This is in the "old" discussions but not "new".

> Because, if the UI is presented to the commenter, then unfortunately it doesn't help with that annoying "hit-and-run" behavior:

No, it's more for people who do come back and reply. I would be open to suggestions that would help with "hit-and-runs" but wouldn't be abused by authors.

> And what's your opinion on adding an appreciation notice in the "Feedback" tab ?

I think there should be an easier way to "like" a script, but that should be combined with a way to "dislike" it, which would lead to complaints about people "disliking" without giving a reason... Again everything needs to be considered otherwise it makes things meaningless.

**Comment by darkred** [comment]
>  I would be open to suggestions that would help with "hit-and-runs" but wouldn't be abused by authors.

Ok, so here is my suggestion, the best I came up with:

add in script reviews a `Report rating` button(next to the existing `Report comment`), available only to the relevant script author, 
with which to be able to report any `Ok`/`Bad` rating that he believes it's untrue,
and if the script author is "trusted" (as you describe above), the rating to immediately switch to `No rating - just a question`, till a moderator either decides to make `No rating` permanent, or revert it.
_Maybe display the `Report rating` button 2-3 days after the post was made, to give the 'reviewer' the "benefit of doubt"_ .

The laziness and ignorance of some 'reviewers' is despicable.

---

By the way, could you please change the rating in [here](https://greasyfork.org/en/scripts/368881-protonmail-remove-forced-signature/discussions/7416) to `No rating` ? I don't think he'll ever come back and reply, it's 3 days now.

**Comment by darkred** [comment]
If you believe that there's nothing more to be added to the discussion,
and that there's no viable solution against the "hit-and-run" behavior,
please feel free to close the issue. 

<sup>I've asked from a mod to change the rating of that '[review](https://greasyfork.org/en/scripts/368881-protonmail-remove-forced-signature/discussions/7416)'<sup>

**Comment by darkred** [comment]
I've asked from a mod to change the rating of that '[review](https://greasyfork.org/en/scripts/368881-protonmail-remove-forced-signature/discussions/7416)'
Update: 
@wOxxOm (the moderator I asked) replied to me that :

> Moderators can't change reviews in the redesigned feedback.

So, could you, as admin, please change the rating?

---

Concluding, unfortunately I can't think of a better approach against "hit-and-run" behavior,
and I have to admit that my suggestion above is rather complicated and far from ideal.

So, if you believe that there's no viable solution against the "hit-and-run" behavior to be found,
and that there's nothing more to be added to the discussion, please feel free to close the issue.

**Comment by JasonBarnabe** [comment]
I think your suggestion is just going to result in the feature being abused - some authors will just report every bad review, untrue or not. Think of any other review system - would it be good if restaurant reviews could be removed just because the restaurant owner wants it?

Regarding moderators... I would guess that even if there was an objective thing that could be tested, it would often be quite difficult for moderators to figure it out - the site is unfamiliar, in a different language, requires an account, etc. I don't think it's feasible.

I think the solution is more around giving the reviewers as much opportunity to revise their review if the script author responds. One thing that I just added was letting them update their review when they respond. Another would be #707, so they are more likely to see the script author's reply. I would open to further suggestions along these lines.

I was also considering changing the "strength" of the review if the reviewer does not respond to replies. e.g. If they post a "bad" review, the script author replies, but the reviewer never comes back, then maybe that one's worth half as much or something. Not sure about this though; it hasn't been fully thought out.

**Comment by darkred** [comment]
> I think the solution is more around giving the reviewers as much opportunity to revise their review if the script author responds. One thing that I just added was letting them update their review when they respond. Another would be #707, so they are more likely to see the script author's reply. I would open to further suggestions along these lines.
>
> I was also considering changing the "strength" of the review if the reviewer does not respond to replies. e.g. If they post a "bad" review, the script author replies, but the reviewer never comes back, then maybe that one's worth half as much or something. Not sure about this though; it hasn't been fully thought out.

I like your approaches a lot. 

I have two suggestions:

1. in addition to #707, this new checkbox to be ticked by default the notifications for replies to the discussions you have started (incl.ratings to scripts). this way they won't have any excuse for "hit-and-run" behavior.

2. regarding:

    > then maybe that one's worth half as much or something.

    I'd suggest their rating to be worth *nothing/no rating* unless they come back and respond to the script author's reply.

---

<sup>I contacted that member via pm, and he finally changed the rating to "No Rating"</sup>

**Comment by darkred** [comment]
What about showing a guiding message to the reviewer when trying to make a No Rating/Bad/OK review ?
Something similar to what GitHub offers, templates: [Using templates to encourage useful issues and pull requests](https://docs.github.com/en/github/building-a-strong-community/using-templates-to-encourage-useful-issues-and-pull-requests), but predefined/standardized by you ? Something like:

> When reporting issues or rate OK/Bad a script, please provide the author with:
> - Browser name and version, script manager, any additional details,
> - A URL example where the issue you want to report, occurs,
> - A screenshot if necessary. 
> - Be as specific and descriptive as possible.
>
> When the author responds, please provide the feedback he might ask. 
> Test the new version if offered, and revise your rating if the new version works ok for you. 
> In other words, try to be constructive and make useful reviews for the GF community.

&nbsp;

Just check this member, mica_ ,   two latest **identical** "reports":  
see [1 (for a script by me)](https://greasyfork.org/scripts/24895-google-youtube-search-link/discussions/71203) and [2 (for a script by someone elese)](https://greasyfork.org/scripts/411895-google-seach-menu-repalce-videos-tab-to-youtube/discussions/71204)

> This is no longer working (Dec. 2020)

In the former case, about a script by me, it works fine and I asked for details, yet he never answered.
The other author asked him for details, didn't got any answer and had to find out himself what the issue was...

&nbsp;

And if you check his [whole activity regarding reviews](https://greasyfork.org/en/discussions?user=12559) , it's almost always hit-and-run:
he never cares to thank/confirm the author when he has implemented/fixed what he reported, nor give details when asked.


---

Or at least dissallow 1-line "reports" ?   
I mean, when a user tries to submit such a short "review", 
to block its submission, and show a message to the reviewer to give more details, and make a more useful report?

&nbsp;

PS. happy holidays !

**Comment by darkred** [comment]
@JasonBarnabe 
I'm aware that moderators can no longer change reviews in the redesigned feedback.
Could you please restore this ability for the mods?

It would serve as a last resort:
after an unfair `Ok`/`Bad` rating, the script author tries to handle the report himself first. 
Then, if there is no answer in more than a few days, he can ask moderators to fix the rating to `No Rating`, 
as it was in the old feedback system.
