### ISSUE TITLE
The new layout annoys me

### ISSUE THREAD

**Issue by Smoke-N-Mirrors** [JasonBarnabe/greasyfork#718]
The new layout is kind of weird, pics are incredibly zoomed and the bottom fixed pics can be scrolled, IT LOOKS EXTREMELY TERRIBLE, and why do u remove the bg-color? In my perspective, it doesn't make any sense
Take a look at this:https://greasyfork.org/en/scripts/393386

**Comment by JasonBarnabe** [comment]
Image sizes are fixed.
