### ISSUE TITLE
Embedded images are no longer scaled horizontally

### ISSUE THREAD

**Issue by chocolateboy** [JasonBarnabe/greasyfork#719]
**Browser**:  Firefox 77.0.1 | **OS**:  Linux (Arch)

I have a couple of scripts which embed images in the description (the "Additional Info" section) rather than using the screenshots carousel. Previously these images were scaled so that the whole image could be seen, but this appears to have been lost recently and they now either a) have a [scrollbar](https://greasyfork.org/en/scripts/38557-github-first-commit) or b) are [cropped](https://greasyfork.org/en/scripts/39308-digg-highlighter).

**Comment by JasonBarnabe** [comment]
Fixed now, thanks.
