### ISSUE TITLE
[Feature Request] Allow scripts to be disabled

### ISSUE THREAD

**Issue by chocolateboy** [JasonBarnabe/greasyfork#720]
I have a script which fixes a nit that [may have been fixed](https://github.com/chocolateboy/userscripts/issues/10#issuecomment-650627657) on the site. It could be that the underlying issue (bug?) has been permanently fixed, or it could be a temporary "fix" (A/B testing?).

Ideally, since it's possible the script could be useful again, I'd like to be able to suspend/disable it with the option to easily resume/enable it again if needed, rather than just deleting it.

I can manually make backups of the markdown and the screenshots and re-upload the script etc, but that's a faff and, of course, the script's ID/URL would be lost. It'd be great if there was a way to remove the script from the site while preserving its details so it can quickly and easily be reinstated if needed.

**Comment by JasonBarnabe** [comment]
Your options are:

1. Mark the script as unlisted. It would still be accessible to anyone with the URL, but would not appear in search results.
2. Delete the script. This is a "soft delete" and you can undelete it at any time. Only you and moderators will be able to access it.
