### ISSUE TITLE
[bug] "show all languages" ("Показать все языки") don't working

### ISSUE THREAD

**Issue by TuTAH1** [JasonBarnabe/greasyfork#721]
If I search something, it shows only results in Russian language, saying "Only Russian is shown. [Show all languages](https://greasyfork.org/ru/scripts?filter_locale=0)." ("Показан только Русский язык. [Показать все языки](https://greasyfork.org/ru/scripts?filter_locale=0)."), but clicking the link does not remove language filter - it remove search text while there's still language filter and there's still text "Only Russian is shown. [Show all languages](https://greasyfork.org/ru/scripts?filter_locale=0)."

**Comment by JasonBarnabe** [comment]
Fixed now, thanks for reporting.
