### ISSUE TITLE
[Regression] jsDelivr dependencies no longer work

### ISSUE THREAD

**Issue by chocolateboy** [JasonBarnabe/greasyfork#722]
These worked as recently as a [few days ago](https://greasyfork.org/en/scripts/405154-twitter-time-tooltip/versions), but now raise an error, e.g.:

### [GitHub First Commit](https://greasyfork.org/en/scripts/38557-github-first-commit)

```
There were some problems with what you posted...

    Code uses an unapproved external script: @require https://cdn.jsdelivr.net/gh/eclecto/jQuery-onMutate@79bbb2b8caccabfc9b9ade046fe63f15f593fef6/src/jquery.onmutate.min.js
```

### [IMDb Tomatoes](https://greasyfork.org/en/scripts/15222-imdb-tomatoes)

```
There were some problems with what you posted...

    Code uses an unapproved external script: @require https://cdn.jsdelivr.net/gh/urin/jquery.balloon.js@8b79aab63b9ae34770bfa81c9bfe30019d9a13b0/jquery.balloon.js
```

**Comment by JasonBarnabe** [comment]
The requirement has been refined to not allow the /gh/ path.

**Comment by chocolateboy** [comment]
Why?

**Comment by JasonBarnabe** [comment]
Oh, the commit-specific ones should be allowed. Didn't realize that was supported.

**Comment by JasonBarnabe** [comment]
I've switched it back to how it was until I can figure out the regex to allow commit-specific ones.

**Comment by JasonBarnabe** [comment]
Allowed patterns have been updated to allow commit-specific GitHub references and anything else that's not a GitHub reference.

https://greasyfork.org/en/help/external-scripts
