### ISSUE TITLE
Collapse banned user's feedback post

### ISSUE THREAD

**Issue by jixunmoe** [JasonBarnabe/greasyfork#726]
Collapse to something like:

> [user] in 2020-06-01:
> The user has been banned [for _short reason here_] and hence the comment has been collapsed. You can still view the comment if you want to.

Mainly because people spam the discussion thread with hateful comments...

Also, would it be worth to add a short reason field to the discussion report?

**Comment by JasonBarnabe** [comment]
Would this be for the comment that caused them to be banned or for other comments that potentially are OK?

**Comment by JixunMoe** [comment]
Maybe a checkbox for that when banning a user? If someone has posted a lot of hateful comments and got banned for that, I would like his/her comments to be hidden by default...

**Comment by JasonBarnabe** [comment]
There are now controls when banning to decide whether their comments should be deleted.
