### ISSUE TITLE
Rich styled additional info

### ISSUE THREAD

**Issue by knoajp** [JasonBarnabe/greasyfork#727]
I want add some inline-styles such as border, background-color, margin, padding and so on.
I don't mind whatever way to add styles, but I want to introduce my scripts with richer styles.

I suppose there are some good sanitized list or sanitizer of HTML attributes or CSS properties.

**Comment by JasonBarnabe** [comment]
I've marked some CSS as allowed. I don't want to do margin/padding due to the possibility of negative values "breaking out" of the container.

https://greasyfork.org/en/help/allowed-markup

**Comment by knoajp** [comment]
Thank you very much!! I'm so glad!!
(but is it difficult to allow only positive values on padding/margin?)

**Comment by knoajp** [comment]
and border-*** properties also help us.
such as bottom, radius, etc.

I browsed the source code of greasyfork to find some part for trying pull request, but it seems to be on server-side which is not on github...?

**Comment by JasonBarnabe** [comment]
https://github.com/JasonBarnabe/greasyfork/blob/bc0278a6583b7521413ef301e443f0e7ff8a91dc/app/helpers/user_text_helper.rb#L56

**Comment by knoajp** [comment]
Oh sorry, I found that, but it just seems to define properties and it is not for allowed values such as negative or positive and so on. Or are there any way to attatch regexp or something to define allowed values? (maybe I should study ruby :-)

Anyway could I add border-*** properties to it and send a pull request?

**Comment by JasonBarnabe** [comment]
I've created https://github.com/rgrove/sanitize/issues/201 and https://github.com/rgrove/sanitize/issues/202 for support in the gem we're using.
