### ISSUE TITLE
Support optional chaining

### ISSUE THREAD

**Issue by Mottie** [JasonBarnabe/greasyfork#728]
Most modern browsers now support [optional chaining](https://caniuse.com/#feat=mdn-javascript_operators_optional_chaining).

I recently started using optional chaining in my userscripts, but the scripts were not auto-updating on GreasyFork. While manually trying to update, I noticed two problems:

- Optional chaining is throwing an error
- The line number showing the problem is one-off

![2020-07-11 18_09_19-Post new version of GitHub Image Preview](https://user-images.githubusercontent.com/136959/87235511-4e0fd480-c3a2-11ea-9e42-14d60ba75f71.png)

Here are the two files (so far) that is having this problem:

- https://github.com/Mottie/GitHub-userscripts/blob/master/github-files-filter.user.js#L208
- https://github.com/Mottie/GitHub-userscripts/blob/master/github-image-preview.user.js#L188

**Comment by JasonBarnabe** [comment]
The dependency chain here is [mini_racer](https://github.com/rubyjs/mini_racer) -> [libv8](https://github.com/rubyjs/libv8) -> v8. From what I can tell, v8 has support for this in a released version, but the others don't.

I would like to support this but there's nothing to be done in this project - mini_racer and libv8 need to release updates.

**Comment by JasonBarnabe** [comment]
The dependencies have released updates and I've upgraded them. You should be able to use optional chaining now.
