### ISSUE TITLE
无法更改注册邮箱？

### ISSUE THREAD

**Issue by RallyQ** [JasonBarnabe/greasyfork#729]
您好！想改变注册的邮箱，设置里允许改，但是更改提交后提示账号名已存在，我不想改变账号名，只想更改邮箱，不知是否可以？

**Comment by jixunmoe** [comment]
Translation:

> Hi! I would like to change the email, however when I do, it gives me an error message "account already exists". Can I change the email without changing the user name?

**Comment by JasonBarnabe** [comment]
What is the URL of your user page (e.g. https://greasyfork.org/en/users/1-jasonbarnabe)?

**Comment by RallyQ** [comment]
> 
> 
> 您的用户页面的URL是什么（例如https://greasyfork.org/en/users/1-jasonbarnabe）？

近一小时前已给您发了两封邮件

**Comment by JasonBarnabe** [comment]
Fixed and responded via email.
