### ISSUE TITLE
Review allowed image types

### ISSUE THREAD

**Issue by JasonBarnabe** [JasonBarnabe/greasyfork#730]

**Comment by jixunmoe** [comment]
will webp be considered? they tend to have better compression ratio + supported in [modern browsers](https://www.caniuse.com/#feat=webp).

**Comment by JasonBarnabe** [comment]
Yes, it's likely to be allowed assuming there are no issues with doing so.

**Comment by JasonBarnabe** [comment]
GIF and WebP added for comments and messages. Scripts will have to wait for #522.
