### ISSUE TITLE
Having typed field search operators in Advanced Search, it returns HTTP 500 error

### ISSUE THREAD

**Issue by No5972** [JasonBarnabe/greasyfork#731]
Or it was my search pose that was incorrect?

Having typed ```@xxx yyy``` in the input box next to the Script Search like ```@incompatible firefox```, it only returns HTTP 500 error. It seems some backend exceptions occurred while processing this kind of keywords.
![ge1](https://user-images.githubusercontent.com/32865305/87260831-4b1dfc80-c4e6-11ea-8b9f-567907a6d1bf.png)
![ge2](https://user-images.githubusercontent.com/32865305/87260832-4ce7c000-c4e6-11ea-9378-b0f5da7e8b35.png)

**Comment by JasonBarnabe** [comment]
`@` is a special character for the Sphinx syntax.

If you're looking for that string in the code, do a code search. This doesn't use the Sphinx syntax.

**Comment by No5972** [comment]
> `@` is a special character for the Sphinx syntax.
> 
> If you're looking for that string in the code, do a code search. This doesn't use the Sphinx syntax.

Issue is found. While typing a field that does not exist in the actually existing fields, it will return 500 errors. 😂 

Maybe a reminder should be displayed while receiving fields that don't exist?
