### ISSUE TITLE
It is suggested to add BootCDN as trusted CDN

### ISSUE THREAD

**Issue by O-AN-drew-O** [JasonBarnabe/greasyfork#732]
BootCDN is a cdn maintained by Bootstrap Chinese Network. When I want to submit a script, I am always prompted that BootCDN is not a trusted CDN
https://www.bootcdn.cn/

**Comment by jixunmoe** [comment]
On a side note, please use jsdelivr (which has CDN nodes in mainland Chhina as well) as possible.

I'm having connectivity issues with bootcdn all the time :/

**Comment by JasonBarnabe** [comment]
Added!
