### ISSUE TITLE
The jQuery accelerator domain name of BootCDN is cdn.bootcdn.net

### ISSUE THREAD

**Issue by O-AN-drew-O** [JasonBarnabe/greasyfork#739]
You can see all jQuery versions: https://www.bootcdn.cn/jquery/
For example, version 3.5.1: https://cdn.bootcdn.net/ajax/libs/jquery/3.5.1/jquery.min.js

**Comment by JasonBarnabe** [comment]
Updated the pattern for BootCDN. Thanks.
