### ISSUE TITLE
jsDelivr dependencies Regexp no work

### ISSUE THREAD

**Issue by cool-delete** [JasonBarnabe/greasyfork#740]
![image](https://user-images.githubusercontent.com/13638610/87804813-fb915500-c886-11ea-992d-3a221a9f04ad.png)

me request `https://cdn.jsdelivr.net/gh/winrey/pcr-wiki-helper@master/js/solver.js`

>       
`^(https?:)?//cdn`  // no matches(https://cdn)

**Comment by JasonBarnabe** [comment]
The reference to a GitHub repo must be commit-specific. Replace "master" with a commit ref.
