### ISSUE TITLE
can't import scripts from github

### ISSUE THREAD

**Issue by consideration-ak** [JasonBarnabe/greasyfork#743]
Script sync failed - Code uses an unapproved external script: @require https://cdn.jsdelivr.net/gh..............., but you said 
The current list is:
jsDelivr GitHub commit-specific references      ^(https?:)?//cdn\.jsdelivr\.net/gh/[^/]+/[^/@]+@[a-f0-9]{40}
WTF???????

**Comment by jixunmoe** [comment]
Care to share the URL?

**Comment by consideration-ak** [comment]
> Care to share the URL?

For example https://cdn.jsdelivr.net/gh/SeaLoong/Bilibili-LRHH/BilibiliAPI.js

**Comment by jixunmoe** [comment]
You need to reference the _exact_ commit.

**Comment by JasonBarnabe** [comment]
What @jixunmoe said.
