### ISSUE TITLE
add `width:100%` to fix Script list page width overflow problem

### ISSUE THREAD

**Issue by dnknn** [JasonBarnabe/greasyfork#744]
https://greasyfork.org/scripts?q=%E7%A6%8F%E5%88%A9%E5%90%A7
A long horizontal scroll bar (`overflow-x`) appears 👇

![555](https://user-images.githubusercontent.com/10995302/88466092-8b747600-cefb-11ea-8db4-a390c90b9f0e.gif)

but 👇 🅲🆂🆂 can fixed it.

**Comment by JasonBarnabe** [comment]
Assuming you mean [https://greasyfork.org/en/scripts/23102-%E7%A6%8F%E5%88%A9%E5%90%A7%E5%B1%8F%E8%94%BD%E8%BE%A3%E9%B8%A1%E5%B8%96%E5%AD%90](this page), I don't see that.

![Screenshot_2020-07-26 福利吧屏蔽辣鸡帖子](https://user-images.githubusercontent.com/583995/88493745-6b36cc80-cf78-11ea-868f-23922feb00ba.png)

**Comment by dnknn** [comment]
No,no... is 👇 `?filter_locale=0` to show more script lists👇
![Pic-200727_1210](https://user-images.githubusercontent.com/10995302/88502797-340cfd80-d002-11ea-8c90-feb8be64b7f7.png)

## [greasyfork.org/scripts?filter_locale=0&q=%E7%A6%8F%E5%88%A9%E5%90%A7](https://greasyfork.org/scripts?filter_locale=0&q=%E7%A6%8F%E5%88%A9%E5%90%A7)
## [greasyfork.org/scripts?filter_locale=0&q=Discuz](https://greasyfork.org/scripts?filter_locale=0&q=Discuz)

&nbsp;

![width](https://user-images.githubusercontent.com/10995302/88502800-366f5780-d002-11ea-94ea-6fc4507a17f4.gif)


### Take another look. When the width of the browser window becomes smaller, it won't `overflow-x`.

![width1](https://user-images.githubusercontent.com/10995302/88503068-30c64180-d003-11ea-80e8-372b07ea548c.gif)

**Comment by Parveenka** [comment]
Stop sending me the junk

**Comment by JasonBarnabe** [comment]
I don't see it on that page either. It wraps perfectly fine.

![Screenshot_2020-07-27 User scripts](https://user-images.githubusercontent.com/583995/88505214-7ef42a00-cf9c-11ea-846a-00f46f789613.png)

**Comment by dnknn** [comment]
URL?

**Comment by JasonBarnabe** [comment]
https://greasyfork.org/en/scripts?filter_locale=0&q=%E7%A6%8F%E5%88%A9%E5%90%A7

**Comment by dnknn** [comment]
Your screen resolution?

**Comment by maple3142** [comment]
It seems to broken only on Chrome, while works fine on FireFox.

**Comment by dnknn** [comment]
@JasonBarnabe 
> It seems to broken only on **Chrome**, while works fine on **FireFox**.

**Comment by JasonBarnabe** [comment]
OK, I see the problem, but the proposed fix (`.sidebarred-main-content {width:100%}`) is not correct. It makes the main content as wide as the main content + sidebar should be.

**Comment by dnknn** [comment]
> but the proposed fix (`.sidebarred-main-content {width:100%}`) is not correct. It makes the main content as wide as the main content + sidebar should be.

I don't know much about html/DOM/JavaScript, etc., and I am not a developer.
I found it by testing accidentally.
