### ISSUE TITLE
Can ✔️ Emoji🔣🤬 ?

### ISSUE THREAD

**Issue by dnknn** [JasonBarnabe/greasyfork#745]
### Can add `Segoe UI Emoji` 🅲🆂🆂 to show color-Emoji❓	

`body {font-family:"Open Sans", sans-serif}` 👇
body {font-family:"Open Sans", sans-serif;**"Segoe UI Emoji"**}

```
body, select, input {font-family:"Open Sans", sans-serif; "Segoe UI Emoji"}
body:lang(zh-CN), select:lang(zh-CN), input:lang(zh-CN) {font-family:"Open Sans", "Microsoft YaHei UI", sans-serif; "Segoe UI Emoji"}
....

```

Can be like 🐈github.CSS for 🔣🤬 👇
`·····,Apple Color Emoji,Segoe UI Emoji`
![Pic-200726_1313](https://user-images.githubusercontent.com/10995302/88472045-df09b280-cf41-11ea-8a04-4b25c2a0b707.png)

**Comment by JasonBarnabe** [comment]
I don't understand what doing this would add support for. What characters don't currently work on Greasy Fork?

**Comment by dnknn** [comment]
> What characters don't currently work on Greasy Fork?

Both can display Unicode characters, but some emojis cannot be displayed as **colorful** emojis.
### https://unicode.org/emoji/proposals.html#existing
>Emoji is divided into black&white and color.
If there is no surface `Segoe UI Emoji`, it will not be displayed as a colored Emoji.

Just give an example: 
## ⚙🛠

![Emoji](https://user-images.githubusercontent.com/10995302/88484504-6cc8ba80-cfa1-11ea-8f71-2a2452808ad2.gif)

----

- The best single Unicode character
https://unicode-table.com

- Support batch multi-select Emoji copy
https://unicode.org/emoji/charts-13.0/emoji-style.txt
http://getemoji.com

**Comment by Parveenka** [comment]
Stop sending me this junk. I keep unsubscribing every day, but it keeps coming.

**Comment by dnknn** [comment]
> I keep unsubscribing every day, but it keeps coming.
@Parveenka  Please take back your words.

![Pic-200727_357](https://user-images.githubusercontent.com/10995302/88488069-63e5e200-cfbd-11ea-8187-8887c9433b30.png)
You are responsible for what you do.
You accidentally clicked to subscribe, did you know? Who can blame it?

**Comment by JasonBarnabe** [comment]
GitHub transforms the emoji you're using to images for me, so every emoji you use is showing up as a colorful version. But in the email notification that didn't happen, so I think I understand what you're talking about. I've added the reference to the font.

**Comment by dnknn** [comment]
> GitHub transforms the emoji you're using to images for me, so every emoji you use is showing up as a colorful version.

No, it is an exception to github doing that.
`GitHub transforms the emoji you're using to images` : It is to be compatible with the old platform system. E.g Win⁷ system

**Comment by jixunmoe** [comment]
I think you might want to add the ones for Mac (Not sure about the font in Linux), Segoe is a font by Microsoft.

**Comment by JasonBarnabe** [comment]
It seems to map automatically to "Twemoji Mozilla" on Linux/Firefox.

**Comment by dnknn** [comment]
> Segoe is a font by Microsoft.

Yes. The final effect of each platform may be different.

<details>
<summary>Details</summary>

![0728002917](https://user-images.githubusercontent.com/10995302/88567008-73bb0000-d069-11ea-8246-bfd3f6e84ab3.png)

</details>


For ❖Windows,can check whether the machine comes with `Segoe UI Emoji` font
### ms-settings:fonts
or		`C:\Windows\Fonts`

<details>
<summary>Details</summary>

![Pic-200728_024](https://user-images.githubusercontent.com/10995302/88566511-b203ef80-d068-11ea-93ca-17b59b41de17.png)

</details>

**Comment by JasonBarnabe** [comment]
If what we have now is a problem on some platform, and making that change would fix it, then let me know.
