### ISSUE TITLE
@require https://cdn.jsdelivr.net/gh/ rejected

### ISSUE THREAD

**Issue by gnadelwartz** [JasonBarnabe/greasyfork#748]
Hi Jason,

since today my external scripts are rejected, even worked in the past and in general it seems not rejected on the rules page:

![grafik](https://user-images.githubusercontent.com/4593242/88642388-b5c36080-d0c0-11ea-9c6e-a3034c8f2b50.png)

but if I add anything behind https://cdn.jsdelivr.net/gh it switches to not allowed
![grafik](https://user-images.githubusercontent.com/4593242/88642520-e2777800-d0c0-11ea-9add-3d7b70d57221.png)

@require https://cdn.jsdelivr.net/gh/gnadelwartz/Enstyler@4.04.251/translations.js

Browser: Firefox, Win 10

**Comment by JasonBarnabe** [comment]
References to GitHub through jsdelivr must now be commit-specific. After the `@` needs to be a commit reference.

**Comment by gnadelwartz** [comment]
It's working except the following URL is rejected:

https://cdn.jsdelivr.net/gh/pieroxy/lz-string@c58a22021000ac2d99377cc0bf9ac193a12563c/libs/lz-string.min.js

**Comment by jixunmoe** [comment]
You are missing a character in the hash.

```
https://cdn.jsdelivr.net/gh/pieroxy/lz-string@c58a22021000ac2d99377cc0bf9ac193a12563c5/libs/lz-string.min.js
```

**Comment by gnadelwartz** [comment]
thanks, I did not notice  because the Link was working

so your check is better than jsdelivr 😁 (and my copy paste)

**Comment by jixunmoe** [comment]
I think is because git allows you to use a "shorter" hash, given that the chance of collision should be fairly low for a small to medium sized project...
