### ISSUE TITLE
Wrong spelling in french

### ISSUE THREAD

**Issue by Procyon-b** [JasonBarnabe/greasyfork#751]
On the user's page, under the "Recent comments" ("Commentaires récents"):
`Replied to a review of Google images - ...`
is translated to:
`En réponse à une ex-amination de Google images - ...`

There is no hyphen in "[examination](https://fr.wiktionary.org/wiki/examination)". 
Also, "review" can be translated to "critique" (like with movies). "examination" is a bit weird for me (but it's valid).

I'm browsing in english, so I haven't noticed until now.

**Comment by JasonBarnabe** [comment]
Thanks! You can update translations yourself on https://www.transifex.com/greasy-fork/greasy-fork/dashboard/.

**Comment by Procyon-b** [comment]
Done.

**Comment by Procyon-b** [comment]
I'm trying to translate the 4 missing ones in FR, starting with the smallest  ;) .
How can I locate where the string is actually used to verify if I have the correct meaning ?

**Comment by JasonBarnabe** [comment]
You can search this repo for the key, but that's a little technical. If you can't figure it out, I can tell you.

**Comment by Procyon-b** [comment]
I'll try to search the repo.
I can even download the code and search locally (total commander built-in search is quite good at it).

**Comment by Procyon-b** [comment]
While browsing in FR, I see that the window's title for the update page is not translated ("Post new version of ...").
I don't see any reference in `greasyfork.yml`

I have translated several items. Do I have to push the modifications, or is it automatic?

**Comment by JasonBarnabe** [comment]
> While browsing in FR, I see that the window's title for the update page is not translated ("Post new version of ...").
I don't see any reference in greasyfork.yml

This was missing, I've added it as an available string to translate.

> I have translated several items. Do I have to push the modifications, or is it automatic?

Neither, it's a command I have to run. I've done it now. Thanks!

**Comment by Procyon-b** [comment]
>> I have translated several items. Do I have to push the modifications, or is it automatic?
>>
> Neither, it's a command I have to run. I've done it now. Thanks!

I meant on transifex. I didn't know if the site kept my modification as a draft, or if it was available to you as soon as it was saved.

It's normal that greasyfork doesn't apply modifications immediately. It would be open to abuse.

**Comment by Procyon-b** [comment]
Unrelated to the initial issue:

An element appears in the untranslated list.
After looking in the source code to locate the page where the text is used, it appears that a french version is already live on the site. Indeed, the history (which appear below my browser viewport) shows 2 older versions.

The text can be found by searching for `"To use user scripts"`

I don't know what to do here. I'll let you fix it (if there is something to fix).

**Comment by JasonBarnabe** [comment]
That string was recently updated, which is why it shows as untranslated. I haven't synced since the English text was changed, so the old text is still appearing on the site.

**Comment by Procyon-b** [comment]
Ok, I'll check and see where is has been modified.
