### ISSUE TITLE
"This script is unavailable to other users until it is reviewed by a moderator."

### ISSUE THREAD

**Issue by darkred** [JasonBarnabe/greasyfork#753]
I updated this script [GreasyFork Bullshit Filter](https://greasyfork.org/en/scripts/12179-greasyfork-bull-filter) a couple of times these days (the diff is just [a few lines](https://greasyfork.org/en/scripts/12179-greasyfork-bull-filter/diff?v1=832301&v2=820385) )
and unfortunately I made a mistake twice in the version bump:
*I use the date as version, like I do with the [other variation](https://greasyfork.org/en/scripts/13514-greasyfork-bull-filter-for-ts-citrus-gfork) that I maintain*
I went from 2019.12.5 --> 2020.30.7 --> 2020.30.7.1 --> 2020.7.31
i.e notice the `30.7` (1st mistake) --> `30.7.31` (continuing the mistake) which I eventual fixed as `7.31`.

But now in the script's page I get 
`This script is unavailable to other users until it is reviewed by a moderator.` ([screenshot](https://user-images.githubusercontent.com/723651/89065268-044c5580-d374-11ea-9c8c-233869f9bc5a.jpg))

Is this caused by my mistake in the version bump?
How can I fix this? *(I'd prefer to continue using the date as version)*

**Comment by JasonBarnabe** [comment]
There's a check on certain keywords because they are especially bullshit-prone. Your filter of this bullshit triggered my filter of this bullshit. I've marked your script as approved, so it won't get flagged again.

**Comment by darkred** [comment]
Thank you.
