### ISSUE TITLE
When the user has set the notifications to "Get an email for new discussions on your scripts or when those discussions get new comments`, the "Notify me of any replies" checkbox to be ticked by default

### ISSUE THREAD

**Issue by darkred** [JasonBarnabe/greasyfork#756]
*(continuing issue #707)*

I'd like to make a suggestion:

when the user has set the notifications as `Get an email when discussions are posted on your scripts or when those discussions get new comments` ([screenshot](https://user-images.githubusercontent.com/723651/89061691-d49a4f00-d36d-11ea-879b-925444a5e8bb.jpg))
then, in such discussion pages that have got new comments,
the `Notify me of any replies` checkbox to be ticked by default, because it's effectively enabled :
![2020-07-31_203915](https://user-images.githubusercontent.com/723651/89061961-4e323d00-d36e-11ea-949b-7b08f59bcc47.jpg)

**Comment by JasonBarnabe** [comment]
Now showing text instead of the checkbox.

**Comment by darkred** [comment]
Thanks a lot.
