### ISSUE TITLE
password reset token expired

### ISSUE THREAD

**Issue by nathgit** [JasonBarnabe/greasyfork#760]
I forgot my password so I had to send a password email. when I clicked on the link in the email I got to the screen to enter a new password, but after pressing the button to reset it gives an error that the token has expired. I opened the email & clicked on the within a minute so obviously it shouldn't be expired. Whats wrong?

**Comment by JasonBarnabe** [comment]
I tried it just now, worked fine for me.

There's a 6-hour limit between when you request the reset and when you did (when you receive the email is irrelevant). Did you do this within 6 hours of the initial request?
