### ISSUE TITLE
🔍Support index/search database for second-level host-domain

### ISSUE THREAD

**Issue by dnknn** [JasonBarnabe/greasyfork#762]
mentioned at #761 have been , just open a new issue to request.

- ### 💥 Current issue: 
![208_07035145](https://user-images.githubusercontent.com/10995302/89576084-55bb7f80-d861-11ea-9977-ede9ad4b8e74.png)

Currently `Greasyfork.org` can only search for first-level domain names. `google.com`
But can not support search  for second-level domain names. `translate.google.com`

  　by-site/|　
---|---
https://greasyfork.org/en/scripts/by-site/google.com |✔️
https://greasyfork.org/en/scripts/by-site/translate.google.com|❌

You only want to search for scripts under specific domains, e.g. `translate.google.com` 
if you search  `google.com`, the scope is very wide, it is difficult for you to pinpoint. 
https://greasyfork.org/en/scripts/by-site/google.com?filter_locale=0

So in desperation, user can only barely use `Code Search`(Full text search),
https://greasyfork.org/scripts/code-search?c=translate.google.com
Full text search is also not good, because the search results are not necessarily accurate.

mentioned at #761

----

- ###  Expected behavior: 
can  `https://greasyfork.org/scripts/by-site/`aaa.bbb.com` `

**Comment by jixunmoe** [comment]
Could you please report issues without emojis? I find it hard to read & follow...

---

请问能否提交不含 Emoji 的报告？大量使用彩色的表情符号让问题报告变得难以阅读，而且容易打断思路。

**Comment by dnknn** [comment]
Sorry, you are right. I re-edited and updated the optimization.

**Comment by knoajp** [comment]
I love your visualized presentation.
The issue sounds quite reasonable and I suppose it is rather easy to update.

But actually I often use google site specific search like this:
https://www.google.com/search?q=translate.google.com+site:greasyfork.org

It's not convenient for listing all of registered scripts, but works enough for searching usable scripts.

**Comment by dnknn** [comment]
There is a professional term called `Domain` and `Subdomain`
