### ISSUE TITLE
Search for discussions

### ISSUE THREAD

**Issue by JasonBarnabe** [JasonBarnabe/greasyfork#768]

**Comment by mwisnicki** [comment]
A simple implementation might be a text input on the right that opens https://www.google.com/search?q=inurl:https://greasyfork.org/en/discussions/$category+$searchterms

**Comment by Geeyun-JY3** [comment]
And feedback of a script.

**Comment by JasonBarnabe** [comment]
Done in 5563e9d486fa472d25786cf33f24c838dd86b667.
