### ISSUE TITLE
Proposing Additional Rating Option

### ISSUE THREAD

**Issue by toddwc** [JasonBarnabe/greasyfork#781]
I propose an additional rating: "**Great**."

It includes the description for "Good" — "script works" — but expands on it by adding "**and is especially useful**."

So:

`Great - script works and is especially useful`

**Comment by JasonBarnabe** [comment]
What benefit would this bring?

**Comment by JasonBarnabe** [comment]
The ratings are deliberately kept to have a minimum number of options. I didn't want to see complaining that they got "only" 4 stars out 5.

I don't think this provides any additional useful information.
