### ISSUE TITLE
When you click to download any script, 404 error

### ISSUE THREAD

**Issue by jerrynottom0** [JasonBarnabe/greasyfork#783]
When you click to download any script, 404 error

**Comment by JasonBarnabe** [comment]
- Navigated to https://greasyfork.org/scripts/1
- Clicked Install

Prompted to install with Tampermonkey. So works for me.

**Comment by jerrynottom0** [comment]
> * Navigated to https://greasyfork.org/scripts/1
> * Clicked Install
> 
> Prompted to install with Tampermonkey. So works for me.
I do not know why, but today both Tampermonkey or violent monkeys can install all the scripts

**Comment by JasonBarnabe** [comment]
:man_shrugging:
