### ISSUE TITLE
Don't redirect unlisted scripts

### ISSUE THREAD

**Issue by fushihara** [JasonBarnabe/greasyfork#786]
I posted an unlisted script, but since the URL of greasyfork is a sequential number, I can guess it easily.
I could find a script that would be unlisted by manually going back a few numbers in the URL.
(I noticed that unlisted scripts can be judged by the presence or absence of the noindex tag)
I know unlisted doesn't guarantee complete privacy, but this is too loose.
By moving a few lines of code using the javascript fetch function for 1 minute, I was able to discover 14 unlisted scripts.

With similar services such as google document and pastebin, since it is a complicated alphanumeric character, brute force is virtually impossible.
If you find it difficult to change the specifications, please add a warning message to the submission form.

**Comment by JasonBarnabe** [comment]
Unlisted just means "unlisted", as in it won't be listed in search results. This is for scripts that perhaps are under development or are not of use to the general population.

Greasy Fork is not the place for secret scripts. If you want something to be secret, you can host it on Google on Pastebin or wherever.
