### ISSUE TITLE
Mac / Safari Userscript alternative - Userscripts

### ISSUE THREAD

**Issue by asm9855** [JasonBarnabe/greasyfork#789]
On Mac OS, there is an alternative to TamperMonkey. Nice UI, open-source, easily installable and hasn't broken anything on my end thus far.

I'd like to recommend it be added to the greasyfork main page, as an option for userscript manager for Safari.

Mac App/Extension: Userscripts
URL: https://apps.apple.com/us/app/userscripts/id1463298887?mt=12

**Comment by JasonBarnabe** [comment]
Thanks for pointing this out. I've added it.
