### ISSUE TITLE
Automagic Jigidi Solver no more running

### ISSUE THREAD

**Issue by Malex141** [JasonBarnabe/greasyfork#791]
Hi, I am new here and not sure about that is the right way to support a problem.
But I will try it:

Today I got the follow message:
Automagic Jigidi Solver disabled!
Jigidi has updated to v3.1824
but solver supports v3.1818
Try updating the userscript and then try again.

The last update is not running with Jigidi v3.1824

**Comment by JasonBarnabe** [comment]
You need to post this as feedback on the script you installed. This repo is for Greasy Fork itself.
