### ISSUE TITLE
How to inject styles into iframe generated by a chrome extension

### ISSUE THREAD

**Issue by ErinPo** [JasonBarnabe/greasyfork#793]
The Chrome extension creates an iFrame like so:

`<iframe src="chrome-extension://okjpocelpnlfdi/app.html"></iframe>`

I tried to match it in Tapermonkey v4.10 using:

// @match  chrome-extension://*
// @match chrome-extension://oknpjjbmpnndlpmnhmekjpocelpnlfdi/app.html

but the script never gets triggered. Does anybody know how to get it to work?

**Comment by eight04** [comment]
It won't work. You can't modify extension pages which belong to other extensions.

**Comment by JasonBarnabe** [comment]
This is not the place to ask. You can try the Greasemonkey/Tampermonkey/whatever repo, or https://greasyfork.org/en/discussions.
