### ISSUE TITLE
Notification received in the language of the poster

### ISSUE THREAD

**Issue by Procyon-b** [JasonBarnabe/greasyfork#794]
I have received today a notification of a reply in a feedback (not my script). The guy, a russian, replied in english, but here is how the notification looks:

Subject: `В обсуждении Отзыв на Better Google на Greasy Fork был добавлен комментарий.`
```
В обсуждении 'Отзыв на Better Google' на Greasy Fork пользователь 'K... L...' добавил следующий комментарий:

---
I apologize, only today I got [snip]
---

Вы можете ответить на него по адресу https://greasyfork.org/scripts/[snip].

Вы получили это уведомление, потому что подписаны на это обсуждение. Вы можете отписаться по адресу
[snip]
```

**Comment by JasonBarnabe** [comment]
What is your preferred locale on https://greasyfork.org/en/users/edit ? In the absence of a preferred locale, it will send in the locale of the person who posted the comment.

**Comment by Procyon-b** [comment]
No preferred locale selected yet.
It seems that I'm bothering you a lot for nothing recently.  ;)

**Comment by JasonBarnabe** [comment]
I've made it set the preferred locale on user creation to the one the user was using when they registered. Doesn't help existing users but should reduce problems in the future. Thanks for the report.

**Comment by Procyon-b** [comment]
No problem.
It's pure logic (when I think about it now). It's in the order: "preferred language" if one is set, or "browser language header". And since notifications have no connection to the browser (and its language)...

**Comment by knoajp** [comment]
If I set preferred locale to Japanese, I receive every emails in Japanese. It's ok, fine.
But I sometimes want to check my script description in other language, but now I failed it, because of auto-redirecting to Japanese view.
So I set it back to no locale. It's not a big issue for me, okay. 😅

**Comment by JasonBarnabe** [comment]
If you use the drop-down in the top-right, you can check other languages. It adds an extra parameter that makes it not send you to your locale.

**Comment by knoajp** [comment]
I see.

I serve language switcher links on top of the description for both users and my own convenience.
https://greasyfork.org/en/scripts/31256-google-search-various-ranges

Okay, it's fine. I prefer not to set locale.

**Comment by Procyon-b** [comment]
Add `?locale_override=1` to your links if you want users with locale to use these links.

**Comment by knoajp** [comment]
Thank you.
That should help it, but I feel a bit dirty on such URLs. And most of my concern is for newcomers on GreasyFork, so they might have no locale settings and "clean" URLs just work. 😀
