### ISSUE TITLE
script list page on mobile device is wrong

### ISSUE THREAD

**Issue by imhsz** [JasonBarnabe/greasyfork#795]
Now, the style of the script list page on the phone is wrong: the width is calculated incorrectly
![Screenshot_2020-09-26-00-09-09-272_com ppcross browser](https://user-images.githubusercontent.com/3312454/94290266-8a5bd580-ff8c-11ea-93ac-56d8e9cbb186.jpg)

**Comment by JasonBarnabe** [comment]
Fixed, thanks for reporting.
