### ISSUE TITLE
Add a `quote comment` buttom beside each comment

### ISSUE THREAD

**Issue by Geeyun-JY3** [JasonBarnabe/greasyfork#799]
I remember Greasy Fork had it before.

**Comment by JasonBarnabe** [comment]
Done. It only deal with text, but it understands selection.

**Comment by Geeyun-JY3** [comment]
> it understands selection

Just like GitHub?

**Comment by JasonBarnabe** [comment]
Works fine for me (Firefox). Note that your selection can't extend outside of a single comment.

![quote](https://user-images.githubusercontent.com/583995/101269420-5cd19c00-3734-11eb-8432-bbf48e6b3459.gif)

**Comment by Geeyun-JY3** [comment]
My bad. It related to external userscript🤦‍♂️.

**Comment by Geeyun-JY3** [comment]
And it seems that there is a linebreak issue (I really don't know how to describe it, just see the pictures).
![](https://user-images.githubusercontent.com/49396421/101269536-becce880-37aa-11eb-801d-e2fce43a5b00.gif)
![image](https://user-images.githubusercontent.com/49396421/101269544-ca201400-37aa-11eb-9996-1a68a730b6cf.png)

**Comment by Geeyun-JY3** [comment]
![](https://user-images.githubusercontent.com/49396421/101269631-d5c00a80-37ab-11eb-8cce-c519ab51e3bc.gif)
Two new line?
![](https://user-images.githubusercontent.com/49396421/101269651-220b4a80-37ac-11eb-9a55-5a56bf6a062b.gif)

**Comment by JasonBarnabe** [comment]
- [ ] Full-comment quote is dropping line breaks (because it's using textContent that doesn't see them)
- [ ] Markdown with selection-comment keeps line breaks, but doesn't properly prefix each line
- [ ] Nested comments are not properly handled

**Comment by JasonBarnabe** [comment]
I've made a number of improvements. The shortcomings right now (that I don't intend to fix anytime soon):

- Selection-quote will do text only, no markup
- Quoting in Markdown will only do the markup for quotes, not anything else.
