### ISSUE TITLE
Exposing style version from Stylus

### ISSUE THREAD

**Issue by tophf** [JasonBarnabe/greasyfork#800]
Stylus is [ready to do it](https://github.com/openstyles/stylus/pull/1051) but I don't like the `window.external` approach as adding a DOM script just to communicate with a page is quite a roundabout and hackish way which may be broken by other extensions that block scripts.

So, I wonder if you would please please implement the detection via standard DOM `CustomEvent` messaging or `window.postMessage` that you implemented on USO years ago?

**Comment by JasonBarnabe** [comment]
@tophf If this was to work via `postMessage`...

- What `origin` would be set to for events triggered by Stylus?
- We give Tampermonkey name and namespace. Would Stylus just be looking at the URL of the page? Note that URLs on Greasy Fork can change if the script/style is renamed. 
- I'd expect the `data` object to contain the installed version.
- It would also be useful to know that Stylus is installed even if the particular style is not.

**Comment by tophf** [comment]
> origin

Same as the page because we would communicate via extension's content script in the current page.

> name and namespace

Yes. Stylus also uses them internally. My current PR is wrong as it looks at the `id` of the URL so let's disregard it.

> to know that Stylus is installed

The [idea](https://github.com/openstyles/stylus/issues/842) was that Stylus would expose itself only when the style is installed. What benefits would GF provide to the user if it knows Stylus (or any similar css extension) is present? I'd say none as you need to show both installer buttons anyway (for js and css).

**Comment by JasonBarnabe** [comment]
> What benefits would GF provide to the user if it knows Stylus (or any similar css extension) is present?

I want to show different UI for people who don't have any script/style manager installed that makes it clearer what they have to do. For those that do have one installed, then I just present an install button like how it is now.

**Comment by tophf** [comment]
Well, I guess it's fine.

**Comment by JasonBarnabe** [comment]
I've put in an [initial implementation](https://github.com/JasonBarnabe/greasyfork/blob/master/app/assets/javascripts/versioncheck.js#L141-L168). It wants a data object with:

- type: style-installed
- version

And it'll just log to console whether it'd an upgrade, downgrade, or reinstall.

Undecided on how it would say that it's not installed at all - `version == null `or a different `type`?

**Comment by tophf** [comment]
Maybe `type` should be `style-version` for all messages? It's neutral, not implying that a style is installed.

**Comment by tophf** [comment]
Uhm, wait. I thought there will be a window.postMessage sent to us with `name` and `namespace` so we don't have to download the meta ourselves.

**Comment by JasonBarnabe** [comment]
I'm not sure what the typical process for this, but we can do that.

Now sending a message:
```
{ type: 'style-version-query', name: name, namespace: namespace, url: location.href }
``

and expecting a response as described above.

**Comment by tophf** [comment]
Nice. I've updated the [PR](https://github.com/openstyles/stylus/pull/1051) and it works for me locally. You can [try it](https://github.com/tophf/stylus/archive/gf.zip) as an unpacked extension.

**Comment by JasonBarnabe** [comment]
I've updated the site's JS to relabel the button based on the results. Try it out.

(It's gonna send `null` if the style is not installed, right?)

**Comment by tophf** [comment]
It's `{type: 'style-version', version: undefined}` but that should be fine as long as you compare using `== null` i.e. double-eq.

**Comment by tophf** [comment]
You wanted to change the UI depending on whether Stylus is installed so will you do it soon? Otherwise this issue may be closed.

**Comment by JasonBarnabe** [comment]
That'll be done in #717, but I would need to wait for this change in Stylus to be released and become widespread.

Thanks for making the changes in Stylus to support this!
