### ISSUE TITLE
My script has been maliciously complained by these accounts again, can the administrator handle it?

### ISSUE THREAD

**Issue by cjshtg** [JasonBarnabe/greasyfork#804]
Script address:https://greasyfork.org/zh-CN/scripts/414015-%E7%99%BE%E5%BA%A6%E7%BD%91%E7%9B%98%E7%9B%B4%E9%93%BE%E6%9E%81%E9%80%9F%E4%B8%8B%E8%BD%BD%E5%8A%A9%E6%89%8B

First of all, this script is usable and does not violate any rules of Greasy Fork. I hope that the administrator of the Chinese server will test it personally! But @lizhiwei2020 @sbbdh will report as soon as the script is uploaded!

The administrator can check whether these two accounts are malicious reports as I said. If the script is really not usable, why don't others report them?

The picture below is a speed test of the extremely fast downloading files from the Baidu network disk owned by the script we provided!

**Comment by JasonBarnabe** [comment]
I really don't like deleted scripts getting reposted. Stop doing that.

What was the original script?

**Comment by cjshtg** [comment]
The upload account of the original script has been deleted by the administrator and there is no way to find it.

In addition, my script may have been deleted by myself by mistake. Every time we submit a refutation reason in the script complaint report, we click the delete script button at the bottom instead of submitting the refutation button.

I’m sorry to bother you.

**Comment by cjshtg** [comment]
> I really don't like deleted scripts getting reposted. Stop doing that.
> 
> What was the original script?

The upload account of the original script has been deleted by the administrator and there is no way to find it.

In addition, my script may have been deleted by myself by mistake. Every time we submit a refutation reason in the script complaint report, we click the delete script button at the bottom instead of submitting the refutation button.

I’m sorry to bother you.

**Comment by JasonBarnabe** [comment]
Items are not permanently deleted by administrators. Do you know the email you used originally to post it? I can then look up what scripts and reports there are related to that account.

**Comment by JasonBarnabe** [comment]
In the future, if you disagree with a report, put complete information for moderators to review. If you believe it is deleted by mistake, you can contact me directly. Do not just repost it.

**Comment by cjshtg** [comment]
> 将来，如果您不同意报告，请提供完整的信息供主持人审阅。如果您认为它被误删除，可以直接与我联系。不要只是重新发布它。

Thank you administrator, we will not upload the deleted script again!
