### ISSUE TITLE
Please check my script again and don't close my question without answering it!

### ISSUE THREAD

**Issue by cjshtg** [JasonBarnabe/greasyfork#808]
The script interface has been rewritten, and the account password can be obtained without mandatory attention.

Some time ago, due to our negligent management, all the previously registered accounts were maliciously replaced by others into ordinary accounts. We have discovered this problem, and we will self-check once a day in the future to correct the errors of the accounts in time.

However, the account password is shared, and it is used by a large number of different IPs every day. There may be a risk of account being cancelled. Although we can fix this risk in time, the website stipulates that the script can only be updated once a day, so we will keep one Get the link to update your account and password in real time.

If the administrator feels that the script is still illegal, please let me know clearly. Let me modify it again. After all, the account and password we provided are indeed available.

The function of this script is to display a free SVIP button when the user opens the webpage Baidu Netdisk.

![1 2](https://user-images.githubusercontent.com/73271666/98489756-54d42880-226a-11eb-9308-96f28a0d2c41.png)
![1 3](https://user-images.githubusercontent.com/73271666/98489760-5998dc80-226a-11eb-82c8-416e208fd62a.png)
![1 4](https://user-images.githubusercontent.com/73271666/98489768-60bfea80-226a-11eb-9ee5-92a1c08c076c.png)

Just click on one and a window for obtaining the account password will pop up.

![1 1](https://user-images.githubusercontent.com/73271666/98489774-69182580-226a-11eb-8e2e-fd3f7b741402.png)

**Comment by cjshtg** [comment]
This is the rewritten script
[【百度网盘SVIP超会员账号分享】（每天更新） (1).user.zip](https://github.com/JasonBarnabe/greasyfork/files/5507505/SVIP.1.user.zip)

**Comment by JasonBarnabe** [comment]
I don't want you on Greasy Fork. Go away.
