### ISSUE TITLE
Please improve the download statistics function of grassfork website

### ISSUE THREAD

**Issue by lengyue-ck** [JasonBarnabe/greasyfork#809]
Dear administrator，recently there are scripts frequently brush download, please verify!  If there is a statistical vulnerability, then i hope you can fix it in the fastest time. I suggest you still see if the token generated by the post address is really valid after clicking on the installation script, and check whether your statistical cookies are true and effective, so as to avoid others' malicious brush downloads and violate the balance!  !

**Comment by JasonBarnabe** [comment]
There are countermeasures in place to stop inflated install counts. I know they still happen and I'm working on more countermeasures. The token in the URL **is** validated; the install is not counted if it's not. If you have further ideas, please let me know.

I've deleted all the scripts you posted for being spam/reposts of the same code. If you find more, please report by the site's reporting function and please be specific that it's spam, repeat posts, or whatever. It's difficult for me as I can't read Chinese so it takes longer to notice the same content.

Just having inflating counts is not a reason for me to delete - how can I be sure that it's the author that's doing it and not something built by someone else?

**Comment by lengyue-ck** [comment]
Dear author, first of all, i think that if you count the number of downloads, you should count the ip address. of course, you should not exclude individuals from using proxy ip. secondly, you can count the mac address and judge by mac code.  Physical mac address: this type of mac address uniquely identifies a terminal on the ethernet, the address is the world's unique hardware address;  The mac address is written to the chip, which is generally read-only and cannot be changed.  But maybe the user falsify the mac address, which needs you to identify, and i haven't done the function of user statistics, and I  can only help you so much.  In addition, the registration function of our website does not check the mailbox, users can register successfully by entering any mailbox, which leads to their malicious registration. 
Although you have , that is, send verification code function to verify that mailbox really belongs to the person .Only my personal advice ,can be appropriate  reference.

**Comment by JasonBarnabe** [comment]
- Counts are already unique by IP
- I don't think web content has access to a device's MAC address.
- Logins are not required to install scripts, so additional verification of users wouldn't do anything. Requiring the user to be logged in to count would be technically possible, but I think that would not be good as it would eliminate almost all valid stats as well.

Thanks for the suggestions, but I don't think any of that is workable.
