### ISSUE TITLE
Can you check if this script was deleted by mistake!

### ISSUE THREAD

**Issue by xazbushr** [JasonBarnabe/greasyfork#810]
Original account email: cjshtg0@163.com

Recently, the script on the shelves has been complained as a junk script and deleted by the administrator!

But can the administrator please review this script again, this is not a junk script, and the blog address we put in the script usage tutorial does not require mandatory attention to use. We also stated at the bottom of the QR code of the blog that you can use the script without following the blog.

In addition, we only put the blog address in the script usage tutorial, and did not put any blog address when the script was used!

If these are not compliant, can you ask the administrator to re-list our script? We immediately delete all blog addresses in the script usage tutorial.

After all, the number of installations and users of our script has reached 70,000 times, and there are many good comments among them. If the administrator deletes our script only by complaints from a few users, our hard work during this period of time will be completely wasted. In theory, our script does not violate the rules of Greasy Fork in principle!

![1](https://user-images.githubusercontent.com/74693691/99616141-a5f8cf00-2a57-11eb-9586-75509fa2fe00.png)

![2](https://user-images.githubusercontent.com/74693691/99616161-aee9a080-2a57-11eb-8822-2a7cca3c4034.png)

[网盘直链下载助手.user.zip](https://github.com/JasonBarnabe/greasyfork/files/5564106/user.zip)

**Comment by JasonBarnabe** [comment]
This was not an accident. It will not be reinstated.
