### ISSUE TITLE
When did Greasy Fork start allowing these junk scripts to be listed?

### ISSUE THREAD

**Issue by oome112** [JasonBarnabe/greasyfork#811]
Dear administrator, when did this kind of junk scripts start to be allowed on Greasy Fork?

1.
https://greasyfork.org/zh-CN/scripts/416042

![1](https://user-images.githubusercontent.com/74694783/99618171-d2164f00-2a5b-11eb-8b8c-60adb0ac5b65.png)

After I installed this script, I found that I need to follow their blog to get the password to use the functions in the script. In addition, when I watched the comments, I found that most of the praise methods seem to come from one person. I guess it should be the author's own registered account that maliciously praised the script without being noticed by the administrator!

2.
https://greasyfork.org/zh-CN/scripts/407980

![sp201119_114027](https://user-images.githubusercontent.com/74694783/99618297-0be75580-2a5c-11eb-8843-7121260eb3ce.png)

This script is even more malicious. After installing this script, there is only a pop-up interface and no one has any functions. I only need to follow their blog address to get the account. Just an account, the script does not provide any functionality. This is a serious violation of the Greasy Fork rules. A script just to allow users to visit a website does not have to be a script, but can be a link.

If the administrator continues to allow such scripts to exist in Greasy Fork, I believe that it will not be long before Greasy Fork will be invaded by most of these junk scripts, and slowly there will be no more users installing scripts from Greasy Fork!

**Comment by JasonBarnabe** [comment]
These should not be allowed on the site. I have deleted them.

If you find more, please report them and provide as much information as you did here. Not all moderators can read Chinese so it's sometimes difficult to judge, but what you said here is clear.
