### ISSUE TITLE
Respect the administrator, report another junk script!

### ISSUE THREAD

**Issue by oome112** [JasonBarnabe/greasyfork#812]
https://greasyfork.org/zh-CN/scripts/409791

![3](https://user-images.githubusercontent.com/74694783/99624044-65ee1800-2a68-11eb-8416-8f829a935df7.png)

This script is very similar to some previously uploaded scripts. After installation, you need to subscribe to their blog to get the password before you can use it.

At the same time, there is no pre-installation prompt in the script description page, and the blog that needs to be subscribed can use the script!

**Comment by JasonBarnabe** [comment]
Deleted, thanks for reporting.
