### ISSUE TITLE
Report another junk script

### ISSUE THREAD

**Issue by code4me20** [JasonBarnabe/greasyfork#815]
https://greasyfork.org/zh-CN/scripts/409668

![image](https://user-images.githubusercontent.com/74841265/99890052-4b00eb00-2c96-11eb-900f-a54206037564.png)

This script is very similar to some previously deleted scripts. After installation, you need to subscribe to their blog to get the token before you can use it.

**Comment by JasonBarnabe** [comment]
This has been deleted, thanks.
