### ISSUE TITLE
Dear administrator, is this method of reducing server costs allowed?

### ISSUE THREAD

**Issue by oome112** [JasonBarnabe/greasyfork#818]
Dear administrator!

Recently I uploaded a script in Greasy Fork that can be used on the baidu.com website, and this script can indeed be used. The main function can be to remove the forced jump to the download request in the client when downloading files from this website of baidu.com, and then directly use the browser or IDM to download the file directly.

However, based on user feedback, the download speed of the browser needs to be increased. But the rules of the baidu.com website have been changing, and the download speed problem has always been a headache.

Later, I thought of a way to register some member accounts of the baidu.com website to share with script installation users, which is free to use. But in order to prevent the member account of baidu.com from being cancelled, it is necessary to change the password frequently!

In this way, we need to create a dedicated server to bear, and the cost of creating a server is too expensive for us to bear.

Therefore, it is hosted on other software servers for users to obtain. This server is similar to the way to subscribe to Twitter groups! It is also similar to joining QQ group in other script description pages!

At the same time, I only added the jump address in the script description page, and did not directly add the jump address in the script interface.

We have tried our best to let script installation users decide whether to use it according to their needs.

I wonder if this method is allowed?

**Comment by JasonBarnabe** [comment]
Sorry, I'm not sure I understand what you're doing. Why would you need to create a server to deal with changing passwords?

**Comment by oome112** [comment]
Because the password is changed, the old password cannot be used, and the new password needs to be updated in time. At the same time, the account is shared, and a large number of IPs are used every day, and some users may maliciously log out the account or change the password, so it may need to be updated five to six times a day.

That's why a server is needed, and then create a timely update sharing page.

**Comment by oome112** [comment]
To put it simply, we provide functions other than scripts in the script description page, but these functions need to be subscribed to a Twitter group to obtain them. I wonder if this method can be allowed?

**Comment by JasonBarnabe** [comment]
I don't understand why you would use Twitter though. There are many services that would let you share this (like GitHub or Pastebin or whatever), and your script could just pull the latest from there.

What you're describing with a Twitter group is explicitly against [the rules](https://greasyfork.org/en/help/code-rules):

> Scripts must not require users to perform an unrelated action, such as sending a payment, subscribing to a channel, joining a group, or liking a page, for the script to be functional, in full or partially.

**Comment by oome112** [comment]
Okay thank you!
