### ISSUE TITLE
Why these evil scripts be allowed on Greasy Fork? 

### ISSUE THREAD

**Issue by cyclone542** [JasonBarnabe/greasyfork#820]
Dear administrator, Why these evil scripts be allowed on Greasy Fork? 

https://greasyfork.org/zh-CN/scripts/409668

What do you think of a script whose function is cheating in online exam? It would fill the correct answers automatically and get full scores in exam. This is so evil ! It's unfair to the students who take the exams through their own efforts.

Worst of all, when I searched related keywords on GF, hundreds of similar cheating scripts displayed. I think Greasy Fork has been invaded by cheating scripts and gradually becomes an online repository of exam cheating tools.

If it's difficult for the moderators to read Chinese, I would like to translate these scripts' descriptions to English, thus you can judge it.

**Comment by JasonBarnabe** [comment]
This script has been deleted, albeit for different reasons.

We take no side on the functionality of scripts. They are only removed for violating one of the rules - https://greasyfork.org/en/help/code-rules
