### ISSUE TITLE
Is this kind of scripts considered as abusive?

### ISSUE THREAD

**Issue by jixunmoe** [JasonBarnabe/greasyfork#824]
See: https://greasyfork.org/en/scripts/416941

It injects another script hosted on GF and use it as a normal script to be injected to the page.
I'm guessing the intention is to "have always updated version of the script".

Do we allow this kind of behaviour? If not, maybe we can block it by checking origin/referrer header?

```
// Metadata + comments snipped...

if (document.querySelector("script#jiangxiaobai-sobj")) {} else {
	let dobj = document, sobj = dobj.createElement('script');
	sobj.setAttribute('src', 'https://greasyfork.org/zh-CN/scripts/413058.js');
	dobj.head.appendChild(sobj);
}
```

**Comment by JasonBarnabe** [comment]
> Scripts must not check for updates at a rate higher than once per day. Note that most user script managers will handle automatic updates, so doing it in the script is unnecessary.

Wouldn't ban them for it, but ask them to change it. This rule is more to reduce server load.

**Comment by jixunmoe** [comment]
Understood.

**Comment by jixunmoe** [comment]
I'm not sure if GF had caching enabled; since this is always pointing to the same address, with caching on it shouldn't cause too much load.

**Comment by JasonBarnabe** [comment]
There can't be long caches on `.user.js` URLs, otherwise updates wouldn't work at all.
