### ISSUE TITLE
Respect the administrator, report another spam script, and belong to the second illegal upload!

### ISSUE THREAD

**Issue by oome112** [JasonBarnabe/greasyfork#825]
https://greasyfork.org/zh-CN/scripts/416948

![sp201201_140626](https://user-images.githubusercontent.com/74694783/100703391-6a0e2400-33de-11eb-98f4-b568ed56974c.png)

The initial installation script opens the user interface, there is no explanation that you need to subscribe to their blog to use it!

But when you click the red button, their blog QR code will pop up. You need to subscribe to their blog and get a token to use it!

![sp201201_140817](https://user-images.githubusercontent.com/74694783/100703526-ac376580-33de-11eb-99dc-bfccf15f019b.png)

Before this script, I reported it to the administrator. This time, the uploader modified the interface and published it again.
But you still need to pay attention to their blog to get the token to use the script!
I think the script provider is a little disgusting! And the script's praise seems to belong to a person's spoken language, a large number of accounts are not certified by the mailbox account!

**Comment by JasonBarnabe** [comment]
Please report this script on Greasy Fork itself so the author has a chance to refute what you say.

https://greasyfork.org/en/scripts/416948-%E7%99%BE%E5%BA%A6%E7%BD%91%E7%9B%98%E7%AE%80%E6%98%93%E4%B8%8B%E8%BD%BD%E5%8A%A9%E6%89%8B-%E7%9B%B4%E9%93%BE%E4%B8%8B%E8%BD%BD%E5%A4%8D%E6%B4%BB%E7%89%88/report
