### ISSUE TITLE
Suggestion: to be able to delete your own discussions and comments

### ISSUE THREAD

**Issue by darkred** [JasonBarnabe/greasyfork#826]
Sometimes you may submit a discussion/comment, where you shortly after change your mind, or you just posted it too early by mistake.
I believe it would be useful to be able to delete your own discussion/comment
for a short time, e.g. 5 mins, provided that there hasn't been any reply yet.
This way you won't have to bother a mod to ask him to delete it for you.

It has happened to me quite a few times, and I wished I had the ability to do it myself, just like in GitHub discussions.

Thank you

**Comment by JasonBarnabe** [comment]
Done.

**Comment by darkred** [comment]
Thanks a lot !
