### ISSUE TITLE
Support having multiline code block inside `<details>` markdown tag

### ISSUE THREAD

**Issue by darkred** [JasonBarnabe/greasyfork#827]
I've tried adding something like the following in a discussion I started,

    <details>
    <summary>Details</summary>
    
    ```javascript
    function msg(){  
     alert);  
    }  
    ```
    </details>

and it was rendered concatenated as a single line, when expanded:
![2020-12-01_210746](https://user-images.githubusercontent.com/723651/100785446-5207c600-3419-11eb-9d08-bc2c2ad934e4.jpg)

**Comment by JasonBarnabe** [comment]
Looks like you can't put markdown inside HTML tags.

```
<div>
**not bold**
</div>

**bold!**
```

**Comment by JasonBarnabe** [comment]
This is https://github.com/vmg/redcarpet/issues/13. If they fix it, I'll update, but otherwise nothing to do in this repo.

**Comment by tophf** [comment]
Could you switch to whatever github itself uses, apparently `kramdown`? Lots of developers got used to its behavior on github. In particular gthub's handling of line breaks within same paragraph is arguably more convenient: they're preserved because that's what most people would expect.
