### ISSUE TITLE
Dear administrator, is it allowed to add advertisement in script description page?

### ISSUE THREAD

**Issue by yizhixiaohaha** [JasonBarnabe/greasyfork#829]
Dear administrator, is it allowed to add such a QR code advertisement in the script description page uploaded? It has nothing to do with the script running. It is just my blog address. Interested script installation users can subscribe to my blog address by scanning this QR code!
If it can be allowed, I will directly explain that this is an advertisement, there is no need for forced subscription, and it has nothing to do with the script running!

Similar to this description:

More mobile phone computer black technology, you can focus on WeChat official account!
This QR code has nothing to do with script running. You can use script without subscription!
![qrcode_for_gh_c322c5b5fc84_258](https://user-images.githubusercontent.com/75403660/100954831-571b6100-3550-11eb-8eae-bde3634e00ad.jpg)

**Comment by JasonBarnabe** [comment]
This is allowed, but you risk raising the suspicion that you need to join the account to use the script.
