### ISSUE TITLE
账号莫名奇妙的就被🈲封了？也不告知原因？

### ISSUE THREAD

**Issue by ilh-github** [JasonBarnabe/greasyfork#832]
账号莫名奇妙的就被🈲封了？也不告知原因？我第一个账号被禁封就算了。刚刚有注册了一个还没两天呢，又给我🈲封了？
什么玩意，谁还敢把东西放在你这个东西里面？？？？
无语了，好歹你给一个原因啊。

**Comment by jixunmoe** [comment]
> 该脚本已被管理员删除且不能被其他用户所访问。删除的原因是：“Requires token”。

```
        , token: '' // 捐助用户可以使用上传选项功能，更精准的匹配答案，此处填写捐助后获取的识别码
```

> 脚本不得要求用户执行无关操作，例如**支付**、订阅频道、加群、或点赞，来使脚本**部分**或全部功能可用。

**Comment by JasonBarnabe** [comment]
:arrow_up:

**Comment by ilh-github** [comment]
TimBL_ 为什么也封了？原因呢？token我去了啊。脚本是免费的，不行你自己试试。


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "JasonBarnabe/greasyfork"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月9日(星期三) 上午6:43
收件人:&nbsp;"JasonBarnabe/greasyfork"<greasyfork@noreply.github.com&gt;;
抄送:&nbsp;"1978805993"<1978805993@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [JasonBarnabe/greasyfork] 账号莫名奇妙的就被🈲封了？也不告知原因？ (#832)





 
⬆️

**Comment by ilh-github** [comment]
是在不理解，我都注册了三个用户了，都没有可以使用的邮箱去注册完了，想在您的网站上发布一个东西就折磨难吗？


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "JasonBarnabe/greasyfork"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月9日(星期三) 上午6:43
收件人:&nbsp;"JasonBarnabe/greasyfork"<greasyfork@noreply.github.com&gt;;
抄送:&nbsp;"1978805993"<1978805993@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [JasonBarnabe/greasyfork] 账号莫名奇妙的就被🈲封了？也不告知原因？ (#832)





 
⬆️

**Comment by JasonBarnabe** [comment]
It's not hard to post something. We posted [this](https://greasyfork.org/en/help/code-rules).
