### ISSUE TITLE
Message system (pm) no longer works (`404 - page not found`)

### ISSUE THREAD

**Issue by darkred** [JasonBarnabe/greasyfork#833]
I've noticed that e.g. https://greasyfork.org/en/forum/messages/inbox
or links from email notifications like `https://greasyfork.org/en/forum/messages/xxx#Message_yyyyy`
all result in "404 - page not found."

**Comment by JasonBarnabe** [comment]
That's the old Vanilla-based forum. It's gone and not coming back.

You can use the new Conversations feature from your user page.

**Comment by darkred** [comment]
Thank you very much for the quick reply!

**Comment by darkred** [comment]
> It's gone and not coming back.

It's bad though that the old messages have not been maintained in the new Conversations:
in my case https://greasyfork.org/en/users/2160-darkred/conversations appears empty, as I haven't sent any pm recently (last was in March).
I suppose it was not possible for you to restore the old messages in the new system? Or not alllowed for privacy reasons? Just asking, because I had sent quite a few pm's in the past all these years.

**Comment by JasonBarnabe** [comment]
I didn't judge it to be worth my time to restore them.

**Comment by darkred** [comment]
I believe it's useful to have the old messages:
as a user in Greasyfork since 2014, I have sent quite a few pm's to various people.
I'd like to see with whom I contacted in the past, on what subject (to avoid repeating in the future),
and to see his responses (to see whether he ever replied, if he was kind/friendly).
It's hard to recall my pm interactions from years back, unfortunately the memory fades over time.

**Comment by jixunmoe** [comment]
> I believe it's useful to have the old messages:
> as a user in Greasyfork since 2014, I have sent quite a few pm's to various people.
> I'd like to see with whom I contacted in the past, on what subject (to avoid repeating in the future),
> and to see his responses (to see whether he ever replied, if he was kind/friendly).
> It's hard to recall my pm interactions from years back, unfortunately the memory fades over time.

Might be a good idea to crawl through emails - if you haven't deleted them yet

**Comment by JasonBarnabe** [comment]
If you really need them, I can also pull them from the DB. That'd be much easier than writing a data migration.

**Comment by darkred** [comment]
@jixunmoe Thanks but unfortunately some of them have been deleted, plus there were cases where the other never responded.

@JasonBarnabe Yes please. May I pm you my email via Conversations ?

**Comment by JasonBarnabe** [comment]
Emailed your history to you.

**Comment by darkred** [comment]
Thanks so much for this, great!
