### ISSUE TITLE
Suggestion: HTML/Markdown toolbar 

### ISSUE THREAD

**Issue by darkred** [JasonBarnabe/greasyfork#834]
What I'd love to have in the site's new layout is a HTML/Markdown toolbar,
to assist in writing in Greasyfork, just like GitHub offers for Markdown.

---

For reference, there is a script by wOxxOm, [Markdown toolbar for GF and USO](https://greasyfork.org/en/scripts/6779-markdown-toolbar-for-uso) that offered exactly that and more, in the old layout.
<details>
<summary>screenshots</summary>

![](https://i.imgur.com/c38YCDU.png)

![](https://i.imgur.com/wjfpYY2.png)

</details>

It applied literally everywhere in the site, in the script area, in the forum, in every textarea.
Unfortunately the author is not interested in updating it for the new GR layout, and he renamed + removed all old Greasyfork `@include` rules off the script in its [latest version](https://greasyfork.org/en/scripts/6779-markdown-toolbar-for-uso/diff?v1=845308&v2=179573).

I tried modifying it myself to make it work, but I find it difficult to manage this.

**Comment by JasonBarnabe** [comment]
I'd be open to something like this (maybe combined with #798), but I'd prefer something already built that I could just integrate.

**Comment by darkred** [comment]
Just wanted to share that I managed to make the [Markdown toolbar](https://greasyfork.org/en/scripts/6779-markdown-toolbar-for-uso) script work with the new GF layout:  
it was just changing 2 lines in version [1.47](https://greasyfork.org/en/scripts/6779-markdown-toolbar-for-gf-and-uso/code?version=179573):

from  
`var inForum = location.href.indexOf('/forum') > 0;` to  
`var inForum = location.href.indexOf('/discussions') > 0;`

and from  
`if (t = wrapper.querySelector('textarea[id*="additional-info"]')) {` to  
`if (t = wrapper.querySelector('textarea[id*="additional-info"], textarea[id*="conversation_messages_attributes_0_content"], textarea[id*="discussion_comments_attributes_0_text"], textarea[id*="comment_text"]')) { `

plus added

```
// @include           https://greasyfork.org/*discussions/*
// @include           https://greasyfork.org/*/conversations/*
```

Here it is:
https://gist.github.com/darkred/1c76e52a997f93b0df5495aebd25c456

I've pm'ed wOxxOm about it.

&nbsp;

Maybe you'd like to incorporate the script to the site code, @JasonBarnabe ?

**Comment by darkred** [comment]
Unfortunately, the script needs a lot more changes in order to work in the new layout.
Sorry for my impatience to share it with you as ready.

**Comment by decembre** [comment]
No solution yet ?

**Comment by JasonBarnabe** [comment]
I don't think this is going to happen. I actually like the small barrier to special formatting. Makes things tend toward being plainer.
