### ISSUE TITLE
users' list and RTL writing

### ISSUE THREAD

**Issue by Procyon-b** [JasonBarnabe/greasyfork#836]
I don't know if it's normal or not, but I've seen this today.
The user's name and the number of scripts are reversed (like in RTL direction), but the word "script" is not.
And aren't japanese and chinese writings also RTL?  (I only know about mangas, so, IDK)

![GF-userlist](https://user-images.githubusercontent.com/40043075/101919030-65115780-3bca-11eb-8530-65004d7469a1.png)

user is 715740

**Comment by JasonBarnabe** [comment]
See also #460.

Japanese and Chinese are not RTL.

**Comment by Procyon-b** [comment]
I wasn't sure about japanese & chinese. When reading mangas in the original format you start with the last page (for us in the West), on each page you read the drawing from right to left, and the order of priority of the captions is from right to left. But I don't know anything about the writing itself (only reading in french).

For the case above, the locale is english. Except for the name itself, isn't it logical for me to see everything in LTR ?

**Comment by JasonBarnabe** [comment]
> Except for the name itself, isn't it logical for me to see everything in LTR

Totally logical. If you look at the source, you can see this is rendered as any other

```html
<li>
  <a href="/en/users/715741-lukipoi">lukipoi</a> - 0 scripts
</li>
<li>
  <a href="/en/users/715740-%D8%A7%D8%A8%D8%B1%D8%A7%D9%87%D9%8A%D9%85">ابراهيم</a> - 0 scripts
</li>
<li>
  <a href="/en/users/715739-%E9%82%B9%E8%99%8E">邹虎</a> - 0 scripts
</li>
```

If you switch to an RTL language, you can see that presumably that one is the only correct one, and everything else is backwards.

![image](https://user-images.githubusercontent.com/583995/101964775-24b8d600-3bd8-11eb-9407-87751597f1b0.png)

I think this must be the browser doing something "smart" about the bidi text.

**Comment by Procyon-b** [comment]
It could be a browser bug. Most probably related to pages with mixed directions.
I know I've seen one specific with RTL when patching someone else extension:
I needed to list hostnames within a limited width, and I used a RTL div to put the ellipsis in front of the name (hiding the less important part of the hostname). But it failed dramatically (only if RTL is used) if the hostname started with a digit. I had to fix this by putting an hidden char in front of it.

**Comment by JasonBarnabe** [comment]
As far as I can tell, there are some heuristics in the browser to determine what to do with ["weak characters"](https://en.wikipedia.org/wiki/Bidirectional_text#Weak_characters) like punctuation. Adding `unicode-bidi: isolate;` to the user name seems to fix the issue.
