### ISSUE TITLE
Give banned users more info

### ISSUE THREAD

**Issue by JasonBarnabe** [JasonBarnabe/greasyfork#838]
- Why they were banned
- Don't come back

**Comment by jixunmoe** [comment]
Maybe we can also propagate delete reason from report to the script page (for the author to understand what went wrong), or at least include a link to the report?

**Comment by JasonBarnabe** [comment]
> Maybe we can also propagate delete reason from report to the script page (for the author to understand what went wrong), or at least include a link to the report?

Yup.
