### ISSUE TITLE
Add "Open Graph protocol" meta tags in HEAD of HTML

### ISSUE THREAD

**Issue by knoajp** [JasonBarnabe/greasyfork#839]
The Open Graph protocol
https://ogp.me/

with the first thumbnail image of the script.
but, I'm worrying that the current image uploader doesn't care about the order of the images.

**Comment by JasonBarnabe** [comment]
What benefit would this bring?

**Comment by knoajp** [comment]
When greasyfork.org URL is posted on SNS or some Open Graph supported services, the post will get a richer embedded view with the image of the script.

https://warfareplugins.com/open-graph-tags-twitter-cards-rich-pins/
http://zduck.com/2013/open-graph-twitter-cards-and-your-blog/
https://davemateer.com/2019/04/07/Twitter-card-open-graph-site-preview

It doesn't have a huge impact, but I guess not so hard to add this feature, and helps to obtain more interest or view on SNS.

**Comment by JasonBarnabe** [comment]
Added title, URL, and image (if any are provided).
