### ISSUE TITLE
Why does the administrator not deal with this kind of garbage script??

### ISSUE THREAD

**Issue by yizhixiaohaha** [JasonBarnabe/greasyfork#843]
https://greasyfork.org/zh-CN/scripts/418182

This script is obviously a garbage drainage script. I complained twice in the script, and both times were revoked by the administrator!

If the administrator can't understand Chinese and can't visit the Chinese website, can you ask the Chinese administrator to audit the script!

I have installed the script many times, and every time I test whether the script can download Baidu network disk file, but it can not be used. Click the download button for a long time to display in the access direct chain, even if you wait for an hour, you can't get the download link, only one script author's blog QR code pops up. I have also asked the script author, but every time the author does not reply or refuses to reply for other reasons!

![演示](https://user-images.githubusercontent.com/75403660/102955511-0b395780-4511-11eb-9209-e9683acf91c9.gif)

There are also good reviews, I have been unable to understand why a script uploaded for only 13 days has so much praise? In addition to good reviews is bad reviews, a moderate review of none! The administrator should not have seen it?

As far as I know, a negative review of a script can be modified into a positive review. Some installation users gave bad reviews that the consultation script could not be used, and the author did not reply. And none of the comments in the praise script were unavailable for consultation!

![1](https://user-images.githubusercontent.com/75403660/102956621-784dec80-4513-11eb-9698-e7eac2ba3a13.png)

![2](https://user-images.githubusercontent.com/75403660/102956629-7ab04680-4513-11eb-97ec-03367a465eb3.png)

If the script is really usable, why doesn't the author provide a way to use the script successfully, and let us modify the evaluation?

As mentioned above, this script is a spam script and has no functions. It has been attracting users to pay attention to the author's blog!

**Comment by jixunmoe** [comment]
Translated discussion:

> OP: Script doesn't work, waited like 10 minutes
> OP: Using Microsoft Edge
> Author: You posted a negative review, don't expect me to help.

Should we have some rules against this kind of toxic behaviour?

**Comment by JasonBarnabe** [comment]
If the script is against [the rules](https://greasyfork.org/en/help/code-rules), please report it, and include detailed information. Note that "not working" is not against the rules. If it's not working, you can post negative feedback.

**Comment by jixunmoe** [comment]
> If the script is against [the rules](https://greasyfork.org/en/help/code-rules), please report it, and include detailed information. Note that "not working" is not against the rules. If it's not working, you can post negative feedback.

(slightly out of topic) I'm referring to the behaviour of the author, whom refuse to help because OP posted as a negative review in my previous comment.

**Comment by JasonBarnabe** [comment]
I would be against a "change your review to good then I'll help you" kind of comment but this comment doesn't seem to go that far. Authors are free to ignore feedback.

**Comment by yizhixiaohaha** [comment]
Well, dear administrator, can I understand this way? I can upload a useless script to the greasy fork, and then the function of this script is only a QR code to guide the installation user to pay attention to my blog, because if it doesn't work, it doesn't violate the rule of greasy fork.
If the script has just been uploaded and is invalid later, I have nothing to say. But this script just uploaded to grey fork is invalid!
This is obviously a vulnerability, I hope the administrator should consider whether it should be fixed!

**Comment by JasonBarnabe** [comment]
If the function of the script is to get people to a blog, then it's spam, and it should be reported. If the function of the script is something else, but that "something else" stops working, and the only thing that still works is the link to the blog, then it's not against the rules, but you're free to give it a bad review.

In other words, "not working" is not against the rules, but "being created for the sole purpose of advertising" is.

GitHub is not a good place to report scripts or discuss rules. GitHub is for the software that runs Greasy Fork. If you want to report a script, use the script reporting function. If you have questions about the decisions of a moderator or interpretation of the rules, use the forum.
