### ISSUE TITLE
Some bug on Japanese Translation?

### ISSUE THREAD

**Issue by knoajp** [JasonBarnabe/greasyfork#850]
https://greasyfork.org/ja/discussions/greasyfork
![20210103-092111](https://user-images.githubusercontent.com/844187/103469200-13ad5000-4da5-11eb-85e6-a9226df5f439.png)

**Comment by JasonBarnabe** [comment]
https://github.com/ruby-i18n/i18n/issues/546

**Comment by JasonBarnabe** [comment]
I've reverted an upgrade to the i18n gem due to the issue above. Won't upgrade it again until that's resolved.

Note you can provide Japanese translations at https://www.transifex.com/greasy-fork/greasy-fork/dashboard/

**Comment by knoajp** [comment]
Aside from the fallback issue, if missing translation causes this, I want to add translations for them, but it seems to be no such entries on transifex. Or... I'm not used enough to transifex for finding exact entries.

I've tried:

text:'Posted By'
text:Posted
text:posted_by_html

and so on.

**Comment by JasonBarnabe** [comment]
`text:` on Transifex is for searching by the English text. What you want to do is `key:posted_by_html`.

**Comment by knoajp** [comment]
I see, thank you.
