### ISSUE TITLE
Allow user's profile to have multiple language versions

### ISSUE THREAD

**Issue by knoajp** [JasonBarnabe/greasyfork#852]
Just an idea.
It'll be more useful for appealing to foreign users.

my current profile:
https://greasyfork.org/ja/users/78927-knoa

**Comment by JasonBarnabe** [comment]
I don't see the case for this. Profiles are generally very short, and if you want to include multiple languages, you can just do so as you did.

**Comment by knoajp** [comment]
I don't want to make my profile messed up with three languages, so I had to write shortly. 🙃
Anyway, it's not a big issue. Thanks.
