### ISSUE TITLE
Can't publish script even after confirming email

### ISSUE THREAD

**Issue by aspenluxxxy** [JasonBarnabe/greasyfork#853]
![image](https://user-images.githubusercontent.com/65794972/103713541-98a58e80-4f8a-11eb-8326-5ba82b2acc5f.png)
![image](https://user-images.githubusercontent.com/65794972/103713554-a22ef680-4f8a-11eb-88e5-22e36206ceb2.png)

Already confirmed my email but it doesn't recognize me as confirmed??

**Comment by JasonBarnabe** [comment]
What is the URL to your user page?

**Comment by aspenluxxxy** [comment]
https://greasyfork.org/en/users/724336-aspenluxxxy

It seems to have fixed itself now? Strange. Perhaps I was impatient.
