### ISSUE TITLE
Suggestion: offer an option to disable grid lines in code view

### ISSUE THREAD

**Issue by darkred** [JasonBarnabe/greasyfork#858]
I'd like to make a suggestion, please:
to offer an option to disable grid lines in script code view
I find it very difficult to read code with them.

<details>
<summary>screenshot example</summary>

page: https://greasyfork.org/en/scripts/6779-markdown-toolbar-for-uso/code

![2021-01-10_191255](https://user-images.githubusercontent.com/723651/104130268-6627d700-5378-11eb-9b07-a1f590822048.jpg)
</details>

Also, for reference, GitHub and OUJS, and editors such as Sublime Text and VSCode don't use grid lines in code view.

---

As an alternative, any leading whitespace characters (tabs/spaces) could be rendered, to assist in visually separating lines.

**Comment by JasonBarnabe** [comment]
I think it's pretty useful if you want to know what line number a piece of code is on. Would it be better if it was a more subtle gray?

**Comment by darkred** [comment]
No, I think it wouldn't help.

it doesn't have to do with the opacity of the gray.
I find that the grid lines, i.e. the alternation of white and gray, however subtle the gray it might be, 
makes it difficult to visually distinguish the various indentation levels and the matching brackets/closures.

Having every other line a slightly different background color,
gives the impression that the white lines are something else than those of the gray color, 

Grid lines are very useful in a Word/Excel/wikipedia table of data.
But not for viewing code, where each line of code (bracket/parenthesis) may end after various lines below.

---

I think that the best approach would be to render any leading whitespace characters (tabs/spaces),
and to highlight the current line on mouse hover.

**Comment by JasonBarnabe** [comment]
I like how it is. It should be easy to make a user script/style to override.

**Comment by darkred** [comment]
Making a CSS to disable the grid lines and highlight line on hover is something easy:

```css
/* Matching regex: ^https:\/\/greasyfork\.org\/.+\/scripts\/.+\/code$ */

.linenums > li:nth-child(2n) {
	background: #fff;
}

.linenums > li:hover {
	background-color: LemonChiffon;
}
```

but creating a userscript to show whitespace characters in code blocks is not something trivial.
