### ISSUE TITLE
Conversations - separate, each with its own title

### ISSUE THREAD

**Issue by darkred** [JasonBarnabe/greasyfork#862]
Currently each message you send to a member, goes under the previous one, i.e. there are no separate conversations with the same member (this was a feature in the previous Greasyfork layout, if I'm not mistaken).

For example in https://greasyfork.org/en/users/2159-woxxom , clicking the `Send message` link, 
(or in my own profile https://greasyfork.org/en/users/2160-darkred, clicking the single `Conversation with wOxxOm` link)
both get you to e.g. https://greasyfork.org/en/users/2160-darkred/conversations/xyz (`xyz` is a 3 digit number), where all your messages to that member are listed in the same page.

And if either you reply using the above `Post reply` form, 
or you use the `Create a new conversation` form, https://greasyfork.org/en/users/2160-darkred/conversations/new
then in both cases all your messages to that member go to the same page.

Also, there's no ability to add a title to your message.

---

My suggestion is the messages to appear as their own conversations,
i.e. if you use the `Create a new conversation` form, 
or unless you reply to a previous message to a member, 
to always create a new separate conversation with the member.

And to be able to add a title to your message, to visually separate the conversations.

**Comment by jixunmoe** [comment]
Not sure if this is the intended behaviour, but I can view the conversation via the link...

**Comment by darkred** [comment]
This shouldn't happen... I edited the link and the comment history

**Comment by jixunmoe** [comment]
https://github.com/JasonBarnabe/greasyfork/blob/036e0788d0f8e3d6be9a68ea1bb918df63e1c362/app/controllers/conversations_controller.rb#L58-L64

I'm guessing that because mods can read it, once the id is known...

**Comment by JasonBarnabe** [comment]
Moderators were able to see all conversations. I've changed it so that they can only see the conversation is a message has been reported.

As for the original request - how it works now is how I intend it to be. It's like sending private messages on virtually any other platform.

**Comment by darkred** [comment]
> As for the original request - how it works now is how I intend it to be. It's like sending private messages on virtually any other platform.

Allow me to disagree, please: 
in phpBB, discourse, reddit, 

I'll give an example:
- I send now a pm to a member about his script A
- a week later I contact him again, now about something regarding moderation (he is also a mod)
- a month later I send him another pm, now for his script B

I used the `Create a new conversation` link on my profile, for each pm 
![2021-01-17_113002](https://user-images.githubusercontent.com/723651/104836645-fe154b80-58b7-11eb-8fee-bb1a6631f34f.jpg)

He replies to each of my pms.

After all these 3 different conversations, in my profile there will be only 1 single link:
![2021-01-17_113606~](https://user-images.githubusercontent.com/723651/104836710-70862b80-58b8-11eb-9b8b-bb7cb70e35a0.jpg)
containing all pms in the same page. They are not nested, and it's not clear which pm is a reply to which one.

I would expect that there are 3 links in there instead of 1:

> - Conversation with member_A. Last message at 1 minute ago by darkred.
> - Conversation with member_A. Last message at 1 week ago by member_A.
> - Conversation with member_A. Last message at 1 month ago by member_A.

---

If you insist the pms to be listed all in the same page,
could you display each reply nested, in order to visually separate them?
