### ISSUE TITLE
Are conversations expiring ?

### ISSUE THREAD

**Issue by Procyon-b** [JasonBarnabe/greasyfork#864]
Not a problem for me, just a question.
I've seen my 2 conversations expiring (1 month) on my user page, but I don't see a link to an archive. Is it because they are gone from the system?

**Comment by JasonBarnabe** [comment]
> but I don't see a link to an archive

"See all conversations"

**Comment by Procyon-b** [comment]
I don't have that link anywhere on the page. Only "Create a new conversation"

**Comment by JasonBarnabe** [comment]
It should show if there are more conversations than your user page lists. You can reach it by adding /conversations to your user URL.

Conversations are not automatically deleted due to age.

**Comment by Procyon-b** [comment]
I don't remember if the link was present when the last conversation was still listed.
Could it be possible that it thinks that no recent conversation means no conversation at all ? Because it shows me this text: "You haven't had any conversations yet."

**Comment by JasonBarnabe** [comment]
Looks like the 'more' link is missing in the case of no-recent/yes-not-recent.

**Comment by JasonBarnabe** [comment]
Fixed.
