### ISSUE TITLE
"More discussions"

### ISSUE THREAD

**Issue by Procyon-b** [JasonBarnabe/greasyfork#865]
When I try to see older discussions beyond the usual 10 most recent, clicking the link "More discussions" sends me to another page where only the 3 most recent are displayed ("On my scripts" selected).

"Comments by me" also displays the same 3.
Under "Subscribed" I see a discussion on someone else's script, that discussion should also appear under "Comments by me".

**Comment by Procyon-b** [comment]
I've also noticed this:
Clicking "See all user activity" under "Recent comments" sends me to the page "Discussions" "All discussions" with a url like `discussions?user=`
Clicking "More discussions" sends me to the "Discussions" page but with the url `discussions?me=script`. Then, if I click "All discussions" I see every discussion made on GF. (currently 2418 pages)

**Comment by JasonBarnabe** [comment]
Can you provide examples of which discussions you expect to see at which URLs?

**Comment by Procyon-b** [comment]
If you can masquerade as me (user 435938) you'll see this:

last 10 (all OK here) (`/users/435938`)
![last-10](https://user-images.githubusercontent.com/40043075/105564301-e4458f80-5d21-11eb-913a-5e2dbbbe4511.PNG)

clicking "More discussions…" shows this: (`/discussions?me=script`)
![all-disc](https://user-images.githubusercontent.com/40043075/105564361-148d2e00-5d22-11eb-9459-6c32aaaf4770.PNG)
it shows only the 3 most recent

clicking "Comments by me" (on the right) once again shows the 3 most recent (`/discussions?me=comment`)
![comments](https://user-images.githubusercontent.com/40043075/105564456-7baae280-5d22-11eb-808c-4e0be82d8aac.PNG)

"Subscribed" (`/discussions?me=subscribed`)
![sub](https://user-images.githubusercontent.com/40043075/105564485-a1d08280-5d22-11eb-8c4f-0d79260a3f6c.PNG)
This list is correct. I mention it here because the second entry is someone else's script, and it should be listed in "Comments by me" too.

When clicking "All discussions" on the right (`/discussions` without any other argument)
![all-all](https://user-images.githubusercontent.com/40043075/105564582-1d323400-5d23-11eb-90ca-61e80319c4a2.PNG)

and finally "All discussions" when accessed from the user page "See all user activity" link: (`/discussions?user=435938`)
![all-user](https://user-images.githubusercontent.com/40043075/105564614-43f06a80-5d23-11eb-819f-b5b575f2ad50.PNG)
again only displays the 3 most recent messages.

Browsing the menu on the right from this url links to pages with both parameters: `user=` and `me=`. They display the same problem as those above that don't have the `user=` parameter.

**Comment by JasonBarnabe** [comment]
How about now?

**Comment by Procyon-b** [comment]
Seems OK
great

**Comment by Procyon-b** [comment]
The last thing is the "All discussions"
It links to everything on GF when clicked from the page opened by "More discussions…" and all mine when the page is opened from "See all user activity"

**Comment by JasonBarnabe** [comment]
Don't know what you mean. Each box on the right is a separate filter. If you change one, the others shouldn't change.

From https://greasyfork.org/en/discussions?me=script, if I click "All discussions" (in the first box), I get https://greasyfork.org/en/discussions.

From https://greasyfork.org/en/discussions?user=435938, if I click "All discussions" (in the second box), I also get https://greasyfork.org/en/discussions

If I was on https://greasyfork.org/en/discussions?me=script&user=435938, I'd need to click "All discussions" in both the first and second boxes to get back to the full list.

**Comment by Procyon-b** [comment]
I mean "All discussions" in the first box in both cases.
The box under the text "Discussions involving me". I was assuming that in the case of `/discussions?me=script`, it was also involving me.

**Comment by JasonBarnabe** [comment]
All the "All" options are just to unset the filters. I think this is working properly, but perhaps a little unclear.

**Comment by Procyon-b** [comment]
Correct.

The other fact is that I can click to see all GF messages from the page `/discussions?user=435938` via the second box,
but I can't see "all my messages" from `/discussions` since there is no second box

**Comment by JasonBarnabe** [comment]
"Comments by me" should be the same result. "See all user activity" is just different because it was designed to let you see anyone's activity, not just yourself.

**Comment by Procyon-b** [comment]
It is clear now.
It's just a bit confusion because it's in a box under "Discussions involving me". And if you only consider that box, the 2 pages are displaying different things (but one has a second box, the other none).
