### ISSUE TITLE
Strikethrough doesn't work for Markdown (ok with HTML)

### ISSUE THREAD

**Issue by darkred** [JasonBarnabe/greasyfork#867]
I've noticed in any textarea in the site, 
that Markdown strikethrough, `~~text~~`, doesn't work/is not rendered , e.g. ~~This was mistaken text~~ .

<details>
<summary>Screenshot</summary>

![2021-01-22_223055](https://user-images.githubusercontent.com/723651/105542135-8903a500-5d01-11eb-8c23-5821689c60ed.jpg)
</details>

*It was working ok in the old GF layout.*

It still works ok for HTML `<strike>text</strike>`.

For reference, `<strike>` is included in https://greasyfork.org/en/help/allowed-markup

Thank you

**Comment by JasonBarnabe** [comment]
Done.

**Comment by darkred** [comment]
Thank you.
