### ISSUE TITLE
 Why is my account banned?

### ISSUE THREAD

**Issue by Tokisaki-Galaxy** [JasonBarnabe/greasyfork#868]
Why is my account banned?
I tried to log in with GitHub, but prompted "GitHub sign in failed: This email has been banned.."

**Comment by JasonBarnabe** [comment]
What is your username, email, or profile URL?

**Comment by Tokisaki-Galaxy** [comment]
email: 1341281757@qq.com

**Comment by JasonBarnabe** [comment]
Don't see any account with that email.

**Comment by JasonBarnabe** [comment]
The email attached to your GitHub was attached to an account that was banned. The account has since been deleted (either by you or because it happened over 6 months ago).

So I can't tell you what you did.

**Comment by Tokisaki-Galaxy** [comment]
I now re register the account to solve this problem.
The problem seems to be that if you log in with an unbound GitHub account, it will show that the e-mail is blocked by mistake

**Comment by JasonBarnabe** [comment]
No, definitely there was an account on Greasy Fork using the email you use in your GitHub that did something and got banned.

Please review https://greasyfork.org/en/help/code-rules if you're going to post scripts.

**Comment by Tokisaki-Galaxy** [comment]
thank you.
