### ISSUE TITLE
The markdown in <details></details> will be invalid.

### ISSUE THREAD

**Issue by XIU2** [JasonBarnabe/greasyfork#873]
When I wanted to use `<details>` to fold the content, I found that the internal markdown was completely invalid.

## Current results:

![01](https://user-images.githubusercontent.com/54703944/108585674-935aa280-7384-11eb-9db2-7d3bd67c8840.png)  ![02](https://user-images.githubusercontent.com/54703944/108585676-93f33900-7384-11eb-9eb5-b54c1d60e94c.png)

****

## My expected result:

****

A simple demonstration:

<details>
<summary>[Click to view]</summary>

****

### 123456

- 123456

</details>

****

## Code:

```
****

A simple demonstration:

<details>
<summary>[Click to view]</summary>

****

### 123456

- 123456

</details>

****
```

**Comment by JasonBarnabe** [comment]
Same as #827.
