### ISSUE TITLE
Add ability to delete feedback thread (beyond the current 5 mins)

### ISSUE THREAD

**Issue by mica** [JasonBarnabe/greasyfork#874]
Something akin to closing an Issue here on GitHub... If I've posted to let someone know their script is broken, I'd like to be able to delete the thread later, after they've fixed it.

**Comment by mica** [comment]
Is there a downside to adding a delete button? Think it'd be a better solution

**Comment by jixunmoe** [comment]
> Is there a downside to adding a delete button? Think it'd be a better solution

I believe is better to keep the history so everyone can see what had happened, e.g. when other people having the same issue.
