### ISSUE TITLE
Broken thumbnail image (403)

### ISSUE THREAD

**Issue by Procyon-b** [JasonBarnabe/greasyfork#876]
One of my script is currently not displaying the thumbnail of the associated screenshot (full size is OK).
`https://greasyfork.org/scripts/395358`

I know that I can fix it by uploading the image again and discard the old version. I'm warning you in case there is a problem elsewhere.

**Comment by JasonBarnabe** [comment]
Fixed. You probably uploaded it when I was playing around with this and had broken it.

**Comment by Procyon-b** [comment]
The image was uploaded when the script was uploaded. That was in January 2020.
The thumbnail was visible until very recently. That's why I've created this issue. In case other images, elsewhere, have the same problem.

**Comment by JasonBarnabe** [comment]
The script was updated recently. When an update happens, it makes a new record for the attachment. That's the date I was referencing.

I'll see if I can run through the DB and find any more cases.

**Comment by Procyon-b** [comment]
In this particular case, was the thumbnail deleted by the system, or was it a "filename" modification?

**Comment by JasonBarnabe** [comment]
My theory is that the record that associated the script to the thumbnail was not properly generated. Generally Rails handles making this, but not in the most optimum way, and that's what I had been playing around with recently.

Or it could be something completely different.

**Comment by JasonBarnabe** [comment]
There were 200 images like yours in the DB. 190 were from Oct 7, which is when I switched the way uploading works. A few more were from Dec 19, when I made further changes. So I'm pretty confident that it's not an ongoing issue.
