### ISSUE TITLE
手机版搜索框候选词

### ISSUE THREAD

**Issue by Renjh5218** [JasonBarnabe/greasyfork#879]
你好，手机版搜索脚本时候选词会遮挡输入法![Screenshot_20210327-175721.jpg](https://user-images.githubusercontent.com/79973902/112717268-79355680-8f26-11eb-9e56-927e34889c01.jpg)

Search history will obscure the input method when searching for scripts in the mobile version,hope it can be improve
Thank you

**Comment by jixunmoe** [comment]
这是浏览器的问题，与网站无关。请向浏览器方反馈问题。

> This is browser's issue, not related to the site. Please report this issue to the browser vendor.
