### ISSUE TITLE
Script/Style Manager Compatibility Statement Requirement

### ISSUE THREAD

**Issue by erosman** [JasonBarnabe/greasyfork#880]
While different script/style manger and browsers offer similar features, they are not identical.

There are far too many userscripts (or userstyles) that ONLY work with a specific mangers and/or browser but developers rarely mention this requirement in the description.

The result is that users install a script and then wonder (and often query extension developer e.g. https://github.com/erosman/support/issues/306) why it doesn't work or work properly with their extension.

Although it is not required for userscripts to work with ALL mangers, I would suggest that it is a reasonable to require developers to state which manager their script is compatible and tested with.

It would also be good if greasyfork would provide a checkbox of managers for the developers to tick.

**Comment by erosman** [comment]
Additionally, you can also allow users to vote compatibility with positive votes (no negatives votes since that would lead to anticompetitive behaviour).

For example ...

🔲 GreaseMoneky (123 users voted compatible)
🔲 TamperMonkey (123 users voted compatible)
🔲 ViolentMoneky (123 users voted compatible)
🔲 FireMonkey (123 users voted compatible)

**Comment by dimisa-RUAdList** [comment]
In the case of RU AdList JS Fixes, compatibility is [described](https://greasyfork.org/en/scripts/19993-ru-adlist-js-fixes#additional-info) in sufficient detail.

**Comment by erosman** [comment]
@dimisa-RUAdList My post was a general post an not about a particular userscript. I did see the compatibility in the description of **RU AdList JS Fixes** but most userscripts do not have it so I brought up the suggestion.

My suggestion was to set up a system to identify compatibility clearly.

**Comment by JasonBarnabe** [comment]
Specify it in the [browser-specific `@compatible` and `@incompatible` keys](https://greasyfork.org/en/help/meta-keys#meta-compatible) by providing a description. In your example, you could list `@compatible chrome` and `@compatible firefox Only in TamperMonkey`.

Alternately or additionally, put it in the additional info. There's not going to be special UI for this.

**Comment by lainverse** [comment]
Thanks. Added `@compatible` keys into my script. For Fx and Chrome for now.
