### ISSUE TITLE
No `Report comment` link in my own comments

### ISSUE THREAD

**Issue by darkred** [JasonBarnabe/greasyfork#881]
I've noticed that there's no  `Report comment` link (just a 'Quote' one) in my own comments
e.g. in my comment [here](https://greasyfork.org/en/scripts/23493-rarbg-torrent-and-magnet-links/discussions/79975#comment-193303)

<details>
<summary>screenshot</summary>

![](https://i.imgur.com/wvvQzhy.jpg)
</details>

I noticed that, after making a comment (not the above) by mistake, and I wanted it to be deleted.
so I had to contact a mod via pm.

Thank you

**Comment by JasonBarnabe** [comment]
This is intentional. If you need to delete a comment (because you posted something private or whatever), then contact a mod.
