### ISSUE TITLE
Script sync fails with a SyntaxError on logical nullish assignment 

### ISSUE THREAD

**Issue by monk-time** [JasonBarnabe/greasyfork#883]
Same issue as https://github.com/JasonBarnabe/greasyfork/issues/728 but with [logical nullish assignment](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Logical_nullish_assignment) (ES2021 feature that is already supported by all major browsers) causing script sync to fail with a SyntaxError:

`Script sync failed - Code contains errors: Uncaught SyntaxError: Unexpected token '??=' at undefined:1567:36.`

https://github.com/JasonBarnabe/greasyfork/blob/17dac187d24a42dc6701216320d9bf868f65ea6b/Gemfile.lock#L233-L234
V8 started supporting this feature at [v8.5](https://v8.dev/blog/v8-release-85). mini_racer has an update available ([0.4.0.beta1](https://github.com/rubyjs/mini_racer/blob/master/CHANGELOG), came out yesterday) where they have switched from libv8 to [libv8-node](https://github.com/sqreen/ruby-libv8-node) ([commit](https://github.com/rubyjs/mini_racer/commit/03e0babcd8b2781b99c08570c3480612b86ec165#diff-30d3134eb72fcd96ce343d5c0359684a5545843b47d7cba45732d3e360cf322f), [explanation](https://github.com/rubyjs/libv8/issues/304)) which should be enough to fix this issue, node supports this feature since v15+. Meanwhile libv8 hasn't been updated from what you're using.

**Comment by JasonBarnabe** [comment]
mini_racer 0.4 is released (but [not published?](https://github.com/rubyjs/mini_racer/issues/191)). I'll try it out and use if it works. Thanks for investigating.

**Comment by JasonBarnabe** [comment]
Updated to mini_racer 0.4, so you should be good to go now.
