### ISSUE TITLE
[Forum] Text preciding with `@` char in `pre` & `code`-tags are linked

### ISSUE THREAD

**Issue by jerone** [JasonBarnabe/greasyfork#92]
Code and `pre`-tags are mainly used for code. Linking to profiles when a word begins with a `@` should probably not happen.

Example: https://greasyfork.org/forum/discussion/107/assessment#Item_1

**Comment by JasonBarnabe** [comment]
Related: https://github.com/vanilla/vanilla/issues/2467

**Comment by tophf** [comment]
[This](https://github.com/vanilla/vanilla/pull/2531) seems to be working.

**Comment by JasonBarnabe** [comment]
With that patch, wouldn't double ats and hashes that were in the code block already cause problems?

Based on what you've done I've put together a more generic solution. Check out https://greasyfork.org/en/forum/discussion/3920/test-of-blocks-on-the-forum

**Comment by JasonBarnabe** [comment]
This is done and a PR has been sent to Vanilla.
