### ISSUE TITLE
Moderator comment on report without resolving

### ISSUE THREAD

**Issue by JasonBarnabe** [JasonBarnabe/greasyfork#930]
e.g. to provide more info

**Comment by jixunmoe** [comment]
Link to `View discussion` does not link correctly.

e.g. for report: [#10586](https://greasyfork.org/reports/10586)

It generates the following:

```
<a href="/87825/discussions">View discussion</a>
```

... which is a 404 link

**Comment by JasonBarnabe** [comment]
Fixed!
