### ISSUE TITLE
I can’t update the script, it says HTTP ERROR 500

### ISSUE THREAD

**Issue by XIU2** [JasonBarnabe/greasyfork#931]
When I click **[Update]**, it will prompt **HTTP ERROR 500** !
All my scripts are like this. Appeared since yesterday.

However, because I have bound to Github, I can still update the script content through Github, but I cannot modify the introduction text of the script.

**I cannot access this page of any script:**  
https://greasyfork.org/zh-CN/scripts/XXXXX/versions/new

**E.g:**  
https://greasyfork.org/zh-CN/scripts/412212/versions/new

When I open the address, it will directly display **HTTP ERROR 500** !

**Comment by JasonBarnabe** [comment]
Fixed by 347ea9f45cb125ecf5777d05c825ab80ece205f8.
