### ISSUE TITLE
Error: Description is invalid

### ISSUE THREAD

**Issue by wwc7654321** [JasonBarnabe/greasyfork#938]
I'm publishing a script with description in s-chinese, but got an error as title said.
Does the description must be in English, and the s-chinese description must be write in an additional description box? 
or it's forbidden to write a too short description

**Comment by wwc7654321** [comment]
It confused me that which rule forbid me from posting, for there is no hint

**Comment by JasonBarnabe** [comment]
No, the description does not have to be English.

Can you attach what you're trying to post?

**Comment by wwc7654321** [comment]
something like "bilibili自动开启分P连播和推荐连播，写了个脚本禁止B站自动推荐连播，保留分P连播。仅对PC客户端有效，跳转时自动拉回原始页面"

**Comment by JasonBarnabe** [comment]
Please attach the entire script you're trying to post here in GitHub.

**Comment by JasonBarnabe** [comment]
There are some anti-spam restrictions, but that's about it. If you have a problem, provide the exact script you're trying to use and I can investigate.
