### ISSUE TITLE
Hello, i do not understand why the website can not delete what the script feedback comments

### ISSUE THREAD

**Issue by lyjhyjyes** [JasonBarnabe/greasyfork#939]
Sometimes, my feedback is solved, and I don't want to bother the author to check it repeatedly, so I want to delete it, but I can't find an entry
https://greasyfork.org/zh-CN/scripts/381682-html5%E8%A7%86%E9%A2%91%E6%92%AD%E6%94%BE%E5%99%A8%E5%A2%9E%E5%BC%BA%E8%84%9A%E6%9C%AC/discussions/87897

**Comment by jixunmoe** [comment]
将评分更改为“好评”或无评价即可。报告错误留档很重要，而且以后可以很方便引用。
