### ISSUE TITLE
script got removed

### ISSUE THREAD

**Issue by feiercrack** [JasonBarnabe/greasyfork#945]
https://greasyfork.org/de/scripts/378976-corrected-coords

script with corrected geocaching coordinates

i used that a lot to verify my work.
now its completely vanished after my long disease.
after a long time period, i am healthy back again and want to use this script again.
but i cant find it anywhere...
what to do?
who was the author / creator?
any help available?
many thanks

**Comment by JasonBarnabe** [comment]
It's been deleted completely from the site, either by the author or by a moderator. We don't have the code any more.
