### ISSUE TITLE
Script got flagged without apparent reason

### ISSUE THREAD

**Issue by jixunmoe** [JasonBarnabe/greasyfork#946]
script in question: 4678

Had a quick look, was last updated in 2016, not sure why it has been flagged up.

Would it make sense to show the reason / pattern matched for those scripts under "Scripts to Review" section?

https://greasyfork.org/en/admin/blocked_script_texts

**Comment by JasonBarnabe** [comment]
It was updated (without updating the code) yesterday.

I've removed the string that it matched. It was something that people used to spam a lot with, but not any more.
