### ISSUE TITLE
Http 403 using Webhook

### ISSUE THREAD

**Issue by ericdanieldavid** [JasonBarnabe/greasyfork#949]
I'm trying to create a webhook that will be linked on Azure DevOps. 

The secret was gerenated and I using "Bitbucket URL of example", otherwise it always give me 403 error. If I just try open the URL on browser it shows 404 error. 

![Azure DevOps Error Message](https://i.imgur.com/g4jm0Lm.jpg)

**Request**

`
Method: POST
URI: https://greasyfork.org/pt-BR/users/19046-ericdanieldavid/webhook?secret=<MY SECRET>
HTTP Version: 1.1
Headers:
{
  Content-Type: application/json; charset=utf-8
}
Content:
{
  "subscriptionId": "XXXXXXXXXXXXXXXXXXXXXXX",
  "notificationId": 17,
  "id": "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
  "eventType": "git.push",
  "publisherId": "tfs",
  "message": null,
  "detailedMessage": null,
  "resource": null,
  "resourceVersion": null,
  "resourceContainers": {
    "collection": {
      "id": "XXXXXXXXXXXXXXXXXXXXXXXX"
    },
    "account": {
      "id": "XXXXXXXXXXXXXXXXXXXXXXX"
    },
    "project": {
      "id": "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
    }
  },
  "createdDate": "2021-06-21T13:49:05.2865289Z"
}
`

**Response**

`
Status Code: 403
Reason Phrase: Forbidden
HTTP Version: 1.1
Headers:
{
  Transfer-Encoding: chunked
  Connection: keep-alive
  X-Frame-Options: SAMEORIGIN
  X-XSS-Protection: 1; mode=block
  X-Content-Type-Options: nosniff
  X-Download-Options: noopen
  X-Permitted-Cross-Domain-Policies: none
  Referrer-Policy: strict-origin-when-cross-origin
  X-Request-Id: 46239efd-e7cf-4a06-bddf-ee57ce460632
  X-Runtime: 0.004885
  Cache-Control: no-cache
  Date: Mon, 21 Jun 2021 13:39:22 GMT
  Server: nginx/1.18.0
  Server: (Ubuntu)
  Content-Type: text/html; charset=utf-8
}
`

**Comment by JasonBarnabe** [comment]
What system is this actually coming from? [The code](https://github.com/JasonBarnabe/greasyfork/blob/f426f8546ff87a82e1c336a593e321a2eb74a4e9/app/controllers/users_controller.rb#L129-L135) will look at the headers to determine what system (and what format) the request is from and what format it's using. If will fall back to GitHub if none of the other checks match.

**Comment by ericdanieldavid** [comment]
Hi Jason, thanks for answer. 

It comes from [Microsoft Azure DevOps](https://azure.microsoft.com/pt-br/services/devops/) cloud plataform. I tryed to force the Agent header, otherwise it didnt work (maybe not possible).

![Print Post](https://i.imgur.com/jcuorUt.png)

**Comment by JasonBarnabe** [comment]
If you're setting `User-Agent: Bitbucket-Webhooks/2.0` and getting 403 then I think the only thing would be [the secret is wrong](https://github.com/JasonBarnabe/greasyfork/blob/f426f8546ff87a82e1c336a593e321a2eb74a4e9/app/controllers/concerns/webhooks.rb#L55-L58).

**Comment by ericdanieldavid** [comment]
Note on print that "User-Agent" not been sent (on rigth side of screen). In other words.... in other word, and lookng code, if User-Agent not received it did not looking secret passed as param (querystring).

My Ruby is so rusty.... but reading code I realyze that it reconstruct the path to get the push, so using Azure DevOps it will not work. 

I'll change my pipeline do another way, no problem dude ;-) 

Tks a lot!
