### ISSUE TITLE
The current `No rating` and `Ok` rating descriptions allow rating abuse

### ISSUE THREAD

**Issue by darkred** [JasonBarnabe/greasyfork#952]
<details>
<summary>Comparison of the current v previous rating categories (click to expand)</summary>

```
- No rating - just a question/comment
- Bad - script does not work
- OK - script works, but could use improvement
- Good - script works
```

Previously they were:

```
- No rating - just a question, comment, feature request, or bug report
- Bad - script doesn't work
- OK - script works, but has significant issues
- Good - script works well
```
</details>

The changed rating descriptions are of `No rating` and `OK`:

`No rating - just a question, comment, feature request, or bug report` has become a plain:
`No rating - just a question/comment`

`OK - script works, but has significant issues` has become:
`OK - script works, but could use improvement`.

I believe that the plain wording of `No rating - just a question/comment`
combined with the existence of `OK - script works, but could use improvement`
allow rating abuse when making feature requests or just questions:

the user gets the wrong impression that, regardless of the script description,
if a script doesn't already have a feature that he wants,
or that its author hasn't foreseen every possible use case, no matter how unusual/rarely used,
gives him the right for an `Ok` rating next to his feature request/question.

That's what's recently happened in this feature request for a script of mine
[Rating `OK` - Is it possible to support TV pages like https://rarbgweb.org/tv/tt8879940/](https://greasyfork.org/en/scripts/21550-rarbg-convert-torrent-timestamps-to-relative-format/discussions/91794)
although that was a feature request, exactly the same as [this one](https://greasyfork.org/en/scripts/23493-rarbg-torrent-and-magnet-links/discussions/16170) that was formerly made for one of my other rarbg scripts (which was also fulfilled).  

&nbsp;
That's why I'd like to ask you please to consider restoring the `No rating` description as it was before:
`No rating - just a question, comment, feature request, or bug report` 
and change `OK` into:
`OK - script works, but has significant bugs`

**Comment by JasonBarnabe** [comment]
I've made adjustments here so that feature requests are explicitly stated for "No rating" and not implied for "OK".
