### ISSUE TITLE
How to update the sync URL?

### ISSUE THREAD

**Issue by Jorengarenar** [JasonBarnabe/greasyfork#954]
If for example I changed the repository name of my UserScript on GitHub, how do I update the sync URL on GreasyFork to the new one?

**Comment by JasonBarnabe** [comment]
Admin tab of the script, visible only to the author of the script.

**Comment by Jorengarenar** [comment]
I open Admin tab and see

  * Promoted Script
  * Source Syncing
    - here I have only an option to put an URL for "_Default additional info (language matches `@name`)_" 
  * Authors
  * Default Locale
  * Moderator log
  * Compare to another script

**Comment by Jorengarenar** [comment]
OK, I needed to turn off the syncing for it to appear
