### ISSUE TITLE
Allow locale info duplication in script metadata

### ISSUE THREAD

**Issue by jeiea** [JasonBarnabe/greasyfork#955]
I'm receiving this error when publishing the below script.
```
There were some problems with what you posted...
    Code should not specify @name:en as 'en' is the default locale.
    Code should not specify @description:en as 'en' is the default locale.
```
```
// ==UserScript==
// @name           test
// @description    tttt
// @name:en        test
// @description:en tttt
// @name:ko        test
// @description:ko tttt
// @match          none
// @version        1
// @author         x
// @namespace      https://greasyfork.org/en/users/x
// ==/UserScript==
"use strict";
```

But we can't know script's default language by the script content itself. In the other words, we can't know the above script's `@name` is english or korean, or some other language without the error.

As the result, tampermonkey can't show the title in correct language in the list. This behavior is inconsistent by the version.

```
// ==UserScript==
// @name           테스트
// @description    o_o
// @name:en        test
// @description:en tttt
// @match          none
// @version        1
// @author         x
// @namespace      https://greasyfork.org/en/users/x
// ==/UserScript==
"use strict";
```

The above script is publishable to greasyfork, but tampermonkey doesn't show the title in korean despite of correct preferences. It may be due to the ambiguity of `@name` 's language. We can't know `@name`'s language by the script content itself unless using heuristic.

Please comment if there's any other recommended way to handle this.

**Comment by JasonBarnabe** [comment]
I don't understand why Tampermonkey needs to know the language of the locale-less `@name` and `@description`. Should it not just use the localized versions if those match the preferred locale, and use the default if not?

**Comment by derjanb** [comment]
@JasonBarnabe There was a bug that preferred `@name` over `@name:en` (Tampermonkey/tampermonkey#1244) which is fixed at the latest BETA version (even though I still have to replace default names with localized ones at some places).

**Comment by jeiea** [comment]
@JasonBarnabe Aside from tampermonkey's implementation, chrome can have multiple user preferred language with priority.

![image](https://user-images.githubusercontent.com/4188984/125907460-fe7ea5e6-c8dc-47e9-9e8a-eb5cf39a0008.png)

When using the above preference (1. english, 2. korean), consider what `name` should be shown to user.

```
// @name           test
// @name:ko        테스트
```

I think `@name:ko` can be shown because we don't know `@name`'s language and korean is on the user language preference. Don't you think this can be ambiguous?

**Comment by JasonBarnabe** [comment]
OK, this is allowed now. If both `@name` and `@name:ko` are specified and the script's locale is `ko`, then `@name` will be used.
