### ISSUE TITLE
Script sync successfully but additional info didnt

### ISSUE THREAD

**Issue by Proanx** [JasonBarnabe/greasyfork#957]
![screenshot](https://user-images.githubusercontent.com/39716510/125398294-b6442c80-e3e1-11eb-8744-ec096fffffbc.png)
Can be preview normally, but no matter use gitee/github link additional info wont be any change

**Comment by JasonBarnabe** [comment]
The code attempts to make URLs absolute. It was failing on your use of `<a name="support"></a>`. I've fixed it.
