### ISSUE TITLE
Two translation issues

### ISSUE THREAD

**Issue by jeiea** [JasonBarnabe/greasyfork#961]
`help.meta_keys.version_html`'s href seems to be broken (https://developer.mozilla.org/en/docs/Toolkit_version_format).

`app/views/users/show.html.erb:34` has hard coded string which is untranslatable.
![image](https://user-images.githubusercontent.com/4188984/126375972-c6822f42-1c82-4115-9467-467cddb313df.png)

**Comment by JasonBarnabe** [comment]
Fixed, may take a day to show up in Transifex though. Thanks for reporting.
