### ISSUE TITLE
Why does the script creator have the power to delete the review?

### ISSUE THREAD

**Issue by Mishasama** [JasonBarnabe/greasyfork#963]
That will make the users can't know the truth. And it undermines freedom of expression.

**Comment by JasonBarnabe** [comment]
They don't. Why do you think they do?

**Comment by Mishasama** [comment]
Oh, maybe the site cache problem? Not sure.
I can't see my negative review one day after I leave it. But it shows up again now.
Sorry to bother you.

**Comment by JasonBarnabe** [comment]
It's possible it was flagged for spam but then approved by a moderator.
