### ISSUE TITLE
inconsistent regex in allowed_require_list

### ISSUE THREAD

**Issue by JAGulin** [JasonBarnabe/greasyfork#964]
The regex on https://greasyfork.org/en/help/external-scripts are inconsistent. Should you update them?

# the gm4-polyfill regex missing ^
This may not be a real problem, but in the test box below it would allow arbitrary URL like this:

xyz.xyz?ignore="https://greasemonkey.github.io/gm4-polyfill/gm4-polyfill.js?"

# `(https?:)?` can start with //
https://stackoverflow.com/questions/4071117/uri-starting-with-two-slashes-how-do-they-behave

Is there any reason to support this? If so, why not for those https-only?

# escape for /

This may not be needed at all, the `https://openuserjs.org/src/libs/xyz.js` passes the test box.
But if you want escape, I suggest you do it consistently.

```
jsDelivr GitHub commit-specific references | ^(https?:)?//cdn\.jsdelivr\.net/gh/[^/]+/[^/@]+@[a-f0-9]{40} |  
jsDelivr-hosted libraries | ^(https?:)?//cdn\.jsdelivr\.net\/(?!gh/).*
Mousetrap | ^https:\//craig\.global\.ssl\.fastly\.net\/js\/mousetrap\/.* 
OpenUserJS libraries | ^(https?:)?//openuserjs.org/src/libs/.+.js.*
```

# escape for .

OpenUserJS libraries also have .org and .js without escape. A minor problem, but should be escaped.

**Comment by JasonBarnabe** [comment]
> the gm4-polyfill regex missing ^

Updated.

> (https?:)? can start with //

If I had to start over, I'd require https on everything. But I don't want to retroactively make scripts invalid by tightening this us.

> escape for /

Updated (added escaping).

> escape for .

Updated.

Thanks for the suggestions.
