### ISSUE TITLE
How to modify the synchronization location of an existing script

### ISSUE THREAD

**Issue by rxliuli** [JasonBarnabe/greasyfork#969]
Previously, when the script was released, the synchronization location was the dist directory of the github master branch. Now I want to change it to the directory of the gh-pages branch. What should I do? (I don’t seem to see the setting to modify the synchronization step position on the management page, only the option to modify the README)

**Comment by JasonBarnabe** [comment]
On the Admin tab, after you turn off syncing, you'll have an input field to turn it back on.

**Comment by rxliuli** [comment]
thx
