### ISSUE TITLE
After the malicious bad ratings report was deleted, I still received the prompt "... has received consecutive bad ratings. Please review your script and reply to the concerns raised in the ratings."

### ISSUE THREAD

**Issue by XIU2** [JasonBarnabe/greasyfork#970]
Yesterday I met a few malicious users with bad reviews.  
After reporting them, they were all blocked and their comments were deleted.  

But today I received a prompt:  
**"... has received consecutive bad ratings. Please review your script and reply to the concerns raised in the ratings."**  
https://greasyfork.org/scripts/412681

I think there is a problem with this mechanism of GreasyFork.  
The deleted comments should be **excluded** (Because being deleted means that the rules are violated.).

I tried to update the script (changed a character), the prompt disappeared, **but an hour later I received the prompt again. . .**

How can I resolve this prompt?

**Comment by JasonBarnabe** [comment]
You are correct in your thought that it was considering deleted discussions. I'll fix this.
