### ISSUE TITLE
greasyfork.org slow to respond

### ISSUE THREAD

**Issue by Procyon-b** [JasonBarnabe/greasyfork#973]
(for me, now is: 12/8 14:30 GMT+2)
Since at least yesterday (24h, maybe even 36-48h) greasyfork.org is slow to respond. It is sometimes even slower than uso.

I've browsed a little, then timed the display of the homepage. Sometimes it loads in a couple of seconds, but it can often take 10 to 40s to respond and then another 5-10 seconds to finish loading (I don't ad-block gf). Same with other pages.

Yesterday I was debugging the updating method used by stylus. In the network tab of the extension, greasyfork.org was the slowest to respond. Sometimes up to 20-30 seconds just for one connection. So it's not just the user's website that is slow.

**Comment by JasonBarnabe** [comment]
Thanks for reporting - I've been away the past few days.

This appears to be an affect of #884 - script's mentions (e.g. when you @ a user) get duplicated in some circumstances, and after numerous doublings, a script can have thousands of mentions. This causes problems when loading a script's previous version, as it has to recalculate some aspects of this. These requests essentially caused 100% CPU load and took an extremely long time to complete, which affected other requests.

I've cleared the bad data, put in a sanity check, and will look into fixing #884 properly.
