### ISSUE TITLE
greasyfork 502 bad gateway on script creation

### ISSUE THREAD

**Issue by ayunami2000** [JasonBarnabe/greasyfork#974]
GreasyFork has been giving me 502 bad gateway every time ive tried today on different wifi networks and computers and browsers and times. It happens when I create the script, and no script is actually created as a result.

**Comment by JasonBarnabe** [comment]
I just posted a script without issue. It may be something about the code you're posting. Can you attach it here in GitHub?

**Comment by JasonBarnabe** [comment]
This is likely bad character encoding in what you're posting.
