### ISSUE TITLE
Include trailing slash `/` when auto-urling 

### ISSUE THREAD

**Issue by darkred** [JasonBarnabe/greasyfork#975]
It occurred to me [here](https://greasyfork.org/en/scripts/420754-1337x-torrent-and-magnet-links/discussions/96026#comment-225029) : the trailing slash `/` was removed in the posted URL (but included in the displayed URL text):
I entered this URL as text `https://1337x.to/sub/81/0/` (working, with trailing `/`) 
but the posted `href` became `https://1337x.to/sub/81/0` (non working, "404 Not Found") :

<details>
<summary>screenshot</summary>

![2021-08-17_204300](https://user-images.githubusercontent.com/723651/129775161-13e0609d-707a-4cef-a615-dd23f1db0c31.jpg)
</details>

The same occurs in the editor|'Preview' tab:
<details>
<summary>screenshot</summary>

![2021-08-17_204336](https://user-images.githubusercontent.com/723651/129775176-31190c4d-e964-4683-868b-5dd179692f9c.jpg)
</details>

&nbsp;
PS. I *think* #958 is related.

**Comment by JasonBarnabe** [comment]
> PS. I think #958 is related.

You think right. Fixed now.
