### ISSUE TITLE
I hope to add a feature to automatically add id to the h1 h2 h3 title to facilitate #hash links (the effect is similar to Github README)~

### ISSUE THREAD

**Issue by XIU2** [JasonBarnabe/greasyfork#980]
Github's README will automatically add id to titles such as **h1, h2, h3**, etc. so that they can be linked via **#hash**.
**for example:**
https://github.com/JasonBarnabe/greasyfork#help

This can be done a lot of things.
**for example:**
- _Allowing users to quickly navigate to the need to look at the location._
- _Or implement a simple catalog yourself._

****

If it is troublesome to process on the server, you can use JavaScript to process it on the browser.
Traverse all the h1 h2 h3 tags, get the title text and format it, and set it to id.
Of course there are drawbacks to this.
Only after the page is loaded, can you use #hash to jump to different locations on this page.
Accessing the URL with #hash alone cannot locate the specified location.

**Comment by JasonBarnabe** [comment]
If there are pages that could use anchors and doesn't have them, feel free to identify and I can add them. Not intending to create some system to add them automatically everywhere, though.
