### ISSUE TITLE
Markdown code tags not working inside <details> element

### ISSUE THREAD

**Issue by aminomancer** [JasonBarnabe/greasyfork#989]
[Example here](https://greasyfork.org/en/scripts/420475-netflix-marathon-pausable), expand the `<details>` element at the bottom. Instead of showing `backdrop-filter` it just shows \`backdrop-filter\`. Elsewhere the tags work fine, it just seems to be a problem inside a `<details>` element.

Thanks! 🙏

**Comment by aminomancer** [comment]
I tried switching to `<code>` tags instead of backticks and that works fine, as long as I add a line break on every line. but it's weird that it parses the markdown tags so differently from VS code's markdown preview or [github's](https://github.com/aminomancer/Netflix-Marathon-Pausable).

**Comment by JasonBarnabe** [comment]
Probably the same issue as https://github.com/vmg/redcarpet/issues/715. It's a problem, but it'll have to get fixed in that repo, so closing this issue.

**Comment by aminomancer** [comment]
Gotcha, thanks
