### ISSUE TITLE
Are you guys aware of OpenUserJS.org?

### ISSUE THREAD

**Issue by isync** [JasonBarnabe/greasyfork#99]
https://github.com/OpenUserJs/OpenUserJS.org

Any plans to merge these projects? ...before all the central goodness of golden userscripts.org times explodes to more microsites.

One idea, maybe, having a central repository of scripts, curated and displayed by two sites and user bases. So that greasyfork and OUJS are mere UI. A bit like metacpan and olden CPAN.

**Comment by JasonBarnabe** [comment]
I've implemented what I talked about about at https://github.com/OpenUserJs/OpenUserJS.org/issues/96#issuecomment-42913306. Users can specify whether they approve of redistribution, and Greasy Fork will compile a list at https://greasyfork.org/en/scripts/redistributable (which includes JSON feeds). Just my script so far, but I imagine it'll grow as people become aware of this. OpenUserJS is free to pull from this list and rehost these scripts. If there's problems reported with the feed, I'll fix it. Other than that, I think this as far it'll go for integration between the two sites for now. OpenUserJS would have to implement an API for the scripts to go the other way (https://github.com/OpenUserJs/OpenUserJS.org/issues/77), and any more complicated interplay seems like it would require that first.

**Comment by sizzlemctwizzle** [comment]
Where exactly is the JSON feed for that page?

**Comment by JasonBarnabe** [comment]
https://greasyfork.org/en/scripts/redistributable.json

Alternate forms on Greasy Fork are mentioned as link rel alternates.

```html

			<link rel="alternate" type="application/atom+xml" href="/en/scripts/redistributable.atom?sort=created" title="New scripts">
			<link rel="alternate" type="application/atom+xml" href="/en/scripts/redistributable.atom?sort=updated" title="Updated scripts">
			<link rel="alternate" type="application/json" href="/en/scripts/redistributable.json" >
			<link rel="alternate" type="application/javascript" href="/en/scripts/redistributable.jsonp?callback=callback" >
			<link rel="alternate" type="application/json" href="/en/scripts/redistributable.json?meta=1" >
			<link rel="alternate" type="application/javascript" href="/en/scripts/redistributable.jsonp?callback=callback&amp;meta=1" >
```

**Comment by sizzlemctwizzle** [comment]
That's very helpful. Thank you.

**Comment by sizzlemctwizzle** [comment]
That's very helpful. Thank you.

Would you mind putting information scraped from script metadata in its own object?
For instance:
``` json
[
  {
    "id": 42,
    "created_at": "2014-02-20T17:49:37.000Z",
    "daily_installs": 0,
    "total_installs": 48,
    "code_updated_at": "2014-08-08T01:50:59.000Z",
    "support_url": null,
    "fan_score": "20.7",
    "meta": {
      "name": "Disable modal dialogs for automation",
      "description": "Disables things like alert, confirm, and prompt - useful for visiting sites with an automated tool like iMacros",
      "namespace": "http:\/\/userstyles.org\/automation",
      "contribution_url": null,
      "contribution_amount": null,
      "license": null,
      "version": "1"
    },
    "good_ratings": 1,
    "ok_ratings": 0,
    "bad_ratings": 0,
    "user": {
      "id": 1,
      "name": "JasonBarnabe",
      "url": "https:\/\/greasyfork.org\/users\/1-jasonbarnabe"
    },
    "url": "https:\/\/greasyfork.org\/scripts\/42-disable-modal-dialogs-for-automation",
    "code_url": "https:\/\/greasyfork.org\/scripts\/42-disable-modal-dialogs-for-automation\/code\/Disable%20modal%20dialogs%20for%20automation.user.js",
    "locale": "en",
    "redistributable": true
  }
]
```

**Comment by JasonBarnabe** [comment]
Is that all meta keys, or just meta keys found that Greasy Fork thinks are useful? I imagine you mean the former.

**Comment by sizzlemctwizzle** [comment]
All would be nice.

**Comment by JasonBarnabe** [comment]
Filed https://github.com/JasonBarnabe/greasyfork/issues/363
