### ISSUE TITLE
Script sets other than "Favorites" should affect "Ratings" and "Favoriters" list

### ISSUE THREAD

**Issue by liangjiancang** [JasonBarnabe/greasyfork#994]
I have observed that adding a script to script sets other than "Favorites" does not affect the "Ratings" and "Favoriters" lists.

If a script is added to a set by a user, that means it's special to him, so why not reflect it in the rating? Personally, I see "Favorites" as the default favorites, and for some special types of scripts they are added to a specific set. At least for me, those added to other sets are instead more cherished than "Favorites".

Of course, since a user can add the same script to multiple sets, additional de-duplication is required, but it is clearly worth it in exchange for more accurate script evaluation.

**Comment by JasonBarnabe** [comment]
Non-favorite script sets can contain scripts by criteria - like all scripts for a certain site. It doesn't make sense to include something like this as a rating.

Script sets is kind of a legacy feature anyway. I may get rid of it if I can figure out a replacement for the "favorites" part.
